### ISSUE TITLE
Fishtank  hfjh.fishbowl.v2

### ISSUE THREAD

**Issue by joseant** [rytilahti/python-miio#1001]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Youpin fishtank
  - Link: https://www.aliexpress.com/i/32986805225.html

Use `miiocli device --ip <ip address> --token <token>`.

Model: hfjh.fishbowl.v2
Hardware version: esp8266
Firmware version: 2.1.3

**Additional context**

I have already obtained the services and properties :

Device 'urn:miot-spec-v2:device:fish-tank:0000A0A2:hfjh-v2:1': Fish Tank with 3 services

* Service siid 1: (Device Information): 4 props, 0 actions

        ## Properties ##
                siid 1: piid: 1 (Device Manufacturer): (string, unit: None) (acc: ['read'])
                siid 1: piid: 2 (Device Model): (string, unit: None) (acc: ['read'])
                siid 1: piid: 3 (Device Serial Number): (string, unit: None) (acc: ['read'])
                siid 1: piid: 4 (Current Firmware Version): (string, unit: None) (acc: ['read'])

* Service siid 2: (Fish Tank): 3 props, 0 actions

        ## Properties ##
                siid 2: piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write', 'notify'])
                siid 2: piid: 2 (Water Pump): (bool, unit: None) (acc: ['read', 'write', 'notify'])
                siid 2: piid: 3 (Pump Flux): (uint8, unit: none) (acc: ['read', 'write', 'notify'])
                        Range: [5, 100, 1]

* Service siid 4: (function): 17 props, 1 actions

        ## Properties ##
                siid 4: piid: 1 (mcu-type): (uint8, unit: none) (acc: ['read', 'notify'])
                        {'value': 0, 'description': 'None'}
                        {'value': 1, 'description': 'One'}
                siid 4: piid: 2 (ledboard-model): (uint8, unit: none) (acc: ['read', 'notify', 'write'])
                        {'value': 0, 'description': 'Sun'}
                        {'value': 1, 'description': 'Color'}
                        {'value': 2, 'description': 'Stream'}
                siid 4: piid: 3 (ledboard-brightness): (uint8, unit: none) (acc: ['read', 'notify', 'write'])
                        Range: [0, 100, 1]
                siid 4: piid: 4 (): (uint32, unit: rgb) (acc: ['read', 'notify', 'write'])
                        Range: [0, 16777215, 1]
                siid 4: piid: 5 (ledboard-color): (uint32, unit: rgb) (acc: ['read', 'notify', 'write'])
                        Range: [0, 16777215, 1]
                siid 4: piid: 6 (ledboard-stream): (uint16, unit: none) (acc: ['read', 'notify', 'write'])
                        Range: [0, 360, 1]
                siid 4: piid: 7 (ledboard-speed): (uint8, unit: none) (acc: ['read', 'notify', 'write'])
                        Range: [0, 100, 1]
                siid 4: piid: 8 (ledboard-time-switch): (bool, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 9 (ledboard-time-open): (string, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 10 (ledboard-time-close): (string, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 11 (feed-time-switch): (bool, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 12 (feed-time): (string, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 13 (feed-num): (uint8, unit: none) (acc: ['read', 'notify', 'write'])
                        Range: [1, 30, 1]
                siid 4: piid: 14 (key-switch): (bool, unit: none) (acc: ['read', 'notify', 'write'])
                siid 4: piid: 15 (feed-time-week): (uint8, unit: none) (acc: ['read', 'notify', 'write'])
                        Range: [0, 127, 1]
                siid 4: piid: 16 (feed-record): (string, unit: none) (acc: [])
                siid 4: piid: 17 (log): (string, unit: none) (acc: [])

        ## Actions ##
                siid 4: aiid 1 set-feed-single: in: [13] -> out: []

        ## Events ##
                siid 4: eiid 1 (feed-record): (args: [16])
                siid 4: eiid 2 (log-up): (args: [17])

The problem is I get this error, when I try to get properties:

miiocli -d device --ip 192.0.3.171 --token xxxxxxxxxxxxxxxxxxxxxxxxx   raw_command get_properties "[{'did': '245935661', 'siid': 1, 'piid': 1}]"
INFO:miio.cli:Debug mode active
Running command raw_command
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.miioprotocol:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x0e\xa8\xae-\x00\x00/\xa9' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('0ea8ae2d')
            ts = 1970-01-01 03:23:21
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 0ea8ae2d with ts: 1970-01-01 03:23:21, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.0.3.171:54321 >>: {'id': 1, 'method': 'get_properties', 'params': [{'did': '245935661', 'siid': 1, 'piid': 1}]}
DEBUG:miio.miioprotocol:192.0.3.171:54321 (ts: 1970-01-01 03:23:22, id: 1) << {'id': 1, 'result': [{'did': '245935661', 'siid': 1, 'piid': 1, 'code': -4004}], 'exe_time': 60}
[{'did': '245935661', 'siid': 1, 'piid': 1, 'code': -4004}]

**Comment by rytilahti** [comment]
Try some other siid than 1 (e.g., `miiocli miotdevice --ip <ip> --token <token> get_property_by 2 1`), that is just for the device information and may not always be properly implemented.

**Comment by joseant** [comment]
Hello.
Thanks for the answer.

I have tried:

miiocli -d miotdevice --ip 192.0.3.171 --token xxxxxxxxxxxx get_property_by 2 1

and I got this:

INFO:miio.cli:Debug mode active
Running command get_property_by
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.miioprotocol:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b"!1\x00 \x00\x00\x00\x00\x0e\xa8\xae-\x00\x02\xe5'" (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('0ea8ae2d')
            ts = 1970-01-03 04:42:15
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 0ea8ae2d with ts: 1970-01-03 04:42:15, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.0.3.171:54321 >>: {'id': 1, 'method': 'get_properties', 'params': [{'did': '2-1', 'siid': 2, 'piid': 1}]}
DEBUG:miio.miioprotocol:192.0.3.171:54321 (ts: 1970-01-03 04:42:16, id: 1) << {'id': 1, 'result': [{'did': '2-1', 'siid': 2, 'piid': 1, 'code': 0, 'value': True}], 'exe_time': 130}
[{'did': '2-1', 'siid': 2, 'piid': 1, 'code': 0, 'value': True}]

**Comment by rytilahti** [comment]
The `value` contains the response for the property, which in this case is power?
```
siid 2: piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write', 'notify'])
```

The `acc` here shows that the value can be both read and written, so you can change that value using `set_property_by <siid> <piid> <value> <type>`. The type is needed for non-string types, e.g., for boolean like in the case above, `miiocli miotdevice set_property_by 2 1 false bool` should work to turn the device off.

Anyway, you could try to read the rest of the properties to find out what the represent, note that the names are not always clear. And if you want to contribute implementing this, take a look at https://github.com/rytilahti/python-miio/blob/master/miio/heater_miot.py which shows how the implementation would look like.

**Comment by joseant** [comment]
thanks, I thought the message **_DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''_**  was an error that prevented getting the value.

**Comment by rytilahti** [comment]
Let's keep this open, as the device is not yet supported by the library.

**Comment by joseant** [comment]
ok

**Comment by ha0y** [comment]
Hey! This one looks similar to the one that my friend owns. He has a `hfjh.fishbowl.v1`, which has a water pump and 2 rgb lights. I 've added an initial support for it in [my integration](https://github.com/ha0y/xiaomi_miot_raw), but he said it doesn't work and he couldn't provide any logs because he is new to hass. If you don't mind, you may give it a try and give us some feedback, so as to facilitate it to be supported by python-miio.

BTW:
the code `-4004`, sometimes just indicates that the device refuses to be accessed via LAN. This happens to some of my device, e.g. `mrbond.airer.m1t`. However, `set_properties` works well. I can't find the solution, but a workaround is to access the device via Xiaomi cloud server. This feature is also available in [my integration](https://github.com/ha0y/xiaomi_miot_raw) and works well. This should be the last choice as it requires a stable Internet.

**Comment by syssi** [comment]
If you access/retrieve unsupported pids the value is `-4003` at some miot device.

**Comment by ha0y** [comment]
> If you access/retrieve unsupported pids the value is `-4003` at some miot device.

Yes. This is also stated in https://iot.mi.com/new/doc/embedded-development/wifi/rpc . While -4004 was `Other internal error`. The piid was supported, however couldn't be read via LAN.

**Comment by pplucky** [comment]
Following the magnificent guide provided [here](https://github.com/rytilahti/python-miio/issues/901), I managed to retrieve and set most useful properties using raw commands.

I am currently not able to trigger the action for single feed, has anyone been able to do via raw command and be kind enough to share with the command line parameters used?

Thanks in advance.
