### ISSUE TITLE
Roborock S7 after Firmware Update 4.1.2-0928 - KeyError

### ISSUE THREAD

**Issue by bbr111** [rytilahti/python-miio#1004]
**Describe the bug**
Error after Firmware Update.

Status, consumable_status, info and other commands are running.

Rebooting the device does not clear the issue.

**Version information (please complete the following information):**
 - OS: Linux Debian
 - python-miio: [Use `miiocli --version` or `pip show python-miio`]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: roborock.vacuum.a15
  - Hardware version: Linux
  - Firmware version: 4.1.2_0928

**To Reproduce**
1.

**Expected behavior**

**Console output**
miiocli vacuum --ip <my_ip> --token <my_token> clean_history    Running command clean_history
<CleaningSummary count=KeyError ids=KeyError total_area=KeyError total_duration=KeyError>

INFO:miio.cli:Debug mode active
DEBUG:miio.vacuum:Read stored sequence ids: {'seq': 36, 'manual_seq': 0}
Running command consumable_status
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.miioprotocol:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x17P\xc6U\x00\x00\x0f%' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('1750c655')
            ts = 1970-01-01 01:04:37
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 1750c655 with ts: 1970-01-01 01:04:37, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:<my_ip>:54321 >>: {'id': 37, 'method': 'get_consumable', 'params': []}
DEBUG:miio.miioprotocol:<my_ip>:54321 (ts: 1970-01-01 01:04:38, id: 37) << {'id': 37, 'result': [{'main_brush_work_time': 37961, 'side_brush_work_time': 37961, 'filter_work_time': 37961, 'filter_element_work_time': 0, 'sensor_dirty_time': 37504}], 'exe_time': 101}
<ConsumableStatus filter=10:32:41 filter_left=5 days, 19:27:19 main_brush=10:32:41 main_brush_left=12 days, 1:27:19 sensor_dirty=10:25:04 sensor_dirty_left=19:34:56 side_brush=10:32:41 side_brush_left=7 days, 21:27:19>

**Comment by rytilahti** [comment]
Hmm, I'm not seeing the error here, so this was probably fixed with #990?

**Comment by fettlaus** [comment]
It seems as if the response contains no records. Maybe try to create a record by lettings the vacuum clean a small area and then try again. I just updated to 4.1.2-0928 as well and everything still works fine.

**Comment by rytilahti** [comment]
If that's the case, a stacktrace would be useful as this should still be fixed not to cause one if no entries are available :-)

**Comment by bbr111** [comment]
After a few short runs, i now have values in reading.

But still having trouble to get last_clean_details

DEBUG:miio.miioprotocol:Discovered 1750c655 with ts: 1970-01-01 00:43:23, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:<my_ip>:54321 >>: {'id': 52, 'method': 'get_clean_summary', 'params': []}
DEBUG:miio.miioprotocol:<my_ip>:54321 (ts: 1970-01-01 00:43:24, id: 52) << {'id': 52, 'result': {'clean_time': 40566, 'clean_area': 547730000, 'clean_count': 67, 'dust_collection_count': 0, 'records': [1617903508, 1617895704, 1617895008, 1617892263, 1617892245, 1617892195, 1617889898, 1617887908, 1617879405, 1617879300, 1617874935, 1617869934, 1617728779, 1617728768, 1617727674, 1617721661, 1617705508, 1617703035, 1617701904, 1617700284]}, 'exe_time': 101}
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.8/site-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/vacuum.py", line 381, in last_clean_details
    if not history.ids:
  File "/usr/local/lib/python3.8/site-packages/miio/vacuumcontainers.py", line 214, in ids
    return list(self.data[3])
KeyError: 3

**Comment by bbr111** [comment]
@fettlaus Thanks.

I tested the PR and it works for me.
