### ISSUE TITLE
Xiaomi Vacuum resume cleaning session from dock capability?

### ISSUE THREAD

**Issue by itchaboy** [rytilahti/python-miio#102]
Hey rytilahti! Currently using the Xiaomi vacuum with Home Assistant. I have used every supported command I can find (even the raw commands), and I can't get the vacuum to dock and resume, you can dock and start a new session and you can pause and resume, but no pause, dock, resume.

BUT! If the vacuum runs low on battery while cleaning and goes back to the dock itself to recharge you can send the same start_pause command to it that normally starts it from the dock, and it will actually resume!

It's as if when the vacuum runs low on battery it enters a perpetually paused state and returns to the dock. Seems like a hidden command or feature to me. Either way it's not something I've been able to replicate without the vacuums automated low battery process occurring. Think you can discover this?

**Comment by rytilahti** [comment]
Hi, is such functionality available through the app? If yes, then it is possible to integrate it. If not, I don't think it is possible, as all that is (unfortunately) handled by the vacuum itself.

**Comment by itchaboy** [comment]
:/ Bummer, no I don't believe it is. I'd have found it by now haha I thought maybe we could find a way to trick the vacuum into thinking it is low on battery or something :D Oh well.. Great work on this btw!

**Comment by rytilahti** [comment]
Glad you like it! Unfortunately I don't think we can trick the vacuum to do anything until someone figures out how to access the filesystem / modify the firmware itself. I'm closing this issue now as we cannot do anything about it.
