### ISSUE TITLE
zeroconf 0.29.0 which is incompatible

### ISSUE THREAD

**Issue by inhibitz** [rytilahti/python-miio#1022]
i have any problem with upgrade module php-miio 0.5.5 (on ha 2021.4.6)
$ pip3 install zeroconf==0.29.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting zeroconf==0.29.0
  Using cached https://www.piwheels.org/simple/zeroconf/zeroconf-0.29.0-py3-none-any.whl (55 kB)
Requirement already satisfied: ifaddr>=0.1.7 in /srv/homeassistant/lib/python3.9/site-packages (from zeroconf==0.29.0) (0.1.7)
Installing collected packages: zeroconf
  Attempting uninstall: zeroconf
    Found existing installation: zeroconf 0.28.8
    Uninstalling zeroconf-0.28.8:
      Successfully uninstalled zeroconf-0.28.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-miio 0.5.5.2 requires zeroconf<0.29,>=0.28, but you have zeroconf 0.29.0 which is incompatible.
Successfully installed zeroconf-0.29.0

how it's fix ? python 3.9 env.

HA not started.

**Comment by rytilahti** [comment]
The linked PR makes the pinning more relaxed, but this will require a new release (which I'm aiming to do this week).
