### ISSUE TITLE
Add new device support - Smartmi Air Purifier

### ISSUE THREAD

**Issue by orionowy** [rytilahti/python-miio#1025]
### Request Smartmi zhimi.airpurifer.za1 - Air Purifier support 
[](https://www.smartmiglobal.com/collections/air-purifier/products/smartmi-air-purifier
)

**Xiaomi App Detalis details:**

```
ID: xxx
IP: 192.168.0.xx
MODEL: zhimi.airpurifer.za1
```

**Comment by lichtteil** [comment]
More info for this model (copy from https://github.com/syssi/xiaomi_airpurifier/issues/181#issuecomment-835790970 ):

Name Smartmi Air Purifier
Model: KQJHQ01ZM
Spec: https://www.aze.com.pl/pl/p/Oczyszczacz-powietrza-Smartmi-Air-Purifier/2483,
https://www.smartmiglobal.com/collections/air-purifier/products/smartmi-air-purifier

Coverage 9-48m², 400m³/h CADR, 30 dB - 64 dB, 40 W (max.)
Sensors: Temperature, laser particle sensor, Total VOC, humidity.

Some things are compatible with zhimi.airpurifier.mb3, but some functionalities are missing:

the device status does not work (the device cannot be turned on and off)
led not working (led: null)
motor speed is not working (motor_speed: null)
fan level does not show value, probably no fan mode (fan_level: null)
other preset_modes, available 3 modes (Auto, Night, Favorite)
preset_mode atributte not work (preset_mode: null)
TVOC sensor status is not displayed
