### ISSUE TITLE
Cannot get status from my zhimi.airpurifier.mb3(Airpurifier 3H)

### ISSUE THREAD

**Issue by rogerbl** [rytilahti/python-miio#1037]
When I issue the command to get info from the airpurifier it works, but when I want to get the status the following error msg comes:
Error: {'code': -5001, 'message': 'command error'}
This is the command I issued to get the status:
miiocli airpurifier --ip 192.168.100.191 --token xxxxxxxxxxxxxxxxxx status
and the info request which works:
miiocli airpurifier --ip 192.168.100.191 --token xxxxxxxxxxxxxxxxxx info
I get the same error as above when I try to connect in a python script.
with AirPurifier(ip,token,0,0)
What can be wrong?
I 've got another older 2s airpurifier which works fine with these commands.
I use python 3.8 on windows 10 and Ubuntu 20  Same error on both.
Model: zhimi.airpurifier.mb3
Hardware version: esp32
Firmware version: 2.0.7

Name: python-miio
Version: 0.5.0.1
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu Rytilahti
Author-email: tpr@iki.fi

**Version information (please complete the following information):**
 - OS: [e.g.Linux]
 - python-miio: [Use `miiocli --version` or `pip show python-miio`]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1.

**Expected behavior**

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

**Comment by rytilahti** [comment]
You have to use `miiocli airpurifiermiot` for this device, #1030 is a similar problem (different module, but same idea).

**Comment by rogerbl** [comment]
Thanks mate

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rytilahti** [comment]
I assume it worked, so I'm closing this now :-)
