### ISSUE TITLE
Roborock S7 can't be added to Home Assistant

### ISSUE THREAD

**Issue by fettlaus** [rytilahti/python-miio#1041]
I have tried adding my S7 today, and I am getting this error, I can add my S4 without any issues

`ERROR (MainThread) [homeassistant.components.xiaomi_miio.device] DeviceException during setup of xiaomi device with host`

I am running core-2021.5.1

_Originally posted by @Claustn in https://github.com/rytilahti/python-miio/issues/990#issuecomment-836828449_

**Comment by fettlaus** [comment]
@Claustn Do you have any additional logs from this?

**Comment by Claustn** [comment]
I tried enabling debug logging in home assistant, but it did not give me a lot more detail.

2021-05-10 23:16:40 DEBUG (MainThread) [homeassistant.components.xiaomi_miio.device] Initializing with host x.y.z.æ (token xxxxxxx...)
2021-05-10 23:16:45 DEBUG (SyncWorker_0) [miio.miioprotocol] Unable to discover a device at address x.y.z.æ
2021-05-10 23:16:45 ERROR (MainThread) [homeassistant.components.xiaomi_miio.device] DeviceException during setup of xiaomi device with host x.y.z.æ

I have confirmed that I have the right IP for the device both on my router, Xiaomi app and the python token extractor, it is running firmware 4.1.2_0978

I am relatively new to HomeAssistant, so I am not sure if there is a way to get even more detailed logs for this, but if you have any suggestions let me know and I will try to get more logs

**Comment by rytilahti** [comment]
The discovery error happens indeed when the device is not answering to the initial handshake, so you could launch tcpdump or wireshark to verify that you are indeed not receiving a response from the device.

If that is the case with your device, feel free to open a PR to update the documentation accordingly :-)

**Comment by Claustn** [comment]
I can confirm via WireShark that I never get a response when I query the S7 from a different subnet than the vacuum itself.

Thank you very much for your help in troubleshooting this

**Comment by fettlaus** [comment]
I assume this issue is kind of solved then.
See #1045
