### ISSUE TITLE
Add xiaomi trouver lds finder support

### ISSUE THREAD

**Issue by dm1trpopov** [rytilahti/python-miio#1042]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: xiaomi trouver lds finder (dreame-vacuum-p2036)
  - Link: https://www.ixbt.com/live/chome/trouver-finder-robot.html

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: dreame-vacuum-p2036
  - Hardware version:
  - Firmware version: 3.5.8_1021

```
INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:  IP 192.168.1.130 (ID: 175b50e5) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.miioprotocol:Discovery done
INFO:miio.discovery:Discovering devices with mDNS for 5 seconds...
WARNING:miio.discovery:Found unsupported device dreame-vacuum-p2036_miio391860453._miio._udp.local. at 192.168.1.130, please report to developers
```

**Comment by rytilahti** [comment]
dreamevacuum may support some of the features, so you could try `miiocli dreamevacuum --ip <addr> --token <token> status` and other commands to see if that's the case. How much of the commands are shared between these vacuums is unknown, but if you wish to improve the implementation,t the script inside devtools directory can be helpful.

**Comment by addrisiof** [comment]
I've tried with status command but seems not work
`miiocli dreamevacuummiot --ip 192.168.1.26 --token TOKEN status

ERROR:miio.miioprotocol:Got error when receiving: timed out
Error: No response from the device`

**Comment by inyerade** [comment]
same here WARNING:miio.discovery:Found unsupported device dreame-vacuum-mc1808_miio332901505._miio._udp.local. at IP, please report to developers

**Comment by inode-** [comment]
More information can for the procol implementation can be found at: https://github.com/openhab/openhab-addons/pull/10254
