### ISSUE TITLE
ble_dbg_tbl_dump user ack timeout

### ISSUE THREAD

**Issue by viiy** [rytilahti/python-miio#1051]
- Python 3.9.5
- miiocli, version 0.5.6

I trying get mibeacon encryption key
run command 
miiocli device --ip <IP> --token <TOKEN> raw_command ble_dbg_tbl_dump '{"table":"evtRuleTbl"}'
token and ip is right but always rescived:
Error: {'code': -9999, 'message': 'user ack timeout'}

**Comment by rezmus** [comment]
device model? token/ip correct?

**Comment by rytilahti** [comment]
Token & IP are correct as this error message comes from the device itself and not from this library. This error is very generic and can happen for example when the device doesn't know that command, doesn't accept the parameters etc.

Otherwise, knowing the model and the reason why you think this command should work might be helpful.

**Comment by viiy** [comment]
I has 5 devices:
ceiling4(YLXD02YL) x 1
ceiling3(YLXD05YL) x 4

All lamps works well in HA, so token and ip are correct.

**Comment by viiy** [comment]
i maked request from windows before, now i was try from LTS, and all work.

**Comment by rezmus** [comment]
@viiy when you send from windows might be better to send like this

```
miiocli device --ip IP --token TOKEN raw_command ble_dbg_tbl_dump {\"table\":\"evtRuleTbl\"}
```

**Comment by viiy** [comment]
> @viiy when you send from windows might be better to send like this
> 
> ```
> miiocli device --ip IP --token TOKEN raw_command ble_dbg_tbl_dump {\"table\":\"evtRuleTbl\"}
> ```

ty

**Comment by rytilahti** [comment]
Is this for yeelight? If yes, should the `yeelight.py` be extended to add direct support for this?

**Comment by rezmus** [comment]
@rytilahti it's for some yeelight devices (ceilings, 1s strip) which can pair yeelight bt remotes/dimmer directly. you can read mac and beaconkey of paired device, which can be later used to decrypt payload (but there are also other ways to get this data).

check https://github.com/custom-components/ble_monitor for details. support for yeelight remotes/dimmer was added recently.

**Comment by rytilahti** [comment]
Thanks @rezmus! I think it's fair enough to add it there, makes it simpler and less error-prone than using raw-commands :-)
