### ISSUE TITLE
Add Dreame L10 Bot Pro (dreame.vacuum.p2029) support

### ISSUE THREAD

**Issue by tabookopencart** [rytilahti/python-miio#1052]
https://www.dreame-technology.com/products/dreame-l10-pro

Model: dreame.vacuum.p2029
Hardware version: Linux
Firmware version: 3.5.8_1052

**Comment by xury77** [comment]
I managed it manually adding  dreamevacuum.py from @microfrost1 repo and even upload a custom langpack to L10:
https://github.com/rytilahti/python-miio/issues/812#issuecomment-841894946
https://github.com/rytilahti/python-miio/issues/812#issue-695959518

**Comment by jeyph** [comment]
> I managed it manually adding dreamevacuum.py from @microfrost1 repo and even upload a custom langpack to L10:
> [#812 (comment)](https://github.com/rytilahti/python-miio/issues/812#issuecomment-841894946)
> [#812 (comment)](https://github.com/rytilahti/python-miio/issues/812#issue-695959518)

Hey xury77,

Can you tell me the steps you did to make the l10 work?

**Comment by xury77** [comment]
Now is easier way. You can use https://github.com/pooyashahidi/xiaomi_vacuum
Of course you still need to get the token. There are many ways to extract a token.
Last time I used a modded Xiaomi Home android app from kapiba.ru or token extractor https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor
Alternate "my old" method is described in attached archive, but is in Polish language. You can use google translator.
[Dreame_L10_polish_lang_pack.zip](https://github.com/rytilahti/python-miio/files/7117251/Dreame_L10_polish_lang_pack.zip)

**Comment by jeyph** [comment]
Thanks! It works perfectly.

**Comment by jeyph** [comment]
Were you able to get a working map on the l10 pro?

**Comment by xury77** [comment]
You mean map for HA? Unfortunately still not available for Dreame family.

**Comment by jaegerschnitzel** [comment]
> Now is easier way. You can use https://github.com/pooyashahidi/xiaomi_vacuum

Thanks, this also works for my brand new Dreame Z10 Pro :-)

**Comment by SebestaJaromir** [comment]
> You mean map for HA? Unfortunately still not available for Dreame family.

Hi Xury77, do you know any news about map creation for Dreame family? Is still not possible or, any new what I overlooked? Thank you very much for.

**Comment by spekkie3** [comment]
Still no map for the dreame fam ? L10 ? :(
