### ISSUE TITLE
Please add support for the Mijia 1G Vacuum!

### ISSUE THREAD

**Issue by OlavRab** [rytilahti/python-miio#1057]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

Xiaomi Mijia 1G 
Model: mijia.vacuum.v2

Use `miiocli device --ip <ip address> --token <token>`.

- Firmware versionL 2.0.8.6139

The vacuum does pretty much the same as the 1C, which is already added.
This one does less things, you can only start,stop,dock and change brush level. Should be relatively easy to implement:)

**Comment by Amareis** [comment]
+1

```
Model: mijia.vacuum.v2
Hardware version: esp32
Firmware version: 2.0.8
```

**Comment by Amareis** [comment]
Oh, ok, so it's working. Just use `g1vacuum` command, and not a `vacuum`!
