### ISSUE TITLE
Mijia ZDG300

### ISSUE THREAD

**Issue by JeedHome44** [rytilahti/python-miio#1071]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: ZDG300
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3]
  - Hardware version:
  - Firmware version:

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

Do you know if Mijia ZDG300 work with python Miio?

**Comment by rezmus** [comment]
afaik you can't pull props for this device. it only push them to cloud when app is connected.
