### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by NadeHouse** [rytilahti/python-miio#108]
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
WARNING:miio.discovery:Found unsupported device chuangmi-plug_miio814031._miio._udp.local. at 192.168.0.xx please report to developers

This is a xiaomi smart power plug.

This message occurs when executing `mirobo discover` 

It is listed in the supported device list as Xiaomi Mi Smart Socket Plug (1 Socket, 1 USB Port).

**Comment by syssi** [comment]
The Chuang Mi V1 is already supported. Just the device name wasn't known so far.
