### ISSUE TITLE
The new way to get device token

### ISSUE THREAD

**Issue by TheSnowfield** [rytilahti/python-miio#1088]
> Tested on Mi Home 6.0.214

### Steps
1. This method needs a rooted android device.
2. Login into Mi Home and load all the devices.
3. Navigate to `/data/data/com.xiaomi.smarthome/files/device/cache` use any file manager.
4. You will see a `device_list_xxxxxxxxx` file.

### Find the token

Here is what the content looks like.

```
 1622439426     PXDP.210508.001.XM129     2 com.xiaomi.smarthome.core.entity.device.MiioDevice  	 403810959  xiaomi.aircondition.mt8 < Mi Smart Ultra Electricity Saving Air Conditioner (1.5HP/Inv   XX:XX:XX:XX:XX:XX       ￒ￿  dd2f4e1aa1ec2512b4f1f04fc8c51214  
```

We can easily figure out the token is `dd2f4e1aa1ec2512b4f1f04fc8c51214`.

### Test it
```bash
$ miiocli device --ip X.X.X.X --token dd2f4e1aa1ec2512b4f1f04fc8c51214 info
Model: xiaomi.aircondition.mt8
Hardware version: esp32
Firmware version: 2.2.0
```

**Comment by rezmus** [comment]
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/
