### ISSUE TITLE
dreame.vacuum.mb1808 unsupported

### ISSUE THREAD

**Issue by pzim-devdata** [rytilahti/python-miio#1104]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  NAME:     Mi Robot Vacuum-Mop 
(THIS IS THE SAME MODEL AS dreame.vacuum.mc1808 (Xiaomi Mijia 1C Sweeping Vacuum Cleaner)
   ID:       415393437
   IP:       192.168.1.xxx
   TOKEN:    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   MODEL:    dreame.vacuum.mb1808
(THIS IS THE SAME MODEL AS  dreame.vacuum.mc1808 ( dreame.vacuum.mC1808)

Use `miiocli device --ip <ip address> --token <token>`.
miiocli vacuum --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxx info :

Model: dreame.vacuum.mb1808
Hardware version: Linux
Firmware version: 3.5.8_1805

**Additional context**
sudo miiocli discover :

INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:Discovery done
INFO:miio.discovery:Discovering devices with mDNS for 5 seconds...
/usr/local/lib/python3.9/dist-packages/zeroconf/_services/browser.py:170: FutureWarning: <miio.discovery.Listener object at 0x7fd6454b2f70> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
  warnings.warn(
WARNING:miio.discovery:Found unsupported device dreame-vacuum-mb1808_miio415393437._miio._udp.local. at 192.168.1.xxx, please report to developers

**Comment by pzim-devdata** [comment]
*****SOLVED*****
It's working very well when I use this command in terminal: 

miiocli **dreamevacuummiot** --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx status

and not 
miiocli vacuum --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx status
mirobo --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx  status
miiocli dreame.vacuum.mc1808 --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx status
miiocli dreame.vacuum.mb1808 --ip 192.168.1.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx status

**Comment by pzim-devdata** [comment]
@Entretoize 

FOR dreame.vacuum.mb1808

**use miiocli, version 0.5.7**

sudo python3 -m pip install python-miio==0.5.7

;-)
Get token : 
bash <(curl -L https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/raw/master/run.sh)

Usage: miiocli dreamevacuummiot [OPTIONS] COMMAND [ARGS]...

EXEMPLES : 

Start vacuum :
miiocli dreamevacuummiot --ip 192.168.1.XXX --token XXXXXXXXXXXXXXXXXXXXXXXX start

Status vacuum : 
zenity --info --window-icon=/home/venus/Documents/Vacuum.png --text="$(miiocli dreamevacuummiot --ip 192.168.1.XXX--token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX status)" 

Stop vacuum : 
miiocli dreamevacuummiot --ip 192.168.1.XXX--token XXXXXXXXXXXXXX stop

Identify vacuum : 
miiocli dreamevacuummiot --ip 192.168.2.XXX --token XXXXXXXXXXXXXXXXXXXXXXXXXXX identify

Home vacuum : 
miiocli dreamevacuummiot --ip 192.168.2.XXX --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXX home

**Comment by pzim-devdata** [comment]
> I get `Error: No such command 'dreamevacuummiot'` is it still available ?

FOR dreame.vacuum.mb1808

use miiocli, version 0.5.7
sudo python3 -m pip unsinstall python-miio
sudo python3 -m pip install python-miio==0.5.7

**Comment by Entretoize** [comment]
> > I get `Error: No such command 'dreamevacuummiot'` is it still available ?
> 
> FOR dreame.vacuum.mb1808
> 
> use miiocli, version 0.5.7 sudo python3 -m pip unsinstall python-miio sudo python3 -m pip install python-miio==0.5.7

Thank you !

**Comment by DeutscheGabanna** [comment]
I'm on `0.5.13` and still do not have the command.

**Comment by rytilahti** [comment]
The command should be `miiocli dreamevacuum` (at least on git master). Try `miiocli --help|grep dreame` to see if that's available.
