### ISSUE TITLE
Xiaomi Roborock S6 MaxV

### ISSUE THREAD

**Issue by michaelmadsen72** [rytilahti/python-miio#1108]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi Roborock S6 MaxV
  - Link: https://us.roborock.com/pages/roborock-s6-maxv

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3]
  - Hardware version:
  - Firmware version:

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

From (miiocli discover):
WARNING:miio.discovery:Found unsupported device roborock-vacuum-a10_miio321552814._miio._udp.local. at 192.168.1.90, please report to developers

**Comment by rytilahti** [comment]
This should be working already using a10, I'll create a PR to add the mdns entry for it though!
