### ISSUE TITLE
WalkingPad A1 Pro WiFi Connection is failed

### ISSUE THREAD

**Issue by name8997** [rytilahti/python-miio#1109]
Device information:

Name(s) of the device: Xiaomi WalkingPad A1 Pro

Use `miiocli discover`

I'm trying to connect the walkingpad of a PC connected to the same wifi with the above command, 
but nothing is discovered.

Is there any other way to connect the device? Or is there a computer setting that needs to be modified?

Walkdingpad is connected well with smartphone through walkingpad app

Thanks

**Comment by rytilahti** [comment]
Did you try `miiocli walkingpad` command already?

**Comment by name8997** [comment]
Thank you for reply

`miiocli walkingpad` command needs IP and token.

But i don't know that and how to get that.

Could you tell me how to know that?

Thanks.

**Comment by dewgenenny** [comment]
Hey @name8997 - check out the top of the README - 

If you already have a token for your device and the device type, you can directly start using miiocli tool. If you don't have a token for your device, refer to [Getting started ](https://python-miio.readthedocs.io/en/latest/discovery.html) section of [the manual](https://python-miio.readthedocs.io/) for instructions how to obtain it.

**Comment by rytilahti** [comment]
Closing as stale, please reopen if this issue is still valid, thanks!
