### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by DMaksimov72** [rytilahti/python-miio#112]
Hello!
Some time ago I noticed this message in the logs:
_2017-11-06 03:41:49 ERROR (MainThread) [homeassistant.components.light.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: philips.light.ceiling_
Previously, the lamp (Xiaomi Philips LED Ceiling Lamp) worked correctly. I can not say exactly when the problem occurred.
I'm using HASSIO Home Assistant 0.57.1. 
My config:
light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Smart LED
    host: ***my_IP***
    token: ***my_token***

**Comment by Gui1ty** [comment]
Hello!

Have a same error with philips.light.ceiling [homeassistant.components.light.xiaomi_miio]
I'm use HomeAssistant on Ubuntu (virtualenv) v.0.57.2.
Lamp is working perfect, before update homeassistant.

Best Regards, Michail.
