### ISSUE TITLE
chuangmi.plug.212a01 

### ISSUE THREAD

**Issue by hzh-hzh** [rytilahti/python-miio#1133]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: 小米智能插座蓝牙网关版

  - Link: https://www.mi.com/buy/detail?product_id=12777

Use `miiocli device --ip <ip address> --token <token>`.

Model: chuangmi.plug.212a01
Hardware version: esp32
Firmware version: 2.1.8_0028

**Additional context**
Currently only the plug with this model can be purchased in Mi Mall, also other online store. So please help add it into the support list, thanks.

**Comment by 3cobblers** [comment]
upupup, the same issue

**Comment by Gerald-Rowe** [comment]
upupup, the same issue !!!

**Comment by Gerald-Rowe** [comment]
Since the old version of the plug cannot be bought now, and this is all available in the market, please help support this product

**Comment by luokui-c12** [comment]
我用这个方式解决了这个问题，希望对各位兄弟有帮助

**Comment by fanlushuai** [comment]
miiocli -d device --ip 192.1xxxx144 --token bc8b4fexxxxaef46cc66c0 raw_command set_properties "[{'did': 'power', 'siid': 2, 'piid': 1, 'value':False}]"
