### ISSUE TITLE
获取token报错

### ISSUE THREAD

**Issue by HF1643** [rytilahti/python-miio#1137]
Traceback (most recent call last):
  File "miio_test.py", line 4, in <module>
    from protocol import Message
  File "/root/python-miio/miio/protocol.py", line 50
    def verify_token(token: bytes):
                          ^
SyntaxError: invalid syntax

https://www.it610.com/article/1279200676949278720.htm
#文件内容 miio_test.py

#-*-coding:utf8-*-
import codecs
import socket
from protocol import Message

helobytes = bytes.fromhex('21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffff')
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.sendto(helobytes, ('172.16.4.14', 54321))#插座ip，端口54321
data, addr = s.recvfrom(1024)
m = Message.parse(data)
tok = codecs.encode(m.checksum, 'hex')
print('token:',tok)

**Comment by rytilahti** [comment]
This needs more details to figure out why it is not working. Are you maybe trying to run your script using python2? What does `python --version` say?
