### ISSUE TITLE
Xiaomi Vacuum v1 - consumables info 

### ISSUE THREAD

**Issue by nenominal** [rytilahti/python-miio#114]
Hi,
currently mirobo returns info about consumables like this:

> mirobo consumables
> Main brush:   1:25:37 (left 12 days, 10:34:23)
> Side brush:   1:25:37 (left 8 days, 6:34:23)
> Filter:       1:25:37 (left 6 days, 4:34:23)
> Sensor dirty: 1:25:25
> 

Is it possible, for the sake of consistency, to have them like in the app?

Ex: 

> Main brush: used 1h,  replace in about 299h, 99%

**Comment by rytilahti** [comment]
I don't see a reason to mimic the original UI, what's your use-case? Would it be enough to add % left? 

If you are using this as a library, that information is passed as `timedelta`s so you can adjust them to your liking. If/when someone wants to work on #98, it makes probably sense to pass this information as mere integers.

**Comment by nenominal** [comment]
I don't use the library in any special way, I just installed and run it on by desktop as is :-) (works like a charm, btw).
The interface is in hours and the output of mirobo is in days. It's easier to understand that you have 298 hours to change the filter, due to the fact that cleaning is in hours as well. Maybe is my OCD, that's all :)

**Comment by rytilahti** [comment]
Glad to hear it's working for you! Indeed, that could be something to implement (allowing formatting print outs in general), but that's not a priority.  The current output is the default "pretty print" coming from `timedelta` class and I would avoid making any hacks for it (maybe some people prefer the current format?), but would accept patches for output formatting (which would also allow the json usecase). If that's worth the effort is another question :-)

**Comment by nenominal** [comment]
Sure it's not a priority : ). Unfortunately I'm not a programmer so I can not help with patches.
Anyway, keep it up with this good work.

**Comment by rytilahti** [comment]
Ok, I'll close this for now in favor of #98 - I think this has to be done in a generic way if at all :-)
