### ISSUE TITLE
How do I bind the device?

### ISSUE THREAD

**Issue by luckystar5408** [rytilahti/python-miio#1159]
**Describe the bug**
Hi! I installed python-miio in my Python, but I don't know how to use Python to get my Xiaomi device.
I can only use miio in Python, and my system is Windows 10 Professional.

**Version information (please complete the following information):**
 - OS: Windows 10 Professional Edition
 - python-miio: 
Name: python-miio
Version: 0.5.8
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu R
Author-email: tpr@iki.fi
License: GPL-3.0-only
Location: c:\users\26670\appdata\roaming\python\python38\site-packages
Requires: cryptography, android-backup, netifaces, tqdm, zeroconf, construct, defusedxml, croniter, pytz, attrs, PyYAML, click, appdirs
Required-by:

**Comment by rytilahti** [comment]
Please reopen this with more details about the issue if it is still valid.
