### ISSUE TITLE
Support for Xiaomi Vacuum-mop pro (STYTJ02YM viomi.vacuum.v8)

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [rytilahti/python-miio#1161]
Looks like china version (styj02ym) is on supported devices list, but euro version (sty *T* j02ym) is missing.
I'm currently hosting maintained version of @nqkdev code: 
https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym and I want to merge this into upstream, so no more forks and installing 3rd-party addons.

**Device information:**

  - Name(s) of the device: Xiaomi Vacuum-Mop pro
  - Link: https://mi-home.pl/mi-robot-vacuum-mop-pro-black

Use `miiocli device --ip <ip address> --token <token>`.

  - Model:  viomi.vacuum.v8
  - Hardware version: Linux
  - Firmware version: 3.5.8_0021

**Additional context**
Probably it's very similar to China version (styj02ym), but exposes less attributes, like no consumables life remaining.

**Comment by rytilahti** [comment]
Have you looked into the shipped viomivacuum implementation to see what types of changes are needed? I'm happy to help with code reviews etc. to get the necessary changes to this library :-)

**Comment by snp88** [comment]
@rytilahti @KrzysztofHajdamowicz Any news about implementing this ?

**Comment by X1pheR** [comment]
It would be great if the STYJ02YM would get native support by python-miio. 🤞🏼

**Comment by X1pheR** [comment]
I believe this will wait untill #1114 is done

**Comment by th0m4sek** [comment]
What non programing owners of this vacuum can do to help integrate it?
