### ISSUE TITLE
Support XiaoMi Humidifier Pro (leshow.humidifier.jsq1)

### ISSUE THREAD

**Issue by WangRicky** [rytilahti/python-miio#1162]
**Device information:**

  - Name(s) of the device:XiaoMi Humidifier Pro
  - Link:https://www.mi.com/buy/detail?product_id=13839&cfrom=search

Use `miiocli device --ip <ip address> --token <token>`.

Model: leshow.humidifier.jsq1
Hardware version: esp32
Firmware version: 2.2.1

**Comment by teamfighter** [comment]
+1 for this
