### ISSUE TITLE
philips.light.ceiling Unsupported device found!

### ISSUE THREAD

**Issue by zamzas** [rytilahti/python-miio#118]
I'm unable to connect to my Xiaomi Philips LED Ceiling Light using home-assistant 0.57.2.
I'm running into the following error:
2017-11-08 10:30:16 ERROR (MainThread) [homeassistant.components.light.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: philips.light.ceiling

When i run python script:
from miio import *
a = Device('10.10.1.27', 'xxx...')
a.info()

I see:
philips.light.ceiling v1.5.1 (34:CE:xx:xx:xx:xx) @ 10.xx.xx.xx - token: xxx...

Please let me know if I can provide any further information. Thanks!

**Comment by rytilahti** [comment]
This has been fixed in homeassistant already and will be part of the next release: https://github.com/home-assistant/home-assistant/pull/10401 .

**Comment by zamzas** [comment]
Thank you so much.
