### ISSUE TITLE
Add Xiaomi Vacuum 1C  dreame.vacuum.mc1808  to Vacuum_Miio Integration

### ISSUE THREAD

**Issue by eadin79** [rytilahti/python-miio#1182]
Please add into the custom list for Miio integration Xiaomi Vacuum 1C  dreame.vacuum.mc1808 
actually is saying:  The device model is not known, not able to setup the device using config flow.

and after configuration done is showing :  Retrying setup: {'code': -9999, 'message': 'user ack timeout'}

Connected with cloud or manuualy is requesting the Device model and for this model there is noting in the drop-down list correct to add.

Thank you.

**Comment by rytilahti** [comment]
Assuming this is related to the homeassistant integration, there are plans to provide common interfaces to allow it to support other vacuums besides roborock ones (#1114). It will take some development effort and time to make that happen though...

**Comment by Wyfy0107** [comment]
What's the status on this ? I recently bought this vacuum model but having trouble connecting it to home assistatant

**Comment by rytilahti** [comment]
I haven't heard of anyone actively working on this, but you could try one of those custom integrations listed in the readme of this repository, or check out https://github.com/rytilahti/python-miio/pull/1356#issuecomment-1072911196 for some ideas if you wish to collaborate on how to get this done properly.
