### ISSUE TITLE
Firmware on Roborock S6 MaxV 3.5.8_6052 incompatible

### ISSUE THREAD

**Issue by medains** [rytilahti/python-miio#1183]
**Describe the bug**
After upgrading to firmware 3.5.8_6052, unable to communicate with vacuum.

**Version information (please complete the following information):**
 - OS: hassio linux
 - python-miio: 0.5.8

**Device information:**
  - Model: roborock.vacuum.a10
  - Hardware version: Linux
  - Firmware version: 3.5.8_6052

**To Reproduce**
1. Start on firmware 3.5.8_5802
2. Confirm communication working
2. Upgrade to 3.5.8_6052
3. Attempt to communicate with the vacuum

**Expected behavior**
Continued access to vacuum

**Workaround**
Factory reset back to previous firmware.

**Comment by rytilahti** [comment]
I don't think this library can do anything to fix that, so I'm closing this issue.
