### ISSUE TITLE
New device: Xiaomi Air Purifier Pro H

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [rytilahti/python-miio#1186]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi Air Purifier Pro H
  - Link: https://ranking-oczyszczaczy.pl/recenzje/xiaomi-pro-h/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airpurifier.vb2
  - Hardware version:
  - Firmware version: 2.0.8.1002

**Additional context**
Very simmilar to model mb3, Home Assistant exposes one unnecessary entity (fan level), where `favorite level` is working fine.

**Comment by rytilahti** [comment]
This is already supported by airpurifier_miot.
