### ISSUE TITLE
Xiaomi Mi PM2.5 Detector [ Working ]

### ISSUE THREAD

**Issue by FMKaiba** [rytilahti/python-miio#1195]
**Device information:**

  - Name(s) of the device: Xiaomi Mi PM2.5 Detector
  - Link: https://xiaomi-mi.ca/air-purifiers/xiaomi-mi-pm25-detector-white/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airmonitor.v1
  - Hardware version: MW300
  - Firmware version: 1.4.3_8103

**Additional context**
Provides PM 2.5 air quality data. Device is working perfectly with home assistant currently. 

miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['power', 'aqi', 'battery']"
`['on', 1, 100]`
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['usb_state']"
`['on']`
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['time_state']"
`['off']`
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['night_state','night_beg_time','night_end_time']"
`['on', 79200, 25200]`
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['sensor_state']"
`['ready']`

**Comment by rytilahti** [comment]
This is already supported by the airqualitymonitor integration, no? I'm unsure what is the issue in question, but it's good to hear it's working :-)

**Comment by FMKaiba** [comment]
It is working and supported, but provides this message on use of miiocli and home assistant: I assumed a possible different hardware / version not matching up?

`WARNING:miio.device:Found an unsupported model 'zhimi.airmonitor.v1' for class 'AirQualityMonitor'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/`

Enviroment: python-miio = 0.5.9

**Comment by rytilahti** [comment]
Ah, indeed, thanks for reporting! The linked PR adds the supported models information to this class.

**Comment by rytilahti** [comment]
Fixed in 0.5.9.1.
