### ISSUE TITLE
mirobo id_file is not being created automatically

### ISSUE THREAD

**Issue by fabian727** [rytilahti/python-miio#1205]
I followed the manual and got stuck at the step to install the firmware:
mirobo --token XXXXXXXXXXXXXXXX --ip ROBOT_IP_ADDRESS update-firmware path/to/built/image.pkg

instead of the update procedure, I got errors.
I got them fixed by creating an id file with {} as content and reference it.
Instead of above command, I would suggest to use:

echo {} >> id_file.txt mirobo --id-file id_file.txt --token XXXXXXXXXXXXXXXX --ip ROBOT_IP_ADDRESS update-firmware path/to/built/image.pkg

Afterwards I also had to downgrade the producers firmware and everything worked like it should.

Thank you for your service, time and effort in this project. I wouldn't have bought an automatic cleaner, which phones home.

**Comment by rytilahti** [comment]
Hi and thanks for the report, glad that you like the project :-)

Some recent change broke the id file creation logic. Until that is fixed, creating that file manually (`$HOME/.cache/python-miio/python-mirobo.seq` with `{}` as content) also works if you want to avoid using `--id-file`.

**Comment by fabian727** [comment]
can you enhance the manual or fix it? Did take the most time of the installation procedure to get the googling done ;)

**Comment by rytilahti** [comment]
The linked PR should fix this, I suppose it wasn't caught earlier as most of the users (if existing) had already used mirobo already at least once, so it was working just fine :-)
