### ISSUE TITLE
Please add mopping control

### ISSUE THREAD

**Issue by arthur-morgan-1** [rytilahti/python-miio#1215]
Hey,
Please add an option to control mopping functions on Roborock S7
it has 5 levels on mopping + Deep/standard choosing 
It would be very useful to control that. especially to choose between mopping or vacuum only.

**Comment by rytilahti** [comment]
You can use the `set_mop_mode` to control the mopping mode, but it supports currently only two modes (standard and deep). There are also controls for `waterflow` ([which has four options](https://github.com/rytilahti/python-miio/blob/0015a5fe2589a6c9236ee2a0af6ab05e7af54aa0/miio/integrations/vacuum/roborock/vacuum.py#L101)), is this what you mean by levels on mopping?

**Comment by arthur-morgan-1** [comment]
oh. I wonder why none of these are implanted on the Home Assistant integration?

**Comment by rytilahti** [comment]
No one has implemented them, I suppose. :-) To be fair, there was also a major rework a release or two ago to make it easier to add add separate sensors, inputs, buttons etc., and it wasn't that simple to add support for such features. So I hope that someone goes and implements more "exotic" features in the future.

**Comment by shred86** [comment]
In addition to the “mop mode”, there’s also a “scrub intensity” setting with 4 options: close, mild, moderate, intense.

**Comment by shred86** [comment]
Just made a PR #1236 for this with more information. Turns out the existing waterflow methods control the scrub intensity.

**Comment by rytilahti** [comment]
As the PR from @shred86 has been merged, this can be closed now.
