### ISSUE TITLE
Mijia Smart Sterilization Humidifier - deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by madxcc** [rytilahti/python-miio#1225]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Mijia Smart Sterilization Humidifier
  - Link: https://www.aliexpress.com/item/4000996247094.html?spm=a2g0o.search0304.0.0.a6ec51e14VlM8z&algo_pvid=0ddc29ce-d600-4c21-bc2a-f6599ed88419&algo_exp_id=0ddc29ce-d600-4c21-bc2a-f6599ed88419-0

Use `miiocli device --ip <ip address> --token <token>`.

Model: deerma.humidifier.jsq5
Hardware version: esp8266
Firmware version: 2.1.3

**Additional context**
probably a newer version of deerma.humidifier.jsq

"
Mijia Intelligent Sterilization Humidifier (EU version?) | deerma.humidifier.jsq | ZNJSQ01DEM | 4.5L, <=38dB, 300mL/h, 24W
Mijia Intelligent Sterilization Humidifier (EU version?) | deerma.humidifier.jsq5 | ZNJSQ01DEM | 4.5L, <=38dB, 300mL/h, 24W
"
Source: https://github.com/syssi/xiaomi_airpurifier

**Comment by madxcc** [comment]
https://github.com/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/fan.py

**Comment by rytilahti** [comment]
Potentially related to #1193?

**Comment by madxcc** [comment]
Hi!
Its working fine with python-miio/miio/airhumidifier_jsqs.py.
p = miio.airhumidifier_jsqs.AirHumidifierJsqs("<IP>","<TOKEN>")
>>> p.info()
deerma.humidifier.jsq5 v2.1.3 (<MAC>) @ <IP> - token: <TOKEN>
>>> p.status()
<AirHumidifierJsqsStatus buzzer=True error=0 is_on=False led_light=True mode=OperationMode.Auto overwet_protect=None power=off relative_humidity=43 tank_filed=False target_humidity=60 temperature=25 water_shortage_fault=False>
>>> p.on()
[{'did': 'power', 'siid': 2, 'piid': 1, 'code': 0}]
>>> p.off()
[{'did': 'power', 'siid': 2, 'piid': 1, 'code': 0}]
>>>

Thanks!
