### ISSUE TITLE
Found an unsupported model 'zhimi.airpurifier.ma2' for class 'AirPurifier'. after update HomeAassistant 2021.12.0

### ISSUE THREAD

**Issue by FaintGhost** [rytilahti/python-miio#1227]
**Describe the bug**
This `zhimi.airpurifier.ma2` in homeassistant integration Xiaomi Miio page is marked as Supported Device, but after update to homeassistant 2021.12.0, I always got this warning.

**Version information (please complete the following information):**
 - OS: HassOS
 - python-miio: Unknown [Use `miiocli --version` or `pip show python-miio`]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: zhimi.humidifier.v1
  - Hardware version: MW300
  - Firmware version: 1.4.3_5103

  - Model: zhimi.airpurifier.ma2
  - Hardware version: MW300
  - Firmware version: 1.4.3_13108
 
**To Reproduce**
After update HA and everytime reboot HA will got this Warning

**Expected behavior**
No Warning

**Console output**
zhimi.humidifier.v1
```
WARNING:miio.device:Found an unsupported model 'zhimi.humidifier.v1' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
```

zhimi.airpurifier.ma2
```
WARNING:miio.device:Found an unsupported model 'zhimi.airpurifier.ma2' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
```

**Comment by darkkatarsis** [comment]
I will not duplicate the same issue but the problem also concerns zhimi.airpurifier.mb3.
