### ISSUE TITLE
Found an unsupported model 'zhimi.airpurifier.mb4' for class 'AirPurifierMB4'

### ISSUE THREAD

**Issue by Chreece** [rytilahti/python-miio#1228]
**Describe the bug**
As mentioned on other issues, the same problems comes for the model AirPurifierMB4 in Home Assistant 2021.12.0

**Version information (please complete the following information):**
 - OS: [e.g.Linux]
 - python-miio: [Use `miiocli --version` or `pip show python-miio`]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1.

**Expected behavior**

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

**Comment by Krzysztonek** [comment]
Same error here or the model AirPurifierMB4 in Home Assistant 2021.12.0:

![obraz](https://user-images.githubusercontent.com/87784133/145717359-8241fd91-9401-48b3-8b7b-93a320396eed.png)

**Comment by rytilahti** [comment]
Are you perchance using some custom component? The warning should name which class is being used, but it's for both of these cases marked as `Device` which is the base class for all implementations. In any case, the warnings themselves should not cause any issues, so it's unclear why they are not working anymore.

**Comment by Krzysztonek** [comment]
When trying to reintegrate Xiaomi devices, after providing correct cloud credentials, I see the following screens:

![obraz](https://user-images.githubusercontent.com/87784133/145720993-f594f512-d05b-41e4-83db-80da09c7c3fb.png)

And after submission I get this:
![obraz](https://user-images.githubusercontent.com/87784133/145721051-76a787fe-decc-4914-a72b-5c85fe311a41.png)

After this step, despite the `sucessfull` message, I don't see any Xiaomi Miio integrations on http://homeassistant:8123/config/integrations page.

**Comment by XLR-24** [comment]
I have exact the same issue after updating HA to 2021.12.0 with my Xiaomi Philips Zhirui downlights. Working fine in the previous version and now not available in HA. Working fine in the Xiaomi app.

**Comment by XLR-24** [comment]
![Screenshot_20211212-140413](https://user-images.githubusercontent.com/76496739/145721869-5bf3dddf-2e83-4919-a0a2-071f69f6f3bf.jpg)

**Comment by rytilahti** [comment]
#1237 fixes the warnings, if there are other issues please open separate reports on them, thanks!
