### ISSUE TITLE
Add supported models

### ISSUE THREAD

**Issue by luisarn** [rytilahti/python-miio#1230]
Hi!

Is there any chances to add the following models? It was working on 2021.11.5:

MODEL_AIRCONDITION_MA2 = 'xiaomi.aircondition.ma2'
MODEL_SA1 = "zhimi.aircondition.sa1"
MODEL_MA1 = "zhimi.aircondition.ma1"
MODEL_MA2 = "zhimi.aircondition.ma2"
MODEL_MA3 = "zhimi.aircondition.ma3"
MODEL_MA4 = "zhimi.aircondition.ma4"
MODEL_VA1 = "zhimi.aircondition.va1"
MODEL_ZA1 = "zhimi.aircondition.za1"
MODEL_ZA2 = "zhimi.aircondition.za2"

Thanks!
Best regards,
Luis

**Comment by rytilahti** [comment]
Which class is using those, I presume it's something custom? I see no mention for these neither inside homeassistant's code base nor in this code base.

**Comment by luisarn** [comment]
Oh yes! It's a custom component that I'm using for some time.
[mi_airconditioner.zip](https://github.com/rytilahti/python-miio/files/7776984/mi_airconditioner.zip)


I've attached it for your reference.

Thanks!
Luis

**Comment by rytilahti** [comment]
You have to modify that custom component then to add those models to the corresponding class (`AirConditionM1` or `AirConditionC1`) :-) If you are the author, or you know them, maybe you'd consider contributing those implementations to this library at some point?

**Comment by rytilahti** [comment]
Closing as downstream issue, we cannot do anything here.
