### ISSUE TITLE
Found an unsupported model 'zhimi.airpurifier.mc1' for class 'AirPurifier' on Jeedom 4.1.27

### ISSUE THREAD

**Issue by myke94** [rytilahti/python-miio#1234]
**Describe the bug**
Warning after execute command `sudo miiocli airpurifier --ip <ip address> --token <token> status`
but if i execute command
`sudo miiocli airpurifier --ip <ip address> --token <token> off`
or 
`sudo miiocli airpurifier --ip <ip address> --token <token> on`
The air purifier went off and on !!

**Version information:**
 - OS: Raspbian GNU/Linux 10 (buster) 32bits (armv7l)
 - python-miio: `miiocli, version 0.5.9.1`

**Device information:**
`sudo miiocli airpurifier --ip <ip address> --token <token> info` :
  - Model: zhimi.airpurifier.mc1
  - Hardware version: MW300
  - Firmware version: 1.4.3_21106

**To Reproduce**
1. After execute command `sudo miiocli airpurifier --ip <ip address> --token <token> status`

**Expected behavior**
No Warning

**Console output**
`
WARNING:miio.device:Found an unsupported model 'zhimi.airpurifier.mc1' for class 'AirPurifier'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Power: on
AQI: 1 μg/m³
Average AQI: 5 μg/m³
Temperature: 20.3 °C
Humidity: 62 %
Mode: auto
LED: True
LED brightness: None
Illuminance: 0 lx
Buzzer: False
Child lock: False
Favorite level: 14
Filter life remaining: 0 %
Filter hours used: 11908
Use time: None s
Purify volume: None m³
Motor speed: 352 rpm
Motor 2 speed: None rpm
Sound volume: None %
Filter RFID product id: x:x:xx:xx
Filter RFID tag: xx:xx:xx:xx:xx:xx:x
Filter type: FilterType.Regular
Learn mode: False
Sleep mode: None
Sleep time: None
Sleep mode learn count: None
AQI sensor enabled on power off: None
`

**Comment by snp88** [comment]
The same is for humidifiers

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: 19:16:11 (2 occurrences)
Last logged: 19:16:11

Found an unsupported model 'zhimi.airpurifier.mb3' for class 'AirPurifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Found an unsupported model 'zhimi.humidifier.ca4' for class 'AirHumidifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
