### ISSUE TITLE
WARNING (SyncWorker_31) [miio.device] Found an unsupported model 'lumi.gateway.v3' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

### ISSUE THREAD

**Issue by kudouxinyi** [rytilahti/python-miio#1238]
**Describe the bug**

2021-12-13 13:53:16 WARNING (SyncWorker_31) [miio.device] Found an unsupported model 'lumi.gateway.v3' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Version information (please complete the following information):**
 - OS: [docker]
 - python-miio: [Use `miiocli --version` or `pip show python-miio`]

**Comment by rytilahti** [comment]
If this is coming from your own code, you should be using `Gateway` class instead of `Device` to control the device. But I'll create a fix to avoid logging this on the base class.
