### ISSUE TITLE
Found an unsupported model 'zhimi.airpurifier.mb3' for class 'AirPurifierMiot'. after update HomeAassistant 2021.12.0

### ISSUE THREAD

**Issue by snp88** [rytilahti/python-miio#1239]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device: Air Purifier 3/3H
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: Air Purifier 3H
  - Hardware version:
  - Firmware version: 2.0.8.0017

**Comment by rytilahti** [comment]
This is being fixed by #1237
