### ISSUE TITLE
Found an unsupported model 'viomi.vacuum.v8' for class 'Vacuum'. after update HomeAassistant 2021.12.0

### ISSUE THREAD

**Issue by snp88** [rytilahti/python-miio#1240]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device:
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: viomi.vacuum.v8
  - Hardware version:
  - Firmware version:

**Comment by rytilahti** [comment]
Viomi vacuums should be using `ViomiVacuum` class, so you are likely running a custom component that is causing this. Please report to its developer, that the vacuum models should be added to the `_supported_models` of the implementation class to suppress the warning :+1:
