### ISSUE TITLE
after upgrade device not recognized - Air Purifier 3H

### ISSUE THREAD

**Issue by bobofruit1970** [rytilahti/python-miio#1255]
**Device information:**

  - Name(s) of the device: Xiaomi Air Purifier 3H
  - Link: https://mi-store.pl/product-pol-1721-Oczyszczacz-powietrza-Xiaomi-Mi-Air-Purifier-3H.html

  - Model: zhimi.airpurifier.mb3

The warning message is:

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: 17:15:05 (1 occurrences)
Last logged: 17:15:05

Found an unsupported model 'zhimi.airpurifier.mb3' for class 'AirPurifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
Updating to the newest homeassistant release (2021.12.2) that was just released should fix this warning.
