### ISSUE TITLE
chuangmi.remote.h102a03

### ISSUE THREAD

**Issue by Efendis** [rytilahti/python-miio#1260]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: IMI Remote
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: chuangmi.remote.h102a03
  - Hardware version:
  - Firmware version: 1.4.3_10

**Additional context**
 So please help add it into the support list, thanks.

**Comment by rytilahti** [comment]
This should already be supported but lacks support for pronto codes, see #495.
