### ISSUE TITLE
Unsupported model "chuangmi.ir.v2" but it works.

### ISSUE THREAD

**Issue by chertvl** [rytilahti/python-miio#1264]
Hello,

With 2021.12.x update get warning about my IR remote is unsupported model, but it works correctly about 1 year and now works too.
It would be great to remove this warning.

Thanks.

**Device information:**

  - Name(s) of the device:  Xiaomi Mi Universal IR Remote   (old model "NDA-08-GZ" with "Mi" logo on them body, not Mijia)
  - Model: chuangmi.ir.v2
  - Firmware version: 1.2.4_38

![image](https://user-images.githubusercontent.com/38353584/146509764-6b8bb92a-b93b-4f03-bb96-da7cf64d209b.png)
![image](https://user-images.githubusercontent.com/38353584/146510429-7c97183d-ff38-4dab-9dc0-09147f560e0f.png)

**Comment by rytilahti** [comment]
Thanks for the report, this has been fixed in #1258 so the warning will disappear when a new release gets made.
