### ISSUE TITLE
Error: {'code': -9999, 'message': 'user ack timeout'}

### ISSUE THREAD

**Issue by mingfanwang** [rytilahti/python-miio#1265]
root@user-VirtualBox:/# miiocli --version
miiocli, version 0.5.9.2
root@user-VirtualBox:/# miiocli chuangmiplug  --ip 192.168.5.118 --token 21c8b58ad4dafbe03af0e194ef5t6y19 info
WARNING:miio.device:Found an unsupported model 'chuangmi.plug.212a01' for class 'ChuangmiPlug'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Model: chuangmi.plug.212a01
Hardware version: esp32
Firmware version: 2.1.8_0032
root@user-VirtualBox:/# miiocli chuangmiplug  --ip 192.168.5.118 --token 21c8b58ad4dafbe03af0e194ef5t6y19 status
WARNING:miio.device:Found an unsupported model 'chuangmi.plug.212a01' for class 'ChuangmiPlug'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Error: {'code': -9999, 'message': 'user ack timeout'}

**Comment by rytilahti** [comment]
That error may happen if an invalid command (or property) is being accessed. Could you try executing the following to see if you get any valid properties?
```
miiocli device --ip 192.168.5.118 --token 21c8b58ad4dafbe03af0e194ef5t6y19 test_properties power on usb_on temperature wifi_led
```
If you get no positive answers, the device might be miot only and will require another implementation than what is provided by chuangmiplug integration.
