### ISSUE TITLE
Found an unsupported model 'chuangmi.ir.v2' for class 'ChuangmiIr'

### ISSUE THREAD

**Issue by jgyoldi** [rytilahti/python-miio#1268]
Hello,

I have two Xiaomi IR Remote devices and I have installed the latest version of Docker Home assistant, In the log I have found the following warninig:

    Logger: miio.device
    Source: /usr/local/lib/python3.9/site-packages/miio/device.py:155
    First occurred: 19 de diciembre de 2021 14:12:27 (2 occurrences)
    Last logged: 19 de diciembre de 2021 14:12:27
    
    Found an unsupported model 'chuangmi.ir.v2' for class 'ChuangmiIr'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

To add the devices to Home Assistant I did the following some time ago:

    remote:
      - platform: xiaomi_miio
        name: ir_salon
        host: !secret ir_salon_ip
        token: !secret ir_salon_token
        hidden: false
    

And this is my Home Assistan information:

## System Health

version | core-2021.12.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-14-amd64
arch | x86_64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4613
Installed Version | 1.18.0
Stage | running
Available Repositories | 987
Installed Repositories | 66

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 33
views | 18
mode | storage

</details>

Regards.

**Comment by rytilahti** [comment]
Fixed by #1258, so the warning will disappear when a new python-miio version gets released!
