### ISSUE TITLE
Found an unsupported model 'zhimi.airpurifier.vb2' for class 'AirPurifierMiot'. 

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [rytilahti/python-miio#1270]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Mi Air Purifier Pro H
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airpurifier.vb2
  - Hardware version:
  - Firmware version:

**Additional context**
If you declare as zhimi.airpurifier.mb3 in Home Assistant then it works 100% without a problem

**Comment by homecb** [comment]
Getting the same warning for the 3C model:
`Found an unsupported model 'zhimi.airp.mb4a' for class 'AirPurifierMB4'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/`

**Comment by jbsky** [comment]
Hello,
I also have this message in warning: 
```Found an unsupported model 'zhimi.airpurifier.mc2' for class 'AirPurifier'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/```

The entity works except it's missing an important feature for H2, the choice between auto, night or manual mode.

Even if the plugin is not complete, the work on this plugin is excellent.

Thank you very much,

Regards,

Jb

**Comment by rytilahti** [comment]
Thanks for reporting! The models outside 'zhimi.airp.mb4a' were already added so the warning will be removed when the next release gets done.

**Comment by megapearl** [comment]
I have another one:

Logger: miio.device
Source: /srv/homeassistant/lib/python3.9/site-packages/miio/device.py:155
First occurred: 24:50:18 (1 occurrences)
Last logged: 24:50:18

Found an unsupported model 'roborock.vacuum.t6' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

It's the same as a S6 (T = china region, S = europe region) and is working fine.

**Comment by rytilahti** [comment]
@megapearl added to the same PR, thanks :+1:

**Comment by hklages** [comment]
metoo: Mi Air Purifier Pro H EU

Found an unsupported model 'zhimi.airpurifier.vb2' for class 'AirPurifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

I use "zhimi.airpurifier.mb3"

**Comment by rytilahti** [comment]
Those are already in the current master, so the warnings will disappear when a new release gets done. I'll close this now as the PR that added some of the missing ones reported in this issue has already been merged. Thanks everyone for reporting missing models! :-)
