### ISSUE TITLE
viomi pro vxkj03 (viomi.airp.v3)

### ISSUE THREAD

**Issue by viotemp1** [rytilahti/python-miio#1271]
Hello,

Any chance to add viomi pro vxkj03? I tested all purifiers and only ma4/mb3 and can connect.
miiocli airpurifiermb4 --ip x.x.x.x --token xyz status
Power: on
AQI: None μg/m³
Mode: OperationMode.Favorite
LED brightness level: 2875
Buzzer: True
Child lock: None
Filter life remaining: None %
Filter hours used: None
Motor speed: None rpm
Favorite RPM: None rpm

Model: viomi.airp.v3
Hardware version: esp8266
Firmware version: 2.0.7

**Comment by badylek** [comment]
it would be great to see this gaining popularity purify - Viomi Smart Air Purifier Pro

**Comment by stuntik** [comment]
Have the same issue. I didn't expect that this purifier is not supported. So sad. 
My model: VIOMI SMART AIR PURIFIER PRO (VXKJ03)
detected by HA as viomi.airp.v3 when I tried to connect it and failed.

Does anyone have a solution? Any chance you could add support?
