### ISSUE TITLE
Request for new vacuum xiaomi mop 2 pro+ (dreame.vacuum.p2041o)

### ISSUE THREAD

**Issue by robertomontinaro80** [rytilahti/python-miio#1274]
**Device information:**
  - Name(s) of the device: xiaomi mop 2 pro+
  - Link: 

Use `miiocli device --ip <ip address> --token <token>`.

Model: dreame.vacuum.p2041o
Hardware version: Linux
Firmware version: 4.1.2_1107

**Additional context**
Thanks in advance.

**Comment by BernieV1977** [comment]
+ 1 to support this device

**Comment by 2pirko** [comment]
I have similar device: **dreame.vacuum.p2150a**
I'd appreciate if this is supported too.

**Comment by Gugulator** [comment]
also have this device dreame.vacuum.p2041o
please add support for this
