### ISSUE TITLE
chuangmi.ir.v2 not supported

### ISSUE THREAD

**Issue by trevor61** [rytilahti/python-miio#1284]
The IR remote control works using the old manual  method

remote:
  - platform: xiaomi_miio
    name: "Kitchen Remote"
    host: 192.xxx.xxx.xxx
    token:  asdfghjklwertyu

but can't be setup via hacs with the new integration

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:155
First occurred: 22:40:19 (1 occurrences)
Last logged: 22:40:19

Found an unsupported model 'chuangmi.ir.v2' for class 'ChuangmiIr'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
The homeassistant integration needs to be converted to use the config flow for remotes, so this issue is not related to this project and therefore I'll close this.
