### ISSUE TITLE
"dreame.vacuum.mc1808" work well with dreamevacuummiot

### ISSUE THREAD

**Issue by Shqrk** [rytilahti/python-miio#1285]
Hi,

I actually using the Xiaomi Mijia Vacuum 1C STYTJ01ZHM (dreame.vacuum.mc1808)

I can run every command like :

miiocli dreamevacuummiot --ip xxx --token xxx status

and i get correctly every informations like this :

Battery Level : 100
Brush life level : 90
Brush life time : 272
...

I can run perfectly too : 
miiocli dreamevacuummiot --ip xxx --token xxx start
miiocli dreamevacuummiot --ip xxx --token xxx stop
miiocli dreamevacuummiot --ip xxx --token xxx home
miiocli dreamevacuummiot --ip xxx --token xxx identify

But i constently get this message before every result command :

WARNING:miio.device:Found an unsupported model 'dreame.vacuum.mc1808' for class 'DreameVacuumMiot'. 
If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

Is it possible to supress this warning message because it works perfectly for my case ?

Thanks for all your work !

**Describe the bug**

**Version information (please complete the following information):**
 - OS: [e.g.Linux]
 - python-miio: [Use `miiocli --version` or `pip show python-miio`]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1.

**Expected behavior**

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

**Comment by DeutscheGabanna** [comment]
I do not have the `dreamevacuummiot` sub-command when trying `miiocli --help` on `python 3.8-64`. `miiocli` is on 0.5.12 version
