### ISSUE TITLE
Xiaomi Mi AirPurifier PRO H (zhimi.airpurifier.vb2) error

### ISSUE THREAD

**Issue by itmp-git** [rytilahti/python-miio#1295]
Hello and thank you for the time spent developing this things! 

I have added a Xiaomi Air Purifier PRO H to HomeAssistant (latest) as **.zhimi.airpurifier.mb3** because could not figure what else to choose. The integration mostly works ok (buzzer does not work) but I keep getting this error:

**WARNING (SyncWorker_0) [miio.device] Found an unsupported model 'zhimi.airpurifier.vb2' for class 'AirPurifierMiot'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/**

I am lost - added as .mb3 but the error says .vb2 ??
The Pro H is like a Pro but bigger, that is about all. I have tried adding .V7, V6 but they don't work at all.
https://www.mi.com/de/product/mi-air-purifier-pro-h/

Also, according to this documentation, the device is supported but indeed as .v2 ?? (confused)
https://python-miio.readthedocs.io/en/latest/

Maybe if you are kind to shed some light ... 
Thank you!

**Version information (please complete the following information):**
Docker Container running HomeAssistant (Latest) on a Synology NAS (DSM 7)
python-miio: Version: 0.5.9.2

**Device information:**
Model: AC-M13-SC
Firmware version: 2.0.8.1002 (got this from the MiHome app)

**Comment by Kpop77** [comment]
Hi! 

I have exactly the same error message in my log file for the same device i.e Xiaomi Air Purifier PRO H.
What more I have noticed that there is no switch to change mode (Auto, Silent, ...)

I would be grateful for any suggestions and help.

**Comment by itmp-git** [comment]
> What more I have noticed that there is no switch to change mode (Auto, Silent, ...)

Hi, there is for me (I have 4 modes + manual). Everything works, except buzzer, that is not a problem in my case.

<img width="391" alt="Screen Shot 2022-01-14 at 01 41 07" src="https://user-images.githubusercontent.com/90578279/149426205-85198653-d9db-4c27-98ca-1339c57cf600.png">

**Comment by rytilahti** [comment]
This should be fixed now by #1287.

**Comment by Space-Kuh** [comment]
I installed the latest release 0.5.11, but AirPurifier Pro H is still not working properly: 

miiocli airpurifier --ip  _yyy_  --token _xxx_ info
WARNING:miio.device:Found an unsupported model 'zhimi.airpurifier.vb2' for class 'AirPurifier'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Model: zhimi.airpurifier.vb2
Hardware version: esp32
Firmware version: 2.0.8

miiocli airpurifier --ip  _yyy_  --token _xxx_ on
Powering on
WARNING:miio.device:Found an unsupported model 'zhimi.airpurifier.vb2' for class 'AirPurifier'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Error: {'code': -5001, 'message': 'command error'}

Any ideas how to make it work?

**Comment by rytilahti** [comment]
Use `miiocli airpurifiermiot`, that model should work with it.

**Comment by Space-Kuh** [comment]
Thank you so much. That works fine :) 👍

**Comment by Space-Kuh** [comment]
Thank you so much - it works :)--Diese Nachricht wurde von irgendeinem technischen Schnickschnack gesendet.Am 14.03.22, 14:58 schrieb "Teemu R." ***@***.***>:

   
  Use miiocli airpurifiermiot, that model should work with it.
