### ISSUE TITLE
Missing model information for a supported device: Xiaomi Mi Mijia Universal IR Wifi Remote Control MJYKQ01CM 2019

### ISSUE THREAD

**Issue by mshuflin** [rytilahti/python-miio#1296]
Received warning this in the log 
`Found an unsupported model 'chuangmi.remote.v2' for class 'ChuangmiIr'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/`

**Device information:**

  - Name(s) of the device: IR Remote
  - Link: Xiaomi Mi Mijia Universal IR Wifi Remote Control MJYKQ01CM 2019

- Model: chuangmi.remote.v2
- Hardware version: ESP32
- Firmware version: 1.3.1_0014

**Comment by rytilahti** [comment]
Thanks, created PR to fix this for the next release! :+1:
