### ISSUE TITLE
Add new device "Mi Smart Power Plug 2 (Wi-Fi and Bluetooth Gateway)"

### ISSUE THREAD

**Issue by ChrisWang1985** [rytilahti/python-miio#1297]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: chuangmi.plug.212a01
  - Link: https://www.mi.com/buy/detail?product_id=12777&cfrom=search

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: chuangmi.plug.212a01
  - Hardware version:  esp32
  - Firmware version:  2.1.8_0028

**Comment by chertvl** [comment]
https://github.com/rytilahti/python-miio/issues/844

**Comment by rytilahti** [comment]
Closing as dupe, thanks!
