### ISSUE TITLE
Xiaomi STYTJ06ZHM (dreame.vacuum.p2149o)

### ISSUE THREAD

**Issue by JeedHome44** [rytilahti/python-miio#1300]
Hello,

Someone know if this vaccum is possible to control it?

https://a.aliexpress.com/_uyI01z

**Comment by Hypfer** [comment]
The STYTJ06ZHM or "Mijia Self-Cleaning Robot Vacuum-Mop Pro" as Mihome calls it is made by Dreame and should for the most part work with the `dreamevacuum` integration.
There are some additional features that are implemented somewhat strangely but for most automation needs it probably won't require any code changes apart from adding the `dreame.vacuum.p2149o` ID

**Comment by Tontze** [comment]
I have Mi Robot Vacuum-Mop P, which is reported in Homeassistant as viomi.vacuum.v8, and HA says it is unsupported.

**Comment by rytilahti** [comment]
No other than roborock vacuums are supported by homeassistant, I hope this will change after #1495 gets done. #1559 is the issue to track for v8 support.

**Comment by Tontze** [comment]
> No other than roborock vacuums are supported by homeassistant, I hope this will change after #1495 gets done. #1559 is the issue to track for v8 support.

Awesome. I found hacs addon that made this viaomi working In home assistant :)
