### ISSUE TITLE
add Roborock T7S Plus support

### ISSUE THREAD

**Issue by ar4ig** [rytilahti/python-miio#1310]
**Device information:**

  - Name(s) of the device: Roborock T7S Plus
  - Link: https://home.miot-spec.com/s/roborock.vacuum.a23

Model: roborock.vacuum.a23
Hardware version: Linux
Firmware version: 4.1.5_1936

**Comment by rytilahti** [comment]
Is it already working using `miiocli roborockvacuum` or `mirobo`?

**Comment by ar4ig** [comment]
it's realy working, and giving a warning about unsupported device like: 
"Found an unsupported model 'roborock.vacuum.a23' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/"
But sometimes miiocli show me the error like {'code': -10002, 'message': 'access denied'}
I think this is due to the fact that the Roborock T7S Plus made only for china region. can you fix that ?

**Comment by sasukebinbin** [comment]
+1 same

**Comment by rytilahti** [comment]
That message is coming from the device itself, so I'm not sure how to fix that. Does it work if you try it again? If yes, maybe we could add a re-try when receiving that error code, similar to what is done for -30001 (https://github.com/rytilahti/python-miio/blob/master/miio/miioprotocol.py#L272).

**Comment by sasukebinbin** [comment]
I don't think you can fix the error code. It shoule be the crack app problem. 
Like you said it coms from the device itself. 
I think if can please just help on the warning msg. 
(Found an unsupported model 'roborock.vacuum.a23' )

**Comment by rytilahti** [comment]
The next release will fix the warning :+1:
