### ISSUE TITLE
Found an unsupported model 'viomi.vacuum.v7' for class 'Vacuum'.

### ISSUE THREAD

**Issue by takthetank** [rytilahti/python-miio#1313]
Hi I'm getting the following warning in Home Assistant:

`Found an unsupported model 'viomi.vacuum.v7' for class 'Vacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/`

**Device information:**

  - Name(s) of the device: Xiaomi Mi Robot Vacuum Mop P (STY**T**J02YM) (Chinese version)
  - Link: [Mi Robot Vacuum-Mop 2 Pro](https://www.mi.com/global/product/mi-robot-vacuum-mop-2-pro/)
  - Model: viomi.vacuum.v7
  - Hardware version: Linux
  - Firmware version: 3.5.3_0047
  - Home Assistant version: 2021.12.10 (docker container)

**Comment by rytilahti** [comment]
This is coming from a custom component (as viomis are supported by `ViomiVacuum` class in this project), so you have to report it to its developer.

**Comment by takthetank** [comment]
I'm not sure it's the components fault, I only use this and it already has the latest version (almost, 0.5.9.1)

[KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym](https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym/blob/master/custom_components/miio2/manifest.json)

**Comment by rytilahti** [comment]
That custom component is wrapping the vacuum class to provide support for something that isn't supported by this library directly. The simplest fix would probably be adjusting the `_supported_models` inside that component to add the models it supports.

**Comment by takthetank** [comment]
When I try to add the vacuum via the original integration (Xiaomi Miio), although it recognizes it from the cloud,
![image](https://user-images.githubusercontent.com/6099270/153714531-ad62268c-35b4-44c1-b950-a9ae063df461.png)

when I press Submit I get hte following error, and it isn't listed in the `Device Model` dropdown:
![image](https://user-images.githubusercontent.com/6099270/153714543-5c685bab-0b0f-485f-bc38-623ce74354f1.png)

Is it not officially supported?

**Comment by rytilahti** [comment]
It is not currently supported, the integration homeassistant ships supports only roborock vacuums.

**Comment by akshay7394** [comment]
@rytilahti sorry I'm pinging you about this literally more than a year later, I'm nowgetting this issue for the v10 vacuum. But, where would I be able to change the _ supported_models?  And, am I correct in assuming that it's not officially supported but some existing commands may also work on v10?

**Comment by rytilahti** [comment]
The supported models is just used to let people know that they should create an issue to add their device as supported to allow programmatically obtaining the class implementing the support for that device. This is just a warning, so if it's working for you, great!

If it isn't working using the `miiocli viomivacuum`, it might be a bug as that `v10` is also listed as supported (at least in the git version).

**Comment by akshay7394** [comment]
> The supported models is just used to let people know that they should create an issue to add their device as supported to allow programmatically obtaining the class implementing the support for that device. This is just a warning, so if it's working for you, great!
> 
> If it isn't working using the `miiocli viomivacuum`, it might be a bug as that `v10` is also listed as supported (at least in the git version).

Oh okay! So I should just raise an issue to get v10 added to the integration? Because the miiocli method works fine for me
