### ISSUE TITLE
chuangmi.remote.v2 is working but shows a warning

### ISSUE THREAD

**Issue by delicon** [rytilahti/python-miio#1315]
I got this warning in the logs:

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:155
First occurred: 12:58:35 (1 occurrences)
Last logged: 12:58:35

Found an unsupported model 'chuangmi.remote.v2' for class 'ChuangmiIr'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
Fixed by #1258, the warning will disappear when a new release gets done.
