### ISSUE TITLE
Xiaomi Mi Mop-2 Lite ijai.vacuum.v10 is working!

### ISSUE THREAD

**Issue by nautiqu3** [rytilahti/python-miio#1319]
Got the ijai.vacuum.v10 and after pairing it to Mi Home as a Mop Essential and using the MIIO in home assistant it works. 
However it doesnt read sensors. Just works to start and set sweep, mop & sweep and mop. Works to bring the vaccum home as well.

**Comment by danyvega1990** [comment]
How did you get it to work? Mine keeps saying that it's an unknown model in HA

**Comment by Dejv311** [comment]
@nautiqu3 Please bestow upon us your knowledge

**Comment by nautiqu3** [comment]
@danyvega1990 @Dejv311 

I have my vacuum configured to Thailands server. Since I live here. All my other Xiaomi products run on Chinese Mainland.  
After configuring the vacuum to Mi App, I added it as a second account via Xiaomi MIOT Auto. Then it shows up with all the correct values in HA. 

![image](https://user-images.githubusercontent.com/6637988/163708548-e435bc1c-c6dd-400b-9484-b12976932f30.png)


Hope it helps! :)

**Comment by Dejv311** [comment]
Hi, thank you for the feedback. Managed to integrate it thanks to your reply. There is just a little bug with the moping profile being interpreted as the fan speed (even on the photo of yours). I started an issue on the MIOT integration - hopefully they will fix it.

**Comment by escobarin3** [comment]
> Xiaomi MIOT Auto.

How did you integrate it? Did you change location or what did you do? I'm still lost

**Comment by escobarin3** [comment]
> Hi @nautiqu3, thank you for the feedback. Managed to integrate it thanks to your reply. There is just a little bug with the mopping profile being interpreted as the fan speed (even in the photo of yours). I started an issue on the MIOT integration - hopefully they will fix it.

@nautiqu3  How did you integrate it? Did you change location or what did you do? I'm still lost

**Comment by Dejv311** [comment]
Hi, I used the [Xiaomi Miot Auto](https://github.com/al-one/hass-xiaomi-miot) HACS custom integration and then followed the UI based integration process (Integration tab in settings -> "+ add integration"). I used IP/token to integrate the device. You have to make an IP reservation for your Vacuum, so that the IP does not change. When searching for your token you have to choose a server, that is the closest to you (in my case it was Germany). You can find the [token extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)  here. I hope this helps a little.

**Comment by escobarin3** [comment]
@Dejv311 Thanks. Problem solved. :)

**Comment by escobarin3** [comment]
@Dejv311  Another question.. have you managed to use the map generated by the vacuum?

**Comment by Dejv311** [comment]
@escobarin3 Not so far, the author is working hard on implementing it. The Vacuum Mop 2 is using entirely new data system since it is made by a completely different company than the previous Xiaomi vacuums. It will be ready soon.

**Comment by brainrom** [comment]
Also confirm, that it works. Using g1vacuum class. At least start and stop works.

**Comment by rytilahti** [comment]
When #1497 gets merged, it would probably be fairly easy to add support for this model, too.
