### ISSUE TITLE
Xiaomi Smart Air Purifier 4 Pro (zhimi.airp.vb4)

### ISSUE THREAD

**Issue by glowtape** [rytilahti/python-miio#1324]
**Device information:**

  - Name(s) of the device: Xiaomi Smart Air Purifier 4 Pro
  - Link: https://www.mi.com/global/product/xiaomi-smart-air-purifier-4-pro/

  - Model: zhimi.airp.vb4
  - Hardware version: esp32
  - Firmware version: 2.2.0

**Additional context**
Not entirely sure why they have two purifiers "4 Pro" models (well, one has the "Smart" label), but the vb4 model seems different from the earlier va2 whose support was committed last week. The difference seems largely just an additional PM10 field and a "display device unit" service that seems to let you control the temperature unit on the display remotely.

See: https://home.miot-spec.com/spec/zhimi.airp.vb4

It seems like intermittently, I should be able to use the va2 model, tho, without PM10 readouts, as soon a new release happens and Home Assistant bumps their dependency accordingly.

**Comment by glowtape** [comment]
I expected the same, turns out it needs to be defined within the HA component using python-miio, too.

**Comment by LintHart** [comment]
> I expected the same, turns out it needs to be defined within the HA component using python-miio, too.

Ah I really appreciate the clarification. Hopefully it will come as a point release in the next few days. 

Think we should open an issue in HA GitHub ?

**Comment by glowtape** [comment]
Couldn't hurt.

What'd help more on the long-term would be Xiaomi to stop clowning around with the property IDs and make sure they match across (future) models.

**Comment by icegello** [comment]
i bought a Xiaomi Smart Air Purifier 4 Pro and received it yesterday.
i connected it to Mi home app.succesfully  and extracted the token and model info. to connect to HA using xiaomi miio
but failed to connect it to HA . miio does not recognize the 4 pro
i found the model is not "zhimi.airp.vb4" but "Xiaomi.airp.va2b".
does anybody know the difference betwen two model?    is "va2b" newer model ?
