### ISSUE TITLE
ijai.vacuum.v14

### ISSUE THREAD

**Issue by wolnlow** [rytilahti/python-miio#1330]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device:
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3]
  - Hardware version:
  - Firmware version:

**Additional context**
https://home.miot-spec.com/spec/ijai.vacuum.v14

**Comment by rytilahti** [comment]
When #1497 gets merged it should be fairly easy to add support also for this model.
