### ISSUE TITLE
ijai.vacuum.v10 unsupported device

### ISSUE THREAD

**Issue by kramzyukdenis** [rytilahti/python-miio#1335]
**Device information:**

  - Name(s) of the device: Mi Robot Vacuum-Mop 2 Lite
  - Link:

  - Model: ijai.vacuum.v10
  - Hardware version: esp32
  - Firmware version: 2.1.7_0038

**Comment by danyvega1990** [comment]
Is this issue dead or someone is working on it?

**Comment by rytilahti** [comment]
This is an open source project without any affiliation to xiaomi nor any of the product vendors, I suppose I should update the readme to make it clear... :-)

So, assuming that no one has indicated here that they are working on it, I doubt someone is working on it currently.

**Comment by danyvega1990** [comment]
Sad, somehow I was expecting it tho

**Comment by rytilahti** [comment]
Duplicate of #1319
