### ISSUE TITLE
Roborock S7 MaxV

### ISSUE THREAD

**Issue by h3nrytan** [rytilahti/python-miio#1336]
- Name(s) of the device: Roborock S7 MaxV
  - Link: https://us.roborock.com/pages/roborock-s7-maxv

  - Model: roborock.vacuum.a27
  - Firmware version: 4.1.5_3246

**Comment by h3nrytan** [comment]
Logs:
Found an unsupported model 'roborock.vacuum.a27' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

So far it is working well.

**Comment by rytilahti** [comment]
Thanks for reporting @h3nrytan!
