### ISSUE TITLE
Support for Smartmi Smart Fan Heater (zhimi.heater.nb1)

### ISSUE THREAD

**Issue by solidssss** [rytilahti/python-miio#1338]
**Device information:**

  - Name(s) of the device: Smartmi Smart Fan Heater (zhimi.heater.nb1)
  - Link: https://www.amazon.es/Xiaomi-Heizger%C3%A4t-Leistung-Schwenkbetrieb-steuerbar/dp/B08P64ZGJJ

  - Model: zhimi.heater.nb1
  - Hardware version: esp32
  - Firmware version: 2.0.8

It would be really nice if this device could be added.

**Comment by rytilahti** [comment]
If you feel comfortable writing some python, take a look at https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-nb1:1 . The implementation for zhimi's miot is at https://github.com/rytilahti/python-miio/blob/master/miio/heater_miot.py which requires creating a mapping between the information in that miot-spec file and the implementation.

**Comment by solidssss** [comment]
> If you feel comfortable writing some python, take a look at https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-nb1:1 . The implementation for zhimi's miot is at https://github.com/rytilahti/python-miio/blob/master/miio/heater_miot.py which requires creating a mapping between the information in that miot-spec file and the implementation.

Thanks for the info. Maybe someone might be able to get this device working with the info you posted. Sadly I got very little knowledge with python and cannot implement this myself...
