### ISSUE TITLE
HA : Found an unsupported model 'dmaker.fan.p11' for class 'FanP11'.

### ISSUE THREAD

**Issue by SNoof85** [rytilahti/python-miio#1347]
**Describe the bug**
Log in HA : 
```Found an unsupported model 'dmaker.fan.p11' for class 'FanP11'.```
My fan is working very fine from HA. All commands are working.  Never had any problem !

**Version information (please complete the following information):**
 - OS: HA OS
 - python-miio: Latest included in HA ?

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
- Model: dmaker.fan.p11
- Hardware version: esp8266
- Firmware version: 2.1.3

**To Reproduce**
1. Start HA !

**Expected behavior**
No log ?

**Console output**
N.A

**Comment by rytilahti** [comment]
This warning has been fixed in #1345 and it will disappear at some point when a new version of python-miio gets released and updated to homeassistant.
