### ISSUE TITLE
viomise not work anymore with viomi v3

### ISSUE THREAD

**Issue by CCVEI** [rytilahti/python-miio#1361]
Until some time ago, (feb. upgrade of HA) my viomi v3 was working good with viomise.
Now it give me error in configuration.yaml

Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

Anyone knows how to solve this ?
Thanks

**Comment by rytilahti** [comment]
There is no [`Vacuum` anymore since the newest release](https://github.com/rytilahti/python-miio/releases/tag/0.5.11) as it was replaced with `RoborockVacuum`. I don't know what "viomise" is, but this issue needs to be fixed at their end so I'm closing this.
