### ISSUE TITLE
roborock.vacuum.c1

### ISSUE THREAD

**Issue by zombie4000** [rytilahti/python-miio#1369]
**Device information:**

  - Name(s) of the device: Xiaowa Lite c1 / Roborock xiaowa c10
  - Link: https://xiaomi-mi.com/cleaning-gear/roborock-xiaowa-vacuum-cleaner-c10-white/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: roborock.vacuum.c1
  - Hardware version: ESP8266
  - Firmware version: 1.3.5

**Additional context**
Found #426 added limited support for roborock.vacuum.c1, but logs said to report this device if it works and it does.

![image](https://user-images.githubusercontent.com/5443050/159185156-ed5e9f1d-a4ba-46d1-8fb0-6fa39c414583.png)
Everything works fine in Home Asistant, except this:
- Consumable
- DnD
- Total counts 

the mirobo commands show all these things, example:
```
mirobo --ip --token consumables:
WARNING:miio.device:Found an unsupported model 'roborock.vacuum.c1' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Main brush:   1 day, 11:26:51 (left 11 days, 0:33:09)
Side brush:   1 day, 11:26:51 (left 6 days, 20:33:09)
Filter:       1 day, 11:26:51 (left 4 days, 18:33:09)
Sensor dirty: 1 day, 11:26:51 (left -1 day, 18:33:09)
```

**Comment by rytilahti** [comment]
Hey @zombie4000 and thanks for chiming in, I'll create a PR to add that model to the list of supported ones so that warning will disappear in the future releases.

Those entities are greyed out as they are disabled, you have to enable them separately to make their values appear.
