### ISSUE TITLE
Unsupported model zhimi.airp.rmb1

### ISSUE THREAD

**Issue by getharder** [rytilahti/python-miio#1398]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi Smart Air Purifier 4 Lite
  - Link: https://home.miot-spec.com/s/zhimi.airp.rmb1  /  https://www.mi.com/de/product/xiaomi-smart-air-purifier-4-lite/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airp.rmb1
  - Hardware version: unkown
  - Firmware version: unkown

thank you, if you need further information contact me, would be happy to help.

**Comment by benwie** [comment]
run into the same problem, would appreciate support for the device!
