### ISSUE TITLE
Cannot turn on or turn off device

### ISSUE THREAD

**Issue by TrustedFloppa** [rytilahti/python-miio#1410]
**Describe the bug**
Cannot turn on or off device

**Version information (please complete the following information):**
 - OS: windows
 - python-miio: C:\Users\acera>miiocli --version
miiocli, version 0.5.10

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
 Model: zhimi.airpurifier.mb3
Hardware version: esp32
Firmware version: 2.0.8

**Expected behavior**
Device turn on

**Console output**
C:\Users\acera>miiocli fan --ip (ip removed) --token (token removed) on
Powering on
WARNING:miio.device:Found an unsupported model 'zhimi.airpurifier.mb3' for class 'Fan'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Error: {'code': -5001, 'message': 'command error'}

**Comment by rytilahti** [comment]
Use `miiocli airpurifiermiot`, that should work :-)
