### ISSUE TITLE
Please add dreame.vacuum.p2140p 

### ISSUE THREAD

**Issue by dmitriytim** [rytilahti/python-miio#1412]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - dreame.vacuum.p2140p:
  - Link: https://home.miot-spec.com/s/dreame.vacuum.p2140p
 

Use `miiocli device --ip <ip address> --token <token>`.

Model: dreame.vacuum.p2140p
Hardware version: Linux
Firmware version: 4.1.6_1012

   # https://home.miot-spec.com/spec/dreame.vacuum.p2140p
    "battery_level": {"siid": 3, "piid": 1},
    "charging_state": {"siid": 3, "piid": 2},
    "device_fault": {"siid": 2, "piid": 2},
    "device_status": {"siid": 2, "piid": 1},
    "brush_left_time": {"siid": 9, "piid": 1},
    "brush_life_level": {"siid": 9, "piid": 2},
    "filter_life_level": {"siid": 11, "piid": 1},
    "filter_left_time": {"siid": 11, "piid": 2},
    "brush_left_time2": {"siid": 10, "piid": 1},
    "brush_life_level2": {"siid": 10, "piid": 2},
    "operating_mode": {"siid": 4, "piid": 1},
    "cleaning_mode": {"siid": 4, "piid": 4},
    "timer_enable": {"siid": 5, "piid": 1},
    "cleaning_time": {"siid": 4, "piid": 2},
    "cleaning_area": {"siid": 4, "piid": 3},
    "first_clean_time": {"siid": 12, "piid": 1},
    "total_clean_time": {"siid": 12, "piid": 2},
    "total_clean_times": {"siid": 12, "piid": 3},
    "total_clean_area": {"siid": 12, "piid": 4},
    "start_time": {"siid": 5, "piid": 2},
    "stop_time": {"siid": 5, "piid": 3},
    "map_view": {"siid": 6, "piid": 1},
    "frame_info": {"siid": 6, "piid": 2},
    "object_name": {"siid": 6, "piid": 3},
    "map_extend_data": {"siid": 6, "piid": 4},
    "volume": {"siid": 7, "piid": 1},
    "voice_package": {"siid": 7, "piid": 2},
    "water_flow": {"siid": 4, "piid": 5},
    "water_box_carriage_status": {"siid": 4, "piid": 6},
    "timezone": {"siid": 8, "piid": 1},
    "home": {"siid": 3, "aiid": 1},
    "locate": {"siid": 7, "aiid": 1},
    "start_clean": {"siid": 4, "aiid": 1},
    "stop_clean": {"siid": 4, "aiid": 2},
    "reset_mainbrush_life": {"siid": 9, "aiid": 1},
    "reset_filter_life": {"siid": 11, "aiid": 1},
    "reset_sidebrush_life": {"siid": 10, "aiid": 1},
    "play_sound": {"siid": 7, "aiid": 2},

Please, if possible, the main thing is to find out the id of the room and set the address cleaning,
like they said that the room ID returns when the cleaning is completed, but I could not catch this event.

**Comment by dmitriytim** [comment]
run miiocli dreamevacuum --model dreame.vacuum.p2140p --ip 192.168.1.154 --token ********* raw_command  action '{"did":"1027278185","siid"
:4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[1,1,0,3,1]]}"}]}'
clean room -success - 

action '{"did":"1027278185","siid":4,"aiid":1,"in":[{"piid":1,"value":20},{"piid":10,"value":"{\"points\":[[2985,1771,1,0,3]]}"}]}'
clean selected zone

**Comment by rytilahti** [comment]
That looks similar to this mapping: https://github.com/rytilahti/python-miio/blob/master/miio/integrations/vacuum/dreame/dreamevacuum_miot.py#L72 so adding a new entry for it would be enough. Mind creating a PR?
