### ISSUE TITLE
Please add IMILAB v1 Vacuum (chuangmi.vacuum.hmi707 model)

### ISSUE THREAD

**Issue by omegasxxi** [rytilahti/python-miio#1418]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device:
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3]
  - Hardware version:
  - Firmware version:

**Comment by rytilahti** [comment]
Yes, it would be great to have a common miot implementation integrated into this library, as there are also people who do not use homeassistant. Unfortunately I have currently no miot devices nor time to work on a "miot" integration to make that happen. https://github.com/rytilahti/python-miio/issues/1495 tracks the state for exposing sensors, settings and switches dynamically, which will be a prerequisite for that.
