### ISSUE TITLE
miio.device:Found an unsupported model 'dreame.vacuum.p2027' for class 'DreameVacuum'

### ISSUE THREAD

**Issue by kris2k2** [rytilahti/python-miio#1420]
**Device information:**

  - Name(s) of the device: Dreame W10
  - Link: https://home.miot-spec.com/spec/dreame.vacuum.p2027
  - Link: https://www.dreametech.com/products/dreame-w10

Use `miiocli device --ip <ip address> --token <token> info.`
- Model: dreame.vacuum.p2027
- Hardware version: Linux
- Firmware version: 4.1.8_1092

Results of : 
`miiocli dreamevacuum --ip <ip> --token <token> status`

WARNING:miio.device:Found an unsupported model 'dreame.vacuum.p2027' for class 'DreameVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
WARNING:miio.miot_device:Unable to find mapping for dreame.vacuum.p2027, falling back to dreame.vacuum.mc1808
ERROR:miio.integrations.vacuum.dreame.dreamevacuum_miot:Unknown ChargingStats (0)
ERROR:miio.integrations.vacuum.dreame.dreamevacuum_miot:Unknown model for cleaning mode (dreame.vacuum.p2027)
ERROR:miio.integrations.vacuum.dreame.dreamevacuum_miot:Unknown FaultStatus (100)
ERROR:miio.integrations.vacuum.dreame.dreamevacuum_miot:Unknown OperatingMode (96)
Battery level: 8
Brush life level: None
Brush left time: None
Charging state: None
Cleaning mode: None
Device fault: None
Device status: Sweeping
Filter left level: None
Filter life level: None
Life brush main: None
Life brush side: None
Life sieve: None
Map view: None
Operating mode: None
Side cleaning brush left time: None
Side cleaning brush life level: None
Time zone: None
Timer enabled: None
Timer start time: None
Timer stop time: None
Voice package: None
Volume: None
Water flow: None
Water box attached: None 
Cleaning time: 77
Cleaning area: None
First clean time: None
Total clean time: None
Total clean times: None
Total clean area: None

**Comment by rytilahti** [comment]
This device should work using `miiocli genericmiot` so I'll close this issue.
