### ISSUE TITLE
Unsupported model: yeelink.light.color7 but mostly works fine

### ISSUE THREAD

**Issue by ai-93** [rytilahti/python-miio#1425]
**Device information:**
  - Name of the device: Mi LED Smart Color Bulb (B22) (Model No: MJDPL02YL)
  - Link: https://store.mi.com/in/item/3203800022

`miiocli device --ip <ip address> --token <token> info`

  - Model: yeelink.light.color7
  - Hardware version: esp8266
  - Firmware version: 2.0.8_0012

**Additional context**

`miiocli yeelight --ip <ip address> --token <token>  status`

    - Name: den_light
    - Update default on change: True
    - Delay in minute before off: 0
    - Music mode: True
    - Developer mode: True
    - Main light
       - Power: True
       - Brightness: 100
       - Color mode: ColorTemperature
       - Temperature: 5714
       - Color flowing mode: False

Music mode being set to true seams a bit odd to me since this device is not advertised to support that.

All the other commands to controll the device seem to be working too except for dump_ble_debug, i am asuming this is an invalid command for this device since it is an esp8266.

`miiocli yeelight --ip <ip address> --token <token>  dump_ble_debug`

    - Error: {'code': -9999, 'message': 'user ack timeout'}

**Comment by rytilahti** [comment]
If you use `--debug`, it will show you the returned payload. Maybe the device just sets the property related to music mode as true even when it's not support nor in use. The linked PR will remove the warning log message.
