### ISSUE TITLE
Unsupported model roborock.vacuum.a46

### ISSUE THREAD

**Issue by gfl699468** [rytilahti/python-miio#1435]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Roborock G10S
  - Link: https://home.miot-spec.com/s/roborock.vacuum.a46
  - It's china version S7 MaxV with structured light camera instead of RGB camera

  - Model: roborock.vacuum.a46
  - Hardware version: Linux
  - Firmware version: 4.1.5_1052

**Additional context**
For now, only found two unknown status:
**26 -> "going to wash the mop"
23 -> "washing the mop"**
perhaps should update code here
https://github.com/rytilahti/python-miio/blob/0b66fb5041e19ea2afcd4688401154f1f67cbea1/miio/integrations/vacuum/roborock/vacuumcontainers.py#L96-L118
is there anything else should be update?

**Comment by rytilahti** [comment]
Thanks for reporting @gfl699468, the linked PR marks this as supported and adds those new status codes.

**Comment by Cefold** [comment]
When will this PR be released?

**Comment by rytilahti** [comment]
Hopefully by the end of this weekend!
