### ISSUE TITLE
Exception when displaying Power load using Plug CLI

### ISSUE THREAD

**Issue by zacharynguyeenx** [rytilahti/python-miio#144]
**Problem**: Running the Plug CLI will cause an exception on `plug_cli.py:81` when displaying Power load due to `PlugStatus.load_power()` not available.

**Suggestion**: get rid of this line or implement `PlugStatus.load_power()`

**Comment by rytilahti** [comment]
Currently only powerstrip offers load_power, I think the cli tool should be modified to detect what type of plug device it's accessing and behave accordingly. Similar to what is done in https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/xiaomi_miio.py .

**Comment by clemenation** [comment]
Ain't the Plug CLI only be used for plugs? `plug_cli.py:56` initializes a `Plug` and there's no initialization of `PowerStrip` found in there.

If it's only for plugs then we don't really have to care about detecting its type for now.

**Comment by rytilahti** [comment]
It would be nice to be able to control also e.g. that powerstrip with the same tool for two reasons: 1) I have not find time to create a generic tool allowing control of all supported devices, and won't be able to do so in the near future, and 2) the interface for plugs and that of the strip share many things in common, so supporting both would not be a big hurdle.
