### ISSUE TITLE
cant import gateway from miio

### ISSUE THREAD

**Issue by exeq89** [rytilahti/python-miio#1443]
**Describe the bug**
Problem with script that worker fine

**Version information (please complete the following information):**
 - OS: fedora 36
 - python-miio: 
  pip show python-miio
Name: python-miio
Version: 0.5.11
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu R
Author-email: tpr@iki.fi
License: GPL-3.0-only
Location: /usr/local/lib/python3.10/site-packages
Requires: android_backup, appdirs, attrs, click, construct, croniter, cryptography, defusedxml, netifaces, pytz, PyYAML, tqdm, zeroconf
Required-by:

**To Reproduce**
1. get into python3
2. run from miio import Gateway:
```
Python 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from miio import Gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/miio/__init__.py", line 4, in <module>
    from importlib_metadata import version  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/usr/local/lib/python3.10/site-packages/importlib_metadata/_adapters.py", line 3, in <module>
    import email.message
  File "/usr/lib64/python3.10/email/message.py", line 15, in <module>
    from email import utils
  File "/usr/lib64/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/etc/zabbix/scripts/socket.py", line 11, in <module>
    from miio import Gateway
ImportError: cannot import name 'Gateway' from partially initialized module 'miio' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/miio/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/miio/__init__.py", line 7, in <module>
    from importlib.metadata import version  # type: ignore
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/usr/lib64/python3.10/importlib/metadata/_adapters.py", line 3, in <module>
    import email.message
  File "/usr/lib64/python3.10/email/message.py", line 15, in <module>
    from email import utils
  File "/usr/lib64/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "/etc/zabbix/scripts/socket.py", line 11, in <module>
    from miio import Gateway
ImportError: cannot import name 'Gateway' from partially initialized module 'miio' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/miio/__init__.py)
```

**Expected behavior**
import gateway from miio ;)

i got some scripts that read temp/humidity and i put them in zabbix, everything was working till yesterda. i didnt install anything new, script is:
```
#!/usr/bin/env python3
import sys, os
# Disable
def blockPrint():
    sys.stderr = open(os.devnull, 'w')

# Restore
def enablePrint():
    sys.stdout = sys.__stdout__

from miio import Gateway
gateway = Gateway("192.168xxxxx", "xxxxx")
blockPrint()
gateway.discover_devices()
enablePrint()
devices = gateway.devices
weather_sensor_1 = devices["lumi.158d0001fa6d43"]
weather_sensor_1.update()
#print(weather_sensor_1.status)
print(weather_sensor_1.status["humidity"])
```

**Comment by TrustedFloppa** [comment]
Uninstall Python-miio and replace it with this version https://github.com/rytilahti/python-miio/releases/tag/0.5.10

**Comment by rytilahti** [comment]
Please rename your script (`/etc/zabbix/scripts/socket.py`) to be something else than `socket.py` and it should work again. I didn't look into why this worked in previous releases, but it's just better to avoid namespace conclusions. The problem is that an import in `miio/__init__.py` (the first line in the stack trace) causes some code in importlib to import a module named `socket` which tries again to import `miio`, causing that circular dependency.

You should always avoid naming your own python files after module names of any external modules (be it a standard library or 3rd party one) that might be imported by other code to avoid such :-)

**Comment by exeq89** [comment]
> 

OMG, you are 'tha' man :)
i forgot i wanted try to read the readings from my zigbee socket, and named a script with socket.py
now i see in stack trace that there is socket.py .. i knew it something easy and stupid. thank you one more time very much :)
