### ISSUE TITLE
Miio integration errors, but I fid not connect this vacuum cleaner in the integration.

### ISSUE THREAD

**Issue by VikeDragon** [rytilahti/python-miio#1452]
The problem
Miio integration errors, but I did not connect this vacuum cleaner in the integration:
Logger: miio.device
Source: /usr/local/lib/python3.10/site-packages/miio/device.py:158
First occurred: 08:42:02 (1 occurrences)
Last logged: 08:42:02

Found an unsupported model 'dreame.vacuum.p2008' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

What version of Home Assistant Core has the issue?
2022.7.2

What was the last working version of Home Assistant Core?
2022.6.7

What type of installation are you running?
Home Assistant Supervised

Integration causing the issue
Xiaomi Miio

Link to integration documentation on our website
https://www.home-assistant.io/integrations/xiaomi_miio

Diagnostics information
No response

Example YAML snippet
No response

Anything in the logs that might be useful for us?
Logger: miio.device
Source: /usr/local/lib/python3.10/site-packages/miio/device.py:158
First occurred: 08:42:02 (1 occurrences)
Last logged: 08:42:02

Found an unsupported model 'dreame.vacuum.p2008' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Additional information
No response

**Comment by rytilahti** [comment]
I'm not sure how you managed to get 'RoborockVacuum' initialized for 'dreame.vacuum.p2008', but that will not work as they are completely different implementations...

The homeassistant integration does not unfortunately currently support other than roborock vacuums.

**Comment by VikeDragon** [comment]
After the updates, the problem disappeared. Although she surprised me no less - why pour errors about what I don't have.
