### ISSUE TITLE
Add support for Xiaomi Robot Vacuum-Mop 2C XMSTJQR2C

### ISSUE THREAD

**Issue by aordynsk** [rytilahti/python-miio#1455]
Please add support for new Xiaomi Robot 

Name: Xiaomi Robot Vacuum-Mop 2C
Model: dreame.vacuum.md1808
Model number: XMSTJQR2C
firmware: 4.3.3_1014

Thanks

**Comment by marceloncosta** [comment]
Excuse my ignorance, but is this topic resolved? I also have a Xiaomi Robot Vacuum-Mop 2C (dreame.vacuum.md1808) and I'm not able to add it to Home Assistant. Or am I doing something wrong? Thanks.
