### ISSUE TITLE
[Scishare Coffe Maker] some commands not working

### ISSUE THREAD

**Issue by OraOraOra0ra** [rytilahti/python-miio#1470]
**Describe the bug**
As a beginner, I encountered some problems when trying to control scishare coffee maker:
After I successfully connected the coffee machine, its commands such as 'on()', 'off()', 'status()' and 'info()' can be used normally, but I tried 'preheat' and 'stop_preheat()' when using the preheat command, I got the return value of 'ok', but the coffee machine didn't respond. Trying boil when a series of instructions such as 'boil_water(160,55)' or make coffee like 'brew_espresso(16,80)', I can only get the return value of 'false'. I can't understand why this is the case. I hope to get your reply.

**Version information (please complete the following information):**
 - OS: Win11
 - python-miio: 0.5.11

**Device information:**
  - Model:scishare.coffee
  - Hardware version:It will be added later
  - Firmware version:It will be added later

**To Reproduce**
'from miio.scishare_coffeemaker import ScishareCoffee'
'sc = ScishareCoffee(ip='xxxxx',token='xxxxxx‘’)'
'sc.on()'
'sc.status()'
'sc.preheat()'
'sc.stop_preheat()'
'sc.boil_water(160, 55)'
'sc.brew_espresso(16,80)'

**Expected behavior**
I hope to control the coffee machine through clear instructions

**Comment by rytilahti** [comment]
See #979
