### ISSUE TITLE
Support for Mi Robot Vacuum-Mop 2 Pro+ (dreame.vacuum.p2041o)

### ISSUE THREAD

**Issue by Gugulator** [rytilahti/python-miio#1476]
Xiamo Miio integration does not have device in the list of available devices.
Trying to sync device from MI account. It is stored in Singapore (sg) location.
Device type: vacuum cleaner
Name: Mi Robot Vacuum-Mop 2 Pro+
Model: STYTJ02ZHM
Real model name: dreame.vacuum.p2041o
Current firmware: 4.3.3._1109

**Comment by arvaisandor1968** [comment]
I have a same problem 2022-07-27 16:26:54 WARNING (SyncWorker_2) [miio.device] Found an unsupported model 'dreame.vacuum.p2041o' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
Looks like this is coming from the homeassistant integration which currently supports only roborock vacuums. There's a plan (https://github.com/rytilahti/python-miio/issues/1114) to consolidate the API to make vacuums from all supported vendors usable in homeassistant, but it needs someone to volunteer to work on it to make that happen.

I'm closing this issue as you can already use the p2041o using this library (`DreameVacuum` class, or from cli using the `miiocli dreamevacuum` command) .
