### ISSUE TITLE
netifaces, cffi, pycryptodome do not build correctly when installing python-miio

### ISSUE THREAD

**Issue by uifor** [rytilahti/python-miio#1481]
PHICOMM N1 is a soft router of arm architecture, installed openwrt, and then encountered these problems when installing python-miio, and it still cannot be installed correctly. It was installed correctly one or two years ago, but now the new version cannot be installed

![image](https://user-images.githubusercontent.com/13254011/181460053-1c06d7cf-ade1-434b-9891-39f99ad30862.png)

**Comment by rytilahti** [comment]
There is nothing this library can easily do to make it work on your platform, you should report this to the developers of the platform you are using and/or request the developers of those dependencies to provide python pre-compiled wheels to the platform.
