### ISSUE TITLE
yeelink.light.mono6 works

### ISSUE THREAD

**Issue by tomechio** [rytilahti/python-miio#1491]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device:
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3]
  - Hardware version:
  - Firmware version:

Miiocli returned this error message to me but the wifi led bulb works perfectly:

WARNING:miio.device:Found an unsupported model 'yeelink.light.mono6' for class 'Yeelight'. 

Now this Xiaomi led buld appeared to my Homeassistant as a Yeelight.

**Comment by rytilahti** [comment]
Could you create a PR to add the information about the bulb to https://github.com/rytilahti/python-miio/blob/master/miio/integrations/light/yeelight/specs.yaml ? I think this is similar to other mono bulbs.

**Comment by asoliverez** [comment]
mono6 is already in the specs.yaml file, but it's still throwing unknown model warning

**Comment by rytilahti** [comment]
Maybe it was added after the most recent release, so it's available only on current git master. But the bulb indeed works, it's also the device I'm using to develop the genericmiot support:
```
❯ miiocli yeelight status
Name: 
Update default on change: True
Delay in minute before off: 0
Developer mode: False
Main light
   Power: True
   Brightness: 60
   Color mode: None
   Temperature: None
   Color flowing mode: False
```
```
❯ miiocli genericmiot status
Service Light (light)
        Switch Status (light:on, access: RW): True (<class 'bool'>, )
        Brightness (light:brightness, access: RW): 60 % (<class 'int'>, min: 1, max: 100, step: 1)
        Power Off Delay Time (light:off-delay-time, access: RW): 0:00:00 (<class 'int'>, min: 0, max: 120, step: 1)
```

**Comment by abu-matterize** [comment]
> mono6 is already in the specs.yaml file, but it's still throwing unknown model warning

Same here. What's your version?
