### ISSUE TITLE
Found an unsupported model roborock.vacuum.a01

### ISSUE THREAD

**Issue by B48D81EFCC** [rytilahti/python-miio#1493]
Hello,

I am using Home Assistent with Xiaomi Miio integration and added my Roborock E4 (no custom firmware etc.).
In the logs I found: Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'.

Nevertheless, I am able to:
- Start cleaning 
- Pause cleaning
- Send the robot back to base

Retrieve entities like
- Current clean area
- Current clean duration
- Filter left
- Last clean area
- Last clean duration
- Last clean end
- Last clean start
- Main brush left
- Sendor sirty left
- Side brush left

From my point of view the device is working.

**Device information:**

- Name(s) of the device: Roborock E4
- Link: https://roborock.com/pages/roborock-e4

- Model: roborock.vacuum.a01
-  Hardware version: esp32
- Firmware version: 2.0.8_0912

**Comment by Lord-Memester** [comment]
```Logger: miio.device
Source: components/xiaomi_miio/__init__.py:233
First occurred: 8:20:43 AM (1 occurrences)
Last logged: 8:20:43 AM

Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
````
This is still listed as an unsupported model for me, but as the original issue stated, it works just fine. I'm using version `0.5.12` of `python-miio` according to the diagnostics file I downloaded from the Xiaomi Miio integration.
