### ISSUE TITLE
xiaomi philips bulb & philips ceiling

### ISSUE THREAD

**Issue by Iv711** [rytilahti/python-miio#151]
Hello.
Who managed to get these lamps to work in Domoticz?
I would be grateful if someone prompted a little instruction for this
Thank you!

**Comment by rytilahti** [comment]
This is not a support forum, I think you'd be best served by contacting Domoticz forums / support channels :-)

**Comment by Iv711** [comment]
I answer myself to my question:

```
sudo su
apt-get install python3-dev
apt-get install python3-pip
apt-get install libffi-dev libssl-dev
apt-get install git-core
pip3 install virtualenv
virtualenv -p python3 testenv
source testenv/bin/activate
pip install -U setuptools
pip install -e git+https://github.com/rytilahti/python-mirobo#egg=python-mirobo
deactivate
sudo mv /home/pi/testenv/bin/miceil /usr/local/bin/
```
And.. Create Dummy + Lua 
commandArray = {}
```
if (devicechanged['Xiaomi Philips Люстра'] == 'On') then
    os.execute('miceil --ip 192.168.1.5 --token 182ab112341dd826b19264a6239c11 on')
elseif (devicechanged['Xiaomi Philips Люстра'] == 'Off') then
    os.execute('miceil --ip 192.168.1.5 --token 182ab112341dd826b19264a6239c11 off')
    end
return commandArray
```

**Comment by arek156** [comment]
Hi, I have a question where to get a light bulb token?

**Comment by deennoo** [comment]
That the tricky parts.

Use mitool kits (Windows app who backup and search for token on your android MiHome app).

Mitool kits need an old version off MiHome 5.0.6 one still store token on app dB. Newer ones doesn't store token

**Comment by arek156** [comment]
unfortunately my huawei p9 requires a password when making a copy, while the mihomekit application displays a message to not enter the password and unfortunately I can not read the key: /

**Comment by salcabo** [comment]
> I answer myself to my question:
> 
> ```
> sudo su
> apt-get install python3-dev
> apt-get install python3-pip
> apt-get install libffi-dev libssl-dev
> apt-get install git-core
> pip3 install virtualenv
> virtualenv -p python3 testenv
> source testenv/bin/activate
> pip install -U setuptools
> pip install -e git+https://github.com/rytilahti/python-mirobo#egg=python-mirobo
> deactivate
> sudo mv /home/pi/testenv/bin/miceil /usr/local/bin/
> ```
> And.. Create Dummy + Lua
> commandArray = {}
> 
> ```
> if (devicechanged['Xiaomi Philips Люстра'] == 'On') then
>     os.execute('miceil --ip 192.168.1.5 --token 182ab112341dd826b19264a6239c11 on')
> elseif (devicechanged['Xiaomi Philips Люстра'] == 'Off') then
>     os.execute('miceil --ip 192.168.1.5 --token 182ab112341dd826b19264a6239c11 off')
>     end
> return commandArray
> ```

Can you tell me if its possible to dim light from domoticz? I know nothing about lua

Thanks
