### ISSUE TITLE
Air quality monitor cgllc.airmonitor.s1 may have updated miio structure after firmware update

### ISSUE THREAD

**Issue by yankebupt** [rytilahti/python-miio#1517]
Air quality monitor cgllc.airmonitor.s1 may have updated datagram structure after firmware update
It gives
ValueError: dictionary update sequence element #0 has length 1; 2 is required
after firmware update

tried:restarting raspberry pi, restart air quality monitor.

**Comment by yankebupt** [comment]
I printed "values" returned by default query, it now return just "ok" for the default status query.

**Comment by rytilahti** [comment]
Yeah, they changed it indeed. The issue is being tracked in #1489 so I'll close this as a dupe :-)
