### ISSUE TITLE
Add support of ijai.vacuum.v3 (Xiaomi Mi Robot Vacuum-Mop 2 Pro BHR5044EU)

### ISSUE THREAD

**Issue by avecheria** [rytilahti/python-miio#1518]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi Mi Robot Vacuum-Mop 2 Pro 
  - Link: https://www.xiaomi.ua/robot-pylesos-xiaomi-mi-home-mijia-mi-robot-vacuum-mop-2-pro-white-eu/p42316/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: ijai.vacuum.v3
  - Hardware version: BHR5044EU
  - Firmware version: 4.3.3_0048

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by atlex** [comment]
I have Mi Robot Vacuum-Mop 2 Pro. The message from my Home Assistant logs:
`Found an unsupported model 'ijai.vacuum.v3' for class 'ViomiVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/`

**Comment by rytilahti** [comment]
This is already tracked in #1385 and there is a PR that is waiting to be reviewed to add support for this library, so I'll close this as a dupe.
