### ISSUE TITLE
Unable to discover using API

### ISSUE THREAD

**Issue by CODeRUS** [rytilahti/python-miio#152]
Currently discover API is very strange. It prints ip addresses to log, but this info is not accessible using api. When trying Device.discover('<broadcast>') or object.do_discover(), i can not obtain discovered device ip address for doing things.

**Comment by rytilahti** [comment]
The discovery interface (based on hello messages) is very ugly indeed, `do_discover()` should probably be renamed to `send_handshake()` or similar as it just sends a hello packet to already known IP address.

Using `Discovery` class is the preferred method for discovering devices, which however does not work on the vacuum if it e.g. is paired and has no cloud connectivity.

**Comment by CODeRUS** [comment]
Can you point to example using Discovery for searching for unpaired device? I am a bit stuck here.

**Comment by rytilahti** [comment]
Oh, I'm unsure if the unpaired one responds over mDNS, but you could try to connect to it (when it's unpaired) and simply run `mirobo discover` to see if it detects it. If yes, then something like this should work:
```
from miio import Discovery
devices = Discovery.discover_mdns()
for ip, dev in devices.items():
    print("%s at addr %s" % (dev, ip))
```

Note that the devices are returned first after enter or some key is pressed (I think a timeout could be added as an option here), and they are initialized accordingly (so a vacuum should be of type `Vacuum`).

**Comment by CODeRUS** [comment]
`mirobo discover` after couple of minutes show nothing...

**Comment by rytilahti** [comment]
Apparently it doesn't use mdns when unpaired :( this leaves us with the fact that the discovery/handshake api should be made better, so I'll leave this issue open.
