### ISSUE TITLE
Unsupported device Xiaomi Smart Air Purifier 4 (zhimi.airp.mb5a)

### ISSUE THREAD

**Issue by Som83** [rytilahti/python-miio#1523]
**Device information:**

  - Name(s) of the device: Xiaomi Smart Air Purifier 4
  - Link: https://www.mi.com/global/product/xiaomi-smart-air-purifier-4/
  - Model: zhimi.airp.mb5a
  - Hardware version: esp32
  - Firmware version: 2.2.1

Work fine with either "--model zhimi.airp.mb5" or "--model zhimi.airp.va2" except for 'set_led_brightness bright'. Backlight just switch off insted of lighting bright. 'Dim' and 'Off' work as intended. 

```
>miiocli airpurifiermiot --model zhimi.airp.mb5 --ip 172.16.0.199 --token **** status
Power: on
Anion: True
AQI: 3 μg/m³
TVOC: None
Average AQI: 6 μg/m³
Humidity: 62 %
Temperature: 19.3 °C
PM10 Density: None μg/m³
Fan Level: 1
Mode: OperationMode.Auto
LED: None
LED brightness: LedBrightness.Dim
LED brightness level: None
Gestures: None
Buzzer: False
Buzzer vol.: None
Child lock: False
Favorite level: 11
Filter life remaining: 73 %
Filter hours used: 1947
Filter left time: 210 days
Use time: None s
Purify volume: 97365 m³
Motor speed: 447 rpm
Filter RFID product id: 0:0:32:36
Filter RFID tag: 81:73:bb:f2:73:54:4
Filter type: FilterType.Regular
```

**Comment by rytilahti** [comment]
Thanks for the report! You could try to add your model to this list (and adjust the status container to fix the reporting) to see if that fixes the issue: https://github.com/rytilahti/python-miio/blob/master/miio/integrations/airpurifier/zhimi/airpurifier_miot.py#L693
