### ISSUE TITLE
How to control Xiaomi Sound

### ISSUE THREAD

**Issue by cuiMarker** [rytilahti/python-miio#1555]
When I use “get_prop” command obtains Xiaomi Sound information, the returned data are all NULL. How can I obtain the Xiaomi Sound information and adjust the volume of the Xiaomi Sound

**Comment by rytilahti** [comment]
That depends on the device in question so there is no generic answer for this, feel free to reopen if this is still an issue and you can provide more information. If the mobile app is showing the information you are looking for, look at https://python-miio.readthedocs.io/en/latest/contributing.html#new-devices for instructions how to perform traffic capture to find out the wanted commands/property names.
