### ISSUE TITLE
mirobo vacuum sound volume control

### ISSUE THREAD

**Issue by alexdom** [rytilahti/python-miio#159]
For Mi Robo Vacuum;  is it possible to control a sound volume or turn it off? Is there an implementation for that with using of raw command option? Is it possible to know the list of raw commands?

**Comment by rytilahti** [comment]
I wasn't able to find out how exactly it is supposed to work, but one can pass a parameter '[number]' or 'number' to `get_sound_volume`. There seems to be no `set_sound_volume`.

Getting to know the raw commands is not so straightforward, it requires either capturing the traffic from the app to the robot like described here https://github.com/aholstenson/miio/blob/master/docs/protocol.md or reverse engineering the application/robot itself.

**Comment by alexdom** [comment]
I tried ` set_sound_volume`, no luck. Then I tried `sound_volume`, and it seems to go through, but the volume is not changed:
`$ mirobo raw_command sound_volume 5
Sending cmd sound_volume with params 5
0
$ mirobo raw_command get_sound_volume
Sending cmd get_sound_volume with params []
[90]
$ mirobo raw_command sound_volume 20
Sending cmd sound_volume with params 20
0
$ mirobo raw_command get_sound_volume
Sending cmd get_sound_volume with params []
[90]
`
