### ISSUE TITLE
Support for roborock.vacuum.a38 (Roborock S7 MaxV Australian Version)

### ISSUE THREAD

**Issue by BAJ810** [rytilahti/python-miio#1609]
**Is your feature request related to a problem? Please describe.**
I am using home assistant and am getting this issue;

Logger: miio.device
Source: components/xiaomi_miio/__init__.py:233
First occurred: 10:09:13 PM (1 occurrences)
Last logged: 10:09:13 PM

Found an unsupported model 'roborock.vacuum.a38' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Describe the solution you'd like**
Support for roborock.vacuum.a38 (Roborock S7 MaxV Australian Version)

**Device information:**
If the enhancement is device-specific, please include also the following information.

  - Name(s) of the device: Roborock S7 MaxV Australian Version
  - Link: https://roborock.com.au/products/roborock-s7-maxv

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: roborock.vacuum.a38
  - Hardware version: Unsure
  - Firmware version: Unsure

**Additional context**

For use in home assistant (Home automation software)

Thanks

**Comment by rytilahti** [comment]
Thanks, the next release will suppress the warning so I'll close this. If you don't mind, feel free to create a PR to add the firmware features information to https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/fw_features.md – this information can be useful at some point to decide which features are available.
