### ISSUE TITLE
Request for deerma.humidifier.jsqm support

### ISSUE THREAD

**Issue by JerryZhangZZY** [rytilahti/python-miio#1623]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: 米家智能除菌加湿器
  - Link: <https://home.miot-spec.com/spec/deerma.humidifier.jsqm>

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: deerma.humidifier.jsqm
  - Hardware version: esp8266
  - Firmware version: 2.1.3.0001

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by rytilahti** [comment]
The current git master has generic miot support, did you already try `miiocli genericmiot`?

**Comment by JerryZhangZZY** [comment]
> The current git master has generic miot support, did you already try `miiocli genericmiot`?

Not yet, I'm using the release version. But I've achieved the controlling using raw command. Anyway, thanks a lot!
