### ISSUE TITLE
Disappearing/changing devices to use ? 

### ISSUE THREAD

**Issue by Tontze** [rytilahti/python-miio#1625]
**Describe the bug**
"miiocli roborockvacuum" option sometimes missing and when its missing, "miiocli vacuum" is present. When "miiocli roborockvacuum" works, there is no "miiocli vacuum" present ? 

**Version information (please complete the following information):**
 - OS: debian
 - python-miio: miiocli, version 0.5.5

**To Reproduce**

Completely random behaviour. 

**Console output**

Today there is no "roborockvacuum" listed, but vacuum is present.

$ miiocli --help
Usage: miiocli [OPTIONS] COMMAND [ARGS]...

Options:
  -d, --debug
  -o, --output [default|json|json_pretty]
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  airconditionermiot
  airconditioningcompanion
  airconditioningcompanionmcn02
  airconditioningcompanionv3
  airdehumidifier
  airdogx3
  airdogx5
  airdogx7sm
  airfresh
  airfresha1
  airfresht2017
  airfreshva4
  airhumidifier
  airhumidifierca1
  airhumidifiercb1
  airhumidifiercb2
  airhumidifierjsq
  airhumidifiermiot
  airhumidifiermjjsq
  airpurifier
  airpurifiermb4
  airpurifiermiot
  airqualitymonitor
  airqualitymonitorcgdn1
  alarm
  alarmclock
  aqaracamera
  basicairpurifiermiot
  ceil
  chuangmicamera
  chuangmiir
  chuangmiplug
  cooker
  curtainmiot
  device
  dreamevacuummiot
  fan
  fanleshow
  fanmiot
  fanp10
  fanp11
  fanp5
  fanp9
  fansa1
  fanv2
  fanza1
  fanza3
  fanza4
  gateway
  gatewaydevice
  heater
  heatermiot
  huizuo
  huizuolampfan
  huizuolampheater
  huizuolampscene
  light
  miotdevice
  philipsbulb
  philipseyecare
  philipsmoonlight
  philipsrwread
  philipswhitebulb
  plug
  plugv1
  plugv3
  powerstrip
  pwznrelay
  radio
  scisharecoffee
  toiletlid
  vacuum
  viomivacuum
  waterpurifier
  waterpurifieryunmi
  wifirepeater
  wifispeaker
  yeelight
  yeelightdualcontrolmodule
  zigbee

**Comment by rytilahti** [comment]
Version 0.5.5 is rather an old version (released in March of 2021), the naming change came in with 0.5.9 (released also already a year ago).

**Comment by Tontze** [comment]
Yeah, how to update ?

**Comment by Tontze** [comment]
Hm, is it possible to have this installed as normal user and root user ? As i do get different outputs as root/normal user with pip install ? 

 Requirement already satisfied: python-miio in ./.local/lib/python3.9/site-packages (0.5.12)

and 

 Requirement already satisfied: python-miio in ./.local/lib/python3.9/site-packages (0.5.5)

**Comment by rytilahti** [comment]
Well, they are two separate installations, generally speaking you should not run python as root.
If you still want to have separate installations, it's preferably to use virtual environments instead of the local prefix when installing packages. Or if you are just using the shipped commands (e.g. `miiocli`), you might find `pipx` useful!

Now to answer your question how to update, `pip` has `--upgrade`/`-U` flag for that.

**Comment by Tontze** [comment]
Hm, my pip does not have --upgrade or -U ?

**Comment by rytilahti** [comment]
`pip install -U python-miio` should work, it's a flag for the install command.

**Comment by rytilahti** [comment]
Great, feel free to close the issue if it's fixed now!
