### ISSUE TITLE
Error: No such command 'genericmiot'.

### ISSUE THREAD

**Issue by 4blacktea** [rytilahti/python-miio#1627]
**Describe the bug**
when i use miiocli genericmiot , i get this err
Error: No such command 'genericmiot'.

**Version information (please complete the following information):**
 - OS: macos(m1)
 - python-miio: Version: 0.5.12

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1.

**Expected behavior**

**Console output**
```bash
miiocli genericmiot status
Usage: miiocli [OPTIONS] COMMAND [ARGS]...
Try 'miiocli --help' for help.

Error: No such command 'genericmiot'.
```

**Comment by rytilahti** [comment]
Hi,

genericmiot is currently only available on the git master as there have been no releases so far, the simplest way to do that is probably:
```
git clone https://github.com/rytilahti/python-miio.git
poetry install
poetry shell
miiocli genericmiot  # or alternatively, instead of launching poetry shell above, poetry run miiocli genericmiot
```
