### ISSUE TITLE
Mi purifier 3H and 3H2 no longer working

### ISSUE THREAD

**Issue by L3o-pold** [rytilahti/python-miio#1632]
**Describe the bug**
I cannot longer fetch status from Mi purifier 3H and 3H2.

**Version information**
Darwin (OSX) and also in a Docker image
Name: python-miio
Version: 0.5.12

**Device information:**
  - Model: zhimi.airpurifier.mb3
  - Hardware version: esp32
  - Firmware version: 2.0.7 / 2.0.5

**To Reproduce**
1.  `miiocli airpurifiermiot --ip=* --token=* info`
Model: zhimi.airpurifier.mb3
Hardware version: esp32
Firmware version: 2.0.7

2. `miiocli airpurifiermiot --ip=* --token=* status`                                                
ERROR:miio.miioprotocol:Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
Error: Unable to recover failed command

**Expected behavior**
Should print device info. I do not reproduce with zhimi.airp.mb5 (2.2.1).

I also use home assistant for monitoring those devices, and it also stopped to work (some days ago I guess, not sure when, but worked 2-3 weeks from now).

<img width="268" alt="image" src="https://user-images.githubusercontent.com/4710495/208664004-125dd59d-7557-4379-84bd-4f248ac3c5cc.png">

**Comment by rytilahti** [comment]
Have you done changes in your network (e.g., moving devices to different subnets)? There has not been that many changes lately, if not something inside homeassistant, as the most recent python-miio release is from July.

**Comment by L3o-pold** [comment]
No network change, all in the same subnetwork 192.168.1.x.

**Comment by L3o-pold** [comment]
I unpluged both purifier, and it started to work again 🎉
