### ISSUE TITLE
Add Xiaomi vacuum mop Pro

### ISSUE THREAD

**Issue by TomTesner** [rytilahti/python-miio#1639]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi vacuum mop Pro
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: viomi.vacuum.v8
  - Hardware version:
  - Firmware version: 3.5.3_0017

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by th0m4sek** [comment]
just wait for next release
https://github.com/rytilahti/python-miio/commit/76870d3cf84e3780baddb74d39a517800f559795

**Comment by adrianmoisey** [comment]
Any idea when the next release will be made?

**Comment by rytilahti** [comment]
When it's somewhat ready as this will be a breaking change release, see #1114 for the plan. Perhaps not all parts will be done for 0.6, but most of the breaking changes should go into that release to avoid breaking it any further.
