### ISSUE TITLE
Roborock Q7 Max

### ISSUE THREAD

**Issue by dyvyak** [rytilahti/python-miio#1640]
Model not supported but working

**Device information:**

  - Name(s) of the device: Xiaomi Roborock Q7 Max
  - Link: https://global.roborock.com/pages/roborock-q7-max

  - Model: roborock.vacuum.a38
  - Hardware version: Linux
  - Firmware version: 4.3.5_0866

**Comment by nijel** [comment]
It should be already supported since https://github.com/rytilahti/python-miio/commit/1c3b463e950040e62dfd29d9d911a7394437b4bc

**Comment by dyvyak** [comment]
> It should be already supported since [1c3b463](https://github.com/rytilahti/python-miio/commit/1c3b463e950040e62dfd29d9d911a7394437b4bc)

Log say that is not supported

**Comment by rytilahti** [comment]
There has been no new release since it was added, but it was fixed already so I'm closing this :-)
