### ISSUE TITLE
Dreame L10s Ultra

### ISSUE THREAD

**Issue by CannonRS** [rytilahti/python-miio#1644]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Dreame L10s Ultra
  - Link: https://dreame-germany.de/products/dreame-l10s-ultra

Use `miiocli device --ip <ip address> --token <token>`.

Command does not work for me:

"Usage: miiocli device [OPTIONS] COMMAND [ARGS]...
Try 'miiocli device --help' for help.

Error: Missing command."

  - Model: dreame.vacuum.r2228o
  - Hardware version:
  - Firmware version: 4.3.743_1125

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by CannonRS** [comment]
Now I've seen that it will be supported next time.

**Comment by rytilahti** [comment]
Indeed, you can either use the `miiocli dreamevacuum` or `miiocli genericmiot` on the current git master so I'll just close this issue.

Feel free to open a new issue if you encounter any issues!
