### ISSUE TITLE
Support request for Roborock G10

### ISSUE THREAD

**Issue by samuelthng** [rytilahti/python-miio#1649]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Roborock G10
  - Link: [Distributer Link](https://shopee.sg/SG-Model-Roborock-G10-Self-Washing-Refill-Dock-Mop-Robot-Vacuum-Cleaner-Auto-Lift-Up-Mop-Smart-Technology-Sweep-i.126007714.20711524705)
  - Model: roborock.vacuum.a30
  - Hardware version: Linux
  - Firmware version: 4.3.5_1258

Couldn't find any references and links of this on Roborock website, seems like a local Singapore/Malaysia specific variant that's only marketed via local distributer channels.

**Additional context**

Almost everything on the G10 already works, except mopping attributes not being published.
It includes mopping, water level and wash mop function.

**Comment by rytilahti** [comment]
Take a look at the `--help` of the integration, some of the mopping features are exposed using separate commands, maybe those are what you are looking for?
```
❯ miiocli roborockvacuum --help|grep -i mop
  mop_dryer_settings        Get mop dryer settings.
  mop_intensity             Get mop scrub intensity setting.
  mop_mode                  Get mop mode setting.
  set_mop_dryer_dry_time    Set mop dryer add-on dry time.
  set_mop_dryer_enabled     Set mop dryer add-on enabled.
  set_mop_intensity         Set mop scrub intensity setting.
  set_mop_mode              Set mop mode setting.
  start_mop_drying          Start mop drying.
  stop_mop_drying           Stop mop drying.

❯ miiocli roborockvacuum --help|grep -i water
  set_waterflow             Set water flow setting.
  waterflow                 Get water flow setting.
```

Btw, would you mind running `miiocli device raw_command get_fw_features` and create a PR to add the information to https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/fw_features.md ?

**Comment by samuelthng** [comment]
I'm using miiocli through an integration on homeassistant, so I'm guessing the integration pulls the data directly from some preconfigured list and it's not detecting the mopping functionality. The docs of the integration pointed me here to get it added, so do correct me if I'm looking into the wrong rabbit hole. 😂

I'll try out the command next week when I have access to the network and see if I find anything to raise a PR for.

**Comment by rytilahti** [comment]
Ah, indeed. My answer here https://github.com/rytilahti/python-miio/issues/1668#issuecomment-1382913057 is related to the issues with the homeassistant integration, which at the moment hardcodes everything so that explains the missing information about the mop functionality :-)

**Comment by samuelthng** [comment]
Thank you for the follow up, #1668 clarified this up for me.
Either way, I've still raised a PR to include the firmware features into the markdown file just for posterity!

https://github.com/marcelrv/XiaomiRobotVacuumProtocol/pull/77
