### ISSUE TITLE
roborock.vacuum.a62 works fine

### ISSUE THREAD

**Issue by Electronlibre2012** [rytilahti/python-miio#1653]
Logger: miio.device
Source: components/xiaomi_miio/__init__.py:235
First occurred: 19:19:39 (1 occurrences)
Last logged: 19:19:39

Found an unsupported model 'roborock.vacuum.a62' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
Fixed in #1582 so the warning will stop appearing at some point when a new release gets done.
