### ISSUE TITLE
VIOMI Alpha 2 Pro

### ISSUE THREAD

**Issue by viotemp1** [rytilahti/python-miio#1658]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device:  VIOMI Alpha 2 Pro
  - Link: [](https://www.viomi.com/robot-vacuums/viomi-alpha-2-pro)

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model:  viomi.vacuum.v22
  - Hardware version: None
  - Firmware version: 0.1.7_2650

**Additional context**

**Comment by rytilahti** [comment]
You could try if `miiocli viomivacuum` works for the device, or alternatively use the common generic implementation using `miiocli genericmiot`.

**Comment by viotemp1** [comment]
miiocli viomivacuum does not work, miiocli genericmiot work. 
Now I need to find out how to add the vacuum in Home Assistant using this genericmiot. Any ideea?

**Comment by rytilahti** [comment]
Getting the homeassistant integration to use the newest developments of this library is an ongoing process (#1114), in the mean time you could check out the custom components linked in the readme. As I haven't tested them, I don't have a preference but they are reported to work. As the device is working using the genericmiot I'll close this issue now.
