### ISSUE TITLE
Release Schedule 

### ISSUE THREAD

**Issue by Aljutor** [rytilahti/python-miio#1665]
**Is your feature request related to a problem? Please describe.**
It is possible to have some type of release schedule for minor updates like bug fixes and new simple devices?

**Describe the solution you'd like**
A once in month minor release would be nice to have. 
But I don't trying to push you, and life sometimes hits hard, take your time. 

**Additional context**
it's 5 months from last public release. And there was same type of a problem already #1463

**Comment by rytilahti** [comment]
The reason I didn't do a separate branching for the 0.5 series is that I expected the 0.6 could become shippable much faster. Alas, that did not happen...

On doing more regular releases, I suppose creating a separate branch & cherry-picking fixes from the master branch would not require that much effort. Do you have some specific candidates for PRs that should be released as part of the 0.5.13? If you (or someone else reading this) wish to help, adding a comment on the PRs that could go into the release would be really helpful: https://github.com/rytilahti/python-miio/compare/0.5.12...master

The new release should contain only rather minor, non-breaking changes (i.e., fixes only) to keep it simple. Adding the supported model information could go in, but I'm not sure how useful they are–as long as the `DeviceFactory` changes are not included–for the time being as those will just suppress the warning logging.

**Comment by Aljutor** [comment]
I am interested in support for zhimi.airp.mb5a and leshow.humidifier.jsq1 but both requires #1581.
As on fixes side - I am not sure, but it better to ask other people about it.

Can #1581 be separated release?  But it may require quite a lot of work to do, so I am not sure.

**Comment by kevin-kraus** [comment]
@rytilahti I've added an issue and PR in the HA/core repository (https://github.com/home-assistant/core/issues/86104) asking for support for the Xiaomi Smart Air Purifier 4 Compact. I've seen that you have added support for this in November. (PR: https://github.com/rytilahti/python-miio/pull/1581) 

Would it be possible to add support for this into `0.5.13`?

Best regards

Kevin

**Comment by rytilahti** [comment]
@kevin-kraus sorry, that's not possible. The genericmiot is one of those pieces that required changes throughout the library, and a rewrite of the homeassistant integration which I'm currently working on.

**Comment by kevin-kraus** [comment]
> @kevin-kraus sorry, that's not possible. The genericmiot is one of those pieces that required changes throughout the library, and a rewrite of the homeassistant integration which I'm currently working on.

Thanks for your reply, any predictions how long it will take approximately until we can expect a new minor version and HomeAssistant integration? (e.g. 2 months etc.?)

**Comment by Aljutor** [comment]
If there any small size tasks that can be contirbuted by someone else, I would like to help .

**Comment by kaystrobach** [comment]
Thank you for all the work.

is there a chance to cherry pick the air purifier 4 compact into the 0.5 branch? Would love it.

**Comment by rytilahti** [comment]
I just wrote about the current state of affairs in https://github.com/rytilahti/python-miio/issues/1808#issuecomment-1696033029 - let's close this issue and continue there. I'm hoping to get the last missing piece (#1814) done asap, but I'm going to need people to do some testing. 

@Aljutor help on adding descriptors to existing integrations (#1617) would be very welcome!
