### ISSUE TITLE
Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'

### ISSUE THREAD

**Issue by dshokouhi** [rytilahti/python-miio#1668]
**Describe the bug**

Got a new vacuum, was able to integrate with Home Assistant and basic commands work

**Version information (please complete the following information):**
 - OS: Linux
 - python-miio: 0.5.12

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: roborock e5
  - Hardware version: unknown?
  - Firmware version:2.0.8_0912

**To Reproduce**
1. Setup vacuum in home assistant, observe logs

**Expected behavior**

Full support?  This vacuum has mopping features but I don't see the mop entities. Haven't found a feature that does not work

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

```
Logger: miio.device
Source: components/xiaomi_miio/__init__.py:235
First occurred: 5:15:36 PM (2 occurrences)
Last logged: 6:00:43 PM

Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
```

**Comment by rytilahti** [comment]
The warning is harmless and will get suppressed when a new release is done (https://github.com/rytilahti/python-miio/blob/master/miio/integrations/vacuum/roborock/vacuum.py#L68), so I'll close this. Information necessary to add mopping information has already been added (#1585), but this will require a major rewrite of the homeassistant integration to make use of it (related to #1114).

If you don't mind, feel free to try if the device reports back supported features (using `miiocli device raw_command get_fw_features`) and create a PR to https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/fw_features.md .
