### ISSUE TITLE
Construct error, "subcon should be a Construct field"

### ISSUE THREAD

**Issue by skorokithakis** [rytilahti/python-miio#167]
Attempting to run `mirobo start` with the latest PyPI version of miio on Python 3.6 (Ubuntu 17.10) produces the following error:

```python
Traceback (most recent call last):
  File "/home/stavros/.local/bin/mirobo", line 7, in <module>
    from miio.vacuum_cli import cli
  File "/home/stavros/.local/lib/python3.6/site-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/home/stavros/.local/lib/python3.6/site-packages/miio/protocol.py", line 179, in <module>
    Const(Int16ub, 0x2131),
  File "/home/stavros/.local/lib/python3.6/site-packages/construct/core.py", line 1277, in __init__
    super(Const, self).__init__(subcon)
  File "/home/stavros/.local/lib/python3.6/site-packages/construct/core.py", line 287, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
```

It has something to do with the `construct` package, but I'm not terribly sure what.

**Comment by rytilahti** [comment]
`construct` package changed their API and it broke everything depending on `Const` types. This is fixed already in master, and after #166 gets done a new package will be released.

**Comment by skorokithakis** [comment]
Ah, thanks Teemu, I looked but I couldn't find a ticket mentioning this, so I opened this one. I'll use master for now.

**Comment by rytilahti** [comment]
Not a thing, I hope that the 0.3.4 will be available from pypi at latest tomorrow, I just want someone to try it out before pushing it everywhere (just in case).

**Comment by skorokithakis** [comment]
For what it's worth, master works for me (it can't communicate with the vacuum, but I think that's the vacuum's problem, not the library's).

**Comment by rytilahti** [comment]
0.3.4 is now released.

**Comment by prograde** [comment]
I still get this error. Running on a Raspberry Pi 3.

**Comment by rytilahti** [comment]
Which version of python-miio and which version of construct are you running? This should have been fixed more than a year ago, so I doubt it's the same problem.
