### ISSUE TITLE
Add support for Mijia Smart Rice Cooker Mini 2

### ISSUE THREAD

**Issue by JackyMao1999** [rytilahti/python-miio#1670]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device:Mijia Smart Rice Cooker Mini 2
  - Link:https://www.mi.com/shop/buy/detail?product_id=16021&cfrom=search

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model:  chunmi.cooker.eh3
  - Hardware version: esp32
  - Firmware version: 2.2.0_0010

**Additional context**
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:cooker:0000A00B:chunmi-eh3:1
https://python-miio.readthedocs.io/en/latest/api/miio.cooker.html

**Comment by rytilahti** [comment]
miot devices are now supported using `genericmiot` integration, you could try that out using `miiocli genericmiot` on the current git master.

**Comment by JackyMao1999** [comment]
Oh thanks, i will try it.

**Comment by gongcy** [comment]
`genericmiot` works, thanks~

**Comment by sidorovit** [comment]
> `genericmiot` works, thanks~

I can't launch any action:
`>miiocli genericmiot  --ip 192.168.1.17 --token f09debe7a37dd33018f2dd[xxxx] --model chunmi.cooker.eh3 call cooker:start-cook
Running command call
{'code': -4003}`

Maybe someone solved this issue?
