### ISSUE TITLE
install_sound on gen2 not working

### ISSUE THREAD

**Issue by BerraKode** [rytilahti/python-miio#168]
I've tried to get this working but without success. I get the following message when trying to upload my pack:
_______
$ mirobo install_sound http://192.168.0.122:80/image-server/es.pkg d41d8cd98f00b204e9800998ecf8427e 1005

Installing from http://192.168.0.122:80/image-server/es.pkg (md5: d41d8cd98f00b204e9800998ecf8427e) for id 1005
<SoundInstallStatus sid: None (state: SoundInstallState.Unknown, error: 0) - progress: 0>
<SoundInstallStatus sid: 1005 (state: SoundInstallState.Downloading, error: 0) - progress: 0>
<SoundInstallStatus sid: 1005 (state: SoundInstallState.Installing, error: 0) - progress: 0>
Error during installation: 4
_______

Is it confirmed this does not work on gen2 or could it be I've done something wrong?

Thanks for the awesome work btw!! 
/BerraKode

**Comment by rytilahti** [comment]
Unfortunately the error codes are unknown at the moment, nor anyone has confirmed whether this works on gen2 (actually no one has reported even if it works, I have just tested that it works on my vacuum).

Anyway, seeing that you are not seeing download progress at all, I would look first into your web-server's logs to see if it ever tries to fetch that `es.pkg` at all. Maybe error 4 is "unable to download" or something similar?

**Comment by BerraKode** [comment]
I get this in my webserver log: 
192.168.0.148 - - [22/Jan/2018:11:38:09 +0100] "GET /image-server/es.pkg HTTP/1.1" 200 249 "-" "-"

So looks like the error is with the vacuum right? I know at least another guy who got this working on his gen1. So maybe gen2 is the villain.

**Comment by rytilahti** [comment]
Ok, may very well be that there's something else we need to pay attention to for gen2 devices, unfortunately I have no answer for this at the moment.

**Comment by rytilahti** [comment]
Could you re-try this with the current git version? The previous server did not send a content-length header as part of the response, which caused problems with firmware update status messages, maybe they check for that differently also for the gen2.

**Comment by BerraKode** [comment]
Would love to. Will let you know tomorrow!

**Comment by BerraKode** [comment]
Unfortunately still the same error message for me :(

**Comment by BerraKode** [comment]
I can only find the install_sound() method (which doesn't have a parameter for sver). How do I use dnld_install_sound? :)

**Comment by rytilahti** [comment]
Potentially interesting for this https://github.com/rytilahti/python-miio/issues/348#issuecomment-400058721 .
