### ISSUE TITLE
Found an unsupported model 'yeelink.light.colorb' for class 'Yeelight'.

### ISSUE THREAD

**Issue by Mostalk** [rytilahti/python-miio#1708]
Model: yeelink.light.colorb
Hardware version: esp8266
Firmware version: 2.0.8_0010

All features work correctly

**Comment by rytilahti** [comment]
Would you mind creating a PR to add that model and information about its supported features to https://github.com/rytilahti/python-miio/blob/master/miio/integrations/yeelight/light/specs.yaml#L109 ?

**Comment by Mostalk** [comment]
Done
