### ISSUE TITLE
Found an unsupported model 'yeelink.light.lamp2' for class 'Yeelight'

### ISSUE THREAD

**Issue by tomasmundt** [rytilahti/python-miio#1756]
**Device information:**

  - Name(s) of the device: Mi Smart LED Desk Lamp Pro
  - Link: https://mistore.se/products/mi-smart-led-desk-lamp-pro

  - Model: yeelink.light.lamp2
  - Hardware version: esp32
  - Firmware version: 2.1.7_0046

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by rytilahti** [comment]
Defined already here, so the warning will disappear when a new release is done: https://github.com/rytilahti/python-miio/blob/2e150a243a4e0731e2b5e8da879ef4f69c209811/miio/integrations/yeelight/light/specs.yaml#L192-L195

**Comment by tomasmundt** [comment]
Does yeelink.light.lamp**22** solve it for the yeelink.light.lamp**2**?

**Comment by rytilahti** [comment]
ohh, sorry, nope. There is a a wildcard below which would, but it may not be correct.. Feel free to create a PR, or if you know the valid values, just type then in a comment and it will get fixed!
