### ISSUE TITLE
Unable to read zhimi.airp.vb4 Xiaomi Smart Air Purifier 4 Pro

### ISSUE THREAD

**Issue by AndreasLM03** [rytilahti/python-miio#1763]
I have a new device model: zhimi.airp.vb4 Xiaomi Smart Air Purifier 4 Pro and would like to read the temperature and humidity using a python script. I have already installed this repo as .git but I do not manage to read out data.

PS C:\Users\bb> miiocli genericmiot --ip 192XXXXXXXX4 --token XXXXXXXXXXXXXXXXXXX status
Running command status

ERROR:miio.click_common:Exception: Unable to discover the device  192XXXXXXXX4
Traceback (most recent call last):
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\click_common.py", line 305, in wrap
    result = kwargs["result"] = func(*args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\click_common.py", line 270, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\click_common.py", line 218, in call
    return method(*args, **kwargs)
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\click_common.py", line 184, in _wrap
    self._fetch_info()
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\integrations\genericmiot\genericmiot.py", line 198, in _fetch_info
    info = super()._fetch_info()
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\device.py", line 163, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\device.py", line 122, in send
    return self._protocol.send(
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\miioprotocol.py", line 162, in send
    self.send_handshake()
  File "C:\Users\bb\miniconda3\lib\site-packages\miio\miioprotocol.py", line 75, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device  192XXXXXXXX4

**Comment by rytilahti** [comment]
The "Unable to discover the device" means that the device did not answer to the initial handshake, are you sure the IP address is correct? You could use wireshark to see if you receive any communications from the device when running that command.

Also, is your computer in the same subnet as the device you are trying to control? Some devices are known to filter the packets based on the source address: https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets

**Comment by AndreasLM03** [comment]
I can access the device in principle

`from miio import *
ip_address = "1XX.XXX.XXX.XX4"  
token = "cXXXXXXXXXXXXXXXXXXXXXXXXXe5"  
device = Device(ip_address, token)
info = device.info()
pprint.pprint(info)
zhimi.airp.vb4 v2.2.0 (EX:XX:XX:XX:XX:XX) @ 1XX.XXX.XXX.XX4 - token: cXXXXXXXXXXXXXXXXXXXXXXXXXe5
`

maybe I have a logic mistake, but all further commants lead to error messages. What would be the minimum code to retrieve temperature, humidity?

**Comment by rytilahti** [comment]
Hmm, that's odd as the info call requires also a handshake to succeed, but if it's working, great!

You can use something like this:
```
from miio import DeviceFactory

dev = DeviceFactory.create("127.0.0.1", 32*"0")
print(dev)

status = dev.status()
print(status)
print(f"Temperature: {status.temperature} - humidity: {status.humidity}")
```

Here's output run against the simulator (`miiocli devtools miot-simulator --model zhimi.airp.vb4`):
```
<AirPurifierMiot: 127.0.0.1 (token: 00000000000000000000000000000000)>
<AirPurifierMiotStatus anion=False aqi=419 average_aqi=234 buzzer=True buzzer_volume=None child_lock=False fan_level=1 favorite_level=8 favorite_rpm=None filter_hours_used=59497 filter_left_time=269 filter_life_remaining=92 filter_rfid_product_id=piid 3 filter_rfid_tag=piid 1 filter_type=FilterType.Regular gestures=None humidity=71 is_on=False led=None led_brightness=LedBrightness.Off led_brightness_level=None mode=OperationMode.Favorite motor_speed=11904 pm10_density=21 power=off purify_volume=1915583039 temperature=9 tvoc=None use_time=None>
Temperature: 9 - humidity: 71
```

You can also use `AirPurifierMiot` directly to avoid using `DeviceFactory` which performs that `info` query in the background to figure out the correct class to use.

**Comment by AndreasLM03** [comment]
Hi rytilahti with your code it works like a charm. I didn't know to use .create calling the DeviceFactory class. 
Many thanks. This issue can be closed

**Comment by rytilahti** [comment]
Great, let's close it then! It's documented in https://github.com/rytilahti/python-miio/#api-usage but rather sparsely.

Here's an example of doing the same using the genericmiot, just for the sake of completeness and in case you (or someone else reading this later on) needs a way to access something that isn't directly available using the airpurifiermiot class:
```
from miio import DeviceFactory

dev = DeviceFactory.create("127.0.0.1", 32*"0", force_generic_miot=True)
print(dev)

status = dev.status()
print(status)
print(f"Temperature: {status.environment_temperature} - humidity: {status.environment_relative_humidity}")
```
Results in:
```
<GenericMiot: 127.0.0.1 (token: 00000000000000000000000000000000)>
<GenericMiotStatus air-purifier:on=True air-purifier:fault=Temp Error (value: 2) air-purifier:mode=Favorite (value: 2) air-purifier:fan-level=Level1 (value: 1) air-purifier:anion=False environment:relative-humidity=17 % environment:pm2.5-density=866 None environment:temperature=83 None environment:pm10-density=50 None environment:air-quality=Poor (value: 3) filter:filter-life-level=12 % filter:filter-used-time=880 days, 0:00:00 filter:filter-left-time=429 days, 0:00:00 alarm:alarm=False physical-controls-locked:physical-controls-locked=False screen:brightness=Brightest (value: 2) device-display-unit:temperature-display-unit=Fahrenheit (value: 2) air-purifier-favorite:fan-level=4 None custom-service:moto-speed-rpm=56828  custom-service:favorite-speed=680  custom-service:motor-set-speed=1672  custom-service:favorite-level=3  custom-service:buttom-door=True custom-service:reboot-cause=REASON-UPDATE (value: 2) custom-service:manual-level=Level2 (value: 2) custom-service:country-code=TW (value: 886) custom-service:favorite-square=piid 12 None aqi:purify-volume=320147655  aqi:average-aqi=242  aqi:aqi-state=AQI-BAD-L (value: 4) aqi:aqi-updata-heartbeat=64349  rfid:rfid-tag=piid 1  rfid:rfid-factory-id=piid 2  rfid:rfid-product-id=piid 3  rfid:rfid-time=piid 4  rfid:rfid-serial-num=piid 5 >
Temperature: 83 - humidity: 17
```
