### ISSUE TITLE
Control Air purifier and Humidifier?

### ISSUE THREAD

**Issue by BerraKode** [rytilahti/python-miio#177]
Hello
First of all I've got the mirobo working and love it!

However I'm unsure how to get the air purifier and humidifier to work. I see the specific python files for them in the miio folder but when I try to import them into my own python file I get all kinds of errors. How do I control those two devices? 

Thanks in advance and thank you for all your hard work!!

Best wishes - BerraKode

**Comment by rytilahti** [comment]
It would help if you'd describe what kind of errors you are getting. But I suppose something like this should work:
```
from miio import AirPurifier, AirHumidifier

airp = AirPurifier(ip, token)
print(airp.info())

airh = AirHumidifer(ip, token)
print(airh.info())
```

or you can also try to access them with the help of `Discovery` class (which will construct you a corresponding device objects).

**Comment by BerraKode** [comment]
I don't have the airpurifier and humidifier yet so I'm trying out on my vacuum. This is what I get:
-----------
pi@HomeController:/usr/local/lib/python3.4/dist-packages/miio$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from miio import Vacuum
ImportError: No module named miio
-----------

I guess my problem is I don't know which folder to put the python file. Or does this mean my system don't have the miio package installed? Thanks for your patience!

**Comment by BerraKode** [comment]
and if I try to "import vacuum" instead it gives me this:
_______
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import vacuum
  File "/usr/local/lib/python3.4/dist-packages/miio/vacuum.py", line 36
    def __init__(self, ip: str, token: str = None, start_id: int = 0,
                         ^
SyntaxError: invalid syntax
_____________

**Comment by BerraKode** [comment]
now I moved it up a folder and it got the import miio working but it complains on each method because there is for example "---->ip:<------ ip" in all the methods:
____
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from miio import Vacuum
  File "/usr/local/lib/python3.4/dist-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/usr/local/lib/python3.4/dist-packages/miio/protocol.py", line 39
    def verify_token(token: bytes):
                          ^
SyntaxError: invalid syntax
_____

**Comment by BerraKode** [comment]
omg I got it working!!!! I was using wrong version of python (have some applications that need python 2 lol). Thanks!!!! Now Im gonna buy humidifier and airpurifier for sure!!

**Comment by rytilahti** [comment]
Glad to hear you got it working! You should get used for virtual environments when working with python, see https://realpython.com/blog/python/python-virtual-environments-a-primer/ , and more importantly you should not keep your scripts under any distribution directory (like inside `dist-packages` nor `miio`). I think we can close this issue now.
