### ISSUE TITLE
Found an unsupported model 'yeelink.light.color5' for class 'Yeelight'

### ISSUE THREAD

**Issue by SantosProgramming** [rytilahti/python-miio#1773]
Device information:

Name: Mi LED Smart Bulb Essential White and Color

Link: https://www.xiaomistore.pt/lampada-mi-smart-led-bulb-essential-white-and-color-eu

Model: yeelink.light.color5 / MJDPL04YL

Plugin version: 11

Firmware version: 2.0.8_0022

**Comment by rytilahti** [comment]
Already in master branch (#1242).
