### ISSUE TITLE
[New Device]temperature-humidity-sensor, 米家蓝牙温湿度计2

### ISSUE THREAD

**Issue by daidaiworm** [rytilahti/python-miio#1781]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**If your device is rather new, it is likely supported already by the `genericmiot` integration. This is currently available only on the git version (until version 0.6.0 is released), so please give it a try before opening a new issue.**

**Device information:**
![image](https://github.com/rytilahti/python-miio/assets/3594904/f00a1733-51d2-4210-932c-95bc2f05d5b8)

  - Name(s) of the device: temperature-humidity-sensor:0000A00A:miaomiaoce-t2, 米家蓝牙温湿度计2
  - Link:
https://home.mi.com/webapp/content/baike/product/index.html?model=miaomiaoce.sensor_ht.t2#/params
https://home.mi.com/webapp/content/baike/product/index.html?model=miaomiaoce.sensor_ht.t2#/

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model: [e.g., lumi.gateway.v3] 米家蓝牙温湿度计2
  - Hardware version:
  - Firmware version:

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

Since it's a bluetooth device, how do I get the data from it? The ip is not a lan ip.
```
miiocli device --ip 61.242.214.191 --token 0b7805d592f04c8d60ecbe00 info

Error: Invalid value for '--token': Token length != 32 chars: 24
```
I got 6 Chuangmi.Plug.212a01 at home. How do I know which plug provide gateway service to temperature-humidity-sensor

**Comment by rytilahti** [comment]
This library supports only wifi-enabled devices, sorry! I found https://github.com/JsBergbau/MiTemperature2 after some googling, but I have no idea if that helps.
