### ISSUE TITLE
Please add support Xiaomi Robot Vacuum-Mop 2C dreame.vacuum.md1808

### ISSUE THREAD

**Issue by wrewolf** [rytilahti/python-miio#1788]
**Is your feature request related to a problem? Please describe.**
Unsupported device

**Describe the solution you'd like**
I see some errorn on log, but I can control mop

**Device information:**
Vacuum cleaner

  - Name(s) of the device: Xiaomi Robot Vacuum-Mop 2C
  - Link: https://home.miot-spec.com/spec/dreame.vacuum.md1808

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model: dreame.vacuum.md1808
  - Hardware version: Linux
  - Firmware version: 4.3.3_1014

**Additional context**
2023-07-04 12:13:30.411 WARNING (SyncWorker_3) [miio.device] Found an unsupported model 'dreame.vacuum.md1808' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by rytilahti** [comment]
This is likely coming from homeassistant which currently only supports roborock vacuums, so I'm closing this. In the future (#1114), we will be able to support also this device.

If you are using this device outside homeassistant, the command to use is `miiocli genericmiot` (or programmatically using the `GenericMiot` class).

**Comment by wrewolf** [comment]
Thank you!
