### ISSUE TITLE
Xiaomi Smart Speaker (IR control)

### ISSUE THREAD

**Issue by danielszilagyi** [rytilahti/python-miio#1803]
`2023-08-02 20:35:15.264 WARNING (SyncWorker_4) [miio.device] Found an unsupported model 'xiaomi.wifispeaker.l05g' for class 'ChuangmiIr'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/` 

**Device information:**

  - Name(s) of the device: Xiaomi Smart speaker with IR
  - Link: https://www.mi.com/global/product/xiaomi-smart-speaker-ir-control/

Use `miiocli device --ip <ip address> --token <token>`.

```shell 
Model: xiaomi.wifispeaker.l05g
Hardware version: Linux
Firmware version: 1.69.7
```

Hello,

Got the warning on the top so opening this issue.

The mentioned device's IR remote actually works fine with manually configured xiaomi_miio integration, and also mentioned in the related [code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/remote.py) as ChuangMi so I believe this could be added to the list of the devices in [here](https://github.com/rytilahti/python-miio/blob/master/miio/integrations/chuangmi/remote/chuangmi_ir.py) but would wait for your confirmation before PR'ing it.

thanks
Daniel

**Comment by rytilahti** [comment]
Hi Daniel,

the list of supported devices will be used to create the correct device instance in the future release, so the PR looks good to me!
