### ISSUE TITLE
Need support for Mi Smart Power Plug 2

### ISSUE THREAD

**Issue by hx0918** [rytilahti/python-miio#1806]
My device is : 
NAME:     Mi Smart Power Plug 2 (Wi-Fi and Bluetooth Gateway)
MODEL:    chuangmi.plug.212a01

Getting error when I type: `miiocli chuangmiplug ...`
WARNING: miio.device: Found an unsupported model 'chuangmi.plug.212a01' for class 'ChuangmiPlug'.

**Comment by rytilahti** [comment]
Are the commands working for this model? If not and it's a rather modern device, you can try using `miiocli genericmiot` (available only in the git version at the moment) to control it.

**Comment by hx0918** [comment]
Yes, the command works, like `miiocli device ... raw_command get_properties "[{'did:'  , 'siid':  , 'piid':   }]"`

So, I am going to close this issue.
