### ISSUE TITLE
 Found an unsupported model 'roborock.vacuum.a75' for class 'RoborockVacuum'

### ISSUE THREAD

**Issue by gluca** [rytilahti/python-miio#1844]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device: Roborock Q Revo
  - Link: https://global.roborock.com/pages/roborock-q-revo

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: [e.g., lumi.gateway.v3] roborock.vacuum.a75
  - Hardware version: N/A
  - Firmware version: 4.3.5_1582

**Comment by discostur** [comment]
Having the same problem ...

**Comment by rytilahti** [comment]
Is it not working, or is it just that it's giving an error? I'd expect that these devices work, but that the model is not yet added to the list of known-to-work devices. The latter can be easily done, the former requires more details about what is not working etc.

**Comment by discostur** [comment]
It's giving the error but i cannot get any information from the roborock. So it doesn't work just prints the error ...

**Comment by gluca** [comment]
Vacuum works perfectly in home assistant, map extractor works as expected too. No problem but this weird log message. I guess the integration already works with vacuum but is not "aware" of it

**Comment by rytilahti** [comment]
#1850 fixes the  warning, @discostur, please open a new issue and post the error you are getting. The _warning_ in this issue is not related to your error.
