### ISSUE TITLE
please add new model(xiaomi.airp.va2b) support

### ISSUE THREAD

**Issue by chazikai24** [rytilahti/python-miio#1875]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**If your device is rather new, it is likely supported already by the `genericmiot` integration. This is currently available only on the git version (until version 0.6.0 is released), so please give it a try before opening a new issue.**
haos 2023.11.3 not support command genericmiot

homeassistant:/usr/src/homeassistant# miiocli genericmiot  --ip XXXX --token XXXX status
Usage: miiocli [OPTIONS] COMMAND [ARGS]...
Try 'miiocli --help' for help.
Error: No such command 'genericmiot'.

**Device information:**

  - Name(s) of the device:xiaomi air purifier pro4
  - Link:https://home.miot-spec.com/s/xiaomi-va2b

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model: xiaomi.airp.va2b
  - Hardware version:ESP32C3
  - Firmware version:1.0.8

**Additional context**
homeassistant:/usr/src/homeassistant# miiocli -d device --ip 10.0.80.40 --token XXXX info
INFO:miio.cli:Debug mode active
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00)\x7f\x81j\x00\x02\x90\x10' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('297f816a')
            ts = 1970-01-02 22:39:12
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 297f816a with ts: 1970-01-02 22:39:12, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:10.0.80.40:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:10.0.80.40:54321 (ts: 1970-01-02 22:39:12, id: 1) << {'id': 1, 'result': {'life': 167952, 'model': 'xiaomi.airp.va2b', 'token': 'XXXX', 'ipflag': 1, 'fw_ver': '1.0.8', 'mcu_fw_ver': '0012', 'miio_ver': '0.1.0', 'hw_ver': 'ESP32C3', 'mmfree': 99136, 'workmode': 1, 'mac': 'D4:F0:EA:06:XX:XX', 'wifi_fw_ver': 'WifiVer.N/A', 'ap': {'ssid': 'XXX', 'bssid': 'A4:1A:3A:xxx:xxx:10', 'rssi': -69, 'primary': 6}, 'netif': {'localIp': '10.0.80.40', 'mask': '255.255.255.0', 'gw': '10.0.80.1'}, 'uid': 84502859, 'config_type': 'app'}, 'exe_time': 10}
DEBUG:miio.device:Detected model xiaomi.airp.va2b
Model: xiaomi.airp.va2b
Hardware version: ESP32C3
Firmware version: 1.0.8

**Comment by rytilahti** [comment]
You need to use the git version for genericmiot until a new release is done. See the readme on how to install it.
