### ISSUE TITLE
Roborock S8 - roborock.vacuum.a51

### ISSUE THREAD

**Issue by edterbak** [rytilahti/python-miio#1921]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**If your device is rather new, it is likely supported already by the `genericmiot` integration. This is currently available only on the git version (until version 0.6.0 is released), so please give it a try before opening a new issue.**

**Device information:**

  - Name(s) of the device: **Roborock S8**
  - Link: **https://global.roborock.com/pages/roborock-s8**

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model: **roborock.vacuum.a51**
  - Hardware version: dont know where to find this.
  - Firmware version: 4.3.5_1602
  - Plug-In Version: MI_MDX_3418
  - MI ID: 2440738436

**Additional context**
Did not find any issue yet. Working nicely. but have not used it for more than 1 day now. If there is more to tell, I will do so here.

**Comment by rytilahti** [comment]
Thanks for the report. All roborock vacuums should indeed work, and this warning will be removed in the future releases, so I'll close this issue.
