### ISSUE TITLE
Xiaomi Smart Standing fan 2 Pro, model: dmaker.fan.p33 .  

### ISSUE THREAD

**Issue by Rafas20** [rytilahti/python-miio#1947]
I tried to integrate my new fan to HA but it does not show any controls for the fan.. Did i made anything wrong? Could you help me please? As a solution i thought to try downgrade the firmware of the fan but thats not easy and safe task (for me at least). 
![image](https://github.com/syssi/xiaomi_fan/assets/143114577/6e894102-84b8-46c0-9608-624c800cb74c)
![image](https://github.com/syssi/xiaomi_fan/assets/143114577/e3769b50-f3c4-45b8-9703-345337e2f74e)

**Comment by lug-gh** [comment]
Are you sure you're in the right project? 
https://github.com/syssi/xiaomi_fan

**Comment by Rafas20** [comment]
> Are you sure you're in the right project? https://github.com/syssi/xiaomi_fan

Developer says that rytilahti contributed to this integration. So as the sissy does not respond i  decided to ask here for it.

**Comment by syssi** [comment]
Lol. :-) Let's try to resolve the issue at the right place: https://github.com/syssi/xiaomi_fan/issues/259

Sorry for the noise.
