### ISSUE TITLE
Add suppport for viomi.vacuum.v13

### ISSUE THREAD

**Issue by dziadzi123** [rytilahti/python-miio#1952]
Plase add support for vacuum cleaner Viomi V3

   NAME:     Viomi V3
   ID:       378325144
   MAC:      5C:6B:D7:15:18:15
   IP:       192.168.188.12
   TOKEN:    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   MODEL:    viomi.vacuum.v13

**Comment by rytilahti** [comment]
This is already supported using `miiocli viomivacuum` / `ViomiVacuum` class.
