### ISSUE TITLE
Unsupported device found! 

### ISSUE THREAD

**Issue by xain** [rytilahti/python-miio#203]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":3600,"channel_0":"on"}', 'short_id': 42290, 'model': '', 'cmd': 'read_ack', 'sid': '158d00021128cb'}

I believe it is [this switch](https://item.jd.com/4607278.html)

**Comment by rytilahti** [comment]
I'm not sure how you found this repository given the URL points to completely another project. Please open an issue there :-)
