### ISSUE TITLE
Trying to get map data without rooting

### ISSUE THREAD

**Issue by lance36** [rytilahti/python-miio#206]
is there any way to obtain the map data in any format?
```bash
 $ mirobo --ip 192.168.1.112 --token <redacted> info
rockrobo.vacuum.v1 v3.3.9_003094 (<redacted>) @ 192.168.1.112 - token: <redacted>
$ mirobo --ip 192.168.1.112 --token <redacted> map
['retry']
```

I know the data is stored somewhere in some format before is sent to te cloud, and there seems to be some sort of functionality inplemented 
```bash
Usage: mirobo [OPTIONS] COMMAND [ARGS]...
Commands:
  map               Return the map token.

```

**Comment by rytilahti** [comment]
From the looks of it your vacuum is not connected to the cloud, as if it would be it would return some sort of token for that call. It is however unknown how to fetch a map from the Xiaomi servers by using this token, and that command is there just for the sake of completeness.

Perhaps we should hide it from the cli or write a better description for it, though. At the moment there is no way to access this data without having a rooted device, so I'm closing this issue as there's nothing we can do about it.

The data itself is stored in a sqlite3 database on the device, there is a parser available here: https://github.com/dgiese/dustcloud/blob/master/xiaomi.vacuum.gen1/mapextractor/extractor.py .
