### ISSUE TITLE
Set mode for Air Purifier 2 not working

### ISSUE THREAD

**Issue by BerraKode** [rytilahti/python-miio#207]
I got all commands working for my Air Purifier 2 except "set_mode()". No matter what I try it won't work. 

This is the error message I get:
-----> x.set_mode(OperationMode.Auto)
NameError: name 'OperationMode' is not defined <----

This is my code:

import miio as mi
ip = "192.168.0.XX"
token = "XXXXXXX"
x=mi.AirPurifier(ip, token)
x.set_mode(OperationMode.Auto)

I've tried all sorts of versions of "auto", mode.auto etc but nothing will work. What am I missing or is this not working anymore?

Thanks in advance!!!!

**Comment by syssi** [comment]
You must import the OperationMode class:

https://github.com/rytilahti/python-miio/blob/master/miio/tests/test_airpurifier.py#L3-L5

**Comment by kofec** [comment]
Here you have example:
https://github.com/kofec/domoticz-AirPurifier/blob/master/MyAir.py

**Comment by BerraKode** [comment]
Thanks it's working now!! :)
