### ISSUE TITLE
yeelink.light.color1 unsupported

### ISSUE THREAD

**Issue by twiggyr** [rytilahti/python-miio#225]
yeelink.light.color1 is reporting as unsupported.
Home Assistant 0.63.2
miio version  "0.3.5"

**Comment by rytilahti** [comment]
Can you be more specific, is this about device discovery or something else? Homeassistant does not use this library for the yeelight bulbs, they are handled with `python-yeelight` library.

**Comment by twiggyr** [comment]
You are correct. Changed to the yeelight config and its working though python-yeelight
I was confused as I could add the light and manage it though the xiaomi mi app.

Sorry about that.
