### ISSUE TITLE
Add support for the Xiaomi Philips LED Ceiling Light 620mm (philips.light.zyceiling)

### ISSUE THREAD

**Issue by kuzyaka** [rytilahti/python-miio#234]
I'm unable to connect to Xiaomi Philips LED Ceiling Light 620mm using home-assistant 0.63.3.

I'm running into the following error:
2018-02-24 21:54:24 ERROR (MainThread) [homeassistant.components.light.xiaomi_miio] Unsupported device found! Please create an issue at http
s://github.com/rytilahti/python-miio/issues and provide the following data: philips.light.zyceiling

**Comment by syssi** [comment]
Please try the development branch of the custom component: https://github.com/syssi/philipslight

And override the model by

```
  - platform: xiaomi_miio
    name: Xiaomi Philips Smart LED Ceiling Lamp
    host: 192.168.130.68
    token: 439e1a89ee5648d20482afa7839ef2ee
    model: philips.light.ceiling
```

**Comment by kuzyaka** [comment]
> Please try the development branch of the custom component: https://github.com/syssi/philipslight
How could I install custom component into HA? Could this be done via overwriting some script file of existing HA installation?

**Comment by kuzyaka** [comment]
Used model overriding and custom component - it works. 
Thank you

**Comment by syssi** [comment]
Perfect! Could you post a screenshot of your mihome app? I want to make sure your light has the same features as the other ceiling lamp.

**Comment by kuzyaka** [comment]
python-miio/ceil_cli.py output of status command:
Power: off
Brightness: 51
Color temperature: 51
Scene: 0
Smart Night Light: True
Auto CCT: True
Countdown of the delayed turn off: 0 seconds

MiHome screens:
https://pasteboard.co/H9eRaxB.png
https://pasteboard.co/H9eQK78.png
https://pasteboard.co/H9eQVK7.png

**Comment by syssi** [comment]
Thanks a lot! Your ceiling lamp will be supported officially soon: https://github.com/home-assistant/home-assistant/pull/12449

**Comment by kuzyaka** [comment]
Sure, discover output:

anton@Ubuntu:~$ mirobo -d discover
INFO:miio.vacuum_cli:Debug mode active
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
DEBUG:miio.discovery:Found a supported 'philips-light-ceiling_mibt62456974._miio._udp.local.', using 'Ceil' class
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        value =  (total 0)
        length = 0
        data =  (total 0)
        offset2 = 32
        offset1 = 32
    header = Container:
        value = Container:
            length = 32
            unknown = 0
            device_id = \x03\xb9\x04\x8e (total 4)
            ts = 1970-01-01 01:39:00
        length = 16
        data = !1\x00 \x00\x00\x00\x00\x03\xb9\x04\x8e\x00\x00\x174 (total 16)
        offset2 = 16
        offset1 = 0
    checksum = \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 (total 16)
DEBUG:miio.device:Discovered 03b9048e with ts: 1970-01-01 01:39:00, token: b'00000000000000000000000000000000'
INFO:miio.discovery:Found a supported 'Ceil' at 192.168.1.150 - token: 00000000000000000000000000000000
WARNING:miio.discovery:Found unsupported device philips-light-zyceiling_mibt62461553._miio._udp.local. at 192.168.1.152, please report to developers
WARNING:miio.discovery:Found unsupported device philips-light-zyceiling_mibt62462211._miio._udp.local. at 192.168.1.151, please report to developers

**Comment by syssi** [comment]
Cool. Thanks! The issue can be closed.
