### ISSUE TITLE
Starting the vacuum clean up after remote control

### ISSUE THREAD

**Issue by auser0** [rytilahti/python-miio#235]
Hello everyone, 

Just wondering if anyone had experience with getting the vacuum to start cleaning after using the remote control. I want to have the vacuum drive to a specific place in the house from the dock, clean for 10 minutes and then return to the dock. I am able to get the script to maneuver the vacuum to the room, however once I start the cleanup, it clears the map and loses the dock location. Any way around this or a specific command I should be using? I am just using raw command ap_rc_start, app_rc_move, and app_rc_end and then start cleanup command.

**Comment by rytilahti** [comment]
There is no way for that afaik. For gen2 robots a specific command is used to command the vacuum to clean the wanted location.

**Comment by auser0** [comment]
I've noticed that if I start cleanup, wait for ~15 seconds so it scans the room and establishes where the charger is, then turn on the remote controls. I can take it anywhere and it will remember where the dock is if I start cleaning. Only issue now is trying to figure out how I can make the vacuum move in the first 15 seconds in a predictable way. So far maybe 4/5 times it follows the same initial path along the wall but maybe the 5th time it moves in a slightly different way that throws off my remote control script.. Will probably have to set up walls around the charger and play around and hope for the best.

**Comment by rytilahti** [comment]
There is no zoned cleanup available which should be used for this, so I think this can be closed now.
