### ISSUE TITLE
Improved support of the Air Humidifier

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#241]
https://github.com/marcelrv/openhab2/blob/xiaomi-miio/addons/binding/org.openhab.binding.miio/database/zhimi.humidifier.v1.json#L104-L126

https://community.home-assistant.io/t/xiaomi-humidifier-support/35672/40

**Comment by leoneleone** [comment]
@syssi 
I have a few questions about the added the Properties:
trans_level, depth, dry

What are these properties and functions exactly?

What does “dry” actually do? It can be toggled in the Mihome.app

Does “depth” refer to Water Level (remaining water level)? 

What is “trans_level”? Is that the Remaining Water reading? 
I’ve checked all the documentation I can find, but these properties don’t seem to have a complete description yet. 

I’m trying to find Water Level readout to use in a homebridge plugin, and I want to understand how the “dry” function works on the .ca1 model of the Humidifier.  

I have zhimi.humidifier.ca1 (set to the Region HongKong). If I try to change that to USA I get an update pop-up. I think the firmware version changes depending on the Region/Locale the MiHome.app is set to.

Your help us very much appreciated.
