### ISSUE TITLE
Unable to discover the device 

### ISSUE THREAD

**Issue by dvido** [rytilahti/python-miio#259]
Hello,

I'm trying to control a Xiaomi smart plug. I'm doing a very simple thing:

print(miio.plug.Plug(token=plug_token, ip=plug_ip).status())

but it's not working. Could anyone point me to a solution here?
Also, I couldn't find any code example of the API usage and the documentation is very limited, would appreciate some help here.

Thanks in advance

**Comment by syssi** [comment]
Please post the error message / exception.

**Comment by dvido** [comment]
The error message is:
Unable to discover a device at address xxxxxxxxxx

The device is available vi the MiHome app.
I'm using python 3

**Comment by syssi** [comment]
This could be an invalid token. How long is your token? How did you retrieve the token? Did you reset the device in the mean time (another wifi network)?

**Comment by syssi** [comment]
I close this issue because of inactivity.
