### ISSUE TITLE
when i try to send a command 

### ISSUE THREAD

**Issue by Dmxsir** [rytilahti/python-miio#277]
im getting an error:
`Transmit of IR command failed, power, exception: {'code': -5008, 'message': 'magic error'}`

**Comment by rytilahti** [comment]
Maybe the command is in wrong format? More information could be helpful here, maybe someone with the device could also test it.

**Comment by Dmxsir** [comment]
You're right,
I did change the command format.
I did follow the instructions on HA site, but it's looks like the format its wrong. 

The right command format for me is:
 Command_on
Command_off
