### ISSUE TITLE
Vacuum v1 new firmware

### ISSUE THREAD

**Issue by leranp** [rytilahti/python-miio#305]
Hi,
The new firmware 3.3.0003194 doesn't work any more with Home Assistant, i suppose that python milo need to update to solve this problem
Any solution?

**Comment by rytilahti** [comment]
I have not had any problems with that firmware, so the problem must be somewhere else. How does it not work precisely? Have you reseted the vacuum (meaning that you would need to obtain the new token somehow)? Has something changed in your network? Is the `mirobo` tool working in console?

**Comment by leranp** [comment]
I have restrart the vacuum and took the token after installing the old version of Mi Home and change it in the Home Assistant configuration, there is any option that the token has changed after upgrade the version? 
My Mi Home version is 5.1.22

**Comment by leranp** [comment]
with mirobo i am getting this error
ERROR:miio.device:Got error when receiving: timed out
WARNING:miio.device:Retrying with incremented id, retries left: 3
ERROR:miio.device:Got error when receiving: timed out
WARNING:miio.device:Retrying with incremented id, retries left: 2

**Comment by lance36** [comment]
i just updated my vacuum to fw 3.3.9_003194 and i can confirm it working without problems with this library

**Comment by leranp** [comment]
My

**Comment by leranp** [comment]
How can i know if the token is wrong or correct?
The miio.discovery show the device

**Comment by leranp** [comment]
The token was incorrect, now everything working
