### ISSUE TITLE
Control Air Conditioner Companion like Xiaomi Mi Smart WiFi Socket

### ISSUE THREAD

**Issue by trlsmax** [rytilahti/python-miio#337]
Hi
Is this library can control the Air Conditioner Companion like Xiaomi Mi Smart WiFi Socket ? Just like the MiJia app do, control the output of 220v of the Air Conditioner Companion.

**Comment by syssi** [comment]
The output of the Air Conditioning Partner socket cannot be controlled. The hardware/device can measure the power consumption but is unable to toggle the socket by design. If you call the turn off/on method of the API a infrared command will be send.

**Comment by trlsmax** [comment]
Did you mean the Air Conditioning Partner is design to not able to toggle the socket ? For example, I connect a light bulb to the socket of Air Conditioning Partner, I can't turn on or off the light bulb anyway ?
But if I use the mijia app, I can turn it on or off. In fact , I want to connect the water heater to it.

**Comment by syssi** [comment]
This is new to me. Which hardware version of the device do you own?

**Comment by trlsmax** [comment]
I will let you know tomorrow

**Comment by trlsmax** [comment]
fw_ver:1.4.1_149
hw_ver:MW300
model:lumi.acpartner.v3
mcu_fw_ver:0149
wifi_fw_ver:SD878x-14.76.36.p84-702.1.0-WM

**Comment by hsie** [comment]
hi, just wonder if you found the fix as I am on the same boat as you.

I want to use the ac partner as a socket so as to turn on/off the water heater, but can't find a way to get it work on home assistant.

as you said, in the mijia app there is a choice that will operate the ac partner as a socket.

**Comment by syssi** [comment]
I made some progress. Can somebody tests these commands?

```
miiocli device --ip DEVIP --token DEVTOKEN raw_command toggle_plug '["on"]'
miiocli device --ip DEVIP --token DEVTOKEN raw_command toggle_plug '["off"]'
```
