### ISSUE TITLE
miiocli plug does not show the USB power status

### ISSUE THREAD

**Issue by elFua** [rytilahti/python-miio#344]
### Description
`miiocli plug` does not display the USB power state for Xiaomi Smart Socket enhanced version (with two USB charging ports).

### Steps to reproduce

Run:

```bash
miiocli plug --token <PLUG_TOKEN> --ip 192.168.1.100 status
```

### Actual output

```
Power: True
USB Power: None
Temperature: 41 °C
Load power: None
WiFi LED: None
```

### Expected output

```
Power: True
USB Power: True
Temperature: 41 °C
Load power: True
WiFi LED: True
```

### Notes:

Also missing outputs for:
 * **Load power**
 * **WiFi LED**

`miiocli plug usb_off/usb_on` work as expected

### Plug info

Output of `miiocli plug --ip 192.168.1.100 --token <TOKEN>  info`:

```
Model: chuangmi.plug.v3
Hardware version: ESP8266
Firmware version: 1.3.0_92
```

Xiaomi Smart Socket enhanced with 2 USB charging ports:
https://www.aliexpress.com/item/Xiaomi-socket-pro-home-WIFI-multifunction-USB-remote-control-home-electricity-statistics-Xiaomi-smart-socket-enhanced/32863730667.html

![xiaomi-smart-plug-specs](https://user-images.githubusercontent.com/1208627/41561028-17800440-7349-11e8-924e-0185219933ab.jpg)

![xiaomi-smart-plug-sku0](https://user-images.githubusercontent.com/1208627/41561045-20dd278e-7349-11e8-92ad-47b1999764f2.jpg)

**Comment by syssi** [comment]
The background: The ChuangmiPlug implementation supports four hardware versions of the device. If you use the library you can select a specific model. The `miiocli` uses a version without USB ports as default at the moment and the model cannot be changed.

For a good UX some issues should be fixed:
1. Make the device model selectable (`--model chuangmi.plug.v3`)
2. Auto-detect the device model on demand (`--model auto`)
3. List only supported properties at the status output (currently all known properties are listed)

**Comment by elFua** [comment]
@syssi:

Thanks for the hint! I realized that for my model the correct command is `miiocli plugv3` and not `miiocli plug` as I tried originally.

With `plugv3` everything works fine:


```bash
# miiocli plugv3

Power: True
USB Power: True
Temperature: 39 °C
Load power: 14.0
WiFi LED: True
```

The output above is as expected, so this ticket can be closed, unless you see the need to improve the invocation syntax or update the documentation.
