### ISSUE TITLE
miiocli plug does not provide the `discover` option

### ISSUE THREAD

**Issue by ghost** [rytilahti/python-miio#345]
`miiocli plug` (also `plugv1` and `plugv3`)  do not provide a `discover` option.

Running `miiocli plug` shows the following options:

```
# miiocli plug
Usage: miiocli plug [OPTIONS] COMMAND [ARGS]...

Options:
  --ip TEXT     [required]
  --token TEXT  [required]
  --help        Show this message and exit.

Commands:
  info          Get miIO protocol information from the...
  off           Power off.
  on            Power on.
  raw_command   Send a raw command to the device.
  set_wifi_led  Set the wifi led on/off.
  status        Retrieve properties.
  usb_off       Power off.
  usb_on        Power on.
```

The options above do not include a `discover` option.

**Comment by syssi** [comment]
PR #343 will add the "discover" option.

**Comment by DAVIZINH0** [comment]
sorry, maybe this question is stupid.
I install using pip3 install python-miio
but if i run the "miiocli plug" and error say to me that i dont installed the "miio"

How can i install the miio ??
