### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by freekeys** [rytilahti/python-miio#346]
Hi - is there a list of error codes and what they mean? I’m getting error 5008 (“magic error”) when running this through Home Assistant. Thanks!

**Comment by rytilahti** [comment]
That's a device specific error, from chuangi_ir (if I recall reading some post about that earlier), right? I suppose it means that the format you are giving it is incorrect, those kind of errors are coming directly from the device and not from this library.

**Comment by rytilahti** [comment]
There is nothing we really can do here, closing.
