### ISSUE TITLE
Information : Xiaomi Aqara Smart Camera Hack

### ISSUE THREAD

**Issue by tanguyfalconnet** [rytilahti/python-miio#347]
Hi,

I would like to know if someone already try to reverse-engineer some xiaomi camera ? Or if someone has any recommandation to hack it ?

I have this one : https://fr.gearbest.com/ip-cameras/pp_978606.html?wid=1433363, and I think it should be cool to use it outside of Mi Home. 

Yesterday I tried to discover it with the miio-python library, and I could access to info() of device module.
I tried to send "get_prop" commands without success, but maybe this is due to the pin code that I add on camera via Mi Home.

Tonight I will get rid of pin code and use Wireshark in MIIM mode.

Otherwise, thanks for your work on this library ;)

Regards,
Tanguy

**Comment by WilliamAnthony** [comment]
Hello, may I ask how is the progress? I'm interested to buy aqara camera, but waiting for its hack.

**Comment by rytilahti** [comment]
Closing this in favor of #373 which contains more information about the camera. Please test and report back there or in the PR!
