### ISSUE TITLE
No response from the device on Xiaomi Roborock v2

### ISSUE THREAD

**Issue by sgtio** [rytilahti/python-miio#349]
I'm trying to set up a Xiaomi roborock v2 and use it through home-assistant. However, I can't get it to work, so perhaps I'm doing something wrong.

I have extracted the pairing token by resetting the wi-fi in the device. I have used both the mirobo cli tool (with the --authenticate flag) and netcat to retrieve the token, just to confirm that it's correct. However, after confiiguring the robot through the Mi App to conect it to my wi-fi, I can't interact with the vacuum cleaner through the cli tool. From what I can see, it looks like the cli tool sends a HELLO message, which the vacuum cleaner answers, and then sends something else with goes unanswered?

Here is a capture with wireshark. I have highlighted the response from the vacuum cleaner:
- IP of the vacuum cleaner: 192.168.10.118 
- IP of my host: 192.168.10.100

```
➜  ~ export MIROBO_IP=192.168.10.118
➜  ~ export MIROBO_TOKEN=524179706b483355455a4d41736a3071
➜  ~ mirobo
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```
Hello from cli tool:
![query-hello](https://user-images.githubusercontent.com/3542989/41809498-e97babfe-76ee-11e8-8c90-343c1b54b86b.png)

Response from vacuum cleaner:
![response-hello](https://user-images.githubusercontent.com/3542989/41809499-e995518a-76ee-11e8-9db7-e7c14d6dd350.png)

Unanswered packet:
![unanswered-query](https://user-images.githubusercontent.com/3542989/41809500-e9b0b45c-76ee-11e8-9c63-78527369b549.png)

So, is there anything I'm doing wrong?
I have stored the wireshark pcap file, so if anybody needs it, please let me know.

Thanks for the help!

EDIT: Added headers to screen captures

**Comment by rytilahti** [comment]
When you provision the device through the mobile app, the device is generating a new token, so you have to obtain the token again after adding it through the app.

**Comment by sgtio** [comment]
That was what I tried in the first place, but all I got was the token composed by all 'f'. I read that this token was received because the robot was already paired, and the token retrieval needed to be done before the pairing with the Mi Home app. I also tried downgrading the app to 5.0.0, to extract the token from the app. Unfortunately it seems like that version of Mi Home is not able to discover the vacuum cleaner.

**Comment by sgtio** [comment]
I have been reading a bit this issue: https://github.com/rytilahti/python-miio/issues/185

Simulating the app from here seems like a plausible solution, but I wanted to ask if someone has tried messaging Xiaomi. Perhaps if enough of us send emails asking them for a way to extract the token, they will comply?

**Comment by J-CMartin** [comment]
I've used Method 3 for Non-rooted Android from the site below and was able to get the token properly. 

https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

The only think that is not mentioned there is the fact that newer versions of the software don't store the token, so version 5.0.29 has to be used:
https://www.apkmirror.com/apk/xiaomi-inc/mihome/mihome-5-0-29-release/

After getting the token from the DB, it all worked fine.

**Comment by sgtio** [comment]
Yeah, I installed the old version of the app and reset the robot. Unfortunately, the app could not find the robot, so I could not initiate the pairing.

**Comment by J-CMartin** [comment]
I don't think you need to pair via the old app necessarily, I've installed the app and signed in to my Xiaomi account, the Robot was already there... AFAIK the difference is that the old App stores the Token locally and the new ones don't.
I tried with version 5.0.0 on a different phone first but the backup was empty, not sure if it was the phone or App version, but then tried the 5.0.29 version and it worked

**Comment by sgtio** [comment]
OK, finally I have some more time to play with this. I have done the pairing with the new app using the european servers, but the old app only allows you to connect to the server in China (maybe also the US) so perhaps I need to go through the onboarding procedure using the server in China (with the new app) and then install the old app. I'm going to give it a quick try and will write back with the results.

**Comment by sgtio** [comment]
Well, nope, that didn't work either. I started up the new app and selected the US server (which is also available in the old app). Paired the robot with the new app and then uninstalled it and installed the old version. Then, I started the old app, selected the US server and signed up. The robot was not there.

Also, I checked the fw version of the vacuum cleaner: 3.3.9_001412

**Comment by sgtio** [comment]
Ok, I got it working. There were two catches I was missing:
One of them is that, despite the device not showing up in the app interface, it actually downloads the token into the database.
The second catch is that you need to select the same server on the old app as with the new app. Since the Europe server is not available in the old app, it can't be used.

So thanks everyone for their help!

**Comment by rytilahti** [comment]
Glad to hear you got it working :-) If you don't mind documenting this somehow to the documentation, it would be appreciated!

**Comment by sgtio** [comment]
Absolutely! I'll publish a patch ASAP
