### ISSUE TITLE
Xiaomi Philips Zhirui Bedside Lamp

### ISSUE THREAD

**Issue by ardeus-ua** [rytilahti/python-miio#351]
Just received the lamp today and want to connect it to Home Assistant.
_https://brightbestlight.com/xiaomi-philips-zhirui-lamp-review/
How can I help to add the support for this lamp?

**Comment by syssi** [comment]
Please extract the token and provide the output of the "info" command (mirobo/miiocli).

**Comment by ardeus-ua** [comment]
philips.light.moonlight v1.5.6

**Comment by syssi** [comment]
I'm looking for a mihome plugin which supports the device right now. Are you able to control the light with the MiHome app?

**Comment by ardeus-ua** [comment]
Yes, MiHome automatically downloaded plugin for the lamp.

**Comment by syssi** [comment]
Do you own a rooted phone and can you provide the plugin (apk file)?

**Comment by ardeus-ua** [comment]
I have checked it with rooted android phone but didn’t found it in the folder where the plugins are usually stored (found 2 plugins for 2 other devices I use but not for the moonlight) will dig additionally.

**Comment by ardeus-ua** [comment]
Found it! Here it is https://drive.google.com/file/d/1E4rbqvgnpd21y_lLfq-XLeMPq7IyKMlS/view?usp=drivesdk

**Comment by ardeus-ua** [comment]
Is there any way I can help in testing? I can forward ports and send you the details via personal message

**Comment by syssi** [comment]
```
# Model name
philips.light.moonlight

# Supported properties
["pow", "sta", "bri", "rgb", "cct", "snm", "spr", "spt", "wke", "bl", "ms", "mb", "wkp"]

# Supported methods
add_mb # Add miband
enable_bl # Night light
enable_sub_voice # Sub voice control?
enable_voice # Voice control
get_band_period # Bracelet work time
get_mb_rssi # Miband RSSI
miIO.bleGetNearbyBandList
get_wakeup_time
get_mb_mac # Miband MAC address
miIO.bleStartSearchBand
en_wakeup
set_band_period
set_bricct # Brightness & Color temperature
set_brirgb # Brightness & RGB
set_bright # Brightness
set_cct # Color temperature
set_rgb # RGB
set_mb_rssi
go_night # Night light / read mode
set_power
apply_fixed_scene
skip_breath
en_sleep
set_sleep_time
enable_mibs
set_wakeup_time
```

**Comment by syssi** [comment]
@ardeus-ua Could you provide the output of

```
$ mirobo --ip your-device-ip --token your-device-token raw_command get_prop "['pow', 'sta', 'bri', 'rgb', 'cct', 'snm', 'spr', 'spt', 'wke', 'bl', 'ms', 'mb', 'wkp']"
```

**Comment by ardeus-ua** [comment]
@syssi Here's what I got 

`Sending cmd get_prop with params ['pow', 'sta', 'bri', 'rgb', 'cct', 'snm', 'spr', 'spt', 'wke', 'bl', 'ms', 'mb', 'wkp']
['off', 0, 1, 16741971, 1, 0, 0, 15, 0, 1, 1, 1, [0, 24, 0]]
`

**Comment by ksoul78** [comment]
Hi, 
Is there anyway to send color cmd, if yes what is the color format : hex ? decimal?
Thanks,

**Comment by syssi** [comment]
You could try the yeelight specs:

> "rgb_value" is the target color, whose type is integer. It should be expressed in decimal integer ranges from 0 to 16777215 (hex: 0xFFFFFF).

```
# 0xFF0000 -> 16711680
$ mirobo --ip your-device-ip --token your-device-token raw_command set_rgb "[16711680]"
```

**Comment by ardeus-ua** [comment]
@syssi Sebastian, as far as I understand, moonlight uses generic commands). What device is the closest by the set of commands?

**Comment by syssi** [comment]
It's a mixture of a philips bulb, yeelight and the philips eyecare device. No implementation will work out of the box.

**Comment by ardeus-ua** [comment]
tricked it to work partially by setting philips.light.zyceiling

**Comment by syssi** [comment]
Could you provide some screenshots of the MiHome app? I don't understand the meaning of various properties (spr, spt, mb, ms, wkp).

**Comment by slakin** [comment]
Hi, 
![screenshot_2018-08-21-12-00-25-177_com xiaomi smarthome](https://user-images.githubusercontent.com/7987510/44392188-53f43680-a53a-11e8-8422-93d3c8306e3a.png)
![screenshot_2018-08-21-11-59-27-594_com xiaomi smarthome](https://user-images.githubusercontent.com/7987510/44392189-53f43680-a53a-11e8-9767-3969addff024.png)
![screenshot_2018-08-21-11-59-39-433_com xiaomi smarthome](https://user-images.githubusercontent.com/7987510/44392190-548ccd00-a53a-11e8-8b02-e9ea65351f9b.png)
![screenshot_2018-08-21-12-00-04-066_com xiaomi smarthome](https://user-images.githubusercontent.com/7987510/44392191-548ccd00-a53a-11e8-8c05-3eca82dd2d39.png)
![screenshot_2018-08-21-12-00-16-019_com xiaomi smarthome](https://user-images.githubusercontent.com/7987510/44392193-548ccd00-a53a-11e8-9879-8bbbfcb107ba.png)

**Comment by ardeus-ua** [comment]
Awesome. Eager to use it as soon as possible

**Comment by frkos** [comment]
It looks like it's not fully supported yet(((
Also i've found some bugs related to scenes. HA allows 1,2,3 and 4 only
But when I chose midnight theme from MI home, it shows as "6" in HA
When I chose music mode, in HA i have the error below:

Got exception while fetching the state: {'code': -5001, 'message': 'music mode'}
