### ISSUE TITLE
Cisco ISB 6030

### ISSUE THREAD

**Issue by airdropbelgium** [rytilahti/python-miio#352]
The on-off command of Cisco ISB 6030 is captured:
Z6WzAJgAAAD6AAAAIwEAAMMBAABwAgAAFAMAALxgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATIEAgQFAgICAgQDBAICBQIGATIEAgQFAgICAgQDBAICBQIGATIEAgQFAgICAgQDBAICBQIGATIEAgQFAgICAgQDBAICBQIGATIEAgQFAgICBAQDBAECBQIAA=

When trying to send it doesn't do anything. IR blaster does send out something because led blinks...

Anyone who can help/understand the captured IR code?

**Comment by irplus-remote** [comment]
I don't know if this is still relevant, but if you need the on-off code for isb6030, i just stumbled across it: 

protocol = Nokia32, device = 35, subdevice = 64, obc = 12, misc = X=38 T=0
0000 0073 0000 0048 000F 000A 0006 000A 0006 0016 0006 000A 0006 001C 0006 0010 0006 000A 0006 000A 0006 000A 0006 000A 0006 0016 0006 0010 0006 0016 0006 000A 0006 000A 0006 001C 0006 000A 0006 0CA3 000F 000A 0006 000A 0006 0016 0006 000A 0006 001C 0006 0010 0006 000A 0006 000A 0006 000A 0006 000A 0006 0016 0006 0010 0006 0016 0006 000A 0006 000A 0006 001C 0006 000A 0006 0CA3 000F 000A 0006 000A 0006 0016 0006 000A 0006 001C 0006 0010 0006 000A 0006 000A 0006 000A 0006 000A 0006 0016 0006 0010 0006 0016 0006 000A 0006 000A 0006 001C 0006 000A 0006 0CA3 000F 000A 0006 000A 0006 0016 0006 000A 0006 001C 0006 0010 0006 000A 0006 000A 0006 000A 0006 000A 0006 0016 0006 0010 0006 0016 0006 000A 0006 000A 0006 001C 0006 000A 0006 0CA3

**Comment by airdropbelgium** [comment]
Yes, still relevant. I guess I'll have to convert this message now to something else?

**Comment by irplus-remote** [comment]
If you're using the latest irplus version, you can use the CISCO, IPN4320 or ISB7500 Code. It should match.

**Comment by airdropbelgium** [comment]
Using the Xiaomi Universal IR and Cisco is not available as an option (or cannot find it).
I was trying via 3rd party to blat via the device and that's working for almost all options, except for the on-off option.

**Comment by irplus-remote** [comment]
Hm, this github tracker is just for irplus. So i don't know about xiaomi. 

https://play.google.com/store/apps/details?id=net.binarymode.android.irplus

**Comment by airdropbelgium** [comment]
Just checked via https://github.com/rytilahti/python-miio/pull/183 and send out the pronto code (which in the end was converted to the same code as in the first post). I think the Xiaomi IR (Chuangmi IR) doesn't support this one...

**Comment by irplus-remote** [comment]
Yea i don't know ill close this issue, as it is probably not related to **irplus**. If it does not work with **irplus** (with integrated IR, or WAVE and CISCO feel free to re-open)

**Comment by irplus-remote** [comment]
Sorry, mixed up the issue, don't worry :)
