### ISSUE TITLE
vacuum refuses to answer if the access to internet is blocked

### ISSUE THREAD

**Issue by IzK666** [rytilahti/python-miio#353]
I have a roborock v2 and I can control the robot only if internet is detected. If I block the internet access  then it does nothing although the blue light of wifi is on.
> $ mirobo 
> ERROR:miio.device:Unable to discover a device at address 10.0.0.8
> Error: Unable to discover the device 10.0.0.8

When I allow the internet access again, I can control it again, but it checks for internet very often. Once disabled, it takes 1 or 2 minutes to refuse answering again.

Don't know if you can do something through the api, or if you can suggest something to avoid it.
FW· version: 3.3.9_003194

**Comment by rytilahti** [comment]
Take a look at, point 2. should apply here: https://github.com/home-assistant/home-assistant/issues/11048#issuecomment-375930041 .
