### ISSUE TITLE
Zoned cleanup start and stops imediately

### ISSUE THREAD

**Issue by acca84** [rytilahti/python-miio#355]
Hello,
I'm trying to use miio from a python script in order to launch a zoned cleanup.
If i execute the command vac.zoned_clean(17800,21600,22700,25000,2), my vacuum starts a zoned cleanup and says "finished zoned cleanup, going back to the dock" after 2 seconds.
Other commands (clean, stop, dock ..) work well.
Is there anything else to do in order to initiate zoned cleanup ?
Regards

**Comment by ciB89** [comment]
try `vac.zoned_clean([17800,21600,22700,25000,2])`

**Comment by EmilBechMadsen** [comment]
I'm having this same issue. Doing what @ciB89 suggests just leads to argument errors, as it's expecting 4 positional arguments, not an array.

Did you make any progress?

**Comment by EmilBechMadsen** [comment]
Ah. After digging I see that @ciB89 spotted the issue here: https://github.com/rytilahti/python-miio/pull/311

What he meant to say in the above comment was: 

`try vac.send("app_zoned_clean", [[17800,21600,22700,25000,2]])`

**Comment by ciB89** [comment]
Yes, thank you :)

**Comment by rytilahti** [comment]
I suppose this is now fixed, please reopen if that's not the case.
