### ISSUE TITLE
Add i18n support for user-visible strings

### ISSUE THREAD

**Issue by jockebq** [rytilahti/python-miio#357]
Is it possible to add more languages for states?
Right now I have a sensor which displays the Mi Vacuum's state. Which might be "Charging", "Cleaning" etc.

Will there be translations for this?
This is the only part of my installation which isn't in Swedish right now.

**Comment by rytilahti** [comment]
At the moment, no. But I think that would be quite easy to add with gettext api, so if there's enough interest maybe it'll be implemented at some point. That's not a priority at the moment though.
