### ISSUE TITLE
Xiaomi Rice Cooker component not working

### ISSUE THREAD

**Issue by PaeseSono** [rytilahti/python-miio#365]
I have tried everything I could to bring up the cooker device show up on my HA but no luck at all.
I followed everything I could do in this github https://github.com/syssi/xiaomi_cooker but still didnt do anything at all.

I get my token using mirobo `discover --handshake 1`
and I can verified the token is working using `mirobo ip <IP> --token <TOKEN> raw_command` like `set_start` with a 60min cooking profile and my cooker did start cooking. I am using chunmi.cooker.normal2 as well which is the K2A profile getting from [
https://l.facebook.com/l.php?u=https%3A%2F%2Fcommunity.home-assistant.io%2Ft%2Fxioami-cooker-integration%2F34273%2F68&h=AT2m2UL3MPn3l1NPXDUYvxWJCNFj_wu7cMGdVljHeNKqcXrlc1lfrTaTinYjtnbpTqxbb3oSzUnxy4mkmDmCUp3Vp9nuH3ryNMhlg1fsqjtqiGLUStb8U0BUwLPE0uXRFTWCfnv5](url)

Anything Im doing here is wrong?

I downloaded the xiaomi_cooker.py files onto my hass.io config/custom_components directory, and i think it load just fine that way? This is my first custom components. In the past I have successfully added the miio_airpurifier without custom components.

**Comment by syssi** [comment]
The HA custom component of the xiaomi cooker is pretty incomplete. Please wait some time. I will improve the component soon.

**Comment by PaeseSono** [comment]
Anything I can help you with in the mean time? I have a few of xiaomi product, jailbroken iphone, android which could help improve the community. Not very comfortable to just sit around and wait you guys do the job alone.

**Comment by syssi** [comment]
Please copy the custom component again to your custom_components folder. You must copy all files and subdirectories. The xiaomi_cooker component is a platform. Copy and update the configuration lines. A few sensors should show up afterwards in HA. If you have trouble please create a issue at the xiaomi_cooker repository. I will provide support!
