### ISSUE TITLE
python-construct-2.9.45

### ISSUE THREAD

**Issue by frostworx** [rytilahti/python-miio#374]
first of all thank you for that great project! :)
current version of python-construct on arch linux is 2.9.45, but python-miio is pinned to 'construct==2.9.41'.
just bumped the required version within my local repo and looks like python-miio works just fine with 2.9.45.

**Comment by fabaff** [comment]
The right way to do it would be to remove the pinning to a given release of construct.

**Comment by syssi** [comment]
This isn't possible. Long story short: A lot of minor releases of construct broke this library in the past. We don't want to pin requirements. There is no better solution at the moment.

**Comment by syssi** [comment]
Ref. https://github.com/home-assistant/home-assistant/pull/13528

**Comment by fabaff** [comment]
What do the developers of `construct` say about breaking the API with minor releases?

**Comment by rytilahti** [comment]
* https://github.com/construct/construct/issues/428
* https://github.com/rytilahti/python-miio/issues/222

I think the API has now been stabilized (due to lack of time from the maintainer), so I think we could proceed to upgrade.

**Comment by frostworx** [comment]
with a likely stabilized construct API it would be the best choice imho to
set 'construct>=2.9.41' as dep for now.
would be also easier to handle for package maintainers and therefore would help to bring (latest) python-miio to more people.
a 'construct>=2.9.41' & 'construct<=$LAST_WORKING' would probably the easiest

**Comment by rytilahti** [comment]
I had a brief conversation with syssi about this and we decided, that as the API has been stabilized we will simply go and remove the pinning for the next release. Let's hope it stays stable!

**Comment by frostworx** [comment]
great decision imho! thank you for heads up! :)

**Comment by syssi** [comment]
Can be closed if #384 is merged.
