### ISSUE TITLE
Unsupported device found: chuangmi.ir.v2

### ISSUE THREAD

**Issue by lucasborin** [rytilahti/python-miio#392]
Log Details (ERROR)
Wed Oct 10 2018 21:02:25 GMT-0300 (Horário Padrão de Brasília)

Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: chuangmi.ir.v2

**Comment by syssi** [comment]
This is a error message of Home Assistant, correct? Could you provide the associated section of your configuration.yaml? The "remote.xiaomi_miio" component cannot produce this error. What did you do? :-)

**Comment by lucasborin** [comment]
[configuration.yaml.txt](https://github.com/rytilahti/python-miio/files/2485430/configuration.yaml.txt)

**Comment by lucasborin** [comment]
Maybe it is related to the socket entry.

**Comment by lucasborin** [comment]
Actually, I removed my sensitive data. That's why my IP and pass are not present in the file enclosed.

**Comment by syssi** [comment]
I know. Please check the IP address of the switch and the remote. Did you use the same IP by accident? Did you interchange the IPs of the devices?

**Comment by shoguevara** [comment]
Ran into the same issue, but after some digging realized that I used the same IP twice: once as the remote and second time for some reason decided to create switch with same IP address ><
Shout out to @syssi for saving me a lot of time!)
