### ISSUE TITLE
xiaomi repeater v1

### ISSUE THREAD

**Issue by aocana** [rytilahti/python-miio#396]
hi, 

i have home assistant releas 0.80.3 working with OS Linux homeassistant 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux. 
i have configured my xiaomi repeater into cofig yaml file :

` - platform: xiaomi_miio
    name: Original Xiaomi Mi Smart WiFi Socket
    host: 192.168.1.253
    token: e25e04cf****a************b3e318fad1`

and im getting following error :

`2018-10-23 16:33:33 ERROR (MainThread) [homeassistant.components.switch.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: xiaomi.repeater.v1`

is there any way to add this device into hass?
thans for the support!

**Comment by syssi** [comment]
You tried to integrate the Repeater as a "switch" component. This cannot work. 

Your configuration should look like this:

```
device_tracker:
  - platform: xiaomi_miio
    host: 192.168.130.73
    token: YOUR_TOKEN
```

**Comment by syssi** [comment]
This issue isn't python-miio related. Please create an issue at the home assistent repository.
