### ISSUE TITLE
Extract Preset IR codes

### ISSUE THREAD

**Issue by km2000us** [rytilahti/python-miio#401]
I was wondering if there is a way to extract the IR codes for devices that are in the servers database.

I would like to control my Air Conditioning units using the HomeAssistant front-end.  The AC units can be controlled using the Mi Home app with the Mainland China server.

I have tried learning the codes for the AC using the existing remotes but the codes do not work when sent using the send command.  I have set it up correctly and can learn and reproduce the codes to control my TV.

**Comment by syssi** [comment]
You could capture & decrypt the network traffic between your smartphone and the xiaomi device.

**Comment by km2000us** [comment]
Thanks for the suggestion - but that is a beyond my current skill sets.....  It would help if you could point me in the right direction for such tutorials.

I have tried to use the Mi Home app to learn AC codes, but it has a message that says AC codes are special and can't be learnt.  I guess that is why codes that are learnt using the remote.xiaomi_miio_learn_command does not work when sent using the remote.send_command.
