### ISSUE TITLE
Constant spam of: Unable to discover a device at address [IP] and Got exception while fetching the state: Unable to discover the device [IP]

### ISSUE THREAD

**Issue by cnrd** [rytilahti/python-miio#407]
Hi

So I have blocked access to the internet in my firewall for my Rockrobo S50, it still works fine in HomeAssistant. (States updating, able to send commands and so on), but I get a constant spam of:

- Unable to discover a device at address [IP]
- Got exception while fetching the state: Unable to discover the device [IP]
- Update of vacuum.xiaomi_vacuum_cleaner is taking over 10 seconds

Given that it correctly updates the state and I'm able to control it, these error messages makes no sense to me.

Is it possible to fix this, such that these errors won't come up when blocking the vacuum from the internet?

**Comment by rytilahti** [comment]
Do you still allow DNS requests to go through? If not, the miio_client (which is responsible for answering the requests on the vacuum) gets stuck and gets restarted automatically by a watchdog. The easiest solution is to allow DNS requests to go through.

**Comment by cnrd** [comment]
Yes I do allow both DHCP and DNS on to the firewall. (I did also try allowing DNS through the firewall, this did not change anything however).

**Comment by SlayDictator** [comment]
Same problem here, DHCP and DNS allowed, logs full of "...Unable to discover device..."

**Comment by SlayDictator** [comment]
Got it! Seems to work when using action REJECT instead of DROP on the firewall.

**Comment by rytilahti** [comment]
Yes, dropping the packets will cause the miio client on the device to crash, and thereby cause those messages. That's been a known problem for a long time, I made a summary here https://github.com/home-assistant/home-assistant/issues/11048#issuecomment-375930041 and left some comments behind in other places to encourage people to contribute to document this which alas never happened. I'll prepare a FAQ to document that and other common issues when I find some time. Or if someone wants to help with that, help would be more than welcome :-)

**Comment by rytilahti** [comment]
Just to add, if the xiaomi domains are resolving to 127.0.0.1 (e.g. you are blocking its access via pihole), you will also be unable to control the device.

**Comment by rytilahti** [comment]
The homeassistant spam issue is fixed as good as we can do by https://github.com/home-assistant/core/pull/41226 so time to close this.
