### ISSUE TITLE
Support for Xiaomi Air Quality Monitor 2gen

### ISSUE THREAD

**Issue by herolee** [rytilahti/python-miio#419]
$ mirobo discover
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
WARNING:miio.discovery:Found unsupported device cgllc-airmonitor-b1_miio57435516._miio._udp.local. at 192.168.0.79, please report to developers

$ mirobo --ip 192.168.0.79 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx info
cgllc.airmonitor.b1 v3.4.4_0077 (34:CE:00:8A:71:CC) @ 192.168.0.79 - token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by syssi** [comment]
Could you provide the output oft:

```
miiocli airqualitymonitor --ip IP --token TOKEN status
```

**Comment by herolee** [comment]
Model: cgllc.airmonitor.b1
Hardware version: Linux
Firmware version: 3.4.4_0077
Network: {'mask': '255.255.255.0', 'gw': '192.168.0.1', 'localIp': '192.168.0.79'}
AP: {'ssid': 'xxx', 'bssid': 'xx:xx:xx:xx:xx:xx'}

**Comment by syssi** [comment]
May be your device isn't compatible to the 1gen device. I will provide another command ASAP to retrieve selected properties only.

**Comment by herolee** [comment]
OK

The product link:
https://item.mi.com/1184500007.html

**Comment by syssi** [comment]
```
# try to retrieve multiple properties with one request
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['power', 'aqi', 'battery']"

# request one property per request
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['power']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['aqi']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['battery']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['usb_state']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['time_state']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['night_state']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['night_beg_time']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['night_end_time']"
miiocli airqualitymonitor --ip IP --token TOKEN raw_command get_prop "['sensor_state']"
```

**Comment by herolee** [comment]
Tried many times,get these results:

Running command raw_command
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
OR:
ERROR:miio.device:Unable to discover a device at address 192.168.0.79
Error: Unable to discover the device 192.168.0.79


Maybe because of the monitor using UDP protocol?

**Comment by syssi** [comment]
This happens usually if the TOKEN isn't correct.

**Comment by syssi** [comment]
Does the `info` call this work?

**Comment by herolee** [comment]
$ mirobo --ip 192.168.0.79 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx info
cgllc.airmonitor.b1 v3.4.4_0077 (34:CE:00:8A:71:CC) @ 192.168.0.79 - token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

$ miiocli airqualitymonitor --ip 192.168.0.79 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx info
Model: cgllc.airmonitor.b1
Hardware version: Linux
Firmware version: 3.4.4_0077
Network: {'mask': '255.255.255.0', 'localIp': '192.168.0.79', 'gw': '192.168.0.1'}
AP: {'ssid': 'xxx', 'bssid': 'xx:xx:xx:xx:xx:xx'}

but most times get 'time out' result.

**Comment by syssi** [comment]
Could you place the device next to your access point just for testing? May be your Wi-Fi connection is unstable/lossy.

**Comment by herolee** [comment]
OK,i'll try again later.

**Comment by herolee** [comment]
I have putted the device next to the AP but get the same result,always time out.

**Comment by syssi** [comment]
Hmm... it's hard to help here because it looks like a firmware issue or protocol incompatibility.

**Comment by herolee** [comment]
OK.Hope the next firmware will fix this issue.
Anyway,thank you for your reply :)

**Comment by mwenyuan** [comment]
I think Xiaomi use a new protocol for device with ESP32 chip. I tried to capture both local network and remote access from io.mi.com communication between Mijia.app and this device.

The communication between app and io.mi.com is like:

`{"id":188,"method":"get_air_data","accessKey":"******","params":{"systemInfo":{"mobileModel":"iPhone10,2","sysName":"iOS","sysVersion":"12.1.4"},"ownerId":"***","userId":"***","platform":"iOS"}}`

`{"code":0,"id":198,"result":{"co2e":721,"humidity":46.799999,"pm25":4.800000,"temperature":18.400000,"temperature_unit":"c","tvoc":0.713078,"tvoc_unit":"mg_m3"}}`

And the local communication is using udp 32761 and start with 0x6e4c, 1st Gen Air Quality Monitor was using udp 54321 and start with 0x2131. I cannot decode these packet with miio library.

these are some sample:

`        "data": {
          "data.data": "6e:4c:9d:8c:40:d1:40:ca:2d:2d:08:2d:00:e7:ca:da:9d:ea:a9:e4:03:95:53:8f:78:1b:4c:b9:e5:d0:e9:ad:6e:2e:8d:8c:40:d0:40:ca:3e:6d:3b:1f:40:a4:cb:d8:82:42:7d:b5:74:8b:90:c5:2d:6d:28:0c:60:e5:fa:ca:61:72:42:68",
          "data.len": "68"
        }
`

`
        "data": {
          "data.data": "6e:4c:9d:8c:40:d1:40:ca:2d:2d:08:2d:00:e7:ca:da:9d:ea:a9:e4:03:95:53:8f:78:1b:4c:b9:e5:d0:e9:ad:6e:2e:8d:8c:40:d0:40:ca:3e:6d:3b:1f:40:a4:cb:d8:82:42:7d:b5:74:8b:90:c5:2d:6d:28:0c:60:e5:fa:ca:61:72:42:68",
          "data.len": "68"
        }
`

**Comment by myvolkov** [comment]
I have the same problem for new firmware:
```
miiocli airqualitymonitor --ip 192.168.1.37 --token XXXXXXXXXXXXX info
Model: cgllc.airmonitor.b1
Hardware version: Linux
Firmware version: 3.4.4_0087
Network: {'mask': '255.255.255.0', 'gw': '192.168.1.1', 'localIp': '192.168.1.37'}
AP: {'bssid': '78:11:dc:f1:08:bc', 'ssid': 'WIFINET'}
```

than

```
miiocli airqualitymonitor --ip 192.168.1.37 --token XXXXXXXXXXXXX status
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```
and if try again ask info after status
```
miiocli airqualitymonitor --ip 192.168.1.37 --token XXXXXXXXXXXXX info
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```
looks like it hangs during several minutes after wrong request 

@mwenyuan, how did you dump and decrypt communication between app and io.mi.com?

**Comment by fwestenberg** [comment]
Hi guys, 

Any progress on this one? I'm also having this product and issue. I rally want to use it in Home Assistant. Let me know if I can help!

**Comment by syssi** [comment]
@fwestenberg Your device doesn't respond, too?

**Comment by fwestenberg** [comment]
No, just the info endpoint as mentioned above..

**Comment by mwenyuan** [comment]
@myvolkov mijia.app connects io.mi.com by https, so I use surge.app to MitM and capture the traffic.

**Comment by euroiasi** [comment]
Hello ! I have a problem with Xiaomi Mijia Smart Air Detector 3.97 Inch HD touch screen Intelligent Linkage 3 High-precision Sensors.
![20190326_102536](https://user-images.githubusercontent.com/49071010/55241674-3d3a5e80-5244-11e9-9fa7-66cc72063624.jpg)
Someone can find a solution ?
Thank you very much !

**Comment by Saniksanik** [comment]
You must call method "get_air_data"

**Comment by syssi** [comment]
Could somebody provide some example payload of the `get_air_data` response?

**Comment by skysilver-lab** [comment]
> Could somebody provide some example payload of the `get_air_data` response?

https://mjdm.ru/forum/viewtopic.php?f=5&t=4863&start=770#p106185

`{"result":{"co2e":1264,"humidity":45.400001525878906,"pm25":31.5,"temperature":29,"temperature_unit":"c","tvoc":0.3199849128723145,"tvoc_unit":"mg_m3"},"id":11}`

**Comment by syssi** [comment]
This is enough to provide basic support of the device.

**Comment by DiegoAstuy** [comment]
sorry one basic question it is possible to get the url command in order to integrate it in HA with the information from skysilver?

**Comment by fwestenberg** [comment]
Added pull request #562 
Workings fine with Home Assistant locally, hope it will be released soon!

**Comment by rytilahti** [comment]
The next version will contain support for thanks to @fwestenberg - closing this issue now.

**Comment by sayzard** [comment]
I found the solution. there are two things must be modified.

**Comment by fwestenberg** [comment]
> I found the solution. there are two things must be modified.
> 
> 1. id must be unique
> 2. accessKey: token on the payload
> 
> ```
> Send b'{"id": 5, "method": "get_air_data", "accessKey": "5a6a6734316c6c5a434d584a32483756", "params": []}\x00'
> 
> Response {'co2e': 1120, 'humidity': 30, 'pm25': 41.5, 'temperature': 23, 'temperature_unit': 'c', 'tvoc': 1.0229264497756958, 'tvoc_unit': 'mg_m3'}
> ```

Solution to what problem? The integration is running fine here.

**Comment by sayzard** [comment]
> > I found the solution. there are two things must be modified.
> > 
> > 1. id must be unique
> > 2. accessKey: token on the payload
> > 
> > ```
> > Send b'{"id": 5, "method": "get_air_data", "accessKey": "5a6a6734316c6c5a434d584a32483756", "params": []}\x00'
> > 
> > Response {'co2e': 1120, 'humidity': 30, 'pm25': 41.5, 'temperature': 23, 'temperature_unit': 'c', 'tvoc': 1.0229264497756958, 'tvoc_unit': 'mg_m3'}
> > ```
> 
> Solution to what problem? The integration is running fine here.

For an example)

**Comment by sayzard** [comment]
> > I found the solution. there are two things must be modified.
> > 
> > 1. id must be unique
> > 2. accessKey: token on the payload
> > 
> > ```
> > Send b'{"id": 5, "method": "get_air_data", "accessKey": "5a6a6734316c6c5a434d584a32483756", "params": []}\x00'
> > 
> > Response {'co2e': 1120, 'humidity': 30, 'pm25': 41.5, 'temperature': 23, 'temperature_unit': 'c', 'tvoc': 1.0229264497756958, 'tvoc_unit': 'mg_m3'}
> > ```
> 
> Solution to what problem? The integration is running fine here.

For an example)

**airqualitymonitor.py**
```
def __init__
  start_id: int = 0 -> unique number
```
**device.py**
```
        if command=='get_air_data':
          cmd = {"id": self._id, "method": command, "accessKey":codecs.encode(self.token, "hex").decode()}
        else:
          cmd = {"id": self._id, "method": command}
```
```
miiocli airqualitymonitor --ip IP --token  TOKEN raw_command get_air_data "[]"
```

**Comment by DiegoAstuy** [comment]
Integration is working fine in my side too, but not all the parameters from the unit are shown in HA; I just got CO2e, TVOC and PM2.5 but no Temperature, Humidity and battery. I don´t know if I´m missing something

**Comment by rytilahti** [comment]
Please open a separate issue for that, the basic support is already in place.
