### ISSUE TITLE
Replace pretty-cron dependency with cron_descriptor

### ISSUE THREAD

**Issue by pluehne** [rytilahti/python-miio#423]
I just realized that [`pretty_cron`](https://github.com/adamchainz/pretty-cron) is [used in a few places in this project](https://github.com/rytilahti/python-miio/search?q=cron&unscoped_q=cron) but [the authors of `pretty_cron` state that it is no longer maintained](https://github.com/adamchainz/pretty-cron#pretty-cron):

> Retired in favour of [`cron_descriptor`](https://pypi.org/project/cron_descriptor/).
>
> This project is no longer maintained.

It might make sense to follow the original authors’ recommendation to switch to `cron_descriptor` instead. Consider this just as a heads-up :slightly_smiling_face:.

**Comment by rytilahti** [comment]
Thanks for reporting this Patrick! pretty_cron is used only in one place (converting cron format to printable format) in mirobo cli tool, however, I don't think the timer functionality is used that much here. The conversion seems to be straightforward though, so I suppose we can either make the change or simply drop the dependency altogether.

**Comment by pluehne** [comment]
@rytilahti: That sounds good! I may be able to help with replacing or dropping the dependency, but I’ll be pretty busy until the end of the year.

**Comment by rytilahti** [comment]
Ok, this is definitely a low priority, and I think changing the dependency should be combined with making the timer functionality more straightforward to use (currently you need to construct your cron string, make sure everything is fine related to the active timezone etc. to use it). But if you want to tackle this, please feel free to do so :-)

**Comment by pluehne** [comment]
I’ll see what I can do. But if you have concrete plans to improve the timer interface, feel free to go ahead and don’t wait for me :slightly_smiling_face:!

**Comment by rytilahti** [comment]
As I'm not personally using it at all (preferring to handle scheduling via other means), so it's not of importance to me, and as is, it's just there for completeness. Therefore I'm wondering if the dependency should be dropped altogether, but I have really no plans on this for a way or another.

**Comment by frostworx** [comment]
looks like this is already fixed. the only occurence of "pretty_cron" is in requirements.txt
