### ISSUE TITLE
chuangmi.plug.hmi205 unsupported device

### ISSUE THREAD

**Issue by bcrowie** [rytilahti/python-miio#427]
Just picked up a few of these: https://www.walmart.com/ip/Xiaomi-Mi-Smart-Plug-No-Hub-Required/295288889

I used MiToolkit to get the tokens and configured in Home Assistant. Unable to see the switches in the interface I checked the logs to see this error:

Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: chuangmi.plug.hmi205

**Comment by syssi** [comment]
Could you try to control the plug nevertheless: 

```
miiocli plug status
miiocli plug on
miiocli plug off
```

**Comment by bcrowie** [comment]
Yes. All three commands work without issue.

**Comment by syssi** [comment]
Cool! I will prepare an update!

**Comment by syssi** [comment]
Could you provide the output of "mirobo discovery"? I'm interested in the mDNS name of the device.

**Comment by bcrowie** [comment]
I tried using 'mirobo discover' and it never provided results after even a few minutes so I give it 'mirobo discover --handshake 1' and this is what it gave me:

user@Server:~$ mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 192.168.0.64 (ID: 0584986b) - token: b'00000000000000000000000000000000'
INFO:miio.device:  IP 192.168.0.63 (ID: 05849df3) - token: b'00000000000000000000000000000000'

Not sure if this is what you need. If not, let me know what I need to do. Thanks for your help!

**Comment by debsahu** [comment]
Thanks for the PR, I was able to get it installed. Temperature reading is weird though! I'm reading 35 and 37. That's like body temperature, @bcrowie what readings are you getting?

**Comment by rytilahti** [comment]
On my `zimi.powerstrip.v2` the temperature is returning 46.07 which is probably not true either? Or maybe it is the temp of some internal part, which is used to control emergency shutdown if it gets too warm?

**Comment by bcrowie** [comment]
With the plug switched off for the whole day i received 30 degrees while testing. I tested after an hour of it being on and it measured 36.
