### ISSUE TITLE
Can't make it work in a Domoticz plugin

### ISSUE THREAD

**Issue by LucasLibis** [rytilahti/python-miio#433]
Hello,

I need help to use python-miio in a Domoticz Plugin.
I created a plugin containing only the default base template. The plugin logs a message each time one of it's methods (onStart, onHeartbeat, etc...) is called.

But as soon as I add 'import miio' in the plugin the methods are no longer called.

Does someone has an idea why my Domoticz plugin stops working when I import miio ?

Thank you

**Comment by kofec** [comment]
Maybe because of ssl library different version. You can take a look on my plugin base on also on this library

**Comment by LucasLibis** [comment]
Hi kofec,
Thank you for your reply, I tried your plugin but I have the same issue.
I'm not sure to understand the correlation with the ssl library, can you explain?

Thank you

**Comment by krotoniec** [comment]
Hello, 

I followed this tutorial - http://cezarowy.blogspot.com/2018/01/xiaomi-air-purifier-2-integracja-z.html

and it worked for me. It's in Polish though but you can easily translate it with Google.

Good luck!

**Comment by LucasLibis** [comment]
Hi krotoniec,

Thank you for the link, I'll give it a try :)

**Comment by rytilahti** [comment]
Hope you got it working! The question here is more related to domoticz than this library, so if you are still having the issue you should report it to domoticz developers :-)
