### ISSUE TITLE
Mirobo does not start on raspberry pi

### ISSUE THREAD

**Issue by thorschtn** [rytilahti/python-miio#442]
Do not get mirobo running on raspberry pi.

I have already updated Python and Pip and all dependencies, installation of python-miio ran without error, but at startup I always get the following error message, what's missing?

`pi@raspberrypi ~ $ mirobo --ip 192.168.178.38 --token 39xxxxxxxxxxxxxxxxxxxxxxa74
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 7, in <module>
    from miio.vacuum_cli import cli
  File "/usr/local/lib/python3.5/site-packages/miio/__init__.py", line 2, in <module>
    from miio.airconditioningcompanion import AirConditioningCompanion
  File "/usr/local/lib/python3.5/site-packages/miio/airconditioningcompanion.py", line 7, in <module>
    from .click_common import command, format_output, EnumType
  File "/usr/local/lib/python3.5/site-packages/miio/click_common.py", line 251, in <module>
    result_msg_fmt: Union[str, callable]="{result}"):
  File "/usr/local/lib/python3.5/typing.py", line 534, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/local/lib/python3.5/typing.py", line 467, in __new__
    params.append(_type_check(p, msg))
  File "/usr/local/lib/python3.5/typing.py", line 299, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Union[arg, ...]: each arg must be a type. Got <built-in function callable>.
`

**Comment by rytilahti** [comment]
The type hint should probably be `Union[str, Callable]`, but I'm curious why this has not been a problem earlier, maybe something was changed in the typing module at some point. Which python version are you using?

**Comment by thorschtn** [comment]
3.5.0

**Comment by syssi** [comment]
I cannot reproduce the issue:

```
$ cd /tmp
$ python3 -m venv test-mirobo
$ cd test-mirobo
$ source bin/activate
$ pip3 install python-miio
Collecting python-miio
  Downloading https://files.pythonhosted.org/packages/22/2b/2496f53ea46ee5a30424b900e77ce6de4892ec5e2b8cf7300a1c20e5e0b2/python_miio-0.4.4-py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 1.3MB/s 
Collecting android-backup (from python-miio)
[...]
Successfully installed android-backup-0.2.0 appdirs-1.4.3 asn1crypto-0.24.0 attrs-18.2.0 cffi-1.11.5 click-7.0 construct-2.9.45 cryptography-2.4.2 idna-2.8 ifaddr-0.1.6 netifaces-0.10.7 pretty-cron-1.2.0 pycparser-2.19 python-miio-0.4.4 pytz-2018.7 six-1.12.0 tqdm-4.28.1 zeroconf-0.21.3
$
$ ./bin/mirobo --ip 192.168.130.57 --token b051cd86f85996283d82ccf9d27bd2db info
chuangmi.plug.m1 v1.2.4_17 (28:6C:07:F5:39:6E) @ 192.168.130.57 - token: b051cd86f85996283d82ccf9d27bd2db
```

**Comment by thorschtn** [comment]
Thanks syssi,

I still have the issue, even in venv.

The differences in my environment are

Pip 18.1 vs. 9.0.1
Setuptools 18.2 vs. 32.3.1.

I need to check this once I'm back home.

**Comment by thorschtn** [comment]
Now I made an update to python 3.5.2 which brought Setuptools 40.6.3 - this made it working! Thanks an lot, the list of Software Versions helped!
