### ISSUE TITLE
xiaomi ir control

### ISSUE THREAD

**Issue by amedsaad** [rytilahti/python-miio#444]
I wrote the"learn" command and press the ON/OFF switch of the remote control and this is the result,I think there is a problem here.
my mirobo version is 0.4.4.

`NFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'seq': 6, 'manual_seq': 0}
DEBUG:miio.vacuum_cli:Connecting to 192.168.1.100 with token 205ea083b10445a79cac8a5b3eb47fc1
Sending cmd miIO.ir_learn with params {'key': '1'}
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        value = b'' (total 0)
        offset2 = 32
        length = 0
        data = b'' (total 0)
        offset1 = 32
    header = Container:
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x06z\x96f' (total 4)
            ts = 1970-01-01 00:01:30
        offset2 = 16
        length = 16
        data = b'!1\x00 \x00\x00\x00\x00\x06z\x96f\x00\x00\x00Z' (total 16)
        offset1 = 0
    checksum = b' ^\xa0\x83\xb1\x04E\xa7\x9c\xac\x8a[>\xb4\x7f\xc1' (total 16)
DEBUG:miio.device:Discovered 067a9666 with ts: 1970-01-01 00:01:30, token: b'205ea083b10445a79cac8a5b3eb47fc1'
DEBUG:miio.device:192.168.1.100:54321 >>: {'params': {'key': '1'}, 'id': 7, 'method': 'miIO.ir_learn'}
DEBUG:miio.device:192.168.1.100:54321 (ts: 1970-01-01 00:01:30, id: 7) << {'result': 0, 'id': 7}
0
DEBUG:miio.vacuum_cli:Writing {'seq': 7, 'manual_seq': 0} to /home/openhabian/.cache/python-miio/python-mirobo.seq`

**Comment by syssi** [comment]
This is fine. Next step is to `read` the learned command from storage `1`.

**Comment by amedsaad** [comment]
I tried the read command but there is an Error 

> Error: {'code': -5003, 'message': 'learn timeout'}

`[07:53:43] openhabian@O1StartUp:~$ mirobo --ip 192.168.1.100 --token 205ea083b10445a79cac8a5b3eb47fc1 -d raw-command miIO.ir_read '{"key": "1"}'
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'manual_seq': 0, 'seq': 13}
DEBUG:miio.vacuum_cli:Connecting to 192.168.1.100 with token 205ea083b10445a79cac8a5b3eb47fc1
Sending cmd miIO.ir_read with params {'key': '1'}
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        offset1 = 32
        length = 0
        data = b'' (total 0)
        offset2 = 32
        value = b'' (total 0)
    header = Container:
        offset1 = 0
        length = 16
        data = b'!1\x00 \x00\x00\x00\x00\x06z\x96f\x00\x00\x01a' (total 16)
        offset2 = 16
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x06z\x96f' (total 4)
            ts = 1970-01-01 00:05:53
    checksum = b' ^\xa0\x83\xb1\x04E\xa7\x9c\xac\x8a[>\xb4\x7f\xc1' (total 16)
DEBUG:miio.device:Discovered 067a9666 with ts: 1970-01-01 00:05:53, token: b'205ea083b10445a79cac8a5b3eb47fc1'
DEBUG:miio.device:192.168.1.100:54321 >>: {'params': {'key': '1'}, 'id': 14, 'method': 'miIO.ir_read'}
DEBUG:miio.device:192.168.1.100:54321 (ts: 1970-01-01 00:05:53, id: 14) << {'error': {'code': -5003, 'message': 'learn timeout'}, 'id': 14}
DEBUG:miio.click_common:Exception: {'code': -5003, 'message': 'learn timeout'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/miio/vacuum_cli.py", line 624, in raw_command
    click.echo(vac.raw_command(cmd, params))
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 304, in raw_command
    return self.send(command, parameters)
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 272, in send
    raise DeviceError(m.data.value["error"])
miio.exceptions.DeviceError: {'code': -5003, 'message': 'learn timeout'}
Error: {'code': -5003, 'message': 'learn timeout'}
`

**Comment by amedsaad** [comment]
Yes, thank you
