### ISSUE TITLE
Moonlight sync with HA

### ISSUE THREAD

**Issue by jokerigno** [rytilahti/python-miio#452]
Hi,

I noticed that if I change color or brightness using moonlight lamp the result doesn't change in HA (0.84.6).

**Comment by rytilahti** [comment]
Does miiocli report the values correctly? If yes, this might be an issue on homeassistant's side.

**Comment by jokerigno** [comment]
Miiocli is the mi home app?

If so the answer is yes: the app report the correct value

**Comment by syssi** [comment]
Please install this library by "pip". It provides a command line interface called `miiiocli`.

**Comment by syssi** [comment]
```
pip3 install python-miio
miiocli -d philipsmoonlight --ip IP --token TOKEN status
```

**Comment by syssi** [comment]
Thanks! If you turn off the "night mode" does the component/library work as expected?

**Comment by jokerigno** [comment]
Yes. If I change color in HA I can see the change in Mi Home app and viceversa. So the Issue seems related to night mode. 

Can in be implemented somehow?

**Comment by jokerigno** [comment]
Ok. It can be done via script but there's still a issue.

Set scene allow values from 1 to 4 while my moonlight bedlamp has 6 scene. And I'm intrested in using the sixth (night mode). 

So @syssi do you think it is still achievable?

**Comment by syssi** [comment]
Honestly I don't know. You could use the miioclio tool to test all cases. I assume the night mode is a fixed brightness + colortemp. Do you want to cancel the night mode if you change the brightness f.e.?

**Comment by jokerigno** [comment]
Yes. I want to create a goodnight scene (with lamps on night mode) but also a goodmorning scene with a different brightness.

**Comment by jokerigno** [comment]
Well. I see that moonlight bedlamp has 6 available scene while component allow to choose between 4. 

@rytilahti maybe it can be added to the component?

**Comment by syssi** [comment]
I've added scene 5 and 6 in the past. I will close this issue.

https://github.com/rytilahti/python-miio/blob/master/miio/philips_moonlight.py#L250-L258

**Comment by jokerigno** [comment]
Thank you!
