### ISSUE TITLE
Support for chuangmi plug m3

### ISSUE THREAD

**Issue by wzhd** [rytilahti/python-miio#454]
It is hard to find a supported device by reading the list of supported devices on the homepage. I bought a smart plug that with just one socket, I thought it may be just the generic `Xiaomi Mi Smart WiFi Socket` listed. But the discover commands produce no output at all.

The model is ZNCZ04CM. The CMIIT ID is 2018DP3791.

From the list of dhcp leases, its name starts with `chuangmi-plug-m3_miio`.

Is it supported or being worked on?

I may give it a try if I get the time and no one has started working on it.

**Comment by syssi** [comment]
It's supported now by https://github.com/rytilahti/python-miio/pull/455

**Comment by Electronlibre2012** [comment]
hello,

sorry but the problem is back 👍 
```
Error unloading entry Prise Salon Ventilateur for xiaomi_miio

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 473, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'b52294f74aede8792918f0be3f602870'

```

i have some and they are unavailable for hours then available for 1 hours then goes unavailable again and again.

I there a way to solved it please. It seems to have happened with HA core 2023.2.x
