### ISSUE TITLE
Send OTA update command with miiocli

### ISSUE THREAD

**Issue by pcmester** [rytilahti/python-miio#479]
In the miiocli documentation, there is an update command, that allows to provide a url and md5 hash to push update to the devices. Unfortunately, there isn't any documentation about the vaild syntax to provide the url and md5. 

Can somebody help with this?

**Comment by rytilahti** [comment]
I'm not sure if the feature has been tested by any other devices besides the vacuum (which I have personally tested), so at the moment the only documentation for that exists in https://python-miio.readthedocs.io/en/latest/vacuum.html#firmware-update - maybe that helps you :-)

**Comment by pcmester** [comment]
This command is not work with other device (only for vacuums), but I have founded this miIO.ota raw command. There is a problem: When I run it, I have -1 result. What causes this problem?

**Comment by rytilahti** [comment]
No idea, maybe the format was wrong? That error is coming from the device so it is hard to say what is the real problem, sorry.

**Comment by ratcashdev** [comment]
I was trying to send a raw miIO.ota command to the Philips EyeCare 2 lamp (as described here:    https://github.com/dgiese/dustcloud/wiki/VacuumRobots-manual-update-root-Howto).
Needless to say, no success. I checked the available firmware in https://github.com/dgiese/dustcloud-documentation/tree/master/philips.light.sread1/firmware/1.3.0.0024 and realized, that this lamp needs more params (especially mcu_url), so I tried with 
`mirobo --ip 192.168.1.90 --token caa7ef3bfb197dc5408141edcc4b63e6 raw-command miIO.ota '{"app_url":"https://github.com/dgiese/dustcloud-documentation/raw/master/philips.light.sread1/firmware/1.3.0.0024/e68ab833f7dd35ee50c1013be967655b_upd_xiaomi.dev.lx1.bin","mcu_url":"https://github.com/dgiese/dustcloud-documentation/raw/master/philips.light.sread1/firmware/1.3.0.0024/8332a64e238f673b57b3d70316415e02_mcu_philips.light.sread1.bin"}'` but I was still getting `-1` as an answer. In any case this post maybe helps someone tackle the remaining obstackles.

**Comment by faceless44** [comment]
try `miIO.ota_instal`l command

**Comment by ratcashdev** [comment]
@faceless44  the command is solid, but I need the correct JSON :(

**Comment by faceless44** [comment]
> @faceless44 the command is solid, but I need the correct JSON :(
localJSONObject.put("method", "miIO.ota_install");
no?

**Comment by ratcashdev** [comment]
@faceless44 I need the json containing the URL to the firmware. Something about app_url and mcu_url.
