### ISSUE TITLE
impossible to get the last version (0.4.5) or even the 0.4.4

### ISSUE THREAD

**Issue by adrienvia** [rytilahti/python-miio#489]
Hi,

I would like to use this for zone cleaning, but when I install it, and check the version mirobo --version, it says 0.4.3, I try to uninstall it, re install it (with several ways) even with  pip install python-miio==0.4.5, and at the end it says "Successfully installed python-miio-0.4.5" but when I check, mirobo, version 0.4.3 ... so I don't have the zoned-clean option...

I really don't understand why

**Comment by syssi** [comment]
Did you install the package as user (~/.local/bin/miiocli) or as root (/use/local/bin/miiocli)? Is guess you have installed the package twice with different locations.

**Comment by adrienvia** [comment]
oh yes, I think i did that, there is miiocli in both locations, the one that I installed today is as root, and the other one is from several months, I think maybe with the xiaomi plugin for domoticz... so with the user pi. so how to uninstall the older one, or both to do a clean install

**Comment by syssi** [comment]
Once per user: `pip uninstall python-miio`.

**Comment by adrienvia** [comment]
thanks, I mixed and getting confused with the sudo command ... it's all good now =)
