### ISSUE TITLE
Roborock v2 zoned_clean() doesn't work

### ISSUE THREAD

**Issue by rogerbl** [rytilahti/python-miio#490]
When the zoned_clean() command is issued in python with proper x and y parameters the roborock starts cleaning, but not in the zone it was supposed to according to the parameters.
Looks like its ignoring the area given in the parameters.

**Comment by Defozo** [comment]
I just set up my Home Assistant to use `app_zoned_clean` on my Roborock v2 and something like this happens to me:

![image](https://user-images.githubusercontent.com/8215510/55275368-6a8b1900-52e5-11e9-8454-2f665ed3b026.png)

![image](https://user-images.githubusercontent.com/8215510/55275398-c35ab180-52e5-11e9-9437-f0712714770f.png)

The robot cleans only a small fragment of the zone.

Is this the same problem?

I wonder if switching off and on `Map saving mode(Beta)` in `Vacuum settings` would help?
Also, I read that when you change the location of the docking base the coordinates would change too. It didn't happen to me. Maybe that's connected with the problem?

**Comment by Defozo** [comment]
I found out that one needs to provide x,y from the lowest left corner and x,y from the highest right corner - in that order. Then, the robot cleans the area just fine.

**Comment by rogerbl** [comment]
Hi and thanks for ur answer!
And I would like to congrat you with a great work supporting the Xiaomi’s devices!

I figured out how to overcome the problem. I’m now using this subprosess code
to get it to work with zone cleaning:

import subprosess
cmd="mirobo --ip "+robo_ip+ " --token "+ robo_token+" zoned_clean [[32566,24867,33966,29817,1],[ 24091,25176,27591,31376,1]] " # just an example
p = subprocess.Popen(cmd)

This works perfect for me! 😊

My problem was the when I called zoned_clean(cmd) in the script, the roborock just started to clean the whole house.
But now it works ok.
I didn’t have a problem with the map though. It just disappered once, but came back after a while.

Keep up with the great work!


Regards
Roger Blomkvist
Blomkvist ITK as
99519810

Automasjon Sunt og trygt innemiljø ITservice
http://bit.do/blomkvistitk



Nettbutikk: http://bit.do/exscg

[QR Code for /exscg]<http://bit.do/qrcode/exscg>

Fra: Michał Kiełtyka <notifications@github.com>
Sendt: lørdag 30. mars 2019 12.23
Til: rytilahti/python-miio <python-miio@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [rytilahti/python-miio] Roborock v2 zoned_clean() doesn't work (#490)


I just set up my Home Assistant to use app_zoned_clean on my Roborock v2 and something like this happens to me:

[image]<https://user-images.githubusercontent.com/8215510/55275368-6a8b1900-52e5-11e9-8454-2f665ed3b026.png>

[image]<https://user-images.githubusercontent.com/8215510/55275398-c35ab180-52e5-11e9-9437-f0712714770f.png>

The robot cleans only a small fragment of the zone.

Is this the same problem?

I wonder if switching off and on Map saving mode(Beta) in Vacuum settings would help?
Also, I read that when you change the location of the docking base the coordinates would change too. It didn't happen to me. Maybe that's connected with the problem?

**Comment by rogerbl** [comment]
Hi again Michal!
I cannot get manual mode to work.
What type of parameters does the move forward, backward, right and left need?
I tried with a number(string) as ‘1’, but it didn’t work.


Vennlig hilsen
Roger Blomkvist
Blomkvist ITK as
99519810

Automasjon Sunt og trygt innemiljø ITservice
http://bit.do/blomkvistitk



Nettbutikk: http://bit.do/exscg

[QR Code for /exscg]<http://bit.do/qrcode/exscg>

Fra: Michał Kiełtyka <notifications@github.com>
Sendt: lørdag 30. mars 2019 14.43
Til: rytilahti/python-miio <python-miio@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [rytilahti/python-miio] Roborock v2 zoned_clean() doesn't work (#490)


I found out that one needs to provide x,y from the lowest left corner and x,y from the highest right corner - in that order. Then, the robot cleans the area just fine.

**Comment by rytilahti** [comment]
Is this still an issue? If not, please consider closing it, thanks!
