### ISSUE TITLE
python-miio not compatible with Python <=3.5.1

### ISSUE THREAD

**Issue by j-muller** [rytilahti/python-miio#494]
Hi guys,

Thank you for your amazing work.
While playing with the library, I realized that the library may not be compatible with Python 3.5.1 (and prior versions) because of the behavior of `typing` that changed.

In Python 3.5, running a simple `from miio.vacuum import Vacuum`, results in:

```python
[...]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/typing.py in _type_check(arg, msg)
    297         arg = _ForwardRef(arg)
    298     if not isinstance(arg, (type, _TypeAlias)):
--> 299         raise TypeError(msg + " Got %.100r." % (arg,))
    300     return arg
    301

TypeError: Union[arg, ...]: each arg must be a type. Got <built-in function callable>.
```

**Comment by rytilahti** [comment]
Hi and thanks for letting us know! Maybe we should bump the requirement to require at least 3.5.3 (or move simply to support only 3.6 and above, as soon as https://github.com/home-assistant/architecture/issues/167 gets implemented). I don't see a reason to spend time supporting old, more obscure python versions (debian stable, which is already very old, ships 3.5.3 already).
