### ISSUE TITLE
Roborock S50: ERROR:miio.updater:No request was made..

### ISSUE THREAD

**Issue by nicedevil007** [rytilahti/python-miio#508]
Hi guys,
I got a problem with my Roborock S50. I flashed him several times before with valetudo and actual firmware. Everything worked great. Now I tryed upgrading to 1844 and I'm not able to get miio to update my robot :(

Here are the commands that I usually use for this: the token is extracted from an iPhone backup, because I wasn't able to get it with mirobo --debug discover --handshake true

`(venv) [root@host rockrobo]# mirobo --ip 192.168.8.1 --token 7150343162784154496b4a796XXXXX update-firmware image/output/v11_001844.fullos.pkg
Going to update from image/output/v11_001844.fullos.pkg
INFO:miio.updater:Serving on 0.0.0.0:40207, timeout 10
INFO:miio.updater:Using local image/output/v11_001844.fullos.pkg (md5: 0529d86a11b7fdb7123dfdff7866a378)
Hosting file at http://192.168.8.140:40207/v11_001844.fullos.pkg
ERROR:miio.updater:No request was made..
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
`
The robot is pingable on this IP

Can anyone help me out?

**Comment by rytilahti** [comment]
Are the other commands working just fine with that token? Is there connectivity via that IP address between the devices? The reason for this is just as the message says, the vacuum never made a try to download the file, which usually indicates that there is problem with connectivity.

**Comment by rytilahti** [comment]
Closing as stale, please reopen if this is still an issue.

**Comment by xobs** [comment]
I am having this issue as well.

One problem was that Python was picking the wrong IP address.  It was choosing the pcap adapter instead of my actual network interface:

```
oing to update from .\flasher\v11_001782.fullos.pkg
INFO:miio.updater:Serving on 0.0.0.0:48189, timeout 10
INFO:miio.updater:Using local .\flasher\v11_001782.fullos.pkg (md5: 84a693dedcdc8ae14a05263579fac059)
Hosting file at http://169.254.115.38:48189/v11_001782.fullos.pkg
Update started!
  0%|                                                                                                                                      | 0/100 [00:00<?, ?it/s]
ERROR:miio.updater:No request was made..
```

This is solved by adding a second `--ip` argument after the command.

It took a couple of tries to actually get the update installed.

A few times I got the `update failed` message:

```
$ mirobo update-status
Update state: UpdateState.Failed
$ 
```
