### ISSUE TITLE
Question about vacuum errors_codes duration

### ISSUE THREAD

**Issue by oncleben31** [rytilahti/python-miio#511]
I monitor and pilot my vacuum in home-assistant.
Some times I receive an error notification in the Xiaomi Home application but it's not catched by home assistant.
As hass, is updating the state every 20 seconds, I wonder if there are some error codes that last few seconds. Is there any knowledge about that, and workaround ideas ?

It happens at least for error n°12 "Low battery" and n°23 "Docking station not reachable"

**Comment by rytilahti** [comment]
Not all information is not delivered as part of the status report, but "events" are pushed to the server by the vacuum. Unfortunately this means that there is currently no way to obtain that information, I think this valetudo issue is related: https://github.com/Hypfer/Valetudo/issues/133 - I will close this issue, as there is really nothing this library can do to change the situation.

I think I had seen the docking station not reachable error at some point, but I may be wrong. In case you are running a really old installation, then this may be relevant: https://github.com/rytilahti/python-miio/pull/379
