### ISSUE TITLE
Discovery mode to chuangmi_camera.

### ISSUE THREAD

**Issue by Om3rr** [rytilahti/python-miio#522]
Hey, I tried to discovery my chuangmi camera and when I tried to run 
from miio.discovery import Discovery
Discovery.discover_mdns()

it raise
Found unsupported device chuangmi-camera-ipc009_miio263372670._miio._udp.local. at 10.0.0.26, please report to developers

**Comment by rytilahti** [comment]
Support for this was added in https://github.com/rytilahti/python-miio/pull/516 so it will part of the next release. Meanwhile you can checkout the git master.
