### ISSUE TITLE
Move Roborock when in error

### ISSUE THREAD

**Issue by henrik242** [rytilahti/python-miio#524]
I'm not home and Mi Home says `Vacuum is tilted`. Looks like the robot is stuck on a doorstep.  Is there a way to send a command to Roborock S6 (or S50) to force it to try getting loose again? 

I have tried logging into my local server and issuing a couple of movement commands (`mirobo manual backward 0.3` etc), but it doesn't seem to move. The `status` command still reports `error! put me on a flat surface!`. 

It still must have made some noise though, because the cat door reported that the cat went outside :D

**Comment by rytilahti** [comment]
What happens if you try to send it back to home? Unfortunately I don't know whether the robby is responsive if it's erroring out, let me know if you find anything :-)
