### ISSUE TITLE
Support for Mi Smart Humidifier (deerma.humidifier.mjjsq)

### ISSUE THREAD

**Issue by rezmus** [rytilahti/python-miio#533]
it's new mi humidifier, miio model deerma.humidifier.mjjsq

https://www.xiaomiyoupin.com/detail?gid=109486
https://ibb.co/n1dwCgS

while i don't have device (yet?) i took a look at the plugin so i leave info here if anybody wants to add support. below you can find all props/methods supported by firmware.

{"method":"get_prop","params":["Humidifier_Gear","Humidity_Value","HumiSet_Value","Led_State","OnOff_State","TemperatureValue","TipSound_State","waterstatus","watertankstatus"]}

props

Humidifier_Gear - speed (1-4, 1 Low, 2 Medium, 3 High, 4 Humidity)
Humidity_Value - humidity value (0-100)
HumiSet_Value - desired humidity value? (not used by plugin atm)
Led_State - led state (0 - off, 1 - on)
OnOff_State - power state (0 - off, 1 - on)
TemperatureValue - temperature value
TipSound_State - sound state (0 - off, 1 - on)
waterstatus - water status (0 - insufficient, 1 - normal)
watertankstatus - water tank status (0 - detached, 1 - installed)

methods

{"method":"Set_HumidifierGears","params":[1-4]} - set speed (Humidifier_Gear prop)
{"method":"Set_OnOff","params":[0/1]} - set power off/on (OnOff_State prop)
{"method":"SetLedState","params":[0/1]} - set led off/on (Led_State prop)
{"method":"SetTipSound_Status","params":[0/1]} - set sound off/on (TipSound_State prop)
{"method":"Set_HumiValue","params":[0-100]} - set desired humidity value? (not used by plugin atm)

**Comment by syssi** [comment]
@rezmus Good job! This should be enough to support the device.

**Comment by dovchinnikov** [comment]
@rezmus hi, could you please teach how "to look at the plugin" to obtain properties and methods?
