### ISSUE TITLE
Add support for WIDETECH WDH318EFW1 dehumidifier (nwt.derh.wdh318efw1)

### ISSUE THREAD

**Issue by stkang** [rytilahti/python-miio#534]
model: nwt.derh.wdh318efw1

https://ko.aliexpress.com/item/32992201709.html

I tried, but I do not know what prop is.

Can I query the prop list of nwt.derh.wdh318efw1?

**Comment by rezmus** [comment]
https://ibb.co/wJ8J5L6

{"method":"get_prop","params":["on_off","mode","fan_st","buzzer","led","child_lock","humidity","temp","compressor_status","fan_speed","tank_full","defrost_status","alarm","auto"]}

humidity, temp, fan_speed - int
compressor_status, tank_full, defrost_status, alarm - on/off

{"method":"set_power","params":["on"]} (on/off) - on_off
{"method":"set_mode","params":["auto"]} (on/auto/dry_cloth) - mode
{"method":"set_fan_level","params":[1]} (1-3) - fan_st
{"method":"set_buzzer","params":["on"]} (on/off) - buzzer
{"method":"set_led","params":["on"]} (on/off) - led
{"method":"set_child_lock","params":["on"]} (on/off) - child_lock
{"method":"set_auto","params":[40]} (40/50/60) - auto

**Comment by stkang** [comment]
@rezmus  Thank you!!
I'll try it!

**Comment by stkang** [comment]
@rezmus @syssi 
I want to distribute to HA too.
When will python-miio 0.4.6? be distributed?

**Comment by syssi** [comment]
@stkang python-miio 0.4.6 is released. Feel free to contribute a HA integration!

**Comment by stkang** [comment]
@syssi Thanks
