### ISSUE TITLE
Roborock Vacuum Bin full

### ISSUE THREAD

**Issue by isabellaalstrom** [rytilahti/python-miio#546]
I was wondering about the possibility to implement the "bin full" state, as the app sends notifications about this. Is this information possible to get from the api?

**Comment by rezmus** [comment]
i'm not 100% sure, but i don't think you can fetch such info. i mean there is an event.bin_full, but no way to get events from local miio api.

**Comment by isabellaalstrom** [comment]
Alright, that's a bummer, but thank you!

**Comment by rezmus** [comment]
i've checked plugin and you should be able to get bin_full info when status is fetched. error code 644 is related to bin problems.

**Comment by isabellaalstrom** [comment]
Is there any way I can test this for s5?

**Comment by isabellaalstrom** [comment]
I know this is a long time ago now, but I haven't really had the time. Today my bin got full though and I though of this. I don't really understand how I should do it. I installed so I can use the cli, but I'm not sure that's where I should be doing this?

**Comment by rytilahti** [comment]
When the bin is full, simply execute `mirobo -d` to see if the `state` or `error_code` in the returned payload indicates something about its state.

**Comment by isabellaalstrom** [comment]
This is what I got!

```DEBUG:miio.miioprotocol:Discovered 0f8e3dc3 with ts: 2020-04-02 12:48:08, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.56:54321 >>: {'id': 3, 'method': 'get_status', 'params': []}
DEBUG:miio.miioprotocol:192.168.1.56:54321 (ts: 2020-04-02 12:48:08, id: 3) << {'result': [{'msg_ver': 3, 'msg_seq': 1953, 'state': 8, 'battery': 100, 'clean_time': 1132, 'clean_area': 21057500, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 101, 'dnd_enabled': 0, 'map_status': 3, 'lock_status': 0}], 'id': 3}
State: Charging
Battery: 100 %
Fanspeed: 101 %
Cleaning since: 0:18:52
Cleaned area: 21.0575 m²
DEBUG:miio.vacuum_cli:Writing {'seq': 3, 'manual_seq': 0} to /home/isabella/.cache/python-miio/python-mirobo.seq

**Comment by rytilahti** [comment]
Unfortunately there is nothing indicating that the bin is full. Does the vacuum allow starting it, or does it indicate an error at the moment you try to start it? If the latter, you could try executing the command straight after hearing the error, some errors are "reseted" after a while.
