### ISSUE TITLE
chuangmi.camera.ipc009 camera stream

### ISSUE THREAD

**Issue by BaQs** [rytilahti/python-miio#547]
Hi,
I saw the chuangmi.camera.ipc009 is supported since few updates.
Do you know if there is a way to catch the camera stream ?

I've been playing around, no way to get this.

It seems videop2proxy would require avID, avPass, p2pid, but again: no way to get that.
It seems this camera requires some private key.

Any help appreciated!

**Comment by impankratov** [comment]
@BaQs there's a telegram group related to adding rtsp support https://t.me/mijav4RTSP
