### ISSUE TITLE
I can not get load_power with my set is Xiaomi Smart WiFi with two usb (chuangmi.plug.v3)

### ISSUE THREAD

**Issue by xiaobai987292** [rytilahti/python-miio#549]
my code is 

```
from miio.chuangmi_plug import ChuangmiPlug
ip='192.168.31.105'

token='c0a62ad33e0f047d15380282c12f2216' # 输入之前获得token

d = ChuangmiPlug(ip=ip, token=token)

x=d.status() # 给出设备的状态

print(x)
```

the result is 
`<ChuangmiPlugStatus power=True, usb_power=None, temperature=40, load_power=None, wifi_led=None>`

the load_power  could get in mihome app

**Comment by syssi** [comment]
Which hardware version of the device do you own? Are you sure it's capable to measure the power usage?

**Comment by xiaobai987292** [comment]
my hardware  could Statistics the power and used-power like image like this


![微信图片_20190915191128](https://user-images.githubusercontent.com/26730099/64920699-233e0980-d7ed-11e9-83f7-a2f077a2bbc0.jpg)
![微信图片_20190915191134](https://user-images.githubusercontent.com/26730099/64920700-23d6a000-d7ed-11e9-9507-52361a248f72.jpg)
![微信图片_20190915191140](https://user-images.githubusercontent.com/26730099/64920701-23d6a000-d7ed-11e9-8ea9-239fe943954a.jpg)

**Comment by syssi** [comment]
Perfect! Could you provide the output of `miiocli info`?

**Comment by xiaobai987292** [comment]
> Perfect! Could you provide the output of `miiocli info`?

hao to get this info ? 
i try this but 
```
$ miiocli info
Usage: miiocli [OPTIONS] COMMAND [ARGS]...
Try "miiocli --help" for help.

Error: No such command "info".
```

**Comment by syssi** [comment]
Thanks! `chuangmi.plug.v3` is the model I was looking for.

**Comment by rezmus** [comment]
use "power" property get get current load for this plug (i know it's inconsistent naming with other plugs which have "load_power").

**Comment by syssi** [comment]
Could you provide the output of:

```
miiocli device --ip 192.168.31.105 --token cda62ad33e0f047db... raw_command get_power '[]'
```

**Comment by Meeeeow** [comment]
@syssi Call device with this command will got:
```
miiocli device --ip 192.168.3.117 --token ...... raw_command get_power "[]"
Running command raw_command
[8900]
```

**Comment by syssi** [comment]
Thanks! The v3 is properly supported. The model must be passed to the constructor. The get_power call is used afterwards.
