### ISSUE TITLE
Support for new vaccum Xiaomi Mijia STYJ02YM 

### ISSUE THREAD

**Issue by kwetnico** [rytilahti/python-miio#550]
Hello,

It's possible to add the new vaccum xaomi.
This model : https://fr.gearbest.com/vacuum-cleaners/pp_009487950353.html

Thanks

**Comment by ABRT29** [comment]
hi, please mee too

**Comment by ABRT29** [comment]
Model number : STYJ02YM
![Capture d’écran 2019-10-01 à 09 17 11](https://user-images.githubusercontent.com/16398440/65941900-6bd00680-e42c-11e9-8eec-2a2a96091b2d.png)

with mi home 5.4.54 : 

{"did":"27XXX6986","token":"72676b4a764bXXXXXXXXXXXXXX5363","longitude":"XXX","latitude":"XXX","**name":"Mi Robot Vacuum-Mop P"**,"pid":"0","localip":"192.168.0.35","mac":"XX:XX:XX:XX:XX:XX","ssid":"XX","bssid":"XX:XX:XX:XX:XX:XX","parent_id":"","parent_model":"","show_mode":1,"**model":"viomi.vacuum.v7",**"adminFlag":1,"shareFlag":0,"permitLevel":16,"isOnline":true,"desc":"Appareil en ligne ","extra":{"isSetPincode":0,"fw_version":"3.5.3_0042","needVerifyCode":0,"isPasswordEncrypt":0}

**Comment by alex7614** [comment]
Hi
Please too

**Comment by HydrelioxGitHub** [comment]
I have this vacuum too. Is there anything we can do for help ?

**Comment by NSDmitry** [comment]
Hi, please too

**Comment by ABRT29** [comment]
have you any news ?

**Comment by edubox** [comment]
> Model number : STYJ02YM
> ![Capture d’écran 2019-10-01 à 09 17 11](https://user-images.githubusercontent.com/16398440/65941900-6bd00680-e42c-11e9-8eec-2a2a96091b2d.png)
> 
> with mi home 5.4.54 :
> 
> {"did":"27XXX6986","token":"72676b4a764bXXXXXXXXXXXXXX5363","longitude":"XXX","latitude":"XXX","**name":"Mi Robot Vacuum-Mop P"**,"pid":"0","localip":"192.168.0.35","mac":"XX:XX:XX:XX:XX:XX","ssid":"XX","bssid":"XX:XX:XX:XX:XX:XX","parent_id":"","parent_model":"","show_mode":1,"**model":"viomi.vacuum.v7",**"adminFlag":1,"shareFlag":0,"permitLevel":16,"isOnline":true,"desc":"Appareil en ligne ","extra":{"isSetPincode":0,"fw_version":"3.5.3_0042","needVerifyCode":0,"isPasswordEncrypt":0}

Where did you get this info? I can't find mine in /Smarthome/log files

**Comment by ABRT29** [comment]
> > Numéro de modèle: STYJ02YM
> > ![Capture d'écran 2019-10-01 à 09 17 11](https://user-images.githubusercontent.com/16398440/65941900-6bd00680-e42c-11e9-8eec-2a2a96091b2d.png)
> > avec mon domicile 5.4.54:
> > {"did": "27XXX6986", "jeton": "72676b4a764bXXXXXXXXXXXXXX5363", "longitude": "XXX", "latitude": "XXX", " **nom": "Mi Robot Vacuum-Mop P"** , "pid": "0", "localip": "192.168.0.35", "mac": "XX: XX: XX: XX: XX", "ssid": "XX", "bssid": "XX: XX: XX : XX: XX: XX "," parent_id ":" "," parent_model ":" "," show_mode ": 1," **modèle ":" viomi.vacuum.v7 ",** " adminFlag ": 1," shareFlag ": 0, "permitLevel": 16, "isOnline": true, "desc": "Appareil en ligne", "extra": {"isSetPincode": 0, "fw_version": "3.5.3_0042 "," needVerifyCode ": 0," isPasswordEncrypt ": 0}
> 
> Où avez-vous obtenu cette information? Je ne trouve pas le mien dans / Smarthome / log files

I got the information from smarthome / logs with version 5.4.54 of the Mi home application (Xiaomi home)

**Comment by rezmus** [comment]
my best guess is that local api is disabled after provisioning, because in the plugin all requests are forced to send via cloud when usually mi home decides whenever use local or cloud.

**Comment by edubox** [comment]
> > > Numéro de modèle: STYJ02YM
> > > ![Capture d'écran 2019-10-01 à 09 17 11](https://user-images.githubusercontent.com/16398440/65941900-6bd00680-e42c-11e9-8eec-2a2a96091b2d.png)
> > > avec mon domicile 5.4.54:
> > > {"did": "27XXX6986", "jeton": "72676b4a764bXXXXXXXXXXXXXX5363", "longitude": "XXX", "latitude": "XXX", " **nom": "Mi Robot Vacuum-Mop P"** , "pid": "0", "localip": "192.168.0.35", "mac": "XX: XX: XX: XX: XX", "ssid": "XX", "bssid": "XX: XX: XX : XX: XX: XX "," parent_id ":" "," parent_model ":" "," show_mode ": 1," **modèle ":" viomi.vacuum.v7 ",** " adminFlag ": 1," shareFlag ": 0, "permitLevel": 16, "isOnline": true, "desc": "Appareil en ligne", "extra": {"isSetPincode": 0, "fw_version": "3.5.3_0042 "," needVerifyCode ": 0," isPasswordEncrypt ": 0}
> > 
> > 
> > Où avez-vous obtenu cette information? Je ne trouve pas le mien dans / Smarthome / log files
> 
> I got the information from smarthome / logs with version 5.4.54 of the Mi home application (Xiaomi home)

Thanks! Got it now! :)

**Comment by edubox** [comment]
> my best guess is that local api is disabled after provisioning, because in the plugin all requests are forced to send via cloud when usually mi home decides whenever use local or cloud.

The problem is that this robot is manufactured by Viomi, not Roborock like other models, I think that the way of use it is not the same and maybe will be impossible to support it (at least not in the same way)

**Comment by rezmus** [comment]
vedor is not important, because all miio devices use same way to communicate, they just use different methods/props. problem here is that local udp 54321 looks disabled after provisioning, so only cloud rpc is used (normally it is only used when device is in different network).

**Comment by ABRT29** [comment]
I am not an expert in this area but what you are saying is that it will be impossible to integrate it into Home-Assistant?

**Comment by rezmus** [comment]
seems not possible with local api.

**Comment by nqkdev** [comment]
I did a quick test with this:

`miio protocol call 192.168.1.105 get_prop '["run_state","mode","err_state","battary_life","box_type","mop_type","s_time","s_area","suction_grade","water_grade","remember_map","has_map","is_mop","has_newmap"]'`

and got a response so local api is possible 👍 

```
[
  5,
  0,
  2103,
  85,
  3,
  1,
  0,
  0,
  1,
  11,
  1,
  1,
  1,
  0
]
```

**Comment by rezmus** [comment]
good news! i wonder why all ppl before had problems using local api. maybe it's related to firmware version?

**Comment by nqkdev** [comment]
I think the api has changed. I don't have the other vacuum so can't tell the difference. Also, Mi home does not connect directly to the local api but it sends rpc commands to the cloud so, without internet, the robot is useless :p

**Comment by ABRT29** [comment]
it does not work like the other models? I would like to drive it from Home-Assistant even if my internet connection is broken

**Comment by kwetnico** [comment]
> ça ne marche pas comme les autres modèles? Je voudrais le conduire à partir de Home-Assistant même si ma connexion Internet est interrompue

Me too

**Comment by jevd** [comment]
Hello,
Same for me, I can't use miiocli or mirobo to manage my Xiaomi STYJ02YM.

When not registered on miHome:
 mirobo discover --handshake 1
sends me the IP (192.168.5.1) and token.

When registered on miHome, vacuum is still detected, but seems not supported:
```
mirobo discover
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
WARNING:miio.discovery:Found unsupported device viomi-vacuum-v7_miio308780740._miio._udp.local. at 192.168.0.16, please report to developers
```

I scanned UDP ports with nmap (vacuum registered on miHome), opened ports are:
53, 67, 5353, 54321

But commands ends with time out.
```
miiocli vacuum --ip 192.168.0.16 --token xxx status
Running command status
ERROR:miio.device:Got error when receiving: timed out

mirobo --ip 192.168.0.16 --token xxx info
ERROR:miio.device:Got error when receiving: timed out
```

I would be happy to help for investigation. :-)

**Comment by rytilahti** [comment]
@jevd 
> When registered on miHome, vacuum is still detected, but seems not supported:

You are using `--handshake 1` in your first example and omitting it for the second. Will it respond with `--handshake 1` after being provisioned?

Also, are you able to request the properties as mentioned by @nqkdev?

Anyway, after the device is provisioned, it's token gets changed and that's why you are getting timed outs.

@nqkdev am I interpreting you correctly, that you were able to request these properties using some firmware version, but that it's blocked in some other? If those properties work in "local mode", it would be fairly simple to add a preliminary implementation for this.

**Comment by jevd** [comment]
@rytilahti ,
After registration on miHome, i use an old version 5.4.54 to get the token and test the other commands.  So i suppose it's ok...

When registered on miHome, the handshake command result is
```
mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 192.168.0.16 (ID: 12679ec4) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.device:Discovery done
```

i don't know which version of miio is used by @nqkdev , but i don't have that command available in my mirobo (version 0.4.7).

All the commands i send to the vacuum ends in time out.

```
miiocli vacuum --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXX status
Running command status

ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```

```
miiocli -d device --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX info
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x12g\x9e\xc4]\xc9\xe0l' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x12g\x9e\xc4' (total 4)
            ts = 2019-11-11 22:27:56
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered 12679ec4 with ts: 2019-11-11 22:27:56, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:192.168.0.16:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:192.168.0.16:54321 (ts: 2019-11-11 22:27:56, id: 1) << {'partner_id': '', 'id': 1, 'code': 0, 'message': 'ok', 'result': {'hw_ver': 'Linux', 'fw_ver': '3.5.3_0044', 'ap': {'ssid': 'XXXXX', 'bssid': 'XXXXXXX'}, 'netif': {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}, 'model': 'viomi.vacuum.v7', 'mac': '5C:E5:0C:XX:XX:XX', 'token': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'life': 258083}}
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0044
Network: {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}
AP: {'ssid': 'XXXXXX', 'bssid': 'XXXXXXX'}
```
please find the result of status command with debug enabled in attachment.

[status command.txt](https://github.com/rytilahti/python-miio/files/3833489/status.command.txt)

**Comment by jevd** [comment]
@rytilahti ,
After registration on miHome, i use an old version 5.4.54 to get the token and test the other commands. So i suppose it's ok...

When registered on miHome, the handshake command result is

```
mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 192.168.0.16 (ID: xxxxxx) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.device:Discovery done
```
i don't know which version of miio is used by @nqkdev , but i don't have that command available in my mirobo (version 0.4.7).

All the commands i send to the vacuum ends in time out.

```
miiocli vacuum --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXX status
Running command status

ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```
```
miiocli -d device --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX info
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\xxxxxxxxx\xe0l' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'xxxxx' (total 4)
            ts = 2019-11-11 22:27:56
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered xxxxxx
[status command.txt](https://github.com/rytilahti/python-miio/files/3833511/status.command.txt)
 with ts: 2019-11-11 22:27:56, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:192.168.0.16:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:192.168.0.16:54321 (ts: 2019-11-11 22:27:56, id: 1) << {'partner_id': '', 'id': 1, 'code': 0, 'message': 'ok', 'result': {'hw_ver': 'Linux', 'fw_ver': '3.5.3_0044', 'ap': {'ssid': 'XXXXX', 'bssid': 'XXXXXXX'}, 'netif': {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}, 'model': 'viomi.vacuum.v7', 'mac': '5C:E5:0C:XX:XX:XX', 'token': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'life': 258083}}
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0044
Network: {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}
AP: {'ssid': 'XXXXXX', 'bssid': 'XXXXXXX'}
```
please find the result of status command with debug enabled in attachment.

[status command.txt](https://github.com/rytilahti/python-miio/files/3833518/status.command.txt)

**Comment by nqkdev** [comment]
@rytilahti I am using the latest firmware (3.5.3_0044). I don't think the local api is blocked in any version. Only the methods and params are different. I was able to figure out a few rpc commands for this. 

Just did a quick hack so that it works with my home-assistant. [Check it out here](https://github.com/nqkdev/home-assistant-vacuum-styj02ym)

**Comment by jevd** [comment]
@rytilahti ,
After registration on miHome, i use an old version 5.4.54 to get the token and test the other commands. So i suppose it's ok...

When registered on miHome, the handshake command result is

```
mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 192.168.0.16 (ID: xxxxxx) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.device:Discovery done

```

i don't know which version of miio is used by @nqkdev , but i don't have that command available ("miio protocol call") in my mirobo version 0.4.7).

All the commands i send to the vacuum ends in time out.

```
miiocli vacuum --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXX status
Running command status

ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```

```
miiocli -d device --ip 192.168.0.16 --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX info
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\xxxxxxxxx\xe0l' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'xxxxx' (total 4)
            ts = 2019-11-11 22:27:56
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.device:Discovered xxxxxx
 with ts: 2019-11-11 22:27:56, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:192.168.0.16:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.device:192.168.0.16:54321 (ts: 2019-11-11 22:27:56, id: 1) << {'partner_id': '', 'id': 1, 'code': 0, 'message': 'ok', 'result': {'hw_ver': 'Linux', 'fw_ver': '3.5.3_0044', 'ap': {'ssid': 'XXXXX', 'bssid': 'XXXXXXX'}, 'netif': {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}, 'model': 'viomi.vacuum.v7', 'mac': '5C:E5:0C:XX:XX:XX', 'token': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'life': 258083}}
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0044
Network: {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}
AP: {'ssid': 'XXXXXX', 'bssid': 'XXXXXXX'}

```
please find the result of status command with debug enabled in attachment.

[status command.txt](https://github.com/rytilahti/python-miio/files/3833525/status.command.txt)
 sorry for deleting previous post, but i forgot to remove sensitive info.

**Comment by rytilahti** [comment]
I just created a PR based on the work done by @nqkdev, thanks a lot! :tada:  

Please feel to test the linked PR and report your findings:
```
$ miiocli viomivacuum
Usage: miiocli viomivacuum [OPTIONS] COMMAND [ARGS]...

Options:
  --ip TEXT     [required]
  --token TEXT  [required]
  --help        Show this message and exit.

Commands:
  home           Return to home.
  info           Get miIO protocol information from the device.
  pause          Pause cleaning.
  raw_command    Send a raw command to the device.
  set_fan_speed  Set fanspeed [silent, standard, medium, turbo].
  start          Start cleaning.
  status         Retrieve properties.
  stop           Stop cleaning.

```

**Comment by rytilahti** [comment]
@jevd thanks for your input, too! Just a side note; `miio` command is from https://github.com/aholstenson/miio .

The respective command for python-miio is `miiocli raw_command`, which can be used to test commands for devices that are not yet supported. So in this case, 
`miiocli --ip <address> --token <token> raw_command '["run_state","mode","err_state","battary_life","box_type","mop_type","s_time","s_area","suction_grade","water_grade","remember_map","has_map","is_mop","has_newmap"]'`should return similar output as @nqkdev gave us.

**Comment by rezmus** [comment]
similar should work for viomi.vacuum.v6 (V-RVCLM21B).

3rd param of set_mode_withroom is room_array_len and next are room ids ([0, 1, 3, 11, 12, 13] = start cleaning rooms 11-13). room ids are encoded in map and it's part of cloud api so best way to get it is log between device <> mi home app (before map format is supported).

some undocumented methods

set_language [1/2] - voice pack (1 - CN, 2 - EN)
set_carpetturbo [0/1/2] - carpet detection with suction level used on carpets (0 - off, 1 - medium suction, 2 - turbo suction)

there is also multimap support, not yet supported by mi home plugin UI.

list of all methods/params (don't test them if you don't know what you are doing).

get_prop
set_mode
set_pointclean
set_wall
set_zone
set_charge
set_ischarge
set_direction
set_suction
set_repeat
set_broken
set_light
set_voice
set_language
set_ordertime
del_ordertime
get_ordertime
set_notdisturb
get_notdisturb
set_carpetturbo
set_remember
set_calibration
get_curpos
set_resetpos
set_resetmap
set_uploadmap
get_consumables
set_consumables
map_plan
add_map
set_mode_withroom
reset_factory
arrange_room
rename_room
set_mop
set_newmap
set_cardoper
set_iswork
set_timezoneorder
set_auto

hw_info
sw_info
run_state
suction_grade
mode
err_state
battary_life
start_time
order_time
s_time
s_area
v_state
zone_data
repeat_state
remember_map
has_map
water_grade
box_type
mop_type
is_mop
light_state
has_newmap
is_charge
is_work

**Comment by boscorelly** [comment]
Thanks, I will try :)

**Comment by jevd** [comment]
Hello, thank you for this update :-)
it seems that i have issue to get it working - but it's probably a configuration issue.
Setup:
```
Ubuntu 18.04 
sudo apt-get install libffi-dev libssl-dev
sudo apt-get install  python3-pip python3-venv python3-dev
python3 -m venv .venv

. .venv/bin/activate
pip3 install -U setuptools
pip3 install asyncio
pip3 install https://github.com/rytilahti/python-miio/archive/viomi.zip
```
version:
pip3 freeze
```
appdirs==1.4.3
attrs==19.3.0
cffi==1.13.2
Click==7.0
construct==2.9.45
cryptography==2.8
ifaddr==0.1.6
netifaces==0.10.9
pkg-resources==0.0.0
pycparser==2.19
python-miio==0.4.7
pytz==2019.3
six==1.13.0
tqdm==4.38.0
zeroconf==0.23.0
```
I can't get any info from the vacuum when it's registered on miHome.
If i unregister it from miHome, it works ! :-) First step OK.

I can run "status", but not "info" command

(.venv) user@server:~$ miiocli viomivacuum --ip 192.168.5.1 --token xxxxxxxxxxxxxxxxxxxxx status
```
State: ViomiVacuumState.Docked
Mode: 0
Error: None
Battery: 100
Fan speed: ViomiVacuumSpeed.Medium
Box type: 3
Mop type: 1
Clean time: 0:00:00
Clean area: 0
Water level: 12
Remember map: True
Has map: True
Has new map: False
Is mop: True
```

(.venv) user@server:~$ miiocli viomivacuum --ip 192.168.5.1 --token xxxxxxxxxx info
```
ERROR:miio.protocol:unable to parse json '': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/jvn/.venv/bin/miiocli", line 11, in <module>
    load_entry_point('python-miio==0.4.7', 'console_scripts', 'miiocli')()
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/device.py", line 352, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/home/jvn/.venv/lib/python3.6/site-packages/miio/device.py", line 278, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
```

i didn't tried the other commands.

**Comment by jevd** [comment]
Thank you very much @rytilahti !!
Finally it's working even when registered on miHome :-)

miiocli viomivacuum --ip 192.168.0.16 --token xxx  info
```
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0044
Network: {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}
AP: {'ssid': 'xxx', 'bssid': 'xxx'}
```

mirobo --ip 192.168.0.16 --token xxxxx raw-command miIO.info
```
Sending cmd miIO.info with params []
{'hw_ver': 'Linux', 'fw_ver': '3.5.3_0044', 'ap': {'ssid': 'xxxx', 'bssid': 'xxx'}, 'netif': {'localIp': '192.168.0.16', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}, 'model': 'viomi.vacuum.v7', 'mac': '5C:E5:xx:xx:xx:xx', 'token': 'xxxxxx', 'life': 770937}
```

**Comment by rumpeltux** [comment]
I also tried a bit:
* Discovery and getting tokens works fine after device reset.
* The app changes the token during provisioning, using Mi Home v5.4.56, I am able to see the new token in some cache files (in /data/data/com.xiaomi.smarthome/cache/smrc4-cache): `adb shell "grep -R '\"token\"' /data/data/com.xiaomi.smarthome"`
* Local API access works after provisioning with the token recovered above
* Local access stops working within a few minutes. Not sure if it’s getting disabled or there’s another token-change performed.

**Comment by rumpeltux** [comment]
> * Local access stops working within a few minutes. Not sure if it’s getting disabled or there’s another token-change performed.

Actually it continues to work, but since rerunning the tool doesn’t keep track of the last sequence-id, it needs more retries / higher ids. As a quick fix, I increased `retry_count=3` to `20` in `device.py` and set `timeout = 0.5` and now it seems to be working reliably.

**Comment by rumpeltux** [comment]
@rezmus Out of curiosity: how did you acquire the list of supported commands?

**Comment by rezmus** [comment]
from robot binaries.

**Comment by rumpeltux** [comment]
A look at current binaries (3.5.3_0045) reveals a couple of more commands not previously mentioned in https://github.com/rytilahti/python-miio/issues/550#issuecomment-552780952:
```
+miIO.ota
+miIO.get_ota_state
+miIO.get_ota_progress
+deal_map
+set_map
+del_map
+get_map
+rename_map
+upload_map
+set_moproute
```

In particular it looks like the device may have multimap support.

Similarly there are params for get_prop:
```
+cur_mapid
+mop_route
+water_percent
+map_num
+side_brush_life
+side_brush_hours
+main_brush_life
+main_brush_hours
+hypa_life
+hypa_hours
+mop_life
+mop_hours
```

For the map editor:
Sample command to divide a room:
    `{'method': 'arrange_room', 'params': {'lang': 'de', 'mapID': 1577912345, 'pointArr': [[1, '3.8_0', '5.4_2.35']], 'roomID': 11, 'type': 1}}`

Sample command to rename a room:
    `{'method': 'rename_room', 'params': [1577912345, 1, 11, 'Living Room']}`

**Comment by ABRT29** [comment]
how to use it from home-assistant?

**Comment by silentkiller88** [comment]
> r ids. As a quick fix, I

Thanks for this! I was struggeling to get it working but this did the trick. I don't understand why it works after multiple tries and why this is STYJ02YM specific.
Is there the ability to fix this in a future version?

**Comment by rytilahti** [comment]
Yes, this should be fixed in miiocli, currently only mirobo has it implemented (in a very hacky way): https://github.com/rytilahti/python-miio/blob/master/miio/vacuum_cli.py#L58 Feel free to open a new issue for that.
