### ISSUE TITLE
Support for Xiaomi Mijia PETKIT Smart Cat Feeder

### ISSUE THREAD

**Issue by alexmorbo** [rytilahti/python-miio#552]
Hello!

Is it possible to add this device?
https://www.aliexpress.com/item/33038533651.html

**Comment by syssi** [comment]
If somebody owns this device we could try to implement it.

**Comment by alexmorbo** [comment]
i have

**Comment by syssi** [comment]
@alexmorbo Do you own a rooted android device? I need the MiHome plugin of your device. It's an APK file which can be downloaded if you have access to your device.

**Comment by alexmorbo** [comment]
This device controlled not by MiHome
Thats PetKit application for that https://play.google.com/store/apps/details?id=com.petkit.abroad&hl=en

**Comment by syssi** [comment]
Alright. I will try to disassemble this app.

**Comment by syssi** [comment]
Are you able to sniff some network traffic between the device and your accesspoint / at the accesspoint? Is your smartphone app able to connect the device directly or is all communication established over a cloud. How does the traffic look like? udp/tcp, plaintext/encrypted?

**Comment by syssi** [comment]
It looks like the device doesn't use the miIO protocol I can find cloud communication only. Sorry!

**Comment by thundergreen** [comment]
hey @syssi I also own this Petkit feeder and would like seeing this connected to my home assistant. Possible to use the cloud communication then instead of locally? would be awesome .) @alexmorbo  did u find a way somehow to integrate this in home assistant ?

**Comment by rytilahti** [comment]
The cloud connectivity is out of scope for this library, and considering that the device is not a miio device, I'm not sure there's anything we can do here, sorry :(

**Comment by arren-ru** [comment]
I own this device too and only possible variants I can see is:
- replace all electronics by custom own with zigbee/wifi (simply just install some basic ESP)
- emulate cloud server (possible but complicated)

I personally do prefer first one and possibly would like to implement it in near future

**Comment by alexmorbo** [comment]
> I own this device too and only possible variants I can see is:
> 
> - replace all electronics by custom own with zigbee/wifi (simply just install some basic ESP)
> 
> - emulate cloud server (possible but complicated)
> 
> 
> 
> I personally do prefer first one and possibly would like to implement it in near future.
> 
> I also have water dispenser and it is pain in ass to spot when blue indicator shows water shortage, so it also needs to be upgraded to WiFi-capable device.
> 
> 

Отпишись, если будет готовый мануал по апгрейду :)
