### ISSUE TITLE
Missing states and error_codes

### ISSUE THREAD

**Issue by SelmaUrban** [rytilahti/python-miio#57]
Hi,
your states and error_codes are incomplete.
Here are some state additions (Merge with Fhem-stats):
> 1: 'Starting up',
> 2: 'Sleeping',
> 3: 'Waiting',
> 4: 'Remote control',
> 5: 'Cleaning',
> 6: 'Returning home',
> 7: 'Manual mode',
> 8: 'Charging',
> 9: 'Charging problem',
> 10: 'Paused',
> 11: 'Spot cleaning',
> 12: 'Error',
> 13: 'Shutting down',
> 14: 'Updating',
> 15: 'Docking',

With new firmware the error_codes-count > 19 (~24)
Please have a look: http://www.robotreviews.com/chat/viewtopic.php?f=6&t=19479&start=60#p140165

Translation 1-19 from Fhem:

> '1' => "Laser sensor fault",
> '2' => "Collision sensor fault",
> '3' => "Wheel floating",
> '4' => "Cliff sensor fault",
> '5' => "Main brush blocked",
> '6' => "Side brush blocked",
> '7' => "Wheel blocked",
> '8' => "Device stuck",
> '9' => "Dust bin missing",
> '10' => "Filter blocked",
> '11' => "Magnetic field detected",
> '12' => "Low battery",
> '13' => "Charging problem",
> '14' => "Battery failure",
> '15' => "Wall sensor fault",
> '16' => "Uneven surface",
> '17' => "Side brush failure",
> '18' => "Suction fan failure",
> '19' => "Unpowered charging station",

(Some are more clearly described)

---

Thx for your cool script! I use it along with alexa + ha-bridge and kivy on a pi display.

**Comment by rytilahti** [comment]
Thanks for your report and you are welcome. The error codes I'm using are from the official documentation (vacuum_cleaner-EN.pdf), and from the looks of it there exists only 19 of them (the enumeration in that link is not just about the error codes but other error situations too). Have you seen more of them in practice?

Thansk for the list of states, a couple of those were still missing and I will add them at some point.

**Comment by SelmaUrban** [comment]
The PDF is outdated / written before firmware 3.3.9.xxx. I have only read about them (20-24).
No error jet on my robot :)

**Comment by rytilahti** [comment]
Ah, that may indeed be the case, I just overlooked and was misled as the format in that list was not the same as for earlier (they are not explicitly talking about error codes).

**Comment by SelmaUrban** [comment]
Is it possible to have a "def status_raw..." that gives the numbers only (with true/false for dnd, is_leaning,..)? 
My pi kivy touchscreen needs it's on textstrings, button on/off info

**Comment by rytilahti** [comment]
There are `state_code` and `error_code` in `VacuumStatus` which return the raw numbers, is that enough for your usecase? The raw data itself is also available through the `data` property of that object (if you want to read `dnd_enabled`, which is the only one besides `msg_ver` which is not exposed. I did not do that as its value was not during my tests the same as the one reported by `dnd` call, but it may have been a glitch..

**Comment by SelmaUrban** [comment]
I will test it. Thx

**Comment by SelmaUrban** [comment]
You're right `state_code` and `error_code` is what i searched for! And `dnd` and `in_cleaning` do not work.
But instead of `in_cleaning` i can ask for `state_code = 5 || 11`

**Comment by rytilahti** [comment]
Nice to hear you got it working. Indeed, there's `is_on` already which checks for the code 5, maybe it should be extended to cover also the spot cleaning and manual mode. For DND it will get updated to the status reports at some point, but the logic itself is not clear to me. There is a separate `dnd` command for getting a more precise dnd information.

**Comment by rytilahti** [comment]
My earlier comment fixes this and makes `state` and `error` not to crash if a definition is missing. Thanks!
