### ISSUE TITLE
Roborock S50 not responding to handshake anymore

### ISSUE THREAD

**Issue by ronenb75** [rytilahti/python-miio#572]
I've been able to root my Roborock S5 few weeks ago, with the usual `mirobo --debug discover --handshake true` followed by `mirobo --ip 192.168.0.xx --token xxx update-firmware /root/rockrobo/output/v11_001886.fullos.pkg`

Last night, after a clean, I couldn't connect to the Valetudo http anymore nor to ssh.
The only way I could communicate with it was Xiaomi Mi Home app, which suggest somehow they managed to flash my rooted rom, even though I checked the firewall and the XI servers were blocked, or the robot reset to default ROM.

I tried to root it again, all the way to hard reset, connecting directly to the S5 wifi and try to get the token, but discovery shows nothing.
I tried sending UDP HEX `21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff` to 192.168.8.1 port 54321 and didn't get any respond.

Is it possible they managed to change the listening port and the hello packet?
Am I missing anything?

**Comment by rezmus** [comment]
not possible, because it's part of mi home setup cloud process for all wifi devices. can you still connect to mi home? what's the current firmware version?

**Comment by ronenb75** [comment]
Sorry, I'm dumb....

Turn out it was my machine for some weird reason.
I tried from another machine, running linux, and it was all good.

Re-flashed the root ROM and all back to normal.
