### ISSUE TITLE
Support for chuangmi.plug.hmi206

### ISSUE THREAD

**Issue by nikitafedorovv** [rytilahti/python-miio#574]

**Comment by rytilahti** [comment]
Is it not already supported? https://github.com/rytilahti/python-miio/blob/master/miio/chuangmi_plug.py#L19 seems to indicate it would be.

**Comment by nikitafedorovv** [comment]
Oh, thanks. I am just acting according to Home Assistant logs, which are as follows:

2019-11-11 02:14:21 ERROR (MainThread) [homeassistant.components.xiaomi_miio.switch] Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: chuangmi.plug.hmi206

I am trying to setup my first home assistance device, so it can be anything. I will re-check configs now and then update status 👍

**Comment by rytilahti** [comment]
Oh, no worries! I took a look at it and looks like it requires a fix at homeassistant's end, the list here does not have `hmi206`: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/xiaomi_miio/switch.py#L41 . I just created a PR to get it added to the next homeassistant release.

**Comment by nikitafedorovv** [comment]
Thank you! Maybe there is some workaround in your mind to make it work while update is not released?

**Comment by rytilahti** [comment]
You could modify the file modified by that PR by hand, unfortunately there's no other workaround for it.

**Comment by nikitafedorovv** [comment]
Thank you!

In case anybody is wondering, in your configuration yaml file you can explicitly specify a model as chuangmi.plug.hmi205 to make hmi206 switch work. It seems to be a good workaround till home assistant update is yet to come.

So your config for hmi206 model will look like this:

switch:
  ...
  host: ...
  ...
  model: 'chuangmi.plug.hmi205'

**Comment by syssi** [comment]
This is the recommended workaround if the device is ~100% compatible to another model! :-)

**Comment by nikitafedorovv** [comment]
Yeah, it turned out this is the case.

**Comment by vedranius** [comment]
Has this been added to latest home assistant?
I've tried adding it manually to configuration.yaml but I only get this:
![image](https://user-images.githubusercontent.com/17914869/95457234-dafe0600-0970-11eb-93be-247a9638d52e.png)

Any help?
