### ISSUE TITLE
Is Air Purifier Pro v6 not supported by Xiaomi anymore?

### ISSUE THREAD

**Issue by yawor** [rytilahti/python-miio#580]
I've been wondering if anyone has been experiencing the same situation as me. My Air Purifier Pro (v6) recently stopped responding to python-miio requests. To get it back to work I've had to unplug the power cable, wait a moment and connect it back. After that it was possible to communicate with the purifier for some time (don't know how long - 10, maybe 15 minutes tops) and the situation repeated itself. No response to python-miio requests. The device itself is about 2 meters from the AP and it worked properly at least few weeks ago (no changes to the network during this time).

I've decided to check the device status in Xiaomi Home, where I've found that the device disappeared from my profile (logging out and back in doesn't help, I've also tried changing locations, but it worked with Honk Kong before). So I've tried resetting the device and adding it again to the app, but now it's not being found anymore. If I select the Mi Air Purifier Pro manually in the app, after first scan timeout the app allows to connect manually, but it is looking for zhimi-airpurifier-v7_miapxxxx SSID, where v6 obviously uses v6 in its SSID.

So unless I'm missing something, it seems like Xiaomi has dropped support for v6. Maybe the network issues before device reset were also related to that fact (maybe the network code in the firmware has a bug where it stops working correctly if the device can't connect to the servers properly?)

Has anyone have any suggestions what should I try?

**Comment by yawor** [comment]
I've decided to disassemble the device to check how everything is connected. My plan is to throw out the Marvell MCU and replace it with ESP32 running ESPHome firmware.
What's nice is that all pins in connectors on the main PCB for all the other components are labelled, so it's going to be much less work than I expected (no need to trace all the signals).
I'm thinking about reusing the PCB by desoldering the Marvell module and then solder wires to the solder pads and connect them to ESP32.
From what I've found out, the display is mostly standard SPI OLED display. The 3-color ring around the OLED screen uses 3 PWM channels to separately control channels of RGB (or maybe red-green-orange according to labels?) LEDs. Each motor is controlled separately with its own PWM signal (they report back the current speed as a PWM). The humidity sensor and NFC reader use I2C bus (maybe they can use the same bus, to be seen) and the air quality sensor uses UART interface. It's mostly a matter of finding correct datasheets as everything looks to be a standard hardware. It's possible that there are even ready for use libraries for everything.

**Comment by rezmus** [comment]
HK = sg api server, you have cn version (v6). if you are using original app you must be on mainland china region, otherwise mi home won't find it.

**Comment by rytilahti** [comment]
Could it be that they are slowly phasing out the support for the old API (although it's accessible for some time at first due to some initialization routines)? This could be related to https://github.com/rytilahti/python-miio/issues/543 .
