### ISSUE TITLE
Pi3 b python error

### ISSUE THREAD

**Issue by dajojonl** [rytilahti/python-miio#588]
Installed python (3.4.2) on pi3 b (octopi build) and installed miio but when i run mirobo it says required python 3.5 
So i uninstalled miio and upgrade to python3.6.5 and then tried installing miio again , it complains it need python 3.4.2 to install .. what am i missing ?
![20191204_221514](https://user-images.githubusercontent.com/22854173/70182227-b4819580-16e3-11ea-9574-cdf99f01e231.jpg)

**Comment by rytilahti** [comment]
Looks like it's still using 3.4 according to the log. However, you should use virtualenv (and potentially specify to it which python version you want to use) to avoid installing packages system-wide :-)

**Comment by dajojonl** [comment]
Ah.. i see. Thank you.  probably it is locked to it . Pi3 is running octopi only so that is replacable with backup image, not worried about that. I'll have a look at this virtual environment,  any specifics for pi3 b debian or good tutorial you know about ?
I have new xiaomi styj02ym and i wanted to switch to english and try some of the commands that are mentioned. I'll take the chance to brick it np.

**Comment by rytilahti** [comment]
I think this is a pretty good write-up on virtual environments: https://realpython.com/python-virtual-environments-a-primer/ but in the simplest case you could simply do the following:
```
virtualenv -p python3 venv
source venv/bin/activate
pip install python-miio # or the git url for PR, see https://stackoverflow.com/questions/13561618/pip-how-to-install-a-git-pull-request/13561621#13561621
miiocli --help
```
