### ISSUE TITLE
Support for Roborock S6/T6

### ISSUE THREAD

**Issue by SamITSupport** [rytilahti/python-miio#593]
Hello! I have new Mi Roborock S6 vacuum cleaner. Is any plan to support it?
S6 firmware 3.5.4_850
I cant integrate it in Home Assistant

 $ mirobo --version
mirobo, version 0.4.7

$ mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 192.168.1.16 (ID: 0f9e81d0) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.device:Discovery done

$ mirobo --ip 192.168.1.16 --token 6d4bxxxxxxxxxxxxxxxxxxxxxxxxxxxx discover
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
WARNING:miio.discovery:Found unsupported device roborock-vacuum-s6_miio262046160._miio._udp.local. at 192.168.1.16, please report to developers

$ mirobo -d --ip 192.168.1.16 --token 6d4bxxxxxxxxxxxxxxxxxxxxxxxxxxxx discover --handshake 1
INFO:miio.vacuum_cli:Debug mode active
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x0f\x9e\x81\xd0]\xec\xf8t' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = b'\x0f\x9e\x81\xd0' (total 4)
            ts = 2019-12-08 13:19:48
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
INFO:miio.device:  IP 192.168.1.16 (ID: 0f9e81d0) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.device:Discovery done

 $ mirobo --ip 192.168.1.16 --token 6d4bxxxxxxxxxxxxxxxxxxxxxxxxxxxx status
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device

**Comment by andrasg** [comment]
I have a Roborock S6 and have no problem using `mirobo`. Out of the possible ways to extract the token, only the iOS backup extraction method worked for me. Other methods produced a token that was not working.

**Comment by rytilahti** [comment]
Sounds like an invalid token (thanks @andrasg for chiming in that it's generally working), please retry to obtain the token and reopen if this is still an issue.
