### ISSUE TITLE
Fully charged state not shown

### ISSUE THREAD

**Issue by andrasg** [rytilahti/python-miio#594]
When the battery is fully charged, the app changes from displaying "Charging" to "Fully charged".  The output of `mirobo status` though still says charging:

```
pi@raspberrypi:~ $ mirobo status
State: Charging
Battery: 100 %
Fanspeed: 101 %
Cleaning since: 0:00:43
Cleaned area: 0.8075 m²
```

How can I detect that the battery has been fully charged?

**Comment by rytilahti** [comment]
What's your use case? This information is what the vacuum itself is reporting and there is no extra magic in there, so checking for 100% would do the trick for detecting a fully charged vacuum.

**Comment by andrasg** [comment]
No real use case, I was just wondering when the `100: "Charging complete"` state would be active.
I am using that exact logic in nodered and rewriting status code to be 100 when `status == 8 and battery == 100`.

**Comment by rytilahti** [comment]
Ok, I'll close this then! That state was added in https://github.com/rytilahti/python-miio/pull/525. So, maybe it's available on some devices, I know that's not the case for my gen1 vacuum though.
