### ISSUE TITLE
Errors not shown for S6

### ISSUE THREAD

**Issue by andrasg** [rytilahti/python-miio#595]
My device keeps saying error 10 (clean filter) but the output doesn't show any errors:

```
pi@raspberrypi:~ $ mirobo raw-command get_status
Sending cmd get_status with params []
[{'msg_ver': 2, 'msg_seq': 4168, 'state': 5, 'battery': 92, 'clean_time': 1185, 'clean_area': 24657500, 'error_code': 0, 'map_present': 1, 'in_cleaning': 1, 'in_returning': 0, 'in_fresh_state': 0, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 102, 'dnd_enabled': 0, 'map_status': 3, 'lock_status': 0}]
```

Note `'error_code: 0'` in the output. I keep getting push notifications in the app about the error.

**Comment by rytilahti** [comment]
Maybe the vacuum is sending that information as an event instead of adjusting the state code, making it unfortunately impossible for us to detect this situation.

**Comment by andrasg** [comment]
No, there seems to be errors which are permanent (eg: cannot return home), these are setting the `error_code`. For recoverable errors, no error is reported. My question is rather how to retrieve info on the non-recoverable errors.

**Comment by rytilahti** [comment]
There is no easy way to do that, as such events are only send to the cloud server and are not broadcasted locally.

**Comment by andrasg** [comment]
That's a pity. Would have been nice to be able to integrate this information with home automation...

Thanks anyway, closing the issue.
