### ISSUE TITLE
Support new device (yeelink.light.lamp4)

### ISSUE THREAD

**Issue by anhnvme** [rytilahti/python-miio#598]
Hello,

I just bought Xiaomi Desklamp with code yeelink.light.lamp4
Can you add it to support ?

How can i send debug for u ? 
thanks

**Comment by syssi** [comment]
The command set of the device looks like a typical yeelight. If you've luck this library works out of the box: https://gitlab.com/stavros/python-yeelight

**Comment by mouth4war** [comment]
Hi can this be reopened. Yeelight component doesn’t support this since firmware upgrade issue.

**Comment by rytilahti** [comment]
If you are talking about the homeassistant component, it does not use this library for yeelight support. It may be possible to add that in the future though. But there is no need to reopen this issue, as the device should work just fine using this library, or if it doesn't please create a new issue with more details what is not working and maybe we can find a solution.
