### ISSUE TITLE
Xiaomi Xiao AI Smart Alarm Clock Time settings

### ISSUE THREAD

**Issue by ddv122** [rytilahti/python-miio#599]
Hi. Xiaomi Xiao AI Smart Alarm Clock 
Is it possible to add a time/zone setting?

**Comment by syssi** [comment]
What's the model name of this device?

**Comment by ddv122** [comment]
zimi-clock-myk01_mibtD166
AI01ZM
after updating the firmware to 3.5.7_0034 and untying them from mi home - it is impossible to set the time, time zones are not used from the phone (manually time zone +3 Moscow), always with time zone +8.

**Comment by syssi** [comment]
```
# Supported methods:

alarm_ops
get_config_version
get_count_down
get_count_down_v2
get_enabled_key_light
get_hourly_system
get_mibrain_env
get_near_wakeup_status
get_night_mode
get_ring
get_volume
set_hourly_system
set_mibrain_env
set_near_wakeup_status
set_night_mode
set_ring
set_volume
```

**Comment by syssi** [comment]
Could you provide the output of

```
miiocli device --ip IP --token TOKEN raw_command get_mibrain_env "[]"
```

**Comment by Koponyeges** [comment]
Command output: 

miiocli device --ip xxx.xxx.xxx.xxx --token xxxxxxxxxxxxxxxxxxxxxxx raw_command get_mibrain_env "[]"
Running command raw_command
['production']

**Comment by syssi** [comment]
It looks like it's not possible to set the timezone via the miIO api. :-(

**Comment by Koponyeges** [comment]
I'm sad.
Thank you for your help!

**Comment by ddv122** [comment]
mi home"POST http://api.m.mi.com/v1/apkversion/iosplugin HTTP/1.1" 304 0
mi home "POST http://api.m.mi.com/v1/apkversion/iosplugin HTTP/1.1" 304 0
mi home "GET http://tp.hd.mi.com/gettimestamp HTTP/1.1" 200 25
mi home"GET http://static.home.mi.…1513670484sxvayydp.jpg HTTP/1.1" 200 62407
AI01ZM "GET http://110.43.0.83/gslb? HTTP/1.1" 200 323
AI01ZM "POST http://account-dcm.ai.…pi/iotdcm/token/verify HTTP/1.1" 401 83

But this information will not help? The information about the time and date is taken not from the site -
Http://110.43.0.83/gslb?
