### ISSUE TITLE
Cannot configure device (Air Purifier V2) while in its network

### ISSUE THREAD

**Issue by dotlurker** [rytilahti/python-miio#601]
Hello. Probably creating a new issue isn't the best way to seek help here, but I got kind of lost in the documentation for setting up and discovering a new device.

I have an Air Purifier 2S which I can successfully discover while the "discoverer" is within the device's wifi network:
```
$ mirobo discover --handshake 1
INFO:miio.device:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.device:  IP 10.0.2.2 (ID: xxxxxxxx) - token: b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
INFO:miio.device:Discovery done
```
Since the device is in a different subnet (10.0.2.2, not within the router's 192.168.0.0/24 network) I am not sure what should be my next step to configure it and get it into my router's subnet. I've tried throwing different command from the `miiocli` at it but pretty much everything is failing with:
`Error: Unable to discover the device 10.0.2.2`.

Given that the documentation for the `miiocli` and setting up in general is sparse, I realise that I'm not doing the next step right. 

I would be glad to help write up some more getting started and setting up information (even go further into it once correctly set up and help with #400)

**Comment by syssi** [comment]
If I remeber correctly the device firmware doesn't support cross subnet communication.

**Comment by dotlurker** [comment]
And is there anything I can do to get the device into router's subnet?
Also, are `status` or `info` type of commands supposed to work if I'm in the same network as the device (in its network) and I have it's IP and Token? 
`miiocli airpurifier --ip 10.0.2.2 --token $TOKEN status`

**Comment by tiagofreire-pt** [comment]
> If I remeber correctly the device firmware doesn't support cross subnet communication.

Could you please confirm this?

Thanks.

**Comment by rytilahti** [comment]
Please check if this is related: https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets - if it is, it would be great if you could create a PR to update the documentation accordingly :-)

**Comment by tiagofreire-pt** [comment]
Could you confirm if using a NAT 1:1 translation between the HA network (192.168.10.0/24) to the Xiaomi IP (192.168.11.46) would work?

**Comment by tiagofreire-pt** [comment]
@dotlurker, the solution is here: https://github.com/home-assistant/core/issues/34305#issuecomment-614920127
