### ISSUE TITLE
Xiaomi Remote Learning & Sending Commands for AC

### ISSUE THREAD

**Issue by ekorsanov01** [rytilahti/python-miio#602]
Hello All,

I hope someone can point me in the right direction. I have configured my Xiaomi remote and is connecting to my HASS but I am having problems learning commands and sending commands.

Learning commands, I am using developer tools and call service ‘remote.xiaomi_miio_learn_command’ after that I point AC remote at device and then I get the code. It seems that everytime I use this command, even when I push the same button on the remote it returns a different raw code. For example turn AC off here is 3 examples of the code learnt;

`mczm8wlkxm02mEsmkyAIKZTUAgpmAQ4CJTSYgD+BTYDHgheAz4DKgZeBl4DPg3eAPAGXgdeAx4A/gD+AP4A/gD+AP4TOAL+AvgD/gD+AP4bHggeAP4A/gX2Iz4A9wAA=`

`mczm8wlkxm02mEsmkyAIKZTUAjppMQB/Ag8BjwQvAZ8DLwMvAZ8BnwIfAY8BjwGPAH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/DY8AfwB/AH8EDwB8gAA=`

`mczm8wlkxm02mEsmkzAIKZTQAjppMQB/Ag+YAMeCFE1AIKZAMsAOQKfgZeCp4IcBH+APAKiAQsAxAHUAY+AP4GHAouAPgF/gL+Bf4C/gL+Af4C/gL+AP4bHgD+Gh4A/ggeDz8AA=`

My other problem is when I try to send command to the IR remote nothing happens (but I am guessing this is because the raw code is incorrect). I have tried completing this in configuration.yaml and also scripts.yaml

Any help would be greatly appreciated.

configuration.yaml
XIAOMI MI REMOTE v2:
remote:

platform: xiaomi_miio
name: mi_remote
host: 192.168.1.136
token: -secret token-
commands:
command:
- raw:mc0mMwlkxm0ymEsmk3AIKZTAAjpnNgB/Ag8BjwQvAZ8DLwMvAZ8BnwIfAY8BjwGPAH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/DY8AfwB/FE8CHwB9gAA=
scripts.yaml
turn_off_ac:
sequence:
- service: remote.send_command
entity_id: remote.mi_remote
data:
command:
- raw:mc0mMwlkxm0ymEsmk3AIKZTAAjpnNgB/Ag8BjwQvAZ8DLwMvAZ8BnwIfAY8BjwGPAH8AfwB/AH8AfwB/AH8AfwB/AH8AfwB/DY8AfwB/FE8CHwB9gAA=

turn_on_ac:
sequence:
- service: remote.send_command
entity_id: remote.mi_remote
data:
command:
- raw:mczm8wlkxm02mEsmkyAIKZTUAjppMQB/Ag8BjwQvAZ8DLwMvAZ8BnwIfAY8BjwGPAH8AfwB/AH8AfwB/AH8AfwB/Co8AfwB/Aw8AfwB/FF8CHwB+gAA=

**Comment by pashok2398** [comment]
+1
Same here with AC, each learn different code.

**Comment by Forsakenrox** [comment]
and so ? no solution ?
