### ISSUE TITLE
BLE gateway

### ISSUE THREAD

**Issue by wiktorvip** [rytilahti/python-miio#610]
Some of Xiaomi devices (like humidifier) have ability to be bluetooth gateway for other devices. Is there any way to add support for that function?

**Comment by a1ien** [comment]
It seems that the gateway sends data only to the cloud. They are not transmitted over the local network.
To check, I turned off the Bluetooth and blocked the Internet on the phone. And the data did not come. Also, when blocking the Internet at the BLE gateway, we also do not receive data.
