### ISSUE TITLE
Xiaomi vacuum v1(003468):  "Unable to discover device" too often

### ISSUE THREAD

**Issue by avatar8000** [rytilahti/python-miio#611]
My vacuum is 003468 v1. I installed python-miio 0.4.5 to window
I've got too often below errors when use "mirobo --ip vacuum -- token vacuum token" 

ERROR:miio.device:Unable to discover a device at address 192.168.1.181
Error: Unable to discover the device 192.168.1.181

It will recoverd in several seconds. but it was really a trouble to me.
BTW, ssh works well when this issue happen, so i think vacuum is not overloaded.

Then, I installed wireshark to capture data frame from window, found there is no response from vacuum. 
my vacuum ip is 192.168.1.181

![image](https://user-images.githubusercontent.com/55876594/72200053-854b0a80-347f-11ea-8c4e-f74c118d5f51.png)

It seems vacuum cannot process miio request, anyone have a better way to make it stable and reliable. 

![image](https://user-images.githubusercontent.com/55876594/72200133-79ac1380-3480-11ea-90e0-232646be3dbc.png)

ssh works well with my vacuum

![image](https://user-images.githubusercontent.com/55876594/72200336-4f0f8a00-3483-11ea-942a-00f92f0b39fb.png)

**Comment by rytilahti** [comment]
Could this be relevant to you? https://python-miio.readthedocs.io/en/latest/troubleshooting.html#intermittent-connection-issues-timeouts-xiaomi-vacuum

**Comment by avatar8000** [comment]
Thanks @rytilahti , Is this the workaround you mentioned ?

change all drop to reject? 

root@rockrobo:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       udp  --  anywhere             anywhere             udp dpt:6665
DROP       tcp  --  anywhere             anywhere             tcp dpt:6665

**Comment by rytilahti** [comment]
@avatar8000 those are input rules on the vacuum and are not relevant for this problem. The problem with the vacuum is that when your router's firewall is blocking the requests by silently dropping them.

**Comment by avatar8000** [comment]
@rytilahti , tcpdump on vacuum shows it received dst port 54321 UDP request. But no response.
So, it seems a different issue with the link above?  Thanks for your help anyway.

**Comment by rytilahti** [comment]
You can check out `/mnt/data/rockrobo/rrlog/miio.log` if there's something helpful in there when that happens.
