### ISSUE TITLE
Can I copy the troubleshooting section to openhab readme

### ISSUE THREAD

**Issue by marcelrv** [rytilahti/python-miio#612]
Hi @rytilahti 

Do you mind if I copy the troubleshooting section to the readme of the miio binding in Openhab.
Dunno if licences are exactly matching en all and how they exactly apply to documentation, hence I wanted to check with you first if you have a problem with that,

https://python-miio.readthedocs.io/en/latest/troubleshooting.html#intermittent-connection-issues-timeouts-xiaomi-vacuum

**Comment by rytilahti** [comment]
Hi @marcelrv – feel free to copy (or link) to the section. I forgot completely to license the documentation when it was introduced, so I leave this issue open for the time being.

One potential license choice could be CC Attribution-NonCommercial-ShareAlike 4.0 which is used by homeassistant for their documentation. This would allow effortless sharing of relevant parts between these two projects. Which license is used by oepnhab for their documentation?

**Comment by marcelrv** [comment]
I was planning indeed to copy it, but also put a link to the original. Just to make sure that if I updates happened, and I did not follow them yet, users have access to the latest.

Wrt to the OH documentation licence... looks like the project at whole is Eclipse Public License 2.0.
