### ISSUE TITLE
Support for Xiaomi Qingping Bluetooth Alarm Clock?

### ISSUE THREAD

**Issue by JsBergbau** [rytilahti/python-miio#614]
Is there support planned for the Xiaomi Qingping Bluetooth Alarm Clock
Please see pictures and a short description here https://www.gearbest.com/blog/new-gear/xiaomi-qingping-bluetooth-alarm-clock-review-9838
I know this article is kind of advertisment, but suitable to show which device I mean.

**Comment by rytilahti** [comment]
Nope, this library only supports wifi-enabled devices, sorry.
