### ISSUE TITLE
miplug module is not working from python scrips

### ISSUE THREAD

**Issue by ksetdekov** [rytilahti/python-miio#621]
After installing miio and python-miio, i try to reproduce the intended behavior, described in the documentation [https://python-miio.readthedocs.io/en/latest/plug.html](https://python-miio.readthedocs.io/en/latest/plug.html), but it does not work from python:
import miio
miplug --ip <plug IP> --token <plug token> on

1. SyntaxError: invalid syntax error no matter, how i format the ip and token
2. Nothing happens, only if i work wrom the command line/ bash, i get the status change.
`miplug --ip <plug IP> --token <plug token> on`
`Power on: ['ok']`

**Comment by rytilahti** [comment]
That's the documentation for the cli tool, the documentation for the library use is located at https://python-miio.readthedocs.io/en/latest/miio.html#module-miio.chuangmi_plug . The list of supported models is shown on top of that page.
