### ISSUE TITLE
Xiaomi STYJ02YM discovered but not responding

### ISSUE THREAD

**Issue by gmag11** [rytilahti/python-miio#628]
I'm trying to control a Xiaomi STYJ02YM vacuum with software 3.5.3_0045. Currently it is linked to Mi Home app.

When running mirobo discover I get this:
```
$ mirobo discover
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
INFO:miio.discovery:Found a supported 'ViomiVacuum' at 192.168.5.234 - token: ffffffffffffffffffffffffffffffff
```

But any other command gives no answer from Vacuum.

```
$ mirobo status
ERROR:miio.device:Got error when receiving: timed out
Error: No response from the device
```

I've setup exports for ip address and token. I've got the token from logs in Android.

With `miiocli viomivacuum`I get this info:
```
$ miiocli viomivacuum --ip 192.168.5.234 --token xxxxxxxxxxxx616661727636xxxxxxxx info
Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0045
Network: {'localIp': '192.168.5.234', 'mask': '255.255.255.0', 'gw': '192.168.5.1'}
AP: {'ssid': 'XXXXXXXXX', 'bssid': 'xx:xx:xx:xx:xx:xx'}
```

I've captured dialog with vacuum using Wireshark. Vacuum only answers handshake. Check the file.

[XiaoMi styj02ym miio.pcapng.gz](https://github.com/rytilahti/python-miio/files/4201789/XiaoMi.styj02ym.miio.pcapng.gz)

Let me know if more debug info is needed.

**Comment by rytilahti** [comment]
`mirobo` command works currently only with Xiaomi vacuums. As the protocol used by viomi is different, `miiocli viomivacuum` and its subcommands is currently the only way to command them.

**Comment by i00** [comment]
I have one of these too ...
also @rytilahti this is a Xiaomi vacuum ...

@gmag11 - Miio does work with it ... but the built in commands are different for it vs the Xiaomi / Roborock ones, so you have to use the raw_command...
Anyway, if you are using it with Home Assistant, there is a component [here](https://github.com/nqkdev/home-assistant-vacuum-styj02ym) that does most of what I need it to do.
