### ISSUE TITLE
MIIO stop working for Xiaomi device ?

### ISSUE THREAD

**Issue by loic69chy** [rytilahti/python-miio#635]
Hi all
I writed an eedomus plugin for Smartmi Humidifier CA1 wich works fine.
this plugin based on python-miio.
Since 3 weeks, the plugin doesn't work and after debug, I found the python-miio test cli isn't working for humidifier with Error 5001 returned.

So, somebody can say me if the support of API Miio on Xiaomi device is already OK on all device ? 
I read that Xiaomi will prefer the MIOT cloud API...

Other way, is Xiaomi changed element on API frame ?
Thanks for your help

**Comment by rytilahti** [comment]
Did you update the firmware of the device or did something else change? There has been no recent breaking changes in this project..

**Comment by cayco** [comment]
I think, I have a similar problem with my device: https://github.com/syssi/xiaomi_airpurifier/issues/51

I did not upgrade it as far as I remember...

**Comment by cayco** [comment]
I've added some details in https://github.com/syssi/xiaomi_airpurifier/issues/51 and the issues still exists. Any ideas how to deal with this?
