### ISSUE TITLE
REQ: vacuum - restore map function ?

### ISSUE THREAD

**Issue by gibman** [rytilahti/python-miio#646]
I just updated to the latest FW (3.5.7_002008) for my roborock S50 unit.
On the main map I now have a button “edit map” clicking on it takes me to a list of max 2 backed up maps to choose from. Also possible to delete maps here.

From here I am able to click on a map and override the current one with my backed up map.
Quite useful.

I wonder if this (restore map function) can be called using this API ?

I haven’t sharkwired the communciation from the vacuum, cloud and my phone - so I have no idea what the payload looks like. But I bet it’s there.

The benefit with this feature would be to always revert to a well known backup copy of the map on each return to the docking bay.

This would fix the problem of having an actual map of closed doors which sadly happens a lot of the time.
This would also fix corrupted maps etc etc.

A good reference map would be one scanned with open doors… obviously :slight_smile:

**Comment by rytilahti** [comment]
Maybe `get_backup_maps` (https://github.com/rytilahti/python-miio/blob/master/miio/vacuum.py#L544) and `use_backup_map` are relevant for this? As I have no device to test those, I don't know. If you try them out, feel free to document your findings to the docs we have! :-)

**Comment by rytilahti** [comment]
Please reopen if this is still valid.
