### ISSUE TITLE
Can i turn off main brush on miio.vacuum?

### ISSUE THREAD

**Issue by guinmoon** [rytilahti/python-miio#647]
Is there a real-time way to turn the main brush on and off? Or the speed of its rotation? I saw that in nav.conf there is a parameter MAIN_BRUSH_NORMAL_PWM.

**Comment by rytilahti** [comment]
That's not possible over the miio interface, afaik. The devices with mop will support "gentle" fanspeed, which turns the fan off(?), so I'd expect that to turn the brush off, too. Maybe that's worth checking out, but there is no much this library can do when the device does not provide an interface to control that, so I'll close this now.

**Comment by guinmoon** [comment]
I have succeeded. If you replace 
```
MAIN_BRUSH_NORMAL_PWM 0.70
MAIN_BRUSH_SLOW_PWM 0.30 
```
at 
```
MAIN_BRUSH_NORMAL_PWM 0.0
MAIN_BRUSH_SLOW_PWM 0.0 
```
and do 
`sudo service rrwatchdoge restart `
then the brush will turn off.
