### ISSUE TITLE
Add support for Xiaomi Air Purifier Pro H please

### ISSUE THREAD

**Issue by memphis3** [rytilahti/python-miio#648]
Hello !
Will Xiaomi Air Purifier Pro H have support for HA? 
Model: zhimi.airpurifier.va1

**Comment by rezmus** [comment]
it should be more or less the same as ma4/mb3.

**Comment by memphis3** [comment]
Yes, but ma4 / mb3 is also not on the support list. I tried to integrate it by auto-detecting and also adding the model, unfortunately, with no result

**Comment by rezmus** [comment]
https://github.com/rytilahti/python-miio/pull/634

**Comment by rytilahti** [comment]
Could you try `miiocli airpurifiermiot info` command and paste the results here? Is `mirobo discover` discovering it?

**Comment by elfrinjo** [comment]
Hi, I have this device and tested the new release today (5.0 not 5.0.1). These were my steps and results:

- Reset the air purifiers network config
- Connect pc to the devices own WiFi
- Run mirobo `discover --handshake 1`
-- Command returns token
- Test `miiocli airpurifiermiot status`
-- Command returns device status
- Use mirobo to reconfigure wifi to switch to use the actual home-wifi
- Run `miiocli airpurifiermiot status` command again
-- This time the command times out

**Comment by rytilahti** [comment]
Hi,

>     * Run `mirobo discover --handshake 1`
>       -- Command returns token

Does it work without the handshake option? `mirobo -d discover` will show some additional details (we are interested in something with `._miio._udp.local.` at the end, that's the device type for autodetection).

>     * Test `miiocli airpurifiermiot status`
>       -- Command returns device status

What does that status display? Is the information correct?

Can you please do `miiocli airpurifiermiot info`? The model number is what 

>     * Use `mirobo` to reconfigure wifi to switch to use the actual home-wifi
> 
>     * Reconnect to the home network and rerun `miiocli airpurifiermiot status` command again
>       -- This time the command times out

This is normal. Every time a device gets reconfigured, it will reset its token. Unfortunately there is no easy way to obtain the token after that :(
> 
> (IP and token options were applied to the commands)

**Comment by rezmus** [comment]
after you connect device to wifi token changes. you need to find another way to obtain token after device is connected like for example mi home mod (tokens are in profile > share > share the device).

**Comment by elfrinjo** [comment]
Darn - I just realize, I have a 3H and not a Pro H. Sorry for the confusion.

**Comment by memphis3** [comment]
> Could you try `miiocli airpurifiermiot info` command and paste the results here? Is `mirobo discover` discovering it?

Unfortunetly I`m noob in programing, can you tell me where I have to put this command ? Also I have mod mi app - I can give you some info from there

**Comment by rytilahti** [comment]
@memphis3 those are command-line commands, so you can execute them in the environment where you have installed python-miio.

**Comment by Notrial** [comment]
Anyone tested Pro H model with MiOT for 3/3H?

**Comment by latel** [comment]
it works for me!

![image](https://user-images.githubusercontent.com/5621862/107846735-ec748480-6e20-11eb-813b-7378105ff418.png)

```bash
~ miiocli --version
miiocli, version 0.5.4
```
