### ISSUE TITLE
How to enhance the Xiaomi camera(chuangmi.camera.ipc019) function

### ISSUE THREAD

**Issue by Silence-kzp** [rytilahti/python-miio#655]
Currently, the chuangmi_camera.py module can be used to perform basic operations on the Xiaomi camera, but the camera cannot be controlled to move up, down, left, and right. I want to add these functions. After trying the methods provided on miio, I cannot parse the json file exported on wireshark The output is garbled, I ca n’t start now, I hope to provide some ideas for me.

**Comment by rezmus** [comment]
>{"method":"set_motor","params":{"operation":2},"id":65877}
<{"result":["OK"],"params":{"angle":43,"elevation":34},"id":65877}

>{"method":"set_motor","params":{"operation":2},"id":23977}
<{"result":["OK"],"params":{"angle":41,"elevation":34},"id":23977}

>{"method":"set_motor","params":{"operation":2},"id":42474}
<{"result":["OK"],"params":{"angle":39,"elevation":34},"id":42474}

operation param is 1-4 (directions), but you can set how much you want move. in response you get angle/elevation (1-100) so you know where you are. if cam reaches far point it can move you get some error.

**Comment by Silence-kzp** [comment]
thx, I tried it and it works, the only thing I am wondering now is why my wireshark can't catch the data of udp port of 54321.
![image](https://user-images.githubusercontent.com/13250487/77842591-bb6a7180-71c6-11ea-9aba-5ab96ee4ab31.png)

**Comment by rytilahti** [comment]
Could you please confirm the orientation directions? Also, @Silence-kzp, is this ipc009 or ipc019?

**Comment by Silence-kzp** [comment]
yep, Is ipc019.

**Comment by rytilahti** [comment]
@Silence-kzp could you please confirm the orientation directions, so that we can get the PR merged for the next release?

**Comment by rezmus** [comment]
@rytilahti i just checked on ipc019e. 1 left, 2 right, 3 up, 4 down. btw: some new models have alarm_sound method (no params) which makes very loud alarm sound for 10s.

**Comment by rytilahti** [comment]
Great, thanks rezmus! :100:

**Comment by shummo** [comment]
Can this model use with Home Assistant?

**Comment by rytilahti** [comment]
Not at the moment, as far as I know. See also https://github.com/rytilahti/python-miio/issues/682#issuecomment-617195390 for my previous comment regarding to video stream, without video stream the camera integration on homeassistant would likely be rather limited.
