### ISSUE TITLE
python-miio v0.5.0 incomplete utils.py

### ISSUE THREAD

**Issue by starkillerOG** [rytilahti/python-miio#659]
When I look at the master branch of rytilahti/python-miio in the file: `python-miio/miio/utils.py` the function `int_to_brightness` is there.
However when I download the source_code of the v0.5.0 release from: https://github.com/rytilahti/python-miio/archive/0.5.0.zip
And extract the files and then look into `python-miio/miio/utils.py` the function `int_to_brightness` is not there.

This causes an import error when installing python-miio through `pip3 install --upgrade python-miio` and then trying to import the gateway class:
```
from miio import DeviceException, gateway
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Others\Python37\lib\site-packages\miio\gateway.py", line 8, in <module>
    from .utils import int_to_rgb, int_to_brightness, brightness_and_color_to_int
ImportError: cannot import name 'int_to_brightness' from 'miio.utils' (...\Python37\lib\site-packages\miio\utils.py)

```

**Comment by starkillerOG** [comment]
@rytilahti do you have any idea what is going on?

**Comment by rytilahti** [comment]
Uhhh, that's really odd.. Must be caused by basing the preparations branch & tagging over wrong tip... I'll prepare 0.5.0.1 to fix that asap.

**Comment by starkillerOG** [comment]
@rytilahti thanks for fixing this so quickly!

**Comment by rytilahti** [comment]
Thank you for quick testing & reporting :-) Goes much faster this way, than realizing it after it's been propagated to downstream. I think this shows the release process needs some improvements though, to avoid having this again in the future...
