### ISSUE TITLE
Xiaomi Mi Air Purifier 3H (zhimi-airpurifier-mb3) 

### ISSUE THREAD

**Issue by djgreko** [rytilahti/python-miio#670]
Hello. I have been purchasing this new device for a few days and was wondering if it will be integrated. I added to the home assistant configuration and I see the entity, but it is not available. Thank you all

**Comment by rytilahti** [comment]
See https://github.com/rytilahti/python-miio/issues/577 . The next homeassistant release (0.109) will support this device.
