### ISSUE TITLE
Add support to Xiaomi Mi Home 360 1080p MJSXJ05CM 

### ISSUE THREAD

**Issue by jonathanhar** [rytilahti/python-miio#671]
Hey guys, 
I tried to connect to my new IP camera today and got this message:
`WARNING:miio.discovery:Found unsupported device chuangmi-camera-ipc019_miio311456450._miio._udp.local. at 192.168.1.117, please report to developers`

Appreciate your help

**Comment by rytilahti** [comment]
The basic support should be there, the linked PR is aimed to improve the support with camera controls but it hasn't been tested so far.
