### ISSUE TITLE
Xiaomi Xiao AI Smart Alarm Clock - get alarm

### ISSUE THREAD

**Issue by Koponyeges** [rytilahti/python-miio#678]
Hi! How to get set alarm?
Please help!
![image](https://user-images.githubusercontent.com/26966452/79697405-f66e3b00-8282-11ea-93b5-564be6629934.png)

**Comment by rytilahti** [comment]
That is not currently implemented, there are some example payloads in the source if someone wants to work on adding support for that: https://github.com/rytilahti/python-miio/blob/master/miio/alarmclock.py#L204
