### ISSUE TITLE
Enhancement request: get snapshot / recording from chuangmi camera

### ISSUE THREAD

**Issue by jonathanhar** [rytilahti/python-miio#682]
Hello guys,
terrific work on this package, it seems to work fantastic.
I saw that a few days ago you added some enhancements to the chuangmi cameras, and I was hoping to ask for a feature of grabbing a snapshot / recording a video.
#655 
Is this possible?
Thanks

**Comment by rytilahti** [comment]
#547 and https://github.com/rytilahti/python-miio/issues/373#issuecomment-427606838 may be relevant. The camera streaming uses different protocol and would likely require lot of work to integrate properly.
