### ISSUE TITLE
`is_on` not correct

### ISSUE THREAD

**Issue by thoron** [rytilahti/python-miio#687]
(Relevant for Roborock S6)
The https://python-miio.readthedocs.io/en/latest/miio.html#miio.vacuumcontainers.VacuumStatus.is_on will not yield correct value as the underlying `in_cleaning` is not a boolean. 

```
mirobo --ip x.x.x.x --token yyy raw-command get_status                                                                          [12:43:00]
Sending cmd get_status with params []
[{'msg_ver': 2, 'msg_seq': 28, 'state': 18, 'battery': 95, 'clean_time': 606, 'clean_area': 8115000, 'error_code': 0, 'map_present': 1, 'in_cleaning': 3, 'in_returning': 0, 'in_fresh_state': 0, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 102, 'dnd_enabled': 0, 'map_status': 3, 'lock_status': 0}]
```

Where the interesting bit is *'in_cleaning': 3*
https://github.com/rytilahti/python-miio/blob/85e119ccb1abc740b1af48ba490a6ee416e625a6/miio/vacuumcontainers.py#L152

**Comment by rytilahti** [comment]
Thanks for the report, I adapted `is_on` to also cover the segment cleaning in the linked PR.

**Comment by thoron** [comment]
So fast man! Thanks for the effort!

**Comment by rytilahti** [comment]
You are welcome, it was a simple fix and I happened to be around :-)
