### ISSUE TITLE
0.5.0 / 0.5.0.1 breaks viomivacuum status

### ISSUE THREAD

**Issue by Bene2103** [rytilahti/python-miio#694]
First of all, thank you guys very much for this awesome piece of software!

I'm using miio with my Xiaomi STYJ02YM which should be the same as some vacuum from Viomi.

I've used python-miio 0.4.8 for quite some time and now decided to upgrade to the actual version because of the improvements which were made to the viomivacuum.

Python-miio 0.4.8 works really well, every command i've done works like a charm.
info: 
![Bildschirmfoto 2020-05-08 um 15 43 34](https://user-images.githubusercontent.com/46553509/81411563-d5db2780-9142-11ea-8fd7-66f199b49216.png)
status:
![Bildschirmfoto 2020-05-08 um 15 45 19](https://user-images.githubusercontent.com/46553509/81411635-f3a88c80-9142-11ea-9fff-fe9f66b06431.png)

Upgraded to 0.5.0.1 i i've seen me confronted with the following output:
info (which works as it should):
![Bildschirmfoto 2020-05-08 um 15 46 13](https://user-images.githubusercontent.com/46553509/81411733-15a20f00-9143-11ea-9051-3645b2749101.png)
status:
![Bildschirmfoto 2020-05-08 um 15 46 58](https://user-images.githubusercontent.com/46553509/81411814-2f435680-9143-11ea-85a9-248a14687ac4.png)

Is there anything i've done wrong? Or anything i can fix myself? 

The next thing is the following.
The robot works fine for some time until it gets unresponsive to python-miio. This was discussed before in some other threads. The only way to communicate with the robot is a power-cycle.
Some quick fix witch doesn't work for me
https://github.com/rytilahti/python-miio/issues/550#issuecomment-557818151
Here is some explanation for the problem
https://github.com/rytilahti/python-miio/issues/597#issuecomment-575198865

I've also tried the installed firmware on the vacuum and updated the vacuum to the newest firmware. The problem still persists.

Is there any fix for this? I'd like to contribute as much as i can! (despite my very low programming skills)

Thank you!

**Comment by rytilahti** [comment]
Thanks for the report, that broke as the naming got changed during improving the presentation. Please check out the linked PR to see if it works!

Unfortunately I have no fix for the connectivity issues, but that should be a separate issue.
