### ISSUE TITLE
New device it's possible ? Ikea tradfri GU10

### ISSUE THREAD

**Issue by andreynet** [rytilahti/python-miio#707]
Hello! Thanks for the work you've done! There are 2 Ikea tradfri GU10 lamps, they can be easily added to Mi Home, but unfortunately they do not appear in the Home Assistant, as I understand they can not connect via miio protocol? Will it be possible to add them to this integration? Thanks you!

**Comment by rytilahti** [comment]
Those are zigbee devices, so it's unlikely that they will be supported by this library. Only potential solution I can imagine could be extending the gateway device support, but that's also a long shot.

Personally I would suggest looking into using zigbee2mqtt to integrate these with homeassistant.
