### ISSUE TITLE
Xiaomi Mi Water Purifier support

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#71]
I wrote a first draft of the device support for the water purifier: https://github.com/rytilahti/python-mirobo/blob/master/mirobo/waterpurifier.py

For additional features the response to the following properties are needed:

```
["press","temperature","uv_state","filter_state","elecval_state","uv_life","mode"]
```

Which operation modes are supported? Are there additional features available at the mi home app?

@nutinshell Could you provide some more details? :-)

**Comment by nutinshell** [comment]
> Which operation modes are supported? Are there additional features available at the mi home app?

Hi, I'm afraid there are no too many operations for a water purifier even in the mi home app, `get_prop []` returns tds, filter life, etc., states info seems much important for a water purifier :)

**Comment by syssi** [comment]
@nutinshell Could you provide an example response of a "get_prop []"? Thanks in advance!

**Comment by syssi** [comment]
Some additional properties of the water purifier: 

"mode","tds","filter1_life","filter1_state","filter_life","filter_state","life","state","level","volume","filter","usage"

**Comment by syssi** [comment]
The water purifier is supported for some time. Closing this one.
