### ISSUE TITLE
xiaomi fan 1x  encountered  'user ack timeout'

### ISSUE THREAD

**Issue by jianyun8023** [rytilahti/python-miio#714]
## xiaomi fan 1x  encountered  'user ack timeout'

I tried docker in host mode, use cli or code.
Later, I also tested the window environment, but the results are no different.
One strange thing is that the debugging found that ts started from 1970

我遇到了图中的用户回应超时问题，尝试在host模式的docker、windows10下都不可以，cli或者代码都是这个问题。docker宿主机未开防火墙，window下设置防火墙打开54321。使用debug模式，发现ts事件参数是从1970年开始。

![image](https://user-images.githubusercontent.com/18240360/83602802-d500ae80-a5a5-11ea-9a68-8317e2ab3985.png)

resp `{'code': -9999, 'message': 'user ack timeout'}`

code 

```python
from miio import Fan

fan = Fan(
    ip="192.168.2.113",
    token="bd5331094c79457c30228129fd53137d",
    lazy_discover=False,
    debug=1,
    model="dmaker.fan.p5"
)
print(fan.info())
state = fan.update_state()
print(state)
# print(fan.status())
fan.on()

print(fan.status())
```

**Comment by jianyun8023** [comment]
This is my problem, I should initialize `FanP5`.
这是我的问题，我应该初始化FanP5。

**Comment by liangxrbiu** [comment]
> This is my problem, I should initialize `FanP5`. 这是我的问题，我应该初始化FanP5。

请问怎么初始化呢 我用的是小米的智能插座 在cmd运行的时候也出现了同样的问题 也是1970开始的 该怎么改呀
