### ISSUE TITLE
fan za3, got token, but does not work

### ISSUE THREAD

**Issue by ichmachnixichgucknur** [rytilahti/python-miio#720]
Using ```miio discover``` I got the token provided after resetting the device. That worked great!
But afterwards nothing works. When configured to my WiFi, I cannot access the device with any tool (of course the App works, so sad).

Do you have any hint on that?

Here is some output:

```  thing:miio:116764076 <- Message: `{"id":1,"result":{"life":24,"model":"zhimi.fan.za3","token":"828000212d8240257ee012456586d2c3","fw_ver":"2.0.3","mcu_fw_ver":"0013","miio_ver":"0.0.3","hw_ver":"esp32","mmfree":85860,"mac":"40:31:3C:B8:61:51","wifi_fw_ver":"v3.1.3-8-gce4d3fe10","netif":{"localIp":"192.168.4.1","mask":"255.255.255.0","gw":"192.168.4.1"},"miio_times":[23,0,0,0]}}` +13ms```

```miiocli --debug fanza3 --ip 192.168.178.38 --token 828000212d8240257ee012456586d2c3 status                                                                        xv12960@uncloudedlaptop
INFO:miio.cli:Debug mode active
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x06\xf5\xad\xac\x00\x00\x02D' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('06f5adac')
            ts = 1970-01-01 00:09:40
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 06f5adac with ts: 1970-01-01 00:09:40, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.178.38:54321 >>: {'id': 1, 'method': 'get_prop', 'params': ['angle']}
DEBUG:miio.miioprotocol:Retrying with incremented id, retries left: 3
```

**Comment by rytilahti** [comment]
After you provision the device by configuring it to connect your wifi, it will regenerate the token so you will have to extract it, see https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/#retrieving-the-access-token
