### ISSUE TITLE
support dmaker.fan.p9 and dmaker.fan.p10

### ISSUE THREAD

**Issue by myixr** [rytilahti/python-miio#721]

**Comment by fineemb** [comment]
+1

**Comment by rytilahti** [comment]
Both of these are miio devices, so someone needs to find out which commands are accepted (either by dumping the info from the firmware, the app, or extracting the token and capturing the network traffic).

**Comment by fineemb** [comment]
The device changed the rules, not UDP54321
[tcpdump (5).zip](https://github.com/rytilahti/python-miio/files/4777348/tcpdump.5.zip)

**Comment by rytilahti** [comment]
That's TCP connection to somewhere in China, using HTTP port for comms, but still to an external host, so this is not the local control traffic. I didn't look into the payloads more closely, but that PCAP doesn't exclude the possibility that it's still locally controllable.

**Comment by rezmus** [comment]
miot ;)

**Comment by chestarss** [comment]
+1

**Comment by fineemb** [comment]
Does not seem to support LAN control

**Comment by rezmus** [comment]
send raw payload, you should get power status in response
'''
{"method":"get_properties","params":[{"did":"yourdevicedid","siid":2,"piid":1}],"id":1234}
'''

**Comment by anhnvme** [comment]
Update xiaomi Spec for P9
http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p9:1

**Comment by biscuitee** [comment]
will the support for dmaker.fan.p9 be added to xiaomi_miio or xiaomi_miio_fan soon? I am waiting for this integration so that i could control the fan :) thanks a million

**Comment by maximatchev** [comment]
I'm very intrested in dmaker.fan.p9 too. Really looking forward to the update xiaomi_miio_fan

**Comment by merdok** [comment]
Both of the fans are using the miot protocol and support lan control. My homebridge plugin supports both of those fans.

**Comment by biscuitee** [comment]
> Both of the fans are using the miot protocol and support lan control. My homebridge plugin supports both of those fans.

great.  could you share how could I incorporate the support of dmaker.fan.p9 into home assistant?  how to I add your plugin to the home assistant?

**Comment by merdok** [comment]
Oh, I guess someone needs to write a home assistant plugin for that, if you use homebridge then you can use my plugin.
