### ISSUE TITLE
viomi: add command for changing the mopping mode

### ISSUE THREAD

**Issue by timothy-morph** [rytilahti/python-miio#725]
The device I have is "STYTJ02YM" , this model [https://www.aliexpress.com/i/4000123281431.html](url)

and it has a mopping modes to choose (Y-Pattern and S-Pattern)
I personally love to use Y-Pattern but I cannot seem to find the command for this.
Is there a command for this? and how?

Thanks! 😃

Here's a screenshot of the setting in the Mi Home app about the Y-pattern:
![image](https://user-images.githubusercontent.com/50393226/84469927-c2c4f580-acb4-11ea-829a-fe72070dcfab.png)

**Comment by rezmus** [comment]
set_moproute [0/1]

**Comment by timothy-morph** [comment]
Thank a lot !!!! :D I'll try and see if I know how to use it.!! Big Thanks!

**Comment by rytilahti** [comment]
Let's keep this open until the command gets added to ViomiVacuum class.
