### ISSUE TITLE
Send multiple params broken result

### ISSUE THREAD

**Issue by nutinshell** [rytilahti/python-miio#73]
Send multiple params to water purifier like `raw_command get_prop '["press","mode"]'`, the result always broken like `[300, 'error']`, only first one is right, no matter how much params sent.

`https://github.com/aholstenson/miio/` cli works well.

Capture shows very different behavior with mirobo, below is a single command ` --method get_prop --params '["press","temperature"]'` :

```
 ->  10.0.1.9 data= {"id":1,"method":"miIO.info","params":[]}
 <-  10.0.1.8 data= {"result":{"life":30300,"token":"a3d7f9****683","mac":"28***:03","fw_ver":"1.2.8","hw_ver":"ESP8266","model":"yunmi.waterpuri.v2","mcu_fw_ver":"0019","wifi_fw_ver":"1.4.0(30e0bd0)","ap":{"rssi":-58,"ssid":"Deep Space Voyager","bssid":"00***:A1"},"netif":{"localIp":"10.0.1.8","mask":"255.255.0.0","gw":"10.0.0.15"},"mmfree":10256},"id":1}
 ->  10.0.1.9 data= N/A
 <-  10.0.1.8 data= N/A
 ->  10.0.1.9 data= {"id":1,"method":"get_prop","params":["press","temperature"]}
 <-  10.0.1.8 data= {"result":{"life":30300,"token":"a3d7f9****683","mac":"28***:03","fw_ver":"1.2.8","hw_ver":"ESP8266","model":"yunmi.waterpuri.v2","mcu_fw_ver":"0019","wifi_fw_ver":"1.4.0(30e0bd0)","ap":{"rssi":-58,"ssid":"Deep Space Voyager","bssid":"00***:A1"},"netif":{"localIp":"10.0.1.8","mask":"255.255.0.0","gw":"10.0.0.15"},"mmfree":10256},"id":1}
 ->  10.0.1.9 data= {"id":1,"method":"get_prop","params":["press","temperature"]}
 <-  10.0.1.8 data= {"result":[300,29],"id":1}
```
any idea?

**Comment by rytilahti** [comment]
Could you please post also the same mirobo command with `-d` and check out if the JSON payloads differ?

**Comment by nutinshell** [comment]
> Could you please post also the same mirobo command with -d and check out if the JSON payloads differ?

hi @rytilahti  it's like:

```
INFO:mirobo.vacuum_cli:Debug mode active
DEBUG:mirobo.vacuum_cli:Read stored sequence ids: {'seq': 3, 'manual_seq': 0}
DEBUG:mirobo.vacuum_cli:Connecting to 10.0.1.8 with token a3d7****3
Sending cmd get_prop with params ['press', 'mode']
DEBUG:mirobo.protocol:Unable to decrypt, returning raw bytes.
DEBUG:mirobo.device:Got a response: Container: 
    data = Container: 
        data =  (total 0)
        value =  (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = !1\x00 \x00\x00\x00\x00\x02\xf6Y\x18\x00\x01l1 (total 16)
        value = Container: 
            length = 32
            unknown = 0
            devtype = 758
            serial = 22808
            ts = 1970-01-02 01:53:53
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = \xa3\xd7\xf9W\xb6\x83\xbe\xe6\xe7\x89\xf17\xb7c\xe6\x83 (total 16)
DEBUG:mirobo.device:Discovered 758 22808 with ts: 1970-01-02 01:53:53, token: b'a3d7****3'
DEBUG:mirobo.device:10.0.1.8:54321 >>: {'id': 4, 'method': 'get_prop', 'params': ['press', 'mode']}
DEBUG:mirobo.device:10.0.1.8:54321 (ts: 1970-01-02 01:53:53, id: 4) << {'result': [410, 'error'], 'id': 4}
[410, 'error']
DEBUG:mirobo.vacuum_cli:Writing {'seq': 4, 'manual_seq': 0} to /tmp/python-mirobo.seq
```

**Comment by rytilahti** [comment]
The first one requests 'press' and 'temperature' whereas the mirobo one does it for 'press' and 'mode'. Could you please check if it works with 'press' and 'temperature', maybe the error is coming from an unknown property?

Another thing to try out is to make that info query before invoking the request (maybe the device uses that as a sort of a handshake?).

**Comment by nutinshell** [comment]
> The first one requests 'press' and 'temperature' whereas the mirobo one does it for 'press' and 'mode'. Could you please check if it works with 'press' and 'temperature', maybe the error is coming from an unknown property?

I said it in very first, JSmiio works fine, all properties known.

> Another thing to try out is to make that info query before invoking the request (maybe the device uses that as a sort of a handshake?).

Tested, no luck.

**Comment by rytilahti** [comment]
Ok, so it must be something else then. Could it be related to the flood protection (if we are sending the commands too fast after that completed handshake?), or that id is not being incremented for the js miio?

It is a bit odd that in the js output the `get_prop` is called twice, first return value being the output of device info and just after that the real result.

**Comment by syssi** [comment]
Could you provide a traffic capture (miioJs vs. mirobo) again? It's easier to verify.

**Comment by nutinshell** [comment]
@syssi let me email you :)

**Comment by syssi** [comment]
I must admin I lost your mail if you sent one.

**Comment by nutinshell** [comment]
@syssi hi, I just resent it again :)

**Comment by lukezzz** [comment]
Had the bug fixed?  I got the same issue:
k.raw_command('get_prop', ['tds','time'])
[11, 'error']

**Comment by syssi** [comment]
Does it work if you request "time" only?

**Comment by lukezzz** [comment]
@syssi,

Tried with Python-miio:
` k.raw_command('get_prop', ['tds','time'])
 [32, 'error']

 k.raw_command('get_prop', ['tds'])
 [32]

 k.raw_command('get_prop', ['time'])
 [1541583582]
`

If I use the js miio tools, I can get the result without error:
`root@raspberrypi:/home/pi# miio protocol call 192.168.98.105 get_prop '["tds","time"]'
 INFO  Attempting to call get_prop on 192.168.98.105

 INFO  Device found, making call

 INFO  Got result:
[
  32,
  1541583712
]`

**Comment by lukezzz** [comment]
Thanks!
