### ISSUE TITLE
xiaomi.aircondition.ma1  Support

### ISSUE THREAD

**Issue by anhnvme** [rytilahti/python-miio#743]
Hello,

I'm tried dump all prop at this device, please check if it can support anything for you 

```
"params":["power","settemp","mode","wind_percent","swing"]}
"result": [0, 24, 2, 101, 0]
"params":["energysave","light","beep","clean","wind_level"]}
"result": [0, 0, 1, "0,0,0,1", 0]
"params":["auxheat","dry","timer","sleep","temperature"]}
"result": [0, 0, "0,0,0,0", 0, 32]
"params":["examine"]}
"result": ["0,0,'none'"]
```

Thanks

**Comment by anhnvme** [comment]
Update xiaomi Spec: http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-ma1:1

**Comment by rezmus** [comment]
spec are useless here, because it does not use miot.

**Comment by anhnvme** [comment]
> spec is useless here, because it does not use miot.

yes, it's use miio man

[root@lab homeassistant]# miiocli device --ip xxxxx --token xxxxx info
Model: xiaomi.aircondition.ma1
Hardware version: esp32
Firmware version: 2.0.9
Network: {'localIp': 'xxxxx', 'mask': '255.255.255.0', 'gw': 'xxxxxxxx'}
AP: {'ssid': 'xxxxxxxx', 'bssid': 'xxxxxxxxx', 'rssi': -39, 'primary': 4}

**Comment by anhnvme** [comment]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["power"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["settemp"]'
> Running command raw_command
> [24.0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["mode"]'
> Running command raw_command
> [2]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["wind_percent"]'
> Running command raw_command
> [101]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["swing"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["energysave"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["light"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["beep"]'
> Running command raw_command
> [1]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["clean"]'
> Running command raw_command
> ['0,0,0,1']
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["wind_level"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["auxheat"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["dry"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["timer"]'
> Running command raw_command
> ['0,0,0,0']
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["sleep"]'
> Running command raw_command
> [0]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["temperature"]'
> Running command raw_command
> [32]
> [root@lab homeassistant]# miiocli device --ip _ip_ --token _token_ raw_command get_prop '["examine"]'
> Running command raw_command
> ["0,0,'none'"]

Request dump by miio_cli

**Comment by anhnvme** [comment]
It's over year but i still need support this device. how can i help  to add it ?
