### ISSUE TITLE
Roborock S5 Max, Failure to connect in Homeassistant.

### ISSUE THREAD

**Issue by Zedread** [rytilahti/python-miio#758]
# The problem

I've 2 Xiaomi robots, the older S5 has no problems, its detected in homeassistant and its available for usage there, the problem resides on the new S5 Max, this vacuum shows as unavailable in home assistant and in the logs we can see the following information:

# The Environment
Home Assistant Core release with the issue: 0.112.4
Last working Home Assistant Core release (if known): No
Operating environment (OS/Container/Supervised/Core): Container
Integration causing this issue: xiaomi_miio.vacuum
Link to integration documentation on our website: https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/

# Problem-relevant ````configuration.yaml````
```
vacuum:
  - platform: xiaomi_miio
    name: Roborock_S5
    host: <ip 1>
    token: <token 1>
  - platform: xiaomi_miio
    name: Roborock_S5_Max
    host: <ip 2>
    token: <token 2>
```
I've the following configuration settings,  i've tried every possible config, like removing the name, putting the S5 Max config first, commenting the normal S5 config out and nothing works, always the same error.

# Traceback/Error logs
````
Logger: homeassistant.components.xiaomi_miio.vacuum
Source: components/xiaomi_miio/vacuum.py:485
Integration: Xiaomi Miio (documentation, issues)
First occurred: 5:24:19 PM (88 occurrences)
Last logged: 5:54:42 PM

Got OSError while fetching the state: [Errno -2] Name does not resolve
````

# Additional information

Using the rrcc app on windows i can connect to my robot.

Using miiocli from inside the docker running homeassistant i can also connect to the robot and these are the commands output:

status command
````
/ # miiocli vacuum --ip <ip 2> --token <token> status
Running command status
<VacuumStatus state=Charging, error=No error bat=100%, fan=103% cleaned 0.0 m² in 0:00:01>
````
info command
````
/ # miiocli vacuum --ip <ip 2> --token <token> info
Model: roborock.vacuum.s5e
Hardware version: Linux
Firmware version: 3.5.8_0862
Network: {'localIp': '<ip 2>', 'mask': '255.255.255.0', 'gw': '192.168.1.1'}
AP: {'ssid': '<home ssid>', 'bssid': '<mac addrs>', 'rssi': -72}
````

````
/ # miiocli vacuum --ip <ip 2> --token <token> fan_speed_presets
Running command fan_speed_presets
INFO:miio.vacuum:model: roborock.vacuum.s5e
{'Silent': 101, 'Standard': 102, 'Medium': 103, 'Turbo': 104, 'Gentle': 105}
````

````
/ # miiocli vacuum --ip <ip 2> --token <token> consumable_status
Running command consumable_status
<ConsumableStatus main: 1:22:56, side: 1:22:56, filter: 1:22:56, sensor dirty: 1:22:56>
````

````
/ # miiocli vacuum --ip <ip 2> --token <token> clean_history
Running command clean_history
<CleaningSummary: 3 times, total time: 1:22:56, total area: 76.04, ids: [1594645032, 1592560788, 1592231256]>
````

````
/ # miiocli vacuum --ip <ip 2> --token <token> last_clean_details
Running command last_clean_details
<CleaningDetails: 2020-07-13 13:57:12 (duration: 0:00:01, done: False), area: 0.0>
````

````
/ # miiocli vacuum --ip <ip 2> --token <token> dnd_status
Running command dnd_status
<DNDStatus enabled: True - between 22:00:00 and 08:00:00>
````

If anymore information is necessary please ask i will try to provide asap, its really frustrating not being able to add the new robot to homeassistant.

**Comment by rytilahti** [comment]
> Got OSError while fetching the state: [Errno -2] Name does not resolve

This sounds like you are using a domain (instead of an ip address), or something that resembles one that is not resolving correctly.

**Comment by Zedread** [comment]
I'm using and ip address, its an address of type 192.168.1.X, the normal S5 is working correctly the S5 Max isn't, they have sequential ip's.

**Comment by Zedread** [comment]
Found the error, you could not see it because i blocked out the ip. I put : instead of . to separate the numbers...
