### ISSUE TITLE
AqaraSmartBulbE27 support added in #729 is not work

### ISSUE THREAD

**Issue by milesking** [rytilahti/python-miio#771]
**Describe the bug**
I have updated the miio version to 5.2.1 which is after the commit #729 , it shows the same error when init AqaraSmartBulbE27 device.

**Version information (please complete the following information):**
 - OS: Raspbian
 - python-miio: 5.2.1

**To Reproduce**
1. init AqaraSmartBulbE27 device

**Expected behavior**
Add AqaraSmartBulbE27 device.

**Console output**
Logger: xiaomi_gateway
Source: /usr/local/lib/python3.8/site-packages/xiaomi_gateway/__init__.py:297

The device with sid ****** isn't supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.

**Comment by starkillerOG** [comment]
You have the wrong integration, the integration you are using is xioami_aqara.
The github brach you are now on is the xiaomi_miio integration.

xiaomi_miio supports AqaraSmartBulbE27 in the lib, but not yet in HomeAssistant.
I am working on adding the devices to HomeAssistant, but don't have much spare time at the moment.

**Comment by milesking** [comment]
Ok, really appreciate your work.
