### ISSUE TITLE
ViomiVacuumState 6 seems to be VaccuumMopping

### ISSUE THREAD

**Issue by fs79** [rytilahti/python-miio#783]
**Is your feature request related to a problem? Please describe.**
When the vacuum is in mop and vacuum mode it states State 6.
So, please add state 6. Feel free to choose a name which follows your naming convention.

Please add state 6 to viomivacuum.py
https://github.com/rytilahti/python-miio/blob/30752c398cdaa41de39be98f7a7a8dc09d45a630/miio/viomivacuum.py#L58
    VacuumMopping = 6

  - Model: Xiaomi  Mi Robot Vacuum-Mop P
  - Hardware version: STYTJ02YM
  - Firmware version: 3.5.3_0017

**Comment by rytilahti** [comment]
Fixed, thanks for reporting! :tada:

**Comment by fs79** [comment]
Hi,
mode 6 is vaccuming and mopping.
There´s a mop only mode which I can´t test because I have no water only tank so maybe its better to call this mode not "mopping" but something which is mopping and vacuuming.

Thanks for being so fast with getting the change included.

**Comment by rytilahti** [comment]
Hi, thanks for the info! I really shouldn't have merged that so quickly.. :-)

I just created a new PR to rename this mode, the good thing is that the previous PR also added a warning message when the status is unknown, so maybe someone at some point will report back when they encounter that.
