### ISSUE TITLE
add error codes 2103 & 2105

### ISSUE THREAD

**Issue by fs79** [rytilahti/python-miio#789]
When the vacuum bot is charging it seems to use error 2103
When the vacuum bot is fully charged it seems to use error 2105.

Lets add the error message definition and check if other have the same observation.
https://github.com/rytilahti/python-miio/blob/30752c398cdaa41de39be98f7a7a8dc09d45a630/miio/viomivacuum.py#L41
    2103: "Charging",
    2105: "Fully charged",

Model: Xiaomi Mi Robot Vacuum-Mop P
Hardware version: STYTJ02YM
Firmware version: 3.5.3_0017

**Comment by rytilahti** [comment]
Feel free to create a PR to add those, but could you also check what does it say for the state when this happens? It feels a bit odd that errors are being reported when everything is actually fine.. :-)

**Comment by fs79** [comment]
You are so right, but the whole thing is a little odd. ;-)
I´´ll update this trhtread with status output when its charging and when its fully charged.
Perhaps I´m overlooking something.

**Comment by fs79** [comment]
1st output with eror 2105. Already modified my viomivacuum.py

State: ViomiVacuumState.Docked
Mode: ViomiMode.Vacuum
Error: Fully charged
Battery: 100
Fan speed: ViomiVacuumSpeed.Silent
Box type: ViomiBinType.Vacuum
Mop type: 0
Clean time: 0:00:02
Clean area: 2.35
Water grade: ViomiWaterGrade.High
Remember map: True
Has map: True
Has new map: False
Mop mode: ViomiMode.Vacuum

**Comment by fs79** [comment]
output with error 2103 charging.  Already modified my viomivacuum.py

State: ViomiVacuumState.Docked
Mode: ViomiMode.Vacuum
Error: Charging (2103)
Battery: 68
Fan speed: ViomiVacuumSpeed.Silent
Box type: ViomiBinType.Vacuum
Mop type: 0
Clean time: 0:00:49
Clean area: 41.86
Water grade: ViomiWaterGrade.High
Remember map: True
Has map: True
Has new map: False
Mop mode: ViomiMode.Vacuum

**Comment by rytilahti** [comment]
Ah, I see. I think they're simply using the error field to indicate also non-error statuses. So I think the question here is, maybe those "non-erroneous" states should be exposed as the state (so instead of `Docked` it would show `Charging` when it's still charging, and so on).

At some point, it would be great to have a common API for all supported vacuums no matter whether it is from rockrobo, viomi or dreame, just to consolidate the API and make it more accessible for downstreams like homeassistant.

**Comment by fs79** [comment]
Please close the issue. 
Made a pull request with the error and other messages I found.

**Comment by fs79** [comment]
Made a pull request with the error and other messages I found.
