### ISSUE TITLE
Xiaomi Smartmi Fresh Air System XFXTDFR02ZM.   upgrade version of  XFXT01ZM with heater.

### ISSUE THREAD

**Issue by wisesokol** [rytilahti/python-miio#791]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: XFXTDFR02ZM
  - Link: https://ultratrade.ru/products/pritochnuiy-vozdyxoochistitel-s-podogrevom-xiaomi-smartmi-fresh-air-system-wall-mounted-heat-version-white-xfxtdfr02zm-/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airfresh.va4
  - Hardware version: MW300
  - Firmware version: 1.4.6_1013

**Additional context**
Hi. I have XFXT01ZM. I use zhimi.airfresh.va2 model/ Work fine.
Today i am upgrade my fan to XFXTDFR02ZM.
With zhimi.airfresh.va2 setup work fine, but:
1. Temperature reading. Instead of 25.5, it shows 2.55. Point offset.
2. No heater control.

**Comment by syssi** [comment]
Thanks for your excellent report! The temperature issue can be fixed easily.

**Comment by syssi** [comment]
Could you describe the difference of both devices? Is the temperature property of both devices broken? Have both devices am heater?

**Comment by wisesokol** [comment]
temperature value is correct, only point shift. 
I forgot to write - the temperature is shown as 2.78000000000000002, instead of 27.8.
Control boards.
![IMG_2563_1](https://user-images.githubusercontent.com/48487551/89573726-bc29a900-d833-11ea-9d47-62a4d44b9a1d.JPG)
![IMG_1015](https://user-images.githubusercontent.com/48487551/89573731-bdf36c80-d833-11ea-97c1-248fafacd2f6.JPG)
Only new, XFXTDFR02ZM, have heater.

**Comment by wisesokol** [comment]
I can access the ubuntu server on my local network if necessary.

**Comment by rezmus** [comment]
var isVa4 = _miot.Device.model === 'zhimi.airfresh.va4';
var ptcStateProp = isVa4 ? 'ptc_state' : null;
var propsArr = ["power", "mode", "aqi", "temp_dec", "humidity", "co2", "f1_hour_used", "child_lock", "buzzer", "led_level", ptcStateProp];

var ptcValue = value === true ? "on" : "off";
_miot.Device.getDeviceWifi().callMethod('set_ptc_state', [ptcValue]).then(function (res) {

**Comment by syssi** [comment]
@wisesokol Could you provide the output/response of:

```
miiocli device --ip IP --token TOKEN raw_command get_prop "['power','temp_dec','aqi','average_aqi','co2','buzzer','child_lock','humidity','led_level','mode','motor1_speed','use_time','ntcT','app_extra','f1_hour_used','filter_life','f_hour','favorite_level','led','ptc_state']"
```

I want to know the raw values of "ptc_state" and "temp_dec".

**Comment by wisesokol** [comment]
osboxes@osboxes:~$ miiocli device --ip 192.168.1.78 --token deab99d2f17c06fa1ae5c80dd65eee39 raw_command get_prop "['power','temp_dec','aqi','average_aqi','co2','buzzer','child_lock','humidity','led_level','mode','motor1_speed','use_time','ntcT','app_extra','f1_hour_used','filter_life','f_hour','favorite_level','led','ptc_state']"
Running command raw_command
['on', 28.0, 1, 1, 1081, 'off', 'off', 40, 1, 'silent', 400, 510000, 34.1, None, 141, None]

**Comment by syssi** [comment]
This is the response of model va2 or va4? I looks like va2 because "ptc_state" is None.

**Comment by wisesokol** [comment]
va4. Now i use only va4 model.
I tried enabling PTC but the answer is the same.

**Comment by syssi** [comment]
Ah, the device cannot provide more than 15 properties per request. Please provide the response of:

```
miiocli device --ip IP --token TOKEN raw_command get_prop "['ntcT','app_extra','f1_hour_used','filter_life','f_hour','favorite_level','led','ptc_state']"
```

**Comment by wisesokol** [comment]
[33.53, None, 141, None, None, None, None, 'off']

**Comment by syssi** [comment]
Perfect!

**Comment by wisesokol** [comment]
By the way,
Fix zhimi.airfresh.va2 temperature #794

For va2 model- va2 integration is correct work. Temperature shows correct.

**Comment by rytilahti** [comment]
@wisesokol was the temperature already correct before that PR, i.e., it is just the va4 that is reporting the temperature differently?

**Comment by rezmus** [comment]
temp_dec: isVa4 ? this.state.temp_dec : this.state.temp_dec / 10,

**Comment by syssi** [comment]
I will update the PR.

**Comment by wisesokol** [comment]
Repeat.
For va2 model- va2 integration is correct work. Temperature shows correct.

**Comment by wisesokol** [comment]
Hi. 
Having problems with integration?
