### ISSUE TITLE
Unable to discover the device (zhimi.airpurifier.ma4)

### ISSUE THREAD

**Issue by poma** [rytilahti/python-miio#798]
**Describe the bug**
Unable to interact with device.

**Version information (please complete the following information):**
 - OS: **Ubuntu 18.04**
 - python-miio: **0.5.3**

**Device information:**
  - Model: Air Purifier 3
  - Hardware version: zhimi.airpurifier.ma4
  - Firmware version: 2.1.3.0022

**To Reproduce**
```bash
$ miiocli device --ip 172.16.*** --token *** info
Error: Unable to discover the device 172.16.***
```

- I verified that the device ip is correct
- I'm able to successfully ping this ip address
- My PC and the device are in the same subnet

Also tried doing this from a Mac (10.15.6, miio 0.5.3):

```bash
$ miiocli device --ip 172.16.*** --token *** info
ERROR:miio.miioprotocol:Got error when receiving: timed out
Error: No response from the device
```

**Comment by poma** [comment]
So how do I troubleshoot this?

**Comment by poma** [comment]
I tried to monitor network with wireshark and it looks like the device responds to handhakes:

```
> 21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
< 2131002000000000123d37c7000007c5ffffffffffffffffffffffffffffffff
```

**Comment by poma** [comment]
Found the reason: outdated token

When I used `-dd` switch I saw errors like `Unable to decrypt, returning raw bytes`, looks like this is a clear sign that token is incorrect

**Comment by rytilahti** [comment]
The `unable to decrypt` message also gets printed during the discovery process, normally the incorrect token causes `Got checksum error which indicates use of an invalid token` error. Are you sure that didn't happen?

Glad you got it working though!

**Comment by poma** [comment]
Nope, got only this one. It happened when miio received a response to
handshake
