### ISSUE TITLE
Xiaomi Mi Robot (viomivacuum), command stability

### ISSUE THREAD

**Issue by fs79** [rytilahti/python-miio#800]
**Describe the bug**
When you send commands it takes a while and sometimes you get a timeout. I solved this by sending the command up to 20 times. (_/usr/local/lib/python3.7/dist-packages/miio/device.py_ **retry_count=20**)
 When I send the move forward command with a duration of 15 seconds it seems the 15 secs start when the command is sent the 1st time to the vacuum cleaner. So if the command needs a while the bot won't move forward 15 secs. 
Possible to start the timer when the robot accepts the command?

**Version information (please complete the following information):**
 - OS: Linux, Python 2.7.16
 - python-miio: miiocli, version 0.5.3

**Device information:**
  - Model: Xiaomi Mi Robot Vacuum Mop Pro
Model: viomi.vacuum.v8
Hardware version: Linux
Firmware version: 3.5.3_0017

**To Reproduce**
miiocli viomivacuum --ip 10.0.*.* --token **1234** move forward --duration 15

**Expected behavior**
Device should start and move forward for the seconds give, p.e. 15 secondes

**Comment by rytilahti** [comment]
The miiocli doesn't keep a record of the recently used sequence ids which is the likely cause for this. I have had plans to consolidate the solution used by mirobo to miiocli, but I haven't found time to do that nor will I have in the near future.

So if anyone is interested on working on adding support for a device database/cache of sorts to the miiocli to fix this, all help is welcome!

**Comment by fs79** [comment]
Maybe related to this issue.
https://github.com/rytilahti/python-miio/issues/813

**Comment by rytilahti** [comment]
Yes, that's related. Only mirobo tool (which works only with rockrobo vacuums) does keep track of used sequence ids.
