### ISSUE TITLE
Nodejs package for mihome devices

### ISSUE THREAD

**Issue by maxinminax** [rytilahti/python-miio#801]
Hi everyone!

I have create a new nodejs package for control mihome device. You can found at: [https://www.npmjs.com/package/node-mihome](https://www.npmjs.com/package/node-mihome)
It's contain many useful feature, such as

- Implement miio protocol (LAN)
- Implement aqara protocol (for aqara/mi zigbee devices)
- Implement micloud protocol: you can login to view list devices and all info (deviceId, token, model...)
...

The package is in development, so welcome all issues and new devices request. I need more support. Thank for all!
Finally, I lo<3 MiHome

**Comment by rytilahti** [comment]
I wouldn't mind adding a list of related projects in the README (considering references can always be useful for someone who's trying to port a feature from library to another), but you should definitely add a comparison to your README describing how this relates (or differs) from aholestenson's miio library (https://github.com/aholstenson/miio) :-)

**Comment by maxinminax** [comment]
> I wouldn't mind adding a list of related projects in the README (considering references can always be useful for someone who's trying to port a feature from library to another), but you should definitely add a comparison to your README describing how this relates (or differs) from aholestenson's miio library (https://github.com/aholstenson/miio) :-)

Thank you!
I have update compare table in README ([https://github.com/maxinminax/node-mihome#compare-with-other-libraries](https://github.com/maxinminax/node-mihome#compare-with-other-libraries)) and add list supported devices too. Many thing to do and I'm going to
