### ISSUE TITLE
Retrieval of tokens from cloud

### ISSUE THREAD

**Issue by bugficks** [rytilahti/python-miio#810]
While trying to get tokens from cloud I've stumbled on:  
https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud  
and way later on:  
https://github.com/squachen/micloud
which seems to be a port of openhab binding.

When added to this lib it should put an end to that cumbersome token retrieval :)

**Comment by rytilahti** [comment]
Hi, I have commented on this in https://github.com/rytilahti/python-miio/issues/728#issuecomment-685967596
