### ISSUE TITLE
Freash air sistem calibration of CO2 sensor command

### ISSUE THREAD

**Issue by wisesokol** [rytilahti/python-miio#814]
**Is your feature request related to a problem? Please describe.**
Hi. This is not a problem

**Describe the solution you'd like**
Is it possible with python-miio to start calibration of the CO2 sensor (CM1106)? It is installed on XFXT01ZM and XFXTDFR02ZM. Perhaps on other xiaomi devices as well.

**Device information:**
zhimi.airfresh.va2
zhimi.airfresh.va4

  - Name(s) of the device: Xiaomi Smartmi Fresh Air System Wall Mountable
  - Link: https://4pda.ru/forum/index.php?showtopic=962736&st=1220

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airfresh.va4 and zhimi.airfresh.va2
  - Hardware version: MW300
  - Firmware version: 1.4.6_1013

**Additional context**
[CM1106+CO2+SENSOR+MODULE+INTRODUCTION.pdf](https://github.com/rytilahti/python-miio/files/5212377/CM1106%2BCO2%2BSENSOR%2BMODULE%2BINTRODUCTION.pdf)

**Comment by rytilahti** [comment]
If this functionality is available through the mi home app, it can definitely be added. One just has to figure out the command that needs to be sent to the device to make it perform that action. A good starting point to do that is https://github.com/aholstenson/miio/blob/master/docs/protocol.md .

**Comment by wisesokol** [comment]
Thanks. There is no such function in mihome. I close issue.
