### ISSUE TITLE
Calling message handler 'onHeartbeat'.

### ISSUE THREAD

**Issue by ebretteville** [rytilahti/python-miio#82]
Hye,
Don't know what title to give to this issue threzad so I just copy/paste the error message.

Python is intalled, token is found, but it's not working, find below the log from domoticz:

`2017-09-25 09:48:08.357 (nono) Poll: {"exception": ""} 2017-09-25 09:48:08.357 Error: (nono) Response mirobo-wrapper exception: 2017-09-25 09:48:08.358 PluginSystem: Starting I/O service thread. 2017-09-25 09:48:08.359 (nono) Calling message handler 'onHeartbeat'. 2017-09-25 09:48:30.964 (nono) Poll: {"exception": ""}`

My xiaomi robot is workinf fine through the mi home app and is called "nono".

Thanks for your help

**Comment by rytilahti** [comment]
Unfortunately there is no enough info (that is, nothing directly relevant to python-mirobo) in that log. Can you maybe enable the debug logging for the `mirobo` package somehow in domoticz? (`logging.getLogger("mirobo").setLevel(logging.DEBUG)` would probably work on the source code level, if there are no a specific way to do that)

**Comment by rytilahti** [comment]
Needs more input to do anything, so I'll close this for now.
