### ISSUE TITLE
Add  optional "Length" parameter to chuangmi_ir.py play_raw().  for "chuangmi.remote.v2" to send some command properly 

### ISSUE THREAD

**Issue by Dozku** [rytilahti/python-miio#820]
**Is your feature request related to a problem? Please describe.**
By soldering wire on TX0 and GND pins on the board then connecting them to TTL, the detail log can be seen using serial console(baud rate: 115200). The log contains TOKEN and all IR sent with details. 
From the log(sent via HA) , I realized the reason why learned AC commands is not working is because it is lack the "length" parameter 
![image](https://user-images.githubusercontent.com/1068096/93661212-99242300-fa88-11ea-886f-4044f9a1abda.png)

If "length" parameter is appended, then the IR for AC is working without any issue.(Tried via miiocli rawcommand)
![image](https://user-images.githubusercontent.com/1068096/93661428-4e0b0f80-fa8a-11ea-9783-1061848d5b9a.png)

**Describe the solution you'd like**
By adding the optional length parameter to the function, the HA xiaomi IR component can be quickly enhanced to support AC commands. 

PS. When sending IR command from Mi APP, the IR code/length/... will be shown on log; so basically all ir code supported by the Mi APP can be extracted.

**Device information:**
Model: chuangmi.remote.v2
Hardware version: esp32
Firmware version: 2.0.6_0006

I am not a good python programmer, so filing the issue and hoping someone good can implement it or provide a better soultion.

**Comment by mpsOxygen** [comment]
Hello,

Do you have any ideea how that length is being calculated? As I have not been able to trigger my AC by sending just the length of the b64 string.
