### ISSUE TITLE
Compatibility with Mr.Bond clothes dryer

### ISSUE THREAD

**Issue by abcjoint** [rytilahti/python-miio#835]
**Device information:**

  - Name(s) of the device: Mr Bond M1 pro Smart Clothes Dryer
  - Link: https://www.gizmochina.com/2018/08/29/xiaomis-mr-bond-m1-smart-clothes-dryer-goes-on-sale-for-1099-yuan-161/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: mrbond.airer.m1pro
  - Hardware version: esp32
  - Firmware version: 2.0.9

**Comment by ha0y** [comment]
If you are to use it in Home Assistant you may try https://github.com/ha0y/xiaomi_miot_raw .
