### ISSUE TITLE
Unsupported device (roborock-vacuum-s6)

### ISSUE THREAD

**Issue by vmarques** [rytilahti/python-miio#841]
WARNING:miio.discovery:Found unsupported device roborock-vacuum-s6_miio262049017._miio._udp.local. at 192.168.1.86, please report to developers

**Comment by rytilahti** [comment]
Could you check if `mirobo` or `miiocli vacuum` commands are working fine for you? If yes, it will be enough to create a patch to add this model to discovery to avoid this warning.

**Comment by vmarques** [comment]
Got this from mirobo, I suspect the token might be wrong,

` % mirobo discover --handshake 1                        
INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:  IP 192.168.1.89 (ID: 035a13eb) - token: b'00000000000000000000000000000000'
INFO:miio.miioprotocol:  IP 192.168.1.90 (ID: 04ffb621) - token: b'00000000000000000000000000000000'
INFO:miio.miioprotocol:  IP 192.168.1.86 (ID: 0f9e8cf9) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.miioprotocol:Discovery done`

**Comment by rytilahti** [comment]
The 3 taps trick is for the gateway token only, for other devices it has to be extracted from the device (https://python-miio.readthedocs.io/en/latest/discovery.html#tokens-from-mi-home-logs) or from the cloud (https://github.com/rytilahti/python-miio/issues/810).

**Comment by vmarques** [comment]
Well, I unleashed hell...
Trying to get the backup to extract the token from sqlite.

Using Mac Catalina, all iTunes tips are outdated, iPhone management moved to finder, and in my particular casse, not showing any of the options, buttons, I need to go to next steps. Filled supprot ticket to Apple.

**Comment by syssi** [comment]
Is your device supported of the mihome app? In this case you should use the cloud method.

**Comment by vmarques** [comment]
> Is your device supported of the mihome app? In this case you should use the cloud method.

Syssi, what do you men by "the cloud method"?

**Comment by syssi** [comment]
Try to use this client: https://github.com/squachen/micloud

**Comment by vmarques** [comment]
Got it! Thanks!!
