### ISSUE TITLE
Notify access support for MIoT Device

### ISSUE THREAD

**Issue by tiandeyu** [rytilahti/python-miio#843]
Hi
I'm developing a plugin for a miot based smart cover, the response for miot call is slow, so I can't get the current position in real-time. But I found there is a notify access in miot-spec-v2. How can we utilize these notify feature in miot?
```json
{
    "iid": 2,
    "type": "urn:miot-spec-v2:property:current-position:00000039:babai-bb82mj:1:0000C805",
    "description": "Current Position",
    "format": "uint8",
    "access": [
        "read",
        "notify"
    ],
    "unit": "percentage",
    "value-range": [
        0,
        100,
        1
    ]
}
```

**Comment by rytilahti** [comment]
The notifications are only send to the cloud (to my knowledge), so there is currently no way to utilize the notify feature.

**Comment by tiandeyu** [comment]
Thx for your reply. I found a document for notify call, send to the cloud when properties changed.
https://iot.mi.com/new/doc/embedded-development/wifi/serial-command-call
