### ISSUE TITLE
Get possible device commands/arguments via API

### ISSUE THREAD

**Issue by dominikkarall** [rytilahti/python-miio#846]
Hi,

I want to use python-miio via API. To always support all integrated devices I would like to do a generic integration where I would like to get all possible commands via API. Is that possible?

I found a way to get device type and the possible commands, but not the options:
```
for device_class in DeviceGroupMeta.device_classes:
    print(device_class.get_device_group().name + ", cmds: " + str(device_class.get_device_group().commands.keys()))
```

It would be great if you could provide an API to get all possible commands and options for a device. Thanks!

**Comment by rytilahti** [comment]
Hi,

how about using annotations (e.g., `Vacuum.add_timer.__annotations__`) which also contain the types where available? Another option could be using the `inspect` class, but annotations & docstrings are something I would personally use.

```
>>> from miio import Vacuum
>>> Vacuum.add_timer
<function Vacuum.add_timer at 0x7f33563f4040>
>>> Vacuum.add_timer.__annotations__
{'cron': <class 'str'>, 'command': <class 'str'>, 'parameters': <class 'str'>}
>>> Vacuum.add_timer.__doc__
'Add a timer.\n\n        :param cron: schedule in cron format\n        :param command: ignored by the vacuum.\n        :param parameters: ignored by the vacuum.'
```

**Comment by dominikkarall** [comment]
Thanks for the hint with annotations. I could finally manage to get everything I need via annotations. Find my implementation here:
https://github.com/dominikkarall/fhem_pythonbinding/blob/master/FHEM/bindings/python/lib/miio/miio.py#L34-L52

I'm using inspect to get all details of the function including parameters. There are still a few methods which don't use annotations for their parameters. I'm going to create PRs if I come across one.

**Comment by rytilahti** [comment]
Glad you got it working, PRs to add annotations are welcome! :-)

In the future, I think that the `Device` class should have introspection capabilities built-in, basically wrapping the annotation data (and `@command()` given information). Something like `commands()` giving a list of `CommandMeta` objects containing all the necessary information in a nice format to easily create dynamic UIs.
