### ISSUE TITLE
Xiaomi Smartmi Evaporation Air Humidifier 2 (zhimi.humidifier.ca4)

### ISSUE THREAD

**Issue by Ciubas** [rytilahti/python-miio#859]
Add to configuration.yaml:

`
fan:
 - platform: xiaomi_miio
    host: 192.168.0.208
    token: 39152_TOKEN_476fe3751
    name: Humidifier2
`

There is no error in log.

Here is it: 
https://github.com/rytilahti/python-miio/releases 

Here is not:
https://github.com/home-assistant/core/blob/df5a8c4dac7037edde99ff4e599a0cfce2f7e145/homeassistant/components/xiaomi_miio/fan.py

![image](https://user-images.githubusercontent.com/53171052/98913083-35860700-24c7-11eb-967b-8761f26c6fe2.png)

Someone forgot to add this here ;)

**Comment by rytilahti** [comment]
Please create an issue at homeassistant's bug tracker for the integration, assuming `miiocli airhumidifiermiot` command is working, this is not a bug in this project :-)

There is also a custom integration by @syssi which may be interesting for you until the official integration gets support for this device: https://github.com/syssi/xiaomi_airpurifier
