### ISSUE TITLE
Xiaomi Mi Robot Vacuum V1 - Fan Speed Issue

### ISSUE THREAD

**Issue by mat4444** [rytilahti/python-miio#860]
**Describe the bug**
This bug report is copied from https://github.com/home-assistant/core/issues/43196
With the Xiaomi Mi Robot Vacuum V1 running on FW 3.5.8_004018, the fan speed options (Silent, Standard, Medium, Turbo and Gentle) are not understood by the vacuum.
However, from Home Assistant, fan speed can be set with the set_fan_speed service using the following integer values:
Silent --> 38
Standard --> 60
Medium --> 75
Turbo --> 100
Gentle --> Not an option for this vacuum

**Version information (please complete the following information):**
- Platform: Raspberry Pi 3B+
- OS: Running on HomeAssistant 0.117.6 (HassOS 4.15)
- python-miio: version 0.5.3

**Device information:**
  - Model: Xiaomi Mi Robot Vacuum V1 (rockrobo.vacuum.v1)
  - Hardware version: Linux ?
  - Firmware version: 3.5.8_004018
(PS: the command line in your bug report template misses 'info' at the end of `miiocli device --ip <ip address> --token <token>`)

**To Reproduce**
Using Home Assistant, I try to change the fan speed of my vacuum (v1) using the built-in options (drop down list), but it does not  work. Nothing happens, there is no acknowledgment nor error message.
![image](https://user-images.githubusercontent.com/53400792/99148878-a1649d00-268a-11eb-9536-03673d69d19e.png)
However, I can use the set_fan_speed service with integer values to change the speed.

**Expected behavior**
The vacuum speed should be changeable by default, using the default options.

**Console output**
No error in Home Assistant log

**Comment by rytilahti** [comment]
So the issue is, that since 3.5.7 for the v1 changed the behavior in regards of fan speed, see https://github.com/home-assistant/core/issues/32723 and issues linked there (and in the fix pr). python-miio was adapted to check for the specific versions when v1 is detected (#643).

The logic is shown at https://github.com/rytilahti/python-miio/blob/master/miio/vacuum.py#L499 but I have no idea how to fix this without breaking anything. There are open questions like was the 100-105 format only temporary for the 3.5.7 series for v1, and could we remove the version detection?

For a quick fix, if you are not using the cloud functionality, simply block its internet access and it will start using the legacy speeds :-)

**Comment by mat4444** [comment]
Hello,
Thank you for your reply. 
I am probably missing something obvious, but I don't see why adding a FW check against version 3.5.8 would be a breaking change? It only requires creating a new fanspeedV3 class with the new values. It won't affect people who still have a vacuum with FW version  3.5.7.
Regarding the cloud functionality, how can I simply block the internet access? Is it an option in xiaomi home app, or should it be done at the router level?

**Comment by syssi** [comment]
On router level.

**Comment by rytilahti** [comment]
Hi, so the question is, is it only the firmware version 3.5.7 that has this different (100-105) fan speed setting, that is, can we use the v1 values on 3.5.8 (https://github.com/rytilahti/python-miio/blob/master/miio/vacuum.py#L55), or do we need a separate v3 for 3.5.8+? 

Also, did you get the values by changing the speed using the official app? They are only slightly off from the v1 values, so if those are the new official ones, maybe we indeed need a v3 mapping for that.

**Comment by mat4444** [comment]
Hi, it seems that fan speed values on firmware 3.5.8 are different from the V1 and V2 values. We would need a V3 set of values.
I got these values using the official Xiaomi app and checking the status of the vacuum in Home Assistant:
Silent = 38
Standard = 60
Turbo = 75
Max =100
They are indeed different from the V1 values

**Comment by raxpa** [comment]
Hi there I have the same issue in the v1 version is there any solution?

**Comment by rytilahti** [comment]
@mat4444 just to clarify the situation, the newer firmware versions only accept specific values (instead of percentages) as previously? So using `set_fan_speed` on homeassistant works fine with 38 (for silent), but trying to set it to 10 won't work?

If so, a PR to add this new set of speeds for those newer firmware versions would be appreciated!

**Comment by mat4444** [comment]
@rytilahti, yes, the new firmware only accept the specific values I mentioned above. A percentage value like 10 does not work.
I have created a branch for these minors modifications, but I have no idea how to test it on my system before creating the PR.
I am almost sure it would work, but better checking first. Can you please point indicate me how to check it ?
Thanks

**Comment by rytilahti** [comment]
Okay, so here's the place where the available fan speeds are decided: https://github.com/rytilahti/python-miio/blob/f481a9ef3c52b4c0dbc1b85936b94c4c8dabdaf7/miio/vacuum.py#L499

The best way to try it out is to execute `miiocli -d vacuum --ip 192.168.xxx.xxx --token xxxxxx fan_speed_presets` & adding unit tests for the fan speed detection for the following cases:
* Unable to query (fallback to old v1 values)
* v1 & firmware version == 3.5.7 = v2 enum
* v1 & firmware version > 3.5.7 = new enum for these fixed values

**Comment by mat4444** [comment]
I am not sure how to use the "fan_speed_presets" option with your command line tool. It only accepts integers.
Anyway, I have tested the updated code directly in HA by replacing the vacuum.py code and it works.
I have create PR #893 but it does not pass two checks. Would you mind having a look at it ?
Thanks!

**Comment by rytilahti** [comment]
Here's how it works on my vacuum:
```
$ miiocli vacuum --ip 192.168.xx.xx --token xxx fan_speed_presets
Running command fan_speed_presets
{'Silent': 38, 'Standard': 60, 'Medium': 77, 'Turbo': 90}
```

For the linting error, simply run `pre-commit run -a` in the directory to fix the issues and commit the changed files, then it should pass the CI checks, too!

**Comment by mat4444** [comment]
Sorry, but that's beyond my github knowledge. I don't know where to run this command. Should it be done locally on my PC ? Or can it be run directly on Github ? Sorry if it's a very dumb question, but I have very little knowledge of Github

**Comment by mat4444** [comment]
Hi, I tried to install some python packages on my PC to try the 'pre-commit' command, but nothing works ... I really don't know what is wrong with my syntax.
The update of the vacuum.py file is very basic. If you don't mind, could you add these lines yourself to your code ? 

line 70 :
```
class FanspeedV3(enum.Enum):
    Silent = 38
    Standard = 60
    Medium = 75
    Turbo = 100
```

line 504:
```
            if version >= (3, 5, 8):
                self._fanspeeds = FanspeedV3
            elif version == (3, 5, 7):
                self._fanspeeds = FanspeedV2
            else:
                self._fanspeeds = FanspeedV1
```

Thanks,
Mathieu

**Comment by rytilahti** [comment]
Hey Mathieu and thanks, I'll take a look at it at some point, unfortunately I'm very busy with other things at the moment so it may take some time to get to it.

Anyway, the simplest way with pre-commit would be the following:
```
(move to the source directory)
poetry install  # installs all the dependencies to a clean virtualenv
poetry run pre-commit run -a  # executes all precommit tests
(commit & push the changed files next)
```

**Comment by deluxestyle** [comment]
I updated manually the vacuum.py in my homeassistant installation and I can confirm that is now working
but I changed the fanspeed to following

`class FanspeedV3(enum.Enum):
    Silent = 38
    Standard = 60
    Turbo = 75
    Max = 100
`

**Comment by rytilahti** [comment]
There was some unnecessary whitespaces that made linting unhappy, I fixed it now. Thanks for the PR, @mat4444 ! :-)

**Comment by mat4444** [comment]
You're welcome ! Thanks for the commit, it honestly was beyond my knowledge with Github !
When can we expect to have this update in H.A ?

**Comment by rytilahti** [comment]
There is no real release schedule in this project, so it's unclear when there will be one. I won't be having any time to do preparations for that until some time in February (I'm not sure about @syssi), and it will still take some time from that until the homeassistant integration gets updated & released. So for the time being you may want to manually edit the file for your own setup :-)
