### ISSUE TITLE
Xiaomi Dishwasher (viomi.dishwasher.m02)

### ISSUE THREAD

**Issue by TheDJVG** [rytilahti/python-miio#874]
**Device information:**

  - Name(s) of the device: Mi Smart Dishwasher 4 sets
  - Link: https://www.mi.com/buy/detail?product_id=11624
  - Model: viomi.dishwasher.m02
  - Hardware version: esp8266
  - Firmware version: 2.1.0

**Additional context**
Hooked up a bus pirate to see what is being send over the wifi chip (conveniently there's place for a header on there) and it display all the possible properties.

### Information I know so far
Property: **programInfo**
- Shows all the available programs, my machine:
```
['0-7102-75|1-7702-75|2-1675-55|3-7522-75|4-6930-60|5-0-0|6-0-0|7-8295-75|8-0-0|9-0-0|248-1800-0|249-4198-75']
```
Based on this information the program's are defined by 3 sections, divided by a `-`.
The first one is the program number, I was able to match these with the programs in the app / on the device:
- 0: Standard
- 1: Eco
- 2: Quick
- 3: Intensive
- 4: Glassware
- 7: Sterilize

The other program(5, 6 ,8 ,9, 248 and 249) are not super clear to me. But I can imagine maybe this is for some factory tests?
For fun I started program 5 and the app sees it as "standard" and the timer always show "00:01" remaining.
When I start program 248 it seems to only run the dry cycle for 30 minutes (which I cannot test as my heating element is broken).

The second part is the total run time of the program in seconds with the last one being the temperature for the program.

Property: **program**
With this you see the current running program (or the last selected program).

You can set (and start) the program with the `set_program` command and a number from `programInfo` as argument. It will start immediately when called (if the door is open it will start when the door is closed).

Property: **wash_status**
Returns the current status of the dishwasher
- 0: Turned off 
- 1: Turn dishwasher on (or stop the current program)
- 2: Start or continue the current program
- 3: Pause the dishwasher

You can set the current status with the `set_wash_status` command and than an option as listed above.

Property: **wash_info** - Lots of unknowns!
Returns information about the current wash. Again divided by `-`

Example output: `['49-1440-2']`
The first number seems to be the seconds it's already running (in this case 49 seconds). The second part seems to be unknown to me, but _maybe_ it's the time when the process will change to the next step? The last part seems to be the current active program.

Property: **wash_process** - Lots of unknowns!
Returns information about the current status of the machine (e.g. what part of the program it's in).

States I've observed so far:
- 0: Standby
- 1: Prewash
- 2: Wash
- 3: Rinse
- 4: Drying

Property: **run_status**

As far as I can see this returns 0 when the door is closed and 128 when the door is open.

Property: **power**

The current status of the device with 1 being on and 0 being off.

You can turn the dishwasher on and off with the `set_power` command

Property: **left_time**
Returns the time in seconds that's left for the current program. 0 when no program is running or when it's finished.

Property: **wash_temp**
Current temperature inside the dishwasher in degrees celsius. Based on a 100k 25c NTC thermistor.

Property: **wash_done_appointment**
Returns information about the next scheduled run for the dishwasher. It's a timestamp in the machine's timezone.

You can set the next schedule by sending the `set_wash_done_appointment` command with `"<timestamp>,<program_number>"` (e.g: `"1606653301,1"`)

If you want to stop the schedule you have to send `"0,<program_number>"` where program number can be any program you want (it will not change to that program after cancelling it).  I could also send anything in place of that program_number when cancelling it.
**Important** to note is that you have to cancel the schedule first before you can schedule a new time. 

Property: **freshdry_interval**
This shows how often the machine should run the fan to refresh the air inside the machine. When it's disabled it shows `0`, when enabled through the app it's set to `8`. It's not clear if this is minutes or something else because I tried to set it to 1 and it didn't start after 1 minute. The maximum value is 255.

You can change the value by using the `set_freshdry_interval_t` command and sending an integer as argument.

Property: **child_lock**
Shows if the child lock is enabled `0` for disabled, `1` for enabled.

You can set this by using the `set_child_lock` command and `0` or `1` as argument.

### Other observations

**Getting properties in a list**
It seems that getting multiple properties with `get_prop` is supported but only if there's no spaces in the list of properties being requested.

This seems to work: `get_prop "wash_status","power"`
This does not work: `get prop "wash_status", "power"`

It looks like the miio cli converts the list to include spaces which causes the result to be:
```
Running command raw_command
[1, 'error']
```

**Internal communication**
It looks like the devices uses two boards to communicate. One with the wifi chip and user interface and the second one that actually executes the commands being sent by the first board. As I've found another RX/TX there I will see if I can get some useful information on the internal bus too (hack it to do even more things?).

**Device token**
The token is refreshed once you pair it again or change the Wireless connection information.

**Unknowns**
Would love to see if it's possible to execute a part of a program (dry for longer for example, but this could maybe be enforced by running program 249).

### Final words

I only spend time so far reverse engineering the properties and commands and did not start with the miio integration yet but would like to keep this issue for that specific work.

Feel free to let me know if you need anything specific tested. My machine is completely apart as the heater is broken so I don't mind probing around and get more information!

**Comment by syssi** [comment]
Good job! It looks like you are already aware of all features (methods & properties) of the device.

**Comment by TheDJVG** [comment]
Making some great progress. Will do some more cleanup of the code and prepare a PR.

Status:
```
Program: Quick
Program state: Prewash
Program time left: 1145
Dishwasher status: Running
Power status: On
Door: Closed
Temperature: 86
Schedule: None
Air refresh interval: 0
Child lock: Disabled
System status (raw): 512
Errors: [<SystemStatus.InsufficientWaterSoftener: 512>]
```

Commands:
```
  cancel_schedule  Cancel an existing schedule.
  child_lock       Set child lock.
  continue         Continue a program.
  info             Get miIO protocol information from the device.
  off              Power off.
  on               Power on.
  pause            Pause a program.
  raw_command      Send a raw command to the device.
  schedule         Schedule a program run.
  start            Start a program (with optional program or current).
  status           Retrieve properties.
  stop             Stop a program.
```

**Comment by Mr-Groch** [comment]
Hi!, After month of observations - wash_status is not complete. I have added missing values in commect to PR https://github.com/rytilahti/python-miio/pull/877/files#r567751125

wash_status = 4 for few minutes after washing is done (if you open offcial Xiaomi Mi Home App then, you will se Washing complete message)
wash_status = 6 when Auto Dry function is currently running (also then left_time will mean when Auto Dry will end)

**Comment by tyjtyj** [comment]
@TheDJVG, are we good to merge this ?

**Comment by tyjtyj** [comment]
@TheDJVG @rytilahti 

After a year waiting, can we merge this or at least release to basic function ? 

I willing to help

**Comment by TheDJVG** [comment]
Unfortunately I no longer have this dishwasher as the heating element failed and I couldn't source a replacement. Someone can take over this effort or I can close it.

**Comment by tyjtyj** [comment]
i dont even need to whole module just need to fill up this for home assistant 
Just need the wash status

sensor:
  - platform: xiaomi_miio_raw
    name: Any Xiaomi MiIO device
    host: 192.168.xx.xx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    # Optional and device specific config parameters
    sensor_property: 'wash_process'   <----?
    sensor_unit: ''
    default_properties_getter: 'get_prop'  <----?
    default_properties:  <----?

**Comment by rytilahti** [comment]
@tyjtyj I haven't ever used the raw integration, but you could try one of the properties listed here for `sensor_property`: https://github.com/rytilahti/python-miio/pull/877/files#diff-64cc86b0df83915bbf53a2b4eccc7492da8c92e4888e5f1067df9f2a08a39f2dR347

As the PR closing this issue requires only some minor style issues, I'll reopen this and finish the PR.
