### ISSUE TITLE
zhimi.heater.mc2 not fully supported

### ISSUE THREAD

**Issue by ee02217** [rytilahti/python-miio#880]
**Describe the bug**
zhimi.heater.mc2 is not fully supported.
Info command works correctly providing the below output:
`$ miiocli heater --ip 192.168.86.94 --token XXXXXXXXXXXXXX info
Model: zhimi.heater.mc2
Hardware version: esp32
Firmware version: 2.0.8
`
However, any other command results in error:
`$ miiocli heater --ip 192.168.86.94 --token XXXXXXXXXXXXXX on
Powering on
Error: {'code': -5001, 'message': 'command error'}`

**Version information (please complete the following information):**
 - OS: Ubuntu 20.04
 - python-miio: miiocli, version 0.5.4

**Device information:**
  - Model: zhimi.heater.mc2
  - Hardware version: esp32
  - Firmware version: 2.0.8

**To Reproduce**
1. run command: `miiocli heater --ip 192.168.86.94 --token XXXXXXXXXXXXXX on`

**Expected behavior**
Heater should turn on.

**Console output**
`Powering on
Error: {'code': -5001, 'message': 'command error'}
`

**Comment by ee02217** [comment]
It seems this should not be a bug, but a new feature, but I dont seem to be able to change that.

**Comment by syssi** [comment]
Miot specs: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-mc2:1

```
Service: siid 1: (Device Information): 4 props, 0 actions
  * Property piid: 1 (Device Manufacturer): (string, unit: None) (acc: ['read'], value-list: [], value-range: None)
  * Property piid: 2 (Device Model): (string, unit: None) (acc: ['read'], value-list: [], value-range: None)
  * Property piid: 3 (Device Serial Number): (string, unit: None) (acc: ['read'], value-list: [], value-range: None)
  * Property piid: 4 (Current Firmware Version): (string, unit: None) (acc: ['read'], value-list: [], value-range: None)
Service: siid 2: (Heater): 3 props, 0 actions
  * Property piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write', 'notify'], value-list: [], value-range: None)
  * Property piid: 2 (Device Fault): (uint8, unit: none) (acc: ['read', 'notify'], value-list: [], value-range: [0, 255, 1])
  * Property piid: 5 (Target Temperature): (float, unit: celsius) (acc: ['read', 'write', 'notify'], value-list: [], value-range: [18, 28, 1])
Service: siid 3: (Countdown): 1 props, 0 actions
  * Property piid: 1 (Countdown Time): (uint32, unit: hours) (acc: ['read', 'write', 'notify'], value-list: [], value-range: [0, 12, 1])
Service: siid 4: (Environment): 1 props, 0 actions
  * Property piid: 7 (Temperature): (float, unit: celsius) (acc: ['read', 'notify'], value-list: [], value-range: [-30, 100, 0.1])
Service: siid 5: (Physical Control Locked): 1 props, 0 actions
  * Property piid: 1 (Physical Control Locked): (bool, unit: None) (acc: ['read', 'write', 'notify'], value-list: [], value-range: None)
Service: siid 6: (Alarm): 1 props, 0 actions
  * Property piid: 1 (Alarm): (bool, unit: None) (acc: ['read', 'write', 'notify'], value-list: [], value-range: None)
Service: siid 7: (Indicator Light): 1 props, 0 actions
  * Property piid: 3 (Brightness): (uint8, unit: percentage) (acc: ['read', 'write', 'notify'], value-list: [], value-range: [0, 1, 1])
Service: siid 8: (私有服务): 4 props, 0 actions
  * Property piid: 1 (按键点击): (uint8, unit: none) (acc: ['notify'], value-list: [], value-range: [0, 4, 1])
  * Property piid: 8 (恒温功能使能): (bool, unit: none) (acc: ['read', 'notify', 'write'], value-list: [], value-range: None)
  * Property piid: 9 (用户使用时长): (uint32, unit: None) (acc: ['read', 'notify'], value-list: [], value-range: [0, 2147483647, 1])
  * Property piid: 10 (country-code): (int32, unit: none) (acc: ['read', 'notify'], value-list: [{'value': 0, 'description': '未知'}, {'value': 1, 'description': 'US, 美国'}, {'value': 82, 'description': 'KR,韩国'}, {'value': 44, 'description': 'EU,欧洲'}, {'value': 81, 'description': 'JP,日本'}, {'value': 7, 'description': 'RU，俄罗斯'}, {'value': 86, 'description': 'CN,中国'}, {'value': 852, 'description': '中国香港'}, {'value': 886, 'description': '中国台湾'}, {'value': 33, 'description': 'FR,法国'}], value-range: None)
  * Event eiid 1 (高温异常): (args: [])
  * Event eiid 2 (NTC 异常): (args: [])
  * Event eiid 3 (状态异常上报。 目前没必要实现): (args: [])
  * Event eiid 4 (eeprom 异常): (args: [])
  * Event eiid 5 (显示通信异常): (args: [])
  * Event eiid 6 (童锁状态下1s内多次连续触发次数，实现方式暂时存疑惑): (args: [])
```

**Comment by ee02217** [comment]
I can confirm that the below commands work:

`###READS###
# Get Target Temperature
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties '[{"piid":5,"siid":2}]' 


# Get Switch Status
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties '[{"piid":1,"siid":2}]' 


# Get fault
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties '[{"piid":2,"siid":2}]'

# Get Mode - ERRO
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties  '[{"piid":6,"siid":2}]'

# Get Environment
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties  '[{"piid":1,"siid":3}]'

# Get Temperature
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties  '[{"piid":7,"siid":4}]' 


# Get Physical Control Locked stauts 
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties '[{"piid":1,"siid":5}]' 

# Get Alarm stauts 
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command get_properties  '[{"piid":1,"siid":6}]' 


###UPDATES###
# Switch Status
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties  '[{"value":True,"siid":2,"piid":1}]'  

# Countdown
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":36000,"siid":3,"piid":1}]'    

# Switch Status
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":True,"siid":2,"piid":1}]'  

# Target Temperature
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":22,"siid":2,"piid":5}]' 

# Mode
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":1,"siid":2,"piid":6}]' 

# Physical Control Locked
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":True,"siid":5,"piid":1}]'

# Alarm
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":True,"siid":6,"piid":1}]'

# Indicator Light
miiocli device --ip <<IP>> --token <<TOKEN>> raw_command set_properties '[{"value":0,"siid":7,"piid":3}]' 
`

The problem is that it only works with raw_commands, not with heater device commands.

**Comment by syssi** [comment]
> The problem is that it only works with raw_commands, not with heater device commands.

This is fine because the `heater` implementation doesn't cover your device right now. I assume there will be a `heatermc2` parameter as soon your device is added.

**Comment by ee02217** [comment]
Great! Thank you for the feedback!
I'll be available for any testing, if needed :)

**Comment by rezmus** [comment]
heatermiot is better. already several models using miotspec (ma2, ma3, mc2, na1, nb1, za2, zb1).

**Comment by ee02217** [comment]
I'm not a developer, but I created a HeaterMiot.py that I tested and it works. If someone can create the pull request it would be great.

Apart from this new file, only a small edit to __init__ to include this new class.

`import enum
import logging
from datetime import timedelta
from typing import Any, Dict, Optional

import click

from .airfilter_util import FilterType, FilterTypeUtil
from .click_common import EnumType, command, format_output
from .exceptions import DeviceException
from .miot_device import MiotDevice

## DEVICE Model: zhimi.heater.mc2
_LOGGER = logging.getLogger(__name__)
_MAPPING = {
    # Heater (siid=2)
    "power": {"siid": 2, "piid": 1},
    "target_temperature": {"siid": 2, "piid": 5},
    "device_fault": {"siid": 2, "piid": 2},
    # Countdown (siid=3)
    "countdown_time": {"siid": 3, "piid": 1},
            ## "value-range": [0, 12, 1]
    # Environment (siid=4)
    "temperature": {"siid": 4, "piid": 7},
            ## "unit": "celsius", "value-range": [-30, 100, 0.1]
    # Physical Control Locked (siid=5)
    "child_lock": {"siid": 5, "piid": 1},            
    # Alarm (siid=6)
    "alarm": {"siid": 6, "piid": 1},
    # Indicator Light (siid=7)
    "led_brightness": {"siid": 7, "piid": 3},
        #     Bright = 0, Dim = 1, Off = 2
    # Private service (siid=8)
    "constant_temperature": {"siid": 8, "piid": 8},
    "user_usage_time": {"siid": 8, "piid": 9},
    "country_code": {"siid": 8, "piid": 10},
}



class HeaterMiotException(DeviceException):
    pass



class LedBrightness(enum.Enum):
    Off = 0
    Dim = 1
    Bright = 2

class OperationMode(enum.Enum):
    Cool = 2
    Dry = 3
    Fan = 4
    Heat = 5


class FanSpeed(enum.Enum):
    Auto = 0
    Level1 = 1
    Level2 = 2
    Level3 = 3
    Level4 = 4
    Level5 = 5
    Level6 = 6
    Level7 = 7


# class TimerStatus:
#     def __init__(self, status):
#         """
#         Countdown timer indicator.
#         Value format: <int>,<int>,<int>,<int>
#         Integer 1: whether the timer is enabled.
#         Integer 2: countdown timer setting value in minutes.
#         Integer 3: the device would be powered on (1) or powered off (0) after timeout.
#         Integer 4: the remaining countdown time in minutes.
#         Example timer value 1: 1,120,0,103
#         indicates the device would be turned off after 120 minutes, remaining 103 minutes.
#         Example timer value 2: 1,60,1,60
#         indicates the device would be turned on after 60 minutes, remaining 60 minutes.
#         Example timer value 3: 0,0,0,0
#         indicates countdown timer not set.
#         Write the first three integers would set the correct countdown timer.
#         Also, if the countdown minutes set to 0, the timer would be disabled.
#         """
#         self.status = [int(value) for value in status.split(",")]

#     @property
#     def enabled(self) -> bool:
#         return bool(self.status[0])

#     @property
#     def countdown(self) -> timedelta:
#         return timedelta(minutes=self.status[1])

#     @property
#     def power_on(self) -> bool:
#         return bool(self.status[2])

#     @property
#     def time_left(self) -> timedelta:
#         return timedelta(minutes=self.status[3])

#     def __repr__(self) -> str:
#         s = (
#             "<TimerStatus enabled=%s, "
#             "countdown=%s, "
#             "power_on=%s, "
#             "time_left=%s>"
#             % (self.enabled, self.countdown, self.power_on, self.time_left)
#         )
#         return s


class HeaterMiotStatus:
    """Container for status reports from the air conditioner which uses MIoT protocol."""

    def __init__(self, data: Dict[str, Any]) -> None:
        """
        Response (MIoT format) of a Mi Smart Space Heater (zhimi.heater.mc2)
        [
            #### TO DO
            {'did': 'power', 'siid': 2, 'piid': 1, 'code': 0, 'value': False},
            {'did': 'mode', 'siid': 2, 'piid': 2, 'code': 0, 'value': 2},
            {'did': 'target_temperature', 'siid': 2, 'piid': 4, 'code': 0, 'value': 26.5},
            {'did': 'eco', 'siid': 2, 'piid': 7, 'code': 0, 'value': False},
            {'did': 'heater', 'siid': 2, 'piid': 9, 'code': 0, 'value': True},
            {'did': 'dryer', 'siid': 2, 'piid': 10, 'code': 0, 'value': True},
            {'did': 'sleep_mode', 'siid': 2, 'piid': 11, 'code': 0, 'value': False},
            {'did': 'fan_speed', 'siid': 3, 'piid': 2, 'code': 0, 'value': 0},
            {'did': 'vertical_swing', 'siid': 3, 'piid': 4, 'code': 0, 'value': True},
            {'did': 'temperature', 'siid': 4, 'piid': 7, 'code': 0, 'value': 28.4},
            {'did': 'buzzer', 'siid': 5, 'piid': 1, 'code': 0, 'value': False},
            {'did': 'led', 'siid': 6, 'piid': 1, 'code': 0, 'value': False},
            {'did': 'electricity', 'siid': 8, 'piid': 1, 'code': 0, 'value': 0.0},
            {'did': 'clean', 'siid': 9, 'piid': 1, 'code': 0, 'value': '0,100,1,1'},
            {'did': 'running_duration', 'siid': 9, 'piid': 5, 'code': 0, 'value': 151.0},
            {'did': 'fan_speed_percent', 'siid': 10, 'piid': 1, 'code': 0, 'value': 101},
            {'did': 'timer', 'siid': 10, 'piid': 3, 'code': 0, 'value': '0,0,0,0'}
        ]
        """
        self.data = data

    @property
    def is_on(self) -> bool:
        """True if the device is turned on."""
        return self.data["power"]

    @property
    def power(self) -> str:
        """Current power state."""
        return "on" if self.is_on else "off"



    @property
    def target_temperature(self) -> float:
        """Target temperature in Celsius."""
        return self.data["target_temperature"]


    @property
    def temperature(self) -> float:
        """Current ambient temperature in Celsius."""
        return self.data["temperature"]

    @property
    def device_fault(self) -> float:
        """Device Faults"""
        return self.data["device_fault"]

    @property
    def countdown_time(self) -> int:
        """Countdown Time"""
        return self.data["countdown_time"]

    @property
    def child_lock(self) -> bool:
        """Child Lock"""
        return self.data["child_lock"]

    @property
    def constant_temperature(self) -> bool:
        """Constant Temperature"""
        return self.data["constant_temperature"]

    @property
    def alarm(self) -> bool:
        """Alarm"""
        return self.data["alarm"]

    @property
    def country_code(self) -> int:
        """Country Code"""
        return self.data["country_code"]

    @property
    def led_brightness(self) -> Optional[LedBrightness]:
        """Return brightness of the LED."""

        if self.data["led_brightness"] is not None:
            try:
                return LedBrightness(self.data["led_brightness"])
            except ValueError as e:
                _LOGGER.exception("Cannot parse led_brightness: %s", e)
                return None

        return None


        ## TO DO
    @property
    def user_usage_time(self) -> timedelta:
        """Total running duration in hours."""
        return timedelta(hours=self.data["user_usage_time"])



 

    def __repr__(self) -> str:
        s = (
            "<HeaterMiotStatus power=%s, "
            "target_temperature=%s, "
            "device_fault=%s, "
            "countdown_time=%s, "
            "temperature=%s, "
            "child_lock=%s, "
            "alarm=%s, "
            "led_brightness=%s, "
            "constant_temperature=%s, "
            "user_usage_time=%s, "
            "country_code=%s"
            % (
                self.power,
                self.target_temperature,
                self.device_fault,
                self.countdown_time,
                self.temperature,
                self.child_lock,
                self.alarm,
                self.led_brightness,
                self.constant_temperature,
                self.user_usage_time,
                self.country_code,                
            )
        )
        return s

    def __json__(self):
        return self.data


class HeaterMiot(MiotDevice):
    """Main class representing the air conditioner which uses MIoT protocol."""

    def __init__(
        self,
        ip: str = None,
        token: str = None,
        start_id: int = 0,
        debug: int = 0,
        lazy_discover: bool = True,
    ) -> None:
        super().__init__(_MAPPING, ip, token, start_id, debug, lazy_discover)

    @command(
        default_output=format_output(
            "",
            "Power: {result.power}\n"
            "Target Temperature: {result.target_temperature} C\n"
            "Device Fault: {result.device_fault}\n"
            "Countdown Time: {result.countdown_time}\n"
            "Room Temperature: {result.temperature} C\n"
            "Child Lock: {result.child_lock}\n"
            "Alarm: {result.alarm}\n"
            "Led Brightness: {result.led_brightness}\n"
            "Constant Temperature: {result.constant_temperature}\n"
            "User Usage Time: {result.user_usage_time}\n"
            "Country Code: {result.country_code}\n",
        )
    )
    def status(self) -> HeaterMiotStatus:
        """Retrieve properties."""

        return HeaterMiotStatus(
            {
                prop["did"]: prop["value"] if prop["code"] == 0 else None
                for prop in self.get_properties_for_mapping()
            }
        )

    @command(default_output=format_output("Powering on"))
    def on(self):
        """Power on."""
        return self.set_property("power", True)

    @command(default_output=format_output("Powering off"))
    def off(self):
        """Power off."""
        return self.set_property("power", False)


    @command(
        click.argument("target_temperature", type=float),
        default_output=format_output(
            "Setting target temperature to {target_temperature}"
        ),
    )
    def set_target_temperature(self, target_temperature: float):
        """Set target temperature in Celsius."""
        if (
            target_temperature < 18.0
            or target_temperature > 28.0
            or target_temperature % 0.5 != 0
        ):
            raise HeaterMiotException(
                "Invalid target temperature: %s" % target_temperature
            )
        return self.set_property("target_temperature", target_temperature)


    @command(
        click.argument("countdown_time", type=int),
        default_output=format_output(
            "Setting timmer to {countdown_time} hours"
        ),
    )

    @command(
        click.argument("child_lock", type=bool),
        default_output=format_output(
            "Setting child lock {countdown_time} "
        ),
    )


    @command(
        click.argument("brightness", type=EnumType(LedBrightness)),
        default_output=format_output("Setting LED brightness to {brightness}"),
    )
    def set_led_brightness(self, brightness: LedBrightness):
        """Set led brightness."""
        return self.set_property("led_brightness", brightness.value)


    @command(
        click.argument("hours", type=int),
        click.argument("delay_on", type=bool),
        default_output=format_output(
            lambda hours, delay_on: "Setting timer to delay on after "
            + str(hours)
            + " hours"
            if delay_on
            else "Setting timer to delay off after " + str(hours) + " hours"
        ),
    )
    def set_timer(self, hours, delay_on):
        """
        Set countdown timer hours and if it would be turned on after timeout.
        Set hours to 0 would disable the timer.
        """
        return self.set_property(
            "countdown_time", ",".join(["1", str(hours), str(int(delay_on))])
        )
`

**Comment by myrayearth** [comment]
Thank you for your analysis.
Successfully controlled raw_command through Miiocli.

If you want to use this file (HeaterMiot.py) on your home Assistant, see the
Can you tell me what to do?
I am using Home Assistant based on Docker.

**Comment by myrayearth** [comment]
> I'm not a developer, but I created a HeaterMiot.py that I tested and it works. If someone can create the pull request it would be great.
> 
Thank you for your analysis.
Successfully controlled raw_command through Miiocli.

If you want to use this file (HeaterMiot.py) on your home Assistant, see the
Can you tell me what to do?
I am using Home Assistant based on Docker.

**Comment by ee02217** [comment]
> If you want to use this file (HeaterMiot.py) on your home Assistant, see the
> Can you tell me what to do?

I can’t really understand if you missed some text there. 
I would love to integrate this in home assistant , but I have no idea how... :(

**Comment by mouth4war** [comment]
Off topic but there is a custom component
https://github.com/sunfang1cn/homeassistant-mi-heater

**Comment by ee02217** [comment]
It doesn’t support this device. And people are saying it doesn’t work anymore :(

**Comment by mouth4war** [comment]
This fork works https://github.com/gaussian8/homeassistant-mi-heater for
two heater models. It uses raw miio commands AFAIK.

**Comment by failover88** [comment]
Through,

`miiocli device --ip 192.168.1.82 --token 32CHARTOKEN raw_command get_properties '[{"piid":5,"siid":2}]'`

I got,

> Running command raw_command
> ERROR:miio.miioprotocol:Got error when receiving: timed out

I have run other raw_command's like several users here, but same result.

[The device token is the right one, got while it was in AP mode through _Packet Sender_.](https://fcabritablog.wordpress.com/2020/12/15/how-to-get-mi-smart-space-heater-s-token-the-easiest-way/)

Specs:
- python-miio version: 0.5.4
- zhmi.heater.mc2 version: 2.0.8.0003

**Comment by rezmus** [comment]
token changes each time your device connects to wifi (is paired). token from ap mode is useless after bind.

**Comment by failover88** [comment]
> token changes each time your device connects to wifi (is paired). token from ap mode is useless after bind.

What method do you recommend to get that token after paired?

**Comment by syssi** [comment]
There are some xiaomi cloud clients which can retrieve all tokens of your mihome account from the cloud.

**Comment by ee02217** [comment]
Easiest option IMHO:
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

**Comment by bafonins** [comment]
Added support for this heater in https://github.com/rytilahti/python-miio/pull/895

**Comment by bafonins** [comment]
@rytilahti Can we close this as support for this device was merged in https://github.com/rytilahti/python-miio/pull/895 ?

**Comment by syssi** [comment]
Yes. Let's close this issue. The device is supported now. Thanks!
