### ISSUE TITLE
Smartmi Radiant Heater smart version .za2 does not work

### ISSUE THREAD

**Issue by IgorAkimenko** [rytilahti/python-miio#886]
Smartmi Radiant Heater smart version .za2 does not work.
miocli heater -ip 192.168.1.112 -token aaaaaaaaaaaaaaaa off
Powering off...
{'code': -5001, 'message': 'command error'}

if using raw_command:
{'code': -9999, 'message': 'user ack timeout'}

Sorry my bad english. Help me pls.

**Comment by rytilahti** [comment]
Use `miiocli heatermiot` instead of heater and it should work!
