### ISSUE TITLE
Support for Xiaomi Air purifier 3C

### ISSUE THREAD

**Issue by arturdobo** [rytilahti/python-miio#888]
**Device information:**

  - Name(s) of the device: Xiaomi Air purifier 3C

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.airpurifier.mb4
  - Hardware version: esp32
  - Firmware version: 2.0.8

**Additional context**

After a quick investigation, it looks like the [specification](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4:2) for Xiaomi Air purifier 3C is a little bit different than the one used currently for air purifiers and only a few of properties match. As a result, it causes `-4005` code on the majority of fields. 

I could prepare some PR to solve that issue, but I'm new in this area and I'd like to confirm whether the way the similar issue has been resolved [here](https://github.com/rytilahti/python-miio/blob/master/miio/fan_miot.py#L14) is a good way to follow?

**Comment by arturdobo** [comment]
Air Purifier 3C supports only a subset of current features declared in `AirPurifierMiot`. The model needs to be split into two separated ones I believe but I'd like to consult whether my proposal I started work on https://github.com/arturdobo/python-miio/commit/6c911e37d1005f9235fa5d3c6856655d40e4263d  is something acceptable or not. If not, could you give me some idea of how to do this? And more thing, I'm not a Python developer, so I don't if my code is idiomatic or not 😛

**Comment by arturdobo** [comment]
Because of no feedback for 3 weeks, I created https://github.com/rytilahti/python-miio/pull/899 for that change

**Comment by calas80** [comment]
Hi,

I have this device, I am very much waiting for an update.

Thanks for this pluging.

**Comment by rytilahti** [comment]
This has been implemented in #899, thanks to @arturdobo! :tada:
