### ISSUE TITLE
viomi.heater.vxtj01 support

### ISSUE THREAD

**Issue by aalbul** [rytilahti/python-miio#889]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device:
Viomi Kick-Line heater Pro
  - Link:
https://www.banggood.com/VIOMI-Internet-Baseboard-Electric-Heater-Pro-Remote-Infrared-Remote-Control-2200W-24-hour-Timing-for-Home-Office-p-1602723.html?akmClientCountry=NL&cur_warehouse=CN

Use `miiocli device --ip <ip address> --token <token> info`.

  - Model: viomi.heater.vxtj01
  - Hardware version: esp8266
  - Firmware version: 2.1.0

**Additional context**

I am a 'happy' owner of this device. I spent some time today trying to make it work with miiocli, but every time I execute:

`miiocli device --ip 192.168.2.190 --token a405643e7dffd6a6xxxxxxxx00 raw_command get_prop`

i'm getting:

`Error: {'code': -9998, 'message': 'user ack invalid'}`

I think it is not related to the token, because if I change it a bit (say changing last 0 to 1) then I cannot even get info about the device.

I Will be happy to follow your instructions/ideas and help to add its support to this beautiful tool.

P.S.: Spec can be found here: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:viomi-vxtj01:1 (leaving it here for myself mainly :))

**Comment by rezmus** [comment]
use miot commands according to spec json.

**Comment by aalbul** [comment]
Unfortunately, i didn't manage to find the way how to do that :(
Could you please point me in the right direction by giving some example?

**Comment by IhorSyerkov** [comment]
```miiocli device --ip <ip> --token <token> raw_command get_prop '[{ "did": "comand_name", "siid": 1, "piid": 1, "code": 0}]'```
siid == service.iid
piid == property.iid
if you want to set value use 
```miiocli device --ip <ip> --token <token> raw_command set_prop '[{ "did": "comand_name", "siid": 1, "piid": 1, "value": <value_to_set>, "code": 0}]'```

P.S. Will add it to the docs

**Comment by IhorSyerkov** [comment]
Or take a look in `python-miio/miio/heater.py` file there common properties for heater, maybe it will work you
