### ISSUE TITLE
ServiceInfo has no attribute 'address' in miio/discovery

### ISSUE THREAD

**Issue by gudvinr** [rytilahti/python-miio#891]
**Describe the bug**

When I run `mirobo discover` it fails with an error.

**Version information (please complete the following information):**
 - OS: Linux
 - python-miio: 0.5.4 (latest from PIP atm)

**To Reproduce**
1. run `mirobo discover`

**Expected behavior**
Getting a list of discovered devices

**Console output**
```
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
Exception in thread zeroconf-ServiceBrowser__miio._udp.local._229705:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python3.9/site-packages/zeroconf/__init__.py", line 1750, in run
    self._service_state_changed.fire(
  File "/home/user/.local/lib/python3.9/site-packages/zeroconf/__init__.py", line 1508, in fire
    h(**kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/zeroconf/__init__.py", line 1606, in on_change
    listener.add_service(*args)
  File "/home/user/.local/lib/python3.9/site-packages/miio/discovery.py", line 256, in add_service
    addr = str(ipaddress.ip_address(info.address))
AttributeError: 'ServiceInfo' object has no attribute 'address'
```

**Comment by elpaso666** [comment]
I have same issue.

**Comment by ulope** [comment]
Same issue.

It seems the `info` object doesn't have an `address` member but rather `addresses` which is a list of addresses.

**Comment by LukaszLapaj** [comment]
Same issue.

**Comment by rytilahti** [comment]
Looks like the used mdns library changed their API at some point, the simple solution would be making a check if `addresses` exist, and fallback to using `address` to keep backwards compatibility. If someone wants to work on that, feel free to create a PR to do that! :-)

**Comment by gudvinr** [comment]
@rytilahti can't you just pin mdns library version or stick to new `addresses` field? It was done in [this](https://github.com/jstasiak/python-zeroconf/pull/260) PR and probably was a part of 0.27.0 release.

**Comment by rytilahti** [comment]
@gudvinr fair enough, I suppose porting to use the new API is the way to fix this. I don't usually like breaking something for users who may have previous versions, but as this only affects the discovery I think it's fine.

**Comment by ulope** [comment]
A tool like this should always be installed into its own virtualenv anyway.
A good helper for that is [pipx](https://pipxproject.github.io/pipx/)

**Comment by rytilahti** [comment]
The problem is, this project is not only for the tool but also for the underlying, fairly widely used (homeassistant, maybe others?) python library. Homeassistant has its own hard dependency pinnings (currently 0.28.7), but this won't be a problem for them, so I'll just merge the linked PR.

**Comment by gcamaraomarques** [comment]
Hi @rytilahti,

Any plans to release this fix? I just installed the tool and I am getting the same error.

**Comment by rytilahti** [comment]
Hi @gcamaraomarques, sorry for the delay! I'll do a new release this week, you can follow #969 which will get closed when new release gets made.

**Comment by gcamaraomarques** [comment]
No problem at all. It is free and open-source. I just asked because it is already on master.

Thank you
