### ISSUE TITLE
Miiocli and Airdog appliance

### ISSUE THREAD

**Issue by lekxfr** [rytilahti/python-miio#892]
Hi, 
Thank you for your big work! It's tremendous. 

I've got a Chinese air dog air purifier. 
When I make a miiocli device info, I've got this datas:
Info Model: airdog.airpurifier.x5
Hardware version: ESP8266
Firmware version: 1.3.5_0005

But I do not succeed in controlling the appliance with miiocli commands. Any advise? 
Thanks

**Comment by rytilahti** [comment]
Did you try any of the commends shown in ```miiocli airdogx3 --help```?
