### ISSUE TITLE
airhumidifier_miot.py - mapping attribute error

### ISSUE THREAD

**Issue by tierman** [rytilahti/python-miio#911]
Hi,
now i get error like: AttributeError: 'AirHumidifierMiotStatus' object has no attribute 'fault'.

To resolve it, please change in airhumidifier_miot.py:
line 83 from  `def error(self)` -> int:  to  `def fault(self) -> int:`
line 231 from `self.error` to `self.fault`
line 210 from `"<AirHumidifierMiotStatus"` to `"<AirHumidifierMiotStatus "` <- only space.

Best regards
Tomek.

**Comment by rytilahti** [comment]
This got fixed in #909 earlier today, thanks for reporting though :-)

**Comment by syssi** [comment]
The issue looks like a follow-up. @tierman this library doesn't access AirHumidifierMiotStatus.fault anywhre. We are calling the property `AirHumidifierMiotStatus.error`. Which implementation expects the `fault` property?

**Comment by tierman** [comment]
@syssi This is my fault. I tried to use Yours library with https://github.com/develop-dvs/domoticz-AirHumidifier2. But there are many problems with new Xiaomi airhumidifier and domoticz library. One of them seemed to be a bug in yours library - but doesn't. 
Now i try to write domoticz plugin to cooperate with xiaomi airhumidifier using your lib.

I am a Java developer and new to Python. Sorry for my incorrect issue report.

**Comment by syssi** [comment]
No problem! Good luck!
