### ISSUE TITLE
[Roborock S6 MaxV] Need a delay between pause and charge commands to return to dock

### ISSUE THREAD

**Issue by stephalltricks** [rytilahti/python-miio#918]
https://github.com/rytilahti/python-miio/blob/5730f535d4691e0c2b4260cd7835b7a43ddc8ab0/miio/vacuum.py#L145:L148

When my Roborock S6 is running, if I run the "home" function, it only makes it pause. I need to run the "home" function a second time to make it go to base.

It needs a delay bewteen the "app_pause" and the "app_charge" commands.

**Comment by rytilahti** [comment]
Could you try modifying your local instance to skip the `app_pause` completely to see if that works on that device? Adding a very short pause would be fine, I suppose, but how long should that be?

**Comment by stephalltricks** [comment]
Hello @rytilahti 
You're right, if I remove app_pause completely it works!

**Comment by rytilahti** [comment]
Okay, great! I think we can do a similar handling as with `fan_speed_presets` and change the behavior of that command depending on the detected device model.

I'd still like to hear some results from people using other devices (besides gen1 vacuums), maybe it's only gen1 that requires pausing prior to asking it to return.

**Comment by stephanerosi** [comment]
For your information, I've run a few more tests :

il add an app_stop (instead of app_pause) : same problem
if I add a delay of 1sec between app_pause and app_charge : it works

**Comment by rytilahti** [comment]
Thanks for your tests @stephanerosi, the linked PR adds a special handling for `roborock.vacuum.a10`, feel free to test it out before it gets merged :-)

**Comment by stephanerosi** [comment]
Just checked out locally and tested.
Works perfectly !
