### ISSUE TITLE
Support for Mi Smart Standing Fan Pro EU/Global (dmaker.fan.p15)

### ISSUE THREAD

**Issue by sjdvda** [rytilahti/python-miio#920]
**Device information:**

  - Name(s) of the device: Mi Smart Standing Fan Pro EU/Global
  - Link: https://www.powerplanetonline.com/xiaomi-mi-smart-standing-fan-pro

  - Model: dmaker.fan.p15
  - Hardware version: esp8266
  - Firmware version: 2.0.7

**Additional context**
Seems to be the global version of dmaker.fan.p11 - I am able to control it with miiocli fanp11 [OPTIONS] command [ARGS]
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p15:1

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/12#issuecomment-770413469
