### ISSUE TITLE
Add support of new device Mi Smart Evaporative Humidifer (deerma.humidifier.jsq4)

### ISSUE THREAD

**Issue by minskmail** [rytilahti/python-miio#922]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Mi Smart Evaporative Humidifer
  - Link: https://github.com/syssi/xiaomi_airpurifier/issues/109

Use `miiocli device --ip <ip address> --token <token>`.

Model: deerma.humidifier.jsq4
Hardware version: RTL8720C
Firmware version: 2.0.3.0006

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by rytilahti** [comment]
`miiocli genericmiot` should support all miot devices directly, so I'll close this now.
