### ISSUE TITLE
Connecting from external network

### ISSUE THREAD

**Issue by Moh-Snoussi** [rytilahti/python-miio#931]
**Is it possible to send command from external network?**

I am able to control the Vacuum on My Local Machine using 
`miiocli dreamevacuum --ip 192.168.** --token 4****** info
`

but the same does not work from an external network.

**Device information:**

  - Model: dreame.vacuum.mc1808

**Context**

I am creating a website and Alexa skill where users can add named zone and configure their dimensions.
the application work locally but not on server and it will be very nice if this will be possible.

**Comment by rytilahti** [comment]
No, it won't likely work without something proxying the connection, and it is not a good idea to expose these devices directly to the Internet anyway.

You will want to have the backend doing the communication with the device, and your web frontend communicating with that backend. I'm closing this as it is not really something this library is designed to do.
