### ISSUE TITLE
No air quality value when aqi is 1

### ISSUE THREAD

**Issue by exelban** [rytilahti/python-miio#958]
Hi.
I'm trying to get air quality from my Xiaomi Air purifier 3C. 
And from time to time I see None value in the `aqi`. I figured out that it's happening when `aqi==1`.

The reason is in this if: https://github.com/rytilahti/python-miio/blob/dfda13edb8bcfd844b2e1f2d7d7374a9a0709ac6/miio/airpurifier_miot.py#L105-L112
PR #930

Does `zhimi.airpurifier.mb4` (and any non `zhimi-airpurifier-mb3`) return 1 when the air quality read was unsuccessful?

Mi Home shows `pm2.5==1`. So I suppose for my model `zhimi.airpurifier.mb4` 1 it's a normal read.

**Device information:**
  - Model: Xiaomi Air purifier 3C (`zhimi.airpurifier.mb4`)

**Comment by rytilahti** [comment]
If you are using homeassistant, check out the historical graph to see if it makes sense that it would be 1. Otherwise, save the data over some time period on see if the values make sense. In the screenshot in #925 you can clearly see that the 1 is not a real measurement.

**Comment by exelban** [comment]
Thanks for the response. 
I'm not using homeassistant. I will try to collect the data and share the results. 
I spend a few days playing with `python-miio` and this purifier. And pretty sure that 1 is a normal read for this model.

**Comment by nefsolive** [comment]
@exelban i see the same, 1 ppm! You are using domoticz?
Sometimes i see 0 ppm and  1ppm! 
Did you still have this values? Im using 3C too.

**Comment by exelban** [comment]
Hi. Nope, I do not use any solution (HA or domoticz). I have my own scripts.
I save data from last week in the influx. And there is a chart of `aqi`.
![Zrzut ekranu 2021-03-30 o 20 29 08](https://user-images.githubusercontent.com/13332412/113038289-a6883b80-9196-11eb-9867-e15f290438bb.png)

Truly, It does not look like 1 is an unsuccessful read. Because the chart looks quite normal. There were a few drops to `1`. But also a few to `3` or `4`. PS: read every 30 min.

I will increase sampling to 1 min for next week. And share the result after.

**Comment by nefsolive** [comment]
Thank u for share the results!
On domoticz i just see the value 1ppm on graph, but it as soon for a test, i just install plugin about 5 days ago and few houres day take ON! 
Maybe its normal 1, but i need more time for make sure!

**Comment by rytilahti** [comment]
Looking at that graph, to me it seems very suspicious that the AQI is first around 15-20 and suddenly drops near to zero for a single measurement (around the third timestamp label) and continues to raise afterwards. Likewise the long period of near zero between 5th and 6th looks odd when considering the whole time series, but I don't really know how AQI gets calculated so... Are those values reasonable? Is the environment changing for those lower measurements suddenly (e.g., open window or some other reason why the air quality would improve just for a while)?

**Comment by harry-xiaomi** [comment]
I have a zhimi-airpurifier-ma4 model device, and I can attest that 1 is a valid aqi value on its OLED display.

**Comment by exelban** [comment]
Yeap, I see 1 aqi on the led screen too.

**Comment by sgurgul** [comment]
I can only confirm. Real (measured) AQI=1 gives no results which seems to be incorrect. LED on the devices shows 1.
When I imitated the pollution and the meaure rised up the value started to be properly reported.

**Comment by bieniu** [comment]
So maybe the best solution for this issue is to cache the AQI value and return the old value if the new value is significantly smaller than the old value?

**Comment by rytilahti** [comment]
Or simply revert it back to return 1, if 1 is definitely a valid value. Note, that even if the device is showing it as `1` it doesn't mean that the real AQI is 1 (maybe also buggy firmware not ignoring the incorrect measurements)? The previous assumption was that the 1 would be used for in-band signaling on incorrect reads, but that may not be true.

Anyway, as I mentioned earlier, I don't know how exactly it is measured, so I cannot really judge on that more than saying that those drops to 1 in the graph do not look normal to me.

**Comment by sgurgul** [comment]
There are two different "1" values

One is a single unexpected value - a peak on the graph. These seems to be common for 3* models from time to time.
If it's hard to recognize "unexpected" factor than maybe a first occuring 1 could be just ignored - previous measured value to be returned instead. The outcome will be just a minor delay in measurements update.

Another is a long-lasting 1 - a normal measure returned easily for hours in a clean air environment.
I own two 3* purifiers and I have never observed such long "1" values happening in any different case (like a firmware failure or any other error). It's just clean air - luckily it happens from time to time so it's really bad that the output from library is None in such case.
