### ISSUE TITLE
Release new version of the library

### ISSUE THREAD

**Issue by arturdobo** [rytilahti/python-miio#969]
Releasing a new version of this library will help to work on integrations for added devices like Xiaomi Air Purifier 3C and others in i.e. Home Assistant.

**Comment by rytilahti** [comment]
Sorry, I'll prepare a new release this week, and try to spend some time to figure out how to make releasing more automated for the future releases!

**Comment by rytilahti** [comment]
Forgot to link this to the release PR (#971), the new release is now available!
