### ISSUE TITLE
Unable to decrypt token for S55 Vacuum

### ISSUE THREAD

**Issue by brunoamaral** [rytilahti/python-miio#973]
**Describe the bug**

Running `mirobo --debug discover --handshake true` the resulting token outputs an error as seen below:

> INFO:miio.miioprotocol:  IP 192.168.1.213 (ID: 0f9c75d5) - token: b'ffffffffffffffffffffffffffffffff'
> DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''

**Version information (please complete the following information):**
 - OS: Linux and MacOS
 - python-miio: 0.5.5.

**To Reproduce**
1. run `mirobo --debug discover --handshake true` on a S55 robot

**Expected behavior**

A clear string for the token

**Comment by rytilahti** [comment]
The token is not send back by most of the devices, so you need to extract it some other way. https://python-miio.readthedocs.io/en/latest/discovery.html#tokens-from-mi-home-logs and its following sections lists several potential ways to do that.

**Comment by brunoamaral** [comment]
If the computer connects to the robot's AP, the token is displayed back. I don't know much about python but it feels like it's expecting a string and gets a stream of bytes instead.

**Comment by rytilahti** [comment]
Ah, okay. Yes, in that case (prior onboarding the device) some devices indeed return back the token. In this case you see the token which is just `f`s => the device has been configured/it is not leaking the token this way.

If you mean the debug log message, that is just something that happens during the handshake (as there is no real payload returned by the device) and should be actually suppressed for the handshakes to avoid confusion.

**Comment by brunoamaral** [comment]
That makes sense and fits my experience. Thank you for clearing it up 🙂 

Changing the debug message would indeed help those just tinkering with the robot once in a while like me.

**Comment by rytilahti** [comment]
Yeah, there is (or at least was) a PR to cleanup the whole discovery/handshake/regular comms handling, but it hasn't been a priority that much. I suppose most of the users do not enable the debug logging so it hasn't been a big issue, but it's definitely something that should be handled better if/when that code gets touched at some point :-)
