### ISSUE TITLE
Please add back the mapping parameter to `MiotDevice` constructor

### ISSUE THREAD

**Issue by ha0y** [rytilahti/python-miio#982]
**Is your feature request related to a problem? Please describe.**
https://github.com/rytilahti/python-miio/pull/905#pullrequestreview-616900975

**Describe the solution you'd like**
Add back the mapping parameter to `MiotDevice` constructor

**Device information:**
None

**Additional context**

**First of all, thanks for your great work! I'm using this library in my integration and this really helps a lot.**

In version 0.5.4, `mapping` is a required parameter of `MiotDevice` constructor. We use 
```python
MiotDevice(ip=host, token=token, mapping=mapping)
```
for it. But in version 0.5.5, `mapping` is an unexpected parameter. Using the code above throws exception. We have to use 
```python
md = MiotDevice(ip=host, token=token)
md.mapping=mapping
```
Likewise, this code won't work for 0.5.4.

This breaks backwards compatibility and may bring many issues to those components that use this library. Now I have to use something like 
```
try: 
MiotDevice(ip=host, token=token, mapping=mapping)
except TypeError: 
md = MiotDevice(ip=host, token=token)
md.mapping=mapping
```
to make sure that my integration works on both versions. That's not grace!

So, please add back the mapping parameter to `MiotDevice` constructor!

**Comment by rytilahti** [comment]
Agreed, this is an unexpected and unwanted regression, thanks for reporting! Considering this affects only the `MiotDevice` constructor, it's an easy fix to reintroduce the parameter again. I will create a PR tomorrow to re-add the parameter & prepare 0.5.5.2 release with only this fix included.

**Comment by rytilahti** [comment]
@ha0y do you mind checking if the linked PR works for you? I'll prepare a new release after your okay.

P.S. Thanks for the thanks, it's great to hear about people using the library! If you want, feel free to create a PR to add your project to the `Users of this library` section in the bottom of the README.md. That section is currently rather disorganized (only discusses about home assistant support), so feel free to adapt that if you feel like it.

**Comment by ha0y** [comment]
Yes - the branch `fix/miotdevice_ctor_regression` works! Thanks!

And I will create another PR to update README.
