### ISSUE TITLE
Missing dependency: pyyaml

### ISSUE THREAD

**Issue by ccoors** [rytilahti/python-miio#986]
**Describe the bug**
python-miio imports `yaml`, but `pyyaml` is not listed as a dependency.

**Version information (please complete the following information):**
 - OS: Linux
 - python-miio: 0.5.5.1

**To Reproduce**
1. `virtualenv venv`
2. `source venv/bin/activate`
3. `pip install python-miio`
4. Run `miiocli` or any other command:
```
$ miiocli
Traceback (most recent call last):
  File "venv/bin/miiocli", line 5, in <module>
    from miio.cli import create_cli
  File "venv/lib/python3.9/site-packages/miio/__init__.py", line 40, in 
    from miio.gateway import Gateway
  File "venv/lib/python3.9/site-packages/miio/gateway/__init__.py", line
    from .alarm import Alarm
  File "venv/lib/python3.9/site-packages/miio/gateway/alarm.py", line 8,
    from .gatewaydevice import GatewayDevice
  File "venv/lib/python3.9/site-packages/miio/gateway/gatewaydevice.py",
    from .gateway import Gateway
  File "venv/lib/python3.9/site-packages/miio/gateway/gateway.py", line 
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Expected behavior**
The `pyyaml` package is installed during `pip install python-miio`.

**Comment by rytilahti** [comment]
Created a new PR to add the dependency & will do a 0.5.5.2 release shortly, thanks for reporting!

**Comment by starkillerOG** [comment]
Sorry that is my fault, I use pyyaml so much i forgot that you actually need to install it and it does not come by default.

**Comment by rytilahti** [comment]
@starkillerOG no worries! It'd be great if you could add a couple of tests to gateway (e.g., verifying that the shipped subdevices file is correctly read by the implementation) next time you work on that code. That'll help catching this sort of issues and potential other issues like incorrectly formatted yaml files :-)
