### ISSUE TITLE
Roborock S7 

### ISSUE THREAD

**Issue by Maveric2005** [rytilahti/python-miio#994]
If i want to send a command to the Roborock S7 i get this Answer:

/usr/local/bin/miiocli -o json_pretty vacuum --ip 192.168.xxx.xxx --token xxxxxxxxxxxxxxxxxxxxxx start 2>&1 Output: Traceback (most recent call last): File "/usr/local/bin/miiocli", line 8, in <module> sys.exit(create_cli()) File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli return cli(auto_envvar_prefix="MIIO") File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1256, in invoke Command.invoke(self, ctx) File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func return f(get_current_context(), *args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/miio/vacuum.py", line 757, in callback with open(id_file, "r") as f, contextlib.suppress( FileNotFoundError: [Errno 2] No such file or directory: '/opt/loxberry/.cache/python-miio/python-mirobo.seq'

do you know the problem?

**Comment by rytilahti** [comment]
Please update to the newest release (or git master). That sequence file problem got fixed in 0.5.5.1 or 0.5.5.2, and current master has a fix for s7's cleaning history (#990).
