### ISSUE TITLE
Can't install python-miio 0.5.5.2 on python3.9.2 Mandatory Rust???

### ISSUE THREAD

**Issue by tordals** [rytilahti/python-miio#997]
Getting this stuff:
  This package requires Rust >=1.41.0.
  ----------------------------------------
error: can't find Rust compiler

ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

- I have the latest pip3 updating does not do anything.
- Is there a way to skip Rust, a huge and totally unnecessary package for RPi just to get outdoors lamps on/off.
Thanks

**Comment by dewgenenny** [comment]
I also got this error when trying to run the setup.py included in the tar.gz file, but had success installing the wheel file using pip3...

**Comment by rytilahti** [comment]
This is likely related to this, but I haven't read into it nor do I know what's the proper way to fix this (besides pinning the dep): https://lwn.net/Articles/845535/

**Comment by rytilahti** [comment]
piwheels is shipping wheels for cryptography, so I'll close this issue now: https://www.piwheels.org/project/cryptography/
